enum OnboardingScreens {
  SIGN_UP = 'SIGN_UP',
  CONFIRM_EMAIL = 'CONFIRM_EMAIL',
  SET_PHONE_NUMBER = 'SET_PHONE_NUMBER',
  CONFIRM_PHONE_NUMBER = 'CONFIRM_PHONE_NUMBER',
  VERIFY_IDENTITY = 'VERIFY_IDENTITY',
  VALIDATING_KYC = 'VALIDATING_KYC',
  KYC_PENDING = 'KYC_PENDING',
  KYC_FAILED = 'KYC_FAILED',
  KYC_REJECTED = 'KYC_REJECTED',
  PERSONAL_DETAILS = 'PERSONAL_DETAILS',
  PHYSICAL_ADDRESS = 'PHYSICAL_ADDRESS',
  MAILING_ADDRESS = 'MAILING_ADDRESS',
  COMPLETE = 'COMPLETE',
}

enum OnboardingActions {
  SIGN_UP_BUTTON_CLICKED = 'SIGN_UP_BUTTON_CLICKED',
  CONFIRM_EMAIL_BUTTON_CLICKED = 'CONFIRM_EMAIL_BUTTON_CLICKED',
  CONFIRM_EMAIL_RESEND_BUTTON_CLICKED = 'CONFIRM_EMAIL_RESEND_BUTTON_CLICKED',
  SET_PHONE_NUMBER_BUTTON_CLICKED = 'SET_PHONE_NUMBER_BUTTON_CLICKED',
  CONFIRM_PHONE_NUMBER_BUTTON_CLICKED = 'CONFIRM_PHONE_NUMBER_BUTTON_CLICKED',
  CONFIRM_PHONE_NUMBER_RESEND_BUTTON_CLICKED = 'CONFIRM_PHONE_NUMBER_RESEND_BUTTON_CLICKED',
  VERIFY_IDENTITY_BUTTON_CLICKED = 'VERIFY_IDENTITY_BUTTON_CLICKED',
  VALIDATING_KYC_BUTTON_CLICKED = 'VALIDATING_KYC_BUTTON_CLICKED',
  PERSONAL_DETAILS_BUTTON_CLICKED = 'PERSONAL_DETAILS_BUTTON_CLICKED',
  PHYSICAL_ADDRESS_BUTTON_CLICKED = 'PHYSICAL_ADDRESS_BUTTON_CLICKED',
  MAILING_ADDRESS_BUTTON_CLICKED = 'MAILING_ADDRESS_BUTTON_CLICKED',
  COMPLETE_BUTTON_CLICKED = 'COMPLETE_BUTTON_CLICKED',
}

export { OnboardingScreens, OnboardingActions };
