export enum CardScreens {
  CARD_WELCOME = 'WELCOME',
  CARD_AUTHENTICATION = 'AUTHENTICATION',
  CARD_OTP_AUTHENTICATION = 'OTP_AUTHENTICATION',
}

export enum CardButtons {
  CARD_VERIFY_ACCOUNT = 'VERIFY_ACCOUNT_BUTTON',
  CARD_AUTHENTICATION_LOGIN_BUTTON = 'AUTHENTICATION_LOGIN_BUTTON',
  CARD_OTP_AUTHENTICATION_CONFIRM_BUTTON = 'OTP_AUTHENTICATION_CONFIRM_BUTTON',
}
