/**
 * Mapping of asset symbols to human-readable names
 *
 * This mapping enables full-text search by name (e.g., "Bitcoin" -> BTC)
 * in addition to symbol search. The names are used in the UI for display
 * and in the search functionality for better user experience.
 *
 * Note: Assets not in this mapping will use their symbol as the name
 * (e.g., new HIP-3 assets will display their symbol until mapped)
 */
export const PERPS_ASSET_NAMES: Record<string, string> = {
  // Major cryptocurrencies
  BTC: 'Bitcoin',
  ETH: 'Ethereum',
  SOL: 'Solana',
  AVAX: 'Avalanche',
  ARB: 'Arbitrum',
  OP: 'Optimism',
  SUI: 'Sui',
  APT: 'Aptos',
  SEI: 'Sei',
  INJ: 'Injective',
  TIA: 'Celestia',
  JUP: 'Jupiter',
  WIF: 'dogwifhat',
  PEPE: 'Pepe',
  BONK: 'Bonk',
  DOGE: 'Dogecoin',
  SHIB: 'Shiba Inu',
  FLOKI: 'Floki',
  MEME: 'Memecoin',
  PENDLE: 'Pendle',
  PYTH: 'Pyth Network',
  JTO: 'Jito',
  ONDO: 'Ondo Finance',
  ENA: 'Ethena',
  W: 'Wormhole',
  STRK: 'Starknet',
  DYM: 'Dymension',
  MATIC: 'Polygon',
  LINK: 'Chainlink',
  UNI: 'Uniswap',
  AAVE: 'Aave',
  MKR: 'Maker',
  SNX: 'Synthetix',
  CRV: 'Curve',
  LDO: 'Lido DAO',
  RPL: 'Rocket Pool',
  FXS: 'Frax Share',
  GMX: 'GMX',
  DYDX: 'dYdX',
  BLUR: 'Blur',
  ATOM: 'Cosmos',
  DOT: 'Polkadot',
  NEAR: 'NEAR Protocol',
  ICP: 'Internet Computer',
  FIL: 'Filecoin',
  RENDER: 'Render',
  GRT: 'The Graph',
  FET: 'Fetch.ai',
  RNDR: 'Render Token',
  TAO: 'Bittensor',
  OCEAN: 'Ocean Protocol',
  AKT: 'Akash Network',
  AR: 'Arweave',
  STX: 'Stacks',
  RUNE: 'THORChain',
  KAVA: 'Kava',
  OSMO: 'Osmosis',
  XRP: 'Ripple',
  ADA: 'Cardano',
  TRX: 'TRON',
  TON: 'Toncoin',
  LTC: 'Litecoin',
  BCH: 'Bitcoin Cash',
  ETC: 'Ethereum Classic',
  XLM: 'Stellar',
  ALGO: 'Algorand',
  XTZ: 'Tezos',
  HBAR: 'Hedera',
  EOS: 'EOS',
  IOTA: 'IOTA',
  ZEC: 'Zcash',
  XMR: 'Monero',
  DASH: 'Dash',
  NEO: 'Neo',
  VET: 'VeChain',
  THETA: 'Theta Network',
  FTM: 'Fantom',
  ONE: 'Harmony',
  FLOW: 'Flow',
  SAND: 'The Sandbox',
  MANA: 'Decentraland',
  AXS: 'Axie Infinity',
  GALA: 'Gala',
  IMX: 'Immutable X',
  ENS: 'Ethereum Name Service',
  APE: 'ApeCoin',
  LIDO: 'Lido DAO',
  COMP: 'Compound',
  SUSHI: 'SushiSwap',
  YFI: 'yearn.finance',
  BAL: 'Balancer',
  '1INCH': '1inch Network',
  ZRX: '0x Protocol',
  BAND: 'Band Protocol',
  CELO: 'Celo',
  KSM: 'Kusama',
  MINA: 'Mina Protocol',
  ROSE: 'Oasis Network',
  ANKR: 'Ankr',
  CHZ: 'Chiliz',
  ENJ: 'Enjin Coin',
  LRC: 'Loopring',
  MASK: 'Mask Network',
  STORJ: 'Storj',
  PERP: 'Perpetual Protocol',
  CKB: 'Nervos Network',
  SKL: 'SKALE',
  NMR: 'Numeraire',
  BNT: 'Bancor',
  REN: 'Ren',
  KNC: 'Kyber Network Crystal',
  OMG: 'OMG Network',
  QTUM: 'Qtum',
  ZIL: 'Zilliqa',
  ICX: 'ICON',
  ONT: 'Ontology',
  ZEN: 'Horizen',
  WAVES: 'Waves',
  IOTX: 'IoTeX',
  SC: 'Siacoin',
  DGB: 'DigiByte',
  RVN: 'Ravencoin',
  SYS: 'Syscoin',
  XEM: 'NEM',
  STMX: 'StormX',
  HOT: 'Holo',
  WIN: 'WINkLink',
  BTT: 'BitTorrent',
  JST: 'JUST',
  SUN: 'Sun Token',
  NFT: 'APENFT',
  BAKE: 'BakeryToken',
  CAKE: 'PancakeSwap',
  BNB: 'BNB',
  XVS: 'Venus',
  ALPACA: 'Alpaca Finance',
  ALICE: 'My Neighbor Alice',
  TLM: 'Alien Worlds',
  SFP: 'SafePal',
  TWT: 'Trust Wallet Token',
  C98: 'Coin98',
  DODO: 'DODO',
  LINA: 'Linear Finance',
  REEF: 'Reef',
  SXP: 'Swipe',
  AUDIO: 'Audius',
  RAY: 'Raydium',
  SRM: 'Serum',
  FIDA: 'Bonfida',
  MNGO: 'Mango',
  OXY: 'Oxygen',
  STEP: 'Step Finance',
  PORT: 'Port Finance',
  MER: 'Mercurial Finance',
  SAMO: 'Samoyedcoin',
  POPCAT: 'Popcat',
  BOME: 'BOOK OF MEME',
  SLERF: 'SLERF',
  MEW: 'cat in a dogs world',
  MOTHER: 'MOTHER IGGY',
  GIGA: 'Gigachad',
  NEIRO: 'First Neiro On Ethereum',
  GOAT: 'Goatseus Maximus',
  PNUT: 'Peanut the Squirrel',
  ACT: 'Act I : The AI Prophecy',
  MOODENG: 'Moo Deng',
  CHILLGUY: 'Just a chill guy',
  HIPPO: 'Sudeng',
  ME: 'Magic Eden',
  MOVE: 'Movement',
  HYPE: 'Hyperliquid',
  AI16Z: 'ai16z',
  VIRTUAL: 'Virtuals Protocol',
  FARTCOIN: 'Fartcoin',
  GRIFFAIN: 'Griffain',
  ZEREBRO: 'Zerebro',
  AIXBT: 'aixbt',
  PENGU: 'Pudgy Penguins',
  TRUMP: 'Official Trump',
  MELANIA: 'Melania Meme',
  AI: 'Artificial Superintelligence Alliance',
  VINE: 'Vine Coin',
  ANIME: 'Animecoin',
  TST: 'Test',
  LAYER: 'UniLayer',
  IP: 'Story',
  BERA: 'Berachain',
  KAITO: 'KAITO',
  MNT: 'Mantle',
  PARTI: 'Particle Network',
  FORM: 'FORM',

  // HIP-3 Stock/Equity assets (with prefix handling)
  // Note: These are accessed via getAssetName which strips the DEX prefix
  TSLA: 'Tesla',
  NVDA: 'NVIDIA',
  AAPL: 'Apple',
  AMZN: 'Amazon',
  GOOGL: 'Alphabet',
  MSFT: 'Microsoft',
  META: 'Meta Platforms',
  NFLX: 'Netflix',
  AMD: 'Advanced Micro Devices',
  INTC: 'Intel',
  COIN: 'Coinbase',
  MSTR: 'MicroStrategy',
  PLTR: 'Palantir',
  UBER: 'Uber',
  LYFT: 'Lyft',
  SHOP: 'Shopify',
  SQ: 'Block',
  PYPL: 'PayPal',
  V: 'Visa',
  MA: 'Mastercard',
  JPM: 'JPMorgan Chase',
  BAC: 'Bank of America',
  GS: 'Goldman Sachs',
  MS: 'Morgan Stanley',
  WFC: 'Wells Fargo',
  C: 'Citigroup',
  DIS: 'Walt Disney',
  NKE: 'Nike',
  SBUX: 'Starbucks',
  MCD: 'McDonalds',
  KO: 'Coca-Cola',
  PEP: 'PepsiCo',
  WMT: 'Walmart',
  TGT: 'Target',
  COST: 'Costco',
  HD: 'Home Depot',
  LOW: 'Lowes',
  PG: 'Procter & Gamble',
  JNJ: 'Johnson & Johnson',
  UNH: 'UnitedHealth',
  PFE: 'Pfizer',
  MRK: 'Merck',
  ABBV: 'AbbVie',
  LLY: 'Eli Lilly',
  TMO: 'Thermo Fisher',
  ABT: 'Abbott Labs',
  CVS: 'CVS Health',
  XOM: 'ExxonMobil',
  CVX: 'Chevron',
  COP: 'ConocoPhillips',
  SLB: 'Schlumberger',
  BA: 'Boeing',
  CAT: 'Caterpillar',
  GE: 'General Electric',
  MMM: '3M',
  HON: 'Honeywell',
  RTX: 'Raytheon',
  LMT: 'Lockheed Martin',
  NOC: 'Northrop Grumman',
  DE: 'John Deere',
  F: 'Ford',
  GM: 'General Motors',
  RIVN: 'Rivian',
  LCID: 'Lucid Motors',
  SPY: 'SPDR S&P 500 ETF',
  QQQ: 'Invesco QQQ Trust',
  IWM: 'iShares Russell 2000',

  // HIP-3 Commodity assets
  GOLD: 'Gold',
  SILVER: 'Silver',
  PLATINUM: 'Platinum',
  PALLADIUM: 'Palladium',
  COPPER: 'Copper',
  OIL: 'Crude Oil',
  GAS: 'Natural Gas',
  WHEAT: 'Wheat',
  CORN: 'Corn',
  COFFEE: 'Coffee',
  SUGAR: 'Sugar',
  COTTON: 'Cotton',
} as const;

/**
 * Get the human-readable name for an asset symbol
 * Handles both regular symbols (BTC) and HIP-3 prefixed symbols (xyz:TSLA)
 *
 * @param symbol - Asset symbol (e.g., 'BTC', 'xyz:TSLA')
 * @returns Human-readable name or the symbol itself if not found
 *
 * @example
 * getAssetName('BTC') // → 'Bitcoin'
 * getAssetName('xyz:TSLA') // → 'Tesla'
 * getAssetName('UNKNOWN') // → 'UNKNOWN'
 */
export function getAssetName(symbol: string): string {
  if (!symbol || typeof symbol !== 'string') {
    return symbol;
  }

  // Check for HIP-3 prefix (e.g., "xyz:TSLA")
  const colonIndex = symbol.indexOf(':');
  const baseSymbol =
    colonIndex > 0 ? symbol.substring(colonIndex + 1) : symbol;

  // Look up in mapping, fall back to base symbol
  return PERPS_ASSET_NAMES[baseSymbol] ?? baseSymbol;
}
