/**
 * Perps feature constants
 */
export const PERPS_TRANSACTIONS_HISTORY_CONSTANTS = {
  ESTIMATED_LIST_ITEM_SIZE: 52,
  ESTIMATED_LIST_HEADER_LAYOUT_SIZE: 48,
  ESTIMATED_LIST_ITEM_LAYOUT_SIZE: 72,
  FLASH_LIST_DRAW_DISTANCE: 200,
  FLASH_LIST_SCROLL_EVENT_THROTTLE: 16,
  LIST_ITEM_SELECTOR_OPACITY: 0.7,
} as const;
