/**
 * Perps feature constants
 */
export const PERPS_TRANSACTIONS_HISTORY_CONSTANTS = {
  FLASH_LIST_DRAW_DISTANCE: 200,
  FLASH_LIST_SCROLL_EVENT_THROTTLE: 16,
  LIST_ITEM_SELECTOR_OPACITY: 0.7,
} as const;
