/**
 * List of controllers that are persisted individually
 * This list should match the controllers that have state change events
 * in BACKGROUND_STATE_CHANGE_EVENT_NAMES
 */
export const CONTROLLER_LIST = [
  'AccountTrackerController',
  'AccountsController',
  'AccountTreeController',
  'AddressBookController',
  'AppMetadataController',
  'AssetsContractController',
  'BridgeController',
  'BridgeStatusController',
  'CurrencyRateController',
  'DeFiPositionsController',
  'EarnController',
  'GasFeeController',
  'KeyringController',
  'LoggingController',
  'MultichainNetworkController',
  'NftController',
  'NetworkController',
  'NetworkEnablementController',
  'PerpsController',
  'PermissionController',
  'PreferencesController',
  'PhishingController',
  'PPOMController',
  'RemoteFeatureFlagController',
  'RewardsController',
  'SelectedNetworkController',
  'SignatureController',
  'SmartTransactionsController',
  'SwapsController',
  'TokenBalancesController',
  'TokenDetectionController',
  'TokenListController',
  'TokenRatesController',
  'TokenSearchDiscoveryController',
  'TokenSearchDiscoveryDataController',
  'TokensController',
  'TransactionController',
  // Snaps-related (only present in certain builds)
  'SnapController',
  'SnapsRegistry',
  'SubjectMetadataController',
  'AuthenticationController',
  'UserStorageController',
  'NotificationServicesController',
  'NotificationServicesPushController',
  'SnapInterfaceController',
  'CronjobController',
] as const;
