name: 'AI E2E Analysis'
description: 'Run AI-powered E2E test selection analysis based on code changes'
inputs:
  event-name:
    description: 'GitHub event name (pull_request, workflow_dispatch, schedule, etc.)'
    required: true
  claude-api-key:
    description: 'Claude API key for AI analysis'
    required: true
  github-token:
    description: 'GitHub token for PR comments'
    required: true
  pr-number:
    description: 'Pull request number for commenting'
    required: true
  repository:
    description: 'Repository name (owner/repo) for commenting'
    required: true
  post-comment:
    description: 'Whether to post a comment to the PR'
    required: false
    default: 'false'

outputs:
  test-matrix:
    description: 'JSON matrix for GitHub Actions test jobs - array of {tag, fileCount, split, totalSplits}'
    value: ${{ steps.ai-analysis.outputs.test_matrix }}

runs:
  using: 'composite'
  steps:
    - name: Full checkout for AI analysis
      uses: actions/checkout@v4
      with:
        fetch-depth: 50

    - name: Disable sparse checkout and restore all files
      shell: bash
      run: |
        git sparse-checkout disable
        git checkout HEAD -- .

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Install minimal dependencies for AI analysis
      shell: bash
      run: |
        echo "📦 Installing only required packages for AI analysis..."
        # Install to a separate location that won't be overwritten
        mkdir -p /tmp/ai-deps
        cd /tmp/ai-deps
        npm init -y
        npm install @anthropic-ai/sdk@latest esbuild-register@latest --no-audit --no-fund
        echo "✅ AI analysis dependencies installed in /tmp/ai-deps"

    - name: Copy AI dependencies to workspace
      shell: bash
      run: |
        echo "📋 Copying AI dependencies to workspace..."
        # Create node_modules if it doesn't exist
        mkdir -p node_modules
        # Copy our pre-installed dependencies
        cp -r /tmp/ai-deps/node_modules/* node_modules/
        echo "✅ AI dependencies available in workspace"

    - name: Check skip-smart-e2e-selection label
      id: check-skip-label
      if: inputs.event-name == 'pull_request' && inputs.pr-number != ''
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "SKIP=false" >> "$GITHUB_OUTPUT"
        if gh pr view ${{ inputs.pr-number }} --repo ${{ inputs.repository }} --json labels --jq '.labels[].name' | grep -qx "skip-smart-e2e-selection"; then
          echo "SKIP=true" >> "$GITHUB_OUTPUT"
          echo "⏭️ SKIP=true due to 'skip-smart-e2e-selection' label on PR"
        fi

    - name: Test Selection AI Analysis
      id: ai-analysis
      shell: bash
      env:
        E2E_CLAUDE_API_KEY: ${{ inputs.claude-api-key }}
        EVENT_NAME: ${{ inputs.event-name }}
        PR_NUMBER: ${{ inputs.pr-number }}
        GH_TOKEN: ${{ inputs.github-token }}
        PR_COMMENT_FILE: pr_comment.md
        GITHUB_REPOSITORY: ${{ inputs.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}
      run: |
        # Check if we should skip (label check or non-PR event)
        SHOULD_SKIP=false
        SKIP_REASON=""

        if [[ "$EVENT_NAME" != "pull_request" ]]; then
          SHOULD_SKIP=true
          SKIP_REASON="only runs on PRs"
        elif [[ -n "${{ steps.check-skip-label.outputs.SKIP }}" ]] && [[ "${{ steps.check-skip-label.outputs.SKIP }}" == "true" ]]; then
          SHOULD_SKIP=true
          SKIP_REASON="skip-smart-e2e-selection label found"
        fi

        if [[ "$SHOULD_SKIP" == "true" ]]; then
          echo "⏭️ Skipping AI analysis - $SKIP_REASON"
          echo "tags=" >> "$GITHUB_OUTPUT"
        else
          echo "✅ Running AI analysis for PR #$PR_NUMBER"
          node .github/scripts/e2e-ai-analysis.mjs 
        fi

    - name: Delete existing AI E2E comments
      if: inputs.post-comment == 'true' && inputs.pr-number != '' && inputs.github-token != '' && steps.ai-analysis.outputs.pr_comment_file != ''
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "🗑️ Deleting all existing AI E2E comments..."

        # Get all AI E2E comment IDs
        ALL_COMMENT_IDS=$(gh api "repos/${{ inputs.repository }}/issues/${{ inputs.pr-number }}/comments" \
          --jq '.[] | select(.body | test("🔍 Smart E2E Test Selection")) | .id')

        COMMENT_COUNT=$(echo "$ALL_COMMENT_IDS" | wc -l | tr -d ' ')
        echo "📊 Found $COMMENT_COUNT existing AI E2E comments"

        if [ -n "$ALL_COMMENT_IDS" ] && [ "$COMMENT_COUNT" -gt 0 ]; then
          echo "🗑️ Deleting all $COMMENT_COUNT AI E2E comments..."

          echo "$ALL_COMMENT_IDS" | while read -r COMMENT_ID; do
            if [ -n "$COMMENT_ID" ]; then
              echo "   Deleting comment: $COMMENT_ID"
              gh api "repos/${{ inputs.repository }}/issues/comments/$COMMENT_ID" \
                --method DELETE > /dev/null 2>&1 || echo "   ⚠️ Failed to delete comment $COMMENT_ID"
            fi
          done
          echo "✨ Cleanup completed - deleted all $COMMENT_COUNT comments"
        else
          echo "📝 No existing AI E2E comments found"
        fi

    - name: Create PR comment with AI E2E Analysis Report
      if: inputs.post-comment == 'true' && inputs.pr-number != '' && inputs.github-token != '' && steps.ai-analysis.outputs.pr_comment_file != ''
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        # Use the PR comment file generated by the script
        PR_COMMENT_FILE="${{ steps.ai-analysis.outputs.pr_comment_file || 'pr_comment.md' }}"

        if [ ! -f "$PR_COMMENT_FILE" ]; then
          echo "⚠️ PR comment file not found: $PR_COMMENT_FILE"
          echo "Skipping PR comment creation"
          exit 0
        fi

        echo "📝 Creating AI E2E analysis comment from $PR_COMMENT_FILE..."
        gh pr comment ${{ inputs.pr-number }} --repo ${{ inputs.repository }} --body-file "$PR_COMMENT_FILE"
        echo "✅ Successfully created comment"
