// Generated to match the output of the `expo-widgets` config plugin
// (`withWidgetSourceFiles.ts` on the `sdk-55` branch of github.com/expo/expo)
// for the `widgets` array declared in `app.config.js`.
//
// This repo is a bare React Native app with a checked-in `ios/` directory, so
// this file is NOT regenerated by `expo prebuild` / Continuous Native
// Generation. When you add or remove a widget kind, you ALWAYS update this
// file by hand — `scripts/ios/setup-expo-widgets-target.rb` never writes
// Swift; it only adds pre-existing `.swift` files to the Xcode target's
// "Sources" build phase (see that script's header for what it actually does).
//
// See docs/widgets/README.md for the full explanation of why this file
// exists and how to regenerate it.
import WidgetKit
import SwiftUI
internal import ExpoWidgets

// WidgetKit limits a single WidgetBundle to 4 widgets, so expo-widgets chunks
// widgets into groups of 4 and chains them via nested `body` calls. We only
// ship one widget today, so there is a single bundle. `WidgetLiveActivity()`
// (expo-widgets' built-in Live Activity renderer) must always be present in
// the last bundle — without it, `createLiveActivity(...)` calls from the app
// (e.g. a future Perps P/L Live Activity) would have no native counterpart to
// render into, even though no Live Activity is registered yet.
@main
struct ExportWidgets0: WidgetBundle {
  var body: some Widget {
    BalanceWidget()
    WidgetLiveActivity()
  }
}
