export const PerpsRecoveryPanelTestIds = {
  PANEL: 'perps-recovery-panel',
  LOADING: 'perps-recovery-loading',
  UNAVAILABLE: 'perps-recovery-unavailable',
  ERROR: 'perps-recovery-error',
  ACTION_ERROR: 'perps-recovery-action-error',
  CHECK_STATUS: 'perps-recovery-check-status',
  RETRY: 'perps-recovery-retry',
  DISPATCH: 'perps-recovery-dispatch',
  PROTECTION: 'perps-recovery-protection',
  REVIEW: 'perps-recovery-review',
  VENUE: 'perps-recovery-venue',
  POSITION: 'perps-recovery-position',
  ORDER: 'perps-recovery-order',
  ACKNOWLEDGE: 'perps-recovery-acknowledge',
  EDIT_PROTECTION: 'perps-recovery-edit-protection',
  REMOVE_PROTECTION: 'perps-recovery-remove-protection',
  REMOVAL_WARNING: 'perps-recovery-removal-warning',
  CONFIRM_REMOVAL: 'perps-recovery-confirm-removal',
  CANCEL_REMOVAL: 'perps-recovery-cancel-removal',
} as const;
