import { MockEventsObject } from '../../framework';

/**
 * Comprehensive mock responses for on-ramp-cache API endpoints
 * Covers all the API calls made by the @consensys/on-ramp-sdk during E2E tests
 * Uses regex patterns to handle both iOS (mobile-ios) and Android (mobile-android) contexts
 */

const ON_RAMP_CACHE_DEFAULT_RESPONSE = {
  parameters: {
    appleMerchantId: '',
    disableLimits: false,
  },
  payments: [
    {
      id: '/payments/apple-pay',
      paymentType: 'apple-pay',
      name: 'Apple Pay',
      score: 285,
      icons: [
        {
          type: 'fontAwesome',
          name: 'apple',
        },
      ],
      logo: {
        light: [
          'assets/Visa-regular@3x.png',
          'assets/Mastercard-regular@3x.png',
        ],
        dark: ['assets/Visa@3x.png', 'assets/Mastercard@3x.png'],
      },
      disclaimer: 'Apple Cash is not supported.',
      delay: [0, 0],
      pendingOrderDescription:
        'Card purchases may take a few minutes to complete.',
      amountTier: [1, 3],
      isApplePay: true,
    },
    {
      id: '/payments/debit-credit-card',
      paymentType: 'debit-credit-card',
      name: 'Debit or Credit',
      score: 268,
      icons: [
        {
          type: 'materialIcons',
          name: 'card',
        },
      ],
      logo: {
        light: [
          'assets/Visa-regular@3x.png',
          'assets/Mastercard-regular@3x.png',
        ],
        dark: ['assets/Visa@3x.png', 'assets/Mastercard@3x.png'],
      },
      disclaimer:
        "Credit card purchases may incur your bank's cash advance fees, subject to your bank's policies.",
      delay: [5, 10],
      pendingOrderDescription:
        'Card purchases may take a few minutes to complete.',
      amountTier: [1, 3],
      sellEnabled: true,
    },
    {
      id: '/payments/instant-bank-transfer',
      paymentType: 'bank-transfer',
      name: 'Instant ACH Bank Transfer',
      score: 130,
      icons: [
        {
          type: 'materialCommunityIcons',
          name: 'bank',
        },
      ],
      logo: {
        light: ['assets/ACHBankTransfer-regular@3x.png'],
        dark: ['assets/ACHBankTransfer@3x.png'],
      },
      delay: [0, 0],
      pendingOrderDescription:
        'Instant transfers may take a few minutes to complete.',
      amountTier: [3, 3],
      supportedCurrency: ['/currencies/fiat/usd'],
      supportedRegions: ['/regions/us'],
    },
    {
      id: '/payments/mobile-money',
      paymentType: 'bank-transfer',
      name: 'Mobile Money',
      score: 330,
      icons: [
        {
          type: 'materialCommunityIcons',
          name: 'bank',
        },
      ],
      logo: {
        light: [],
        dark: [],
      },
      delay: [0, 10],
      pendingOrderDescription:
        'Instant transfers may take a few minutes to complete.',
      amountTier: [1, 1],
    },
    {
      id: '/payments/wire-transfer',
      paymentType: 'bank-transfer',
      name: 'Wire Transfer',
      score: 380,
      icons: [
        {
          type: 'materialCommunityIcons',
          name: 'bank',
        },
      ],
      logo: {
        light: ['assets/payments/wire.png'],
        dark: ['assets/payments/wire.png'],
      },
      delay: [1440, 4320],
      pendingOrderDescription:
        'Bank transfers may take a few business days to complete.',
      amountTier: [3, 3],
      supportedRegions: [
        '/regions/us',
        '/regions/fr',
        '/regions/pt',
        '/regions/gb',
      ],
    },
    {
      id: '/payments/ach-bank-transfer',
      paymentType: 'bank-transfer',
      name: 'ACH Bank Transfer',
      score: 390,
      icons: [
        {
          type: 'materialCommunityIcons',
          name: 'bank',
        },
      ],
      logo: {
        light: ['assets/ACHBankTransfer-regular@3x.png'],
        dark: ['assets/ACHBankTransfer@3x.png'],
      },
      delay: [1440, 7200],
      pendingOrderDescription:
        'Bank transfers may take a few business days to complete.',
      amountTier: [3, 3],
      supportedCurrency: ['/currencies/fiat/usd'],
      supportedRegions: ['/regions/us'],
    },
  ],
  cryptoCurrencies: [
    {
      id: '/currencies/crypto/1/0x0000000000000000000000000000000000000000',
      idv2: '/currencies/crypto/1/0x0000000000000000000000000000000000000000',
      legacyId: '/currencies/crypto/1/eth',
      network: {
        active: true,
        chainId: '1',
        chainName: 'Ethereum Mainnet',
        shortName: 'Ethereum',
      },
      logo: 'https://uat-static.cx.metamask.io/api/v2/tokenIcons/assets/eip155/1/erc20/0x0000000000000000000000000000000000000000.png',
      decimals: 18,
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      name: 'Ethereum',
    },
    {
      id: '/currencies/crypto/1/0x6b175474e89094c44da98b954eedeac495271d0f',
      idv2: '/currencies/crypto/1/0x6b175474e89094c44da98b954eedeac495271d0f',
      legacyId: '/currencies/crypto/1/dai',
      network: {
        active: true,
        chainId: '1',
        chainName: 'Ethereum Mainnet',
        shortName: 'Ethereum',
      },
      logo: 'https://uat-static.cx.metamask.io/api/v2/tokenIcons/assets/eip155/1/erc20/0x6b175474e89094c44da98b954eedeac495271d0f.png',
      decimals: 18,
      address: '0x6b175474e89094c44da98b954eedeac495271d0f',
      symbol: 'DAI',
      name: 'Dai Stablecoin',
    },
    {
      id: '/currencies/crypto/1/0xdac17f958d2ee523a2206206994597c13d831ec7',
      idv2: '/currencies/crypto/1/0xdac17f958d2ee523a2206206994597c13d831ec7',
      legacyId: '/currencies/crypto/1/usdt',
      network: {
        active: true,
        chainId: '1',
        chainName: 'Ethereum Mainnet',
        shortName: 'Ethereum',
      },
      logo: 'https://uat-static.cx.metamask.io/api/v2/tokenIcons/assets/eip155/1/erc20/0xdac17f958d2ee523a2206206994597c13d831ec7.png',
      decimals: 6,
      address: '0xdac17f958d2ee523a2206206994597c13d831ec7',
      symbol: 'USDT',
      name: 'Tether USD',
    },
    {
      id: '/currencies/crypto/1/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
      idv2: '/currencies/crypto/1/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
      legacyId: '/currencies/crypto/1/usdc',
      network: {
        active: true,
        chainId: '1',
        chainName: 'Ethereum Mainnet',
        shortName: 'Ethereum',
      },
      logo: 'https://uat-static.cx.metamask.io/api/v2/tokenIcons/assets/eip155/1/erc20/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48.png',
      decimals: 6,
      address: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
      symbol: 'USDC',
      name: 'USDC',
    },
  ],
  fiatCurrencies: [
    {
      id: '/currencies/fiat/eur',
      symbol: 'EUR',
      name: 'Euro',
      decimals: 2,
      denomSymbol: '€',
    },
    {
      id: '/currencies/fiat/usd',
      symbol: 'USD',
      name: 'US Dollar',
      decimals: 2,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/aoa',
      symbol: 'AOA',
      name: 'Kwanza',
      decimals: 2,
      denomSymbol: 'Kz',
    },
    {
      id: '/currencies/fiat/xcd',
      symbol: 'XCD',
      name: 'East Caribbean Dollar',
      decimals: 2,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/ars',
      symbol: 'ARS',
      name: 'Argentine Peso',
      decimals: 2,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/aud',
      symbol: 'AUD',
      name: 'Australian Dollar',
      decimals: 2,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/bbd',
      symbol: 'BBD',
      name: 'Barbados Dollar',
      decimals: 2,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/bzd',
      symbol: 'BZD',
      name: 'Belize Dollar',
      decimals: 2,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/bmd',
      symbol: 'BMD',
      name: 'Bermudian Dollar',
      decimals: 2,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/inr',
      symbol: 'INR',
      name: 'Indian Rupee',
      decimals: 2,
      denomSymbol: '₹',
    },
    {
      id: '/currencies/fiat/nok',
      symbol: 'NOK',
      name: 'Norwegian Krone',
      decimals: 2,
      denomSymbol: 'kr',
    },
    {
      id: '/currencies/fiat/brl',
      symbol: 'BRL',
      name: 'Brazilian Real',
      decimals: 2,
      denomSymbol: 'R$',
    },
    {
      id: '/currencies/fiat/bnd',
      symbol: 'BND',
      name: 'Brunei Dollar',
      decimals: 2,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/bgn',
      symbol: 'BGN',
      name: 'Bulgarian Lev',
      decimals: 2,
      denomSymbol: 'лв.',
    },
    {
      id: '/currencies/fiat/xaf',
      symbol: 'XAF',
      name: 'CFA Franc BEAC',
      decimals: 0,
      denomSymbol: 'Fr',
    },
    {
      id: '/currencies/fiat/cad',
      symbol: 'CAD',
      name: 'Canadian Dollar',
      decimals: 2,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/clp',
      symbol: 'CLP',
      name: 'Chilean Peso',
      decimals: 0,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/cop',
      symbol: 'COP',
      name: 'Colombian Peso',
      decimals: 2,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/kmf',
      symbol: 'KMF',
      name: 'Comorian Franc',
      decimals: 0,
      denomSymbol: 'Fr',
    },
    {
      id: '/currencies/fiat/nzd',
      symbol: 'NZD',
      name: 'New Zealand Dollar',
      decimals: 2,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/crc',
      symbol: 'CRC',
      name: 'Costa Rican Colon',
      decimals: 2,
      denomSymbol: '₡',
    },
    {
      id: '/currencies/fiat/hrk',
      symbol: 'HRK',
      name: 'Kuna',
      decimals: 2,
      denomSymbol: 'kn',
    },
    {
      id: '/currencies/fiat/czk',
      symbol: 'CZK',
      name: 'Czech Koruna',
      decimals: 2,
      denomSymbol: 'Kč',
    },
    {
      id: '/currencies/fiat/dkk',
      symbol: 'DKK',
      name: 'Danish Krone',
      decimals: 2,
      denomSymbol: 'kr',
    },
    {
      id: '/currencies/fiat/djf',
      symbol: 'DJF',
      name: 'Djibouti Franc',
      decimals: 0,
      denomSymbol: 'Fr',
    },
    {
      id: '/currencies/fiat/dop',
      symbol: 'DOP',
      name: 'Dominican Peso',
      decimals: 2,
      denomSymbol: 'RD$',
    },
    {
      id: '/currencies/fiat/szl',
      symbol: 'SZL',
      name: 'Lilangeni',
      decimals: 2,
      denomSymbol: 'L',
    },
    {
      id: '/currencies/fiat/fkp',
      symbol: 'FKP',
      name: 'Falkland Islands Pound',
      decimals: 2,
      denomSymbol: '£',
    },
    {
      id: '/currencies/fiat/fjd',
      symbol: 'FJD',
      name: 'Fiji Dollar',
      decimals: 2,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/gel',
      symbol: 'GEL',
      name: 'Lari',
      decimals: 2,
      denomSymbol: '₾',
    },
    {
      id: '/currencies/fiat/ghs',
      symbol: 'GHS',
      name: 'Ghana Cedi',
      decimals: 2,
      denomSymbol: 'GH₵',
    },
    {
      id: '/currencies/fiat/gtq',
      symbol: 'GTQ',
      name: 'Quetzal',
      decimals: 2,
      denomSymbol: 'Q',
    },
    {
      id: '/currencies/fiat/gbp',
      symbol: 'GBP',
      name: 'Pound Sterling',
      decimals: 2,
      denomSymbol: '£',
    },
    {
      id: '/currencies/fiat/hnl',
      symbol: 'HNL',
      name: 'Lempira',
      decimals: 2,
      denomSymbol: 'L',
    },
    {
      id: '/currencies/fiat/hkd',
      symbol: 'HKD',
      name: 'Hong Kong Dollar',
      decimals: 2,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/huf',
      symbol: 'HUF',
      name: 'Forint',
      decimals: 2,
      denomSymbol: 'Ft',
    },
    {
      id: '/currencies/fiat/isk',
      symbol: 'ISK',
      name: 'Iceland Krona',
      decimals: 0,
      denomSymbol: 'kr',
    },
    {
      id: '/currencies/fiat/idr',
      symbol: 'IDR',
      name: 'Rupiah',
      decimals: 2,
      denomSymbol: 'Rp',
    },
    {
      id: '/currencies/fiat/ils',
      symbol: 'ILS',
      name: 'New Israeli Sheqel',
      decimals: 2,
      denomSymbol: '₪',
    },
    {
      id: '/currencies/fiat/jmd',
      symbol: 'JMD',
      name: 'Jamaican Dollar',
      decimals: 2,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/jpy',
      symbol: 'JPY',
      name: 'Yen',
      decimals: 0,
      denomSymbol: '¥',
    },
    {
      id: '/currencies/fiat/kzt',
      symbol: 'KZT',
      name: 'Tenge',
      decimals: 2,
      denomSymbol: '₸',
    },
    {
      id: '/currencies/fiat/kes',
      symbol: 'KES',
      name: 'Kenyan Shilling',
      decimals: 2,
      denomSymbol: 'Sh',
    },
    {
      id: '/currencies/fiat/krw',
      symbol: 'KRW',
      name: 'Won',
      decimals: 0,
      denomSymbol: '₩',
    },
    {
      id: '/currencies/fiat/kgs',
      symbol: 'KGS',
      name: 'Som',
      decimals: 2,
      denomSymbol: 'с',
    },
    {
      id: '/currencies/fiat/zar',
      symbol: 'ZAR',
      name: 'Rand',
      decimals: 2,
      denomSymbol: 'R',
    },
    {
      id: '/currencies/fiat/chf',
      symbol: 'CHF',
      name: 'Swiss Franc',
      decimals: 2,
      denomSymbol: 'Fr.',
    },
    {
      id: '/currencies/fiat/mga',
      symbol: 'MGA',
      name: 'Malagasy Ariary',
      decimals: 2,
      denomSymbol: 'Ar',
    },
    {
      id: '/currencies/fiat/mwk',
      symbol: 'MWK',
      name: 'Malawi Kwacha',
      decimals: 2,
      denomSymbol: 'MK',
    },
    {
      id: '/currencies/fiat/myr',
      symbol: 'MYR',
      name: 'Malaysian Ringgit',
      decimals: 2,
      denomSymbol: 'RM',
    },
    {
      id: '/currencies/fiat/mru',
      symbol: 'MRU',
      name: 'Ouguiya',
      decimals: 2,
      denomSymbol: 'UM',
    },
    {
      id: '/currencies/fiat/mxn',
      symbol: 'MXN',
      name: 'Mexican Peso',
      decimals: 2,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/mdl',
      symbol: 'MDL',
      name: 'Moldovan Leu',
      decimals: 2,
      denomSymbol: 'L',
    },
    {
      id: '/currencies/fiat/mzn',
      symbol: 'MZN',
      name: 'Mozambique Metical',
      decimals: 2,
      denomSymbol: 'MT',
    },
    {
      id: '/currencies/fiat/ngn',
      symbol: 'NGN',
      name: 'Naira',
      decimals: 2,
      denomSymbol: '₦',
    },
    {
      id: '/currencies/fiat/omr',
      symbol: 'OMR',
      name: 'Rial Omani',
      decimals: 3,
      denomSymbol: 'ر.ع.',
    },
    {
      id: '/currencies/fiat/pgk',
      symbol: 'PGK',
      name: 'Kina',
      decimals: 2,
      denomSymbol: 'K',
    },
    {
      id: '/currencies/fiat/pyg',
      symbol: 'PYG',
      name: 'Guarani',
      decimals: 0,
      denomSymbol: '₲',
    },
    {
      id: '/currencies/fiat/pen',
      symbol: 'PEN',
      name: 'Sol',
      decimals: 2,
      denomSymbol: 'S/.',
    },
    {
      id: '/currencies/fiat/php',
      symbol: 'PHP',
      name: 'Philippine Peso',
      decimals: 2,
      denomSymbol: '₱',
    },
    {
      id: '/currencies/fiat/pln',
      symbol: 'PLN',
      name: 'Zloty',
      decimals: 2,
      denomSymbol: 'zł',
    },
    {
      id: '/currencies/fiat/qar',
      symbol: 'QAR',
      name: 'Qatari Rial',
      decimals: 2,
      denomSymbol: 'QR',
    },
    {
      id: '/currencies/fiat/ron',
      symbol: 'RON',
      name: 'Romanian Leu',
      decimals: 2,
      denomSymbol: 'lei',
    },
    {
      id: '/currencies/fiat/rwf',
      symbol: 'RWF',
      name: 'Rwanda Franc',
      decimals: 0,
      denomSymbol: 'Fr',
    },
    {
      id: '/currencies/fiat/stn',
      symbol: 'STN',
      name: 'Dobra',
      decimals: 2,
      denomSymbol: 'Dd',
    },
    {
      id: '/currencies/fiat/sar',
      symbol: 'SAR',
      name: 'Saudi Riyal',
      decimals: 2,
      denomSymbol: 'SAR',
    },
    {
      id: '/currencies/fiat/scr',
      symbol: 'SCR',
      name: 'Seychelles Rupee',
      decimals: 2,
      denomSymbol: '₨',
    },
    {
      id: '/currencies/fiat/sgd',
      symbol: 'SGD',
      name: 'Singapore Dollar',
      decimals: 2,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/sbd',
      symbol: 'SBD',
      name: 'Solomon Islands Dollar',
      decimals: 2,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/srd',
      symbol: 'SRD',
      name: 'Surinam Dollar',
      decimals: 2,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/sek',
      symbol: 'SEK',
      name: 'Swedish Krona',
      decimals: 2,
      denomSymbol: 'kr',
    },
    {
      id: '/currencies/fiat/twd',
      symbol: 'TWD',
      name: 'New Taiwan Dollar',
      decimals: 2,
      denomSymbol: 'NT$',
    },
    {
      id: '/currencies/fiat/tjs',
      symbol: 'TJS',
      name: 'Somoni',
      decimals: 2,
      denomSymbol: 'с.',
    },
    {
      id: '/currencies/fiat/tzs',
      symbol: 'TZS',
      name: 'Tanzanian Shilling',
      decimals: 2,
      denomSymbol: 'Sh',
    },
    {
      id: '/currencies/fiat/thb',
      symbol: 'THB',
      name: 'Baht',
      decimals: 2,
      denomSymbol: '฿',
    },
    {
      id: '/currencies/fiat/top',
      symbol: 'TOP',
      name: 'Pa’anga',
      decimals: 2,
      denomSymbol: 'T$',
    },
    {
      id: '/currencies/fiat/try',
      symbol: 'TRY',
      name: 'Turkish Lira',
      decimals: 2,
      denomSymbol: '₺',
    },
    {
      id: '/currencies/fiat/tmt',
      symbol: 'TMT',
      name: 'Turkmenistan New Manat',
      decimals: 2,
      denomSymbol: 'm.',
    },
    {
      id: '/currencies/fiat/ugx',
      symbol: 'UGX',
      name: 'Uganda Shilling',
      decimals: 0,
      denomSymbol: 'USh',
    },
    {
      id: '/currencies/fiat/aed',
      symbol: 'AED',
      name: 'UAE Dirham',
      decimals: 2,
      denomSymbol: 'Dhs',
    },
    {
      id: '/currencies/fiat/uyu',
      symbol: 'UYU',
      name: 'Peso Uruguayo',
      decimals: 2,
      denomSymbol: '$',
    },
    {
      id: '/currencies/fiat/vnd',
      symbol: 'VND',
      name: 'Dong',
      decimals: 0,
      denomSymbol: '₫',
    },
  ],
  limits: {
    minAmount: 2,
    maxAmount: 50000,
    feeDynamicRate: 0,
    feeFixedRate: 0,
  },
};

export const ON_RAMP_SDK_MOCKS: MockEventsObject = {
  GET: [
    {
      urlEndpoint:
        /^https:\/\/on-ramp-cache\.uat-api\.cx\.metamask\.io\/regions\/[^/]+\/light\?sdk=2\.1\.10&context=mobile-(?:ios|android)&keys=&fiat=%2Fcurrencies%2Ffiat%2Fusd&crypto=%2Fcurrencies%2Fcrypto%2F1%2F0x0000000000000000000000000000000000000000&action=buy&multiplePayments=true$/,
      responseCode: 200,
      response: ON_RAMP_CACHE_DEFAULT_RESPONSE,
    },
    {
      urlEndpoint:
        /^https:\/\/on-ramp-cache\.uat-api\.cx\.metamask\.io\/regions\/networks\?sdk=2\.1\.10&context=mobile-(?:ios|android)&keys=$/,
      responseCode: 200,
      response: {
        networks: [
          {
            active: true,
            chainId: '1',
            chainName: 'Ethereum Mainnet',
            shortName: 'Ethereum',
            nativeTokenSupported: true,
          },
        ],
      },
    },
  ],
};
