# Single source of truth for all build configurations
# Protected by CODEOWNERS: mobile-platform team
#
# Usage:
#   - CI reads this file to configure builds
#   - Local dev can override via .js.env (takes precedence)
#   - LaunchDarkly overrides remote_feature_flags at runtime
#
# Structure:
#   - env: sets environment variables directly (servers, build config, etc.)
#   - secrets: maps env var names to GitHub Secret names
#   - code_fencing: features to include via code fencing
#   - remote_feature_flags: build-time defaults for LaunchDarkly flags (seeded into RemoteFeatureFlagController)
#
# GitHub Environment determines actual secret values - builds.yml just maps the names.

# =============================================================================
# YAML Anchors (reusable config blocks)
# =============================================================================

# Server URLs (production defaults, override in test/e2e/exp/dev builds)
_servers: &servers
  PORTFOLIO_API_URL: "https://portfolio.api.cx.metamask.io"
  SECURITY_ALERTS_API_URL: "https://security-alerts.api.cx.metamask.io"
  DECODING_API_URL: "https://signature-insights.api.cx.metamask.io/v1"
  AUTH_SERVICE_URL: "https://auth-service.api.cx.metamask.io"
  REWARDS_API_URL: "https://rewards.api.cx.metamask.io"
  BAANX_API_URL: "https://api.baanx.com"
  RAMPS_ENVIRONMENT: "production"

# Common secrets (shared across ALL builds - same names, GitHub Environment determines values)
_secrets: &secrets
  # Infrastructure
  MM_SENTRY_AUTH_TOKEN: "MM_SENTRY_AUTH_TOKEN"
  MM_SENTRY_DSN: "MM_SENTRY_DSN"
  GOOGLE_SERVICES_B64_IOS: "GOOGLE_SERVICES_B64_IOS"
  GOOGLE_SERVICES_B64_ANDROID: "GOOGLE_SERVICES_B64_ANDROID"
  # API Keys
  MM_INFURA_PROJECT_ID: "MM_INFURA_PROJECT_ID"
  WALLET_CONNECT_PROJECT_ID: "WALLET_CONNECT_PROJECT_ID"
  MM_FOX_CODE: "MM_FOX_CODE"
  MM_BRANCH_KEY_LIVE: "MM_BRANCH_KEY_LIVE"
  # Analytics
  SEGMENT_WRITE_KEY: "SEGMENT_WRITE_KEY"
  SEGMENT_PROXY_URL: "SEGMENT_PROXY_URL"
  SEGMENT_DELETE_API_SOURCE_ID: "SEGMENT_DELETE_API_SOURCE_ID"
  SEGMENT_REGULATIONS_ENDPOINT: "SEGMENT_REGULATIONS_ENDPOINT"
  # Features/Announcements
  FEATURES_ANNOUNCEMENTS_ACCESS_TOKEN: "FEATURES_ANNOUNCEMENTS_ACCESS_TOKEN"
  FEATURES_ANNOUNCEMENTS_SPACE_ID: "FEATURES_ANNOUNCEMENTS_SPACE_ID"
  # Firebase
  FCM_CONFIG_API_KEY: "FCM_CONFIG_API_KEY"
  FCM_CONFIG_AUTH_DOMAIN: "FCM_CONFIG_AUTH_DOMAIN"
  FCM_CONFIG_STORAGE_BUCKET: "FCM_CONFIG_STORAGE_BUCKET"
  FCM_CONFIG_PROJECT_ID: "FCM_CONFIG_PROJECT_ID"
  FCM_CONFIG_MESSAGING_SENDER_ID: "FCM_CONFIG_MESSAGING_SENDER_ID"
  FCM_CONFIG_APP_ID: "FCM_CONFIG_APP_ID"
  FCM_CONFIG_MEASUREMENT_ID: "FCM_CONFIG_MEASUREMENT_ID"
  # QuickNode
  QUICKNODE_MAINNET_URL: "QUICKNODE_MAINNET_URL"
  QUICKNODE_ARBITRUM_URL: "QUICKNODE_ARBITRUM_URL"
  QUICKNODE_AVALANCHE_URL: "QUICKNODE_AVALANCHE_URL"
  QUICKNODE_BASE_URL: "QUICKNODE_BASE_URL"
  QUICKNODE_LINEA_MAINNET_URL: "QUICKNODE_LINEA_MAINNET_URL"
  QUICKNODE_MONAD_URL: "QUICKNODE_MONAD_URL"
  QUICKNODE_OPTIMISM_URL: "QUICKNODE_OPTIMISM_URL"
  QUICKNODE_POLYGON_URL: "QUICKNODE_POLYGON_URL"
  # OAuth
  IOS_GOOGLE_CLIENT_ID: "IOS_GOOGLE_CLIENT_ID"
  IOS_GOOGLE_REDIRECT_URI: "IOS_GOOGLE_REDIRECT_URI"
  ANDROID_APPLE_CLIENT_ID: "ANDROID_APPLE_CLIENT_ID"
  ANDROID_GOOGLE_CLIENT_ID: "ANDROID_GOOGLE_CLIENT_ID"
  ANDROID_GOOGLE_SERVER_CLIENT_ID: "ANDROID_GOOGLE_SERVER_CLIENT_ID"
  # Card/Baanx
  MM_CARD_BAANX_API_CLIENT_KEY: "MM_CARD_BAANX_API_CLIENT_KEY"

# Main code fencing features
_code_fencing_main: &code_fencing_main
  - preinstalled-snaps
  - keyring-snaps
  - multi-srp
  - solana
  - bitcoin
  - tron

# Flask code fencing features (includes experimental)
_code_fencing_flask: &code_fencing_flask
  - flask
  - preinstalled-snaps
  - external-snaps
  - keyring-snaps
  - multi-srp
  - solana
  - bitcoin
  - tron

# =============================================================================
# Remote Feature Flags - Build-time defaults (seeded into RemoteFeatureFlagController)
# LaunchDarkly will override these at runtime
# Production (conservative) defaults - override in dev/exp builds as needed
# =============================================================================
_remote_feature_flags: &remote_feature_flags
  # Perps
  perpsPerpTradingEnabled: false
  perpsPerpTradingServiceInterruptionBannerEnabled: false
  perpsPerpGtmOnboardingModalEnabled: false
  perpsOrderBookEnabled: false
  perpsFeedbackEnabled: false
  # Earn/Staking
  earnPooledStakingEnabled: true
  earnPooledStakingServiceInterruptionBannerEnabled: false
  earnStablecoinLendingEnabled: true
  earnStablecoinLendingServiceInterruptionBannerEnabled: false
  earnMusdConversionFlowEnabled: false
  earnMusdCtaEnabled: false
  earnMusdConversionAssetOverviewCtaEnabled: false
  earnMusdConversionTokenListItemCtaEnabled: false
  earnMusdConversionRewardsUiEnabled: false
  earnMerklCampaignClaiming: false

# =============================================================================
# Build Configurations
# =============================================================================
# Based on client distribution matrix - see docs for full mapping
# Environments: production, rc, test, e2e, exp, dev

builds:
  # ---------------------------------------------------------------------------
  # MAIN BUILDS
  # ---------------------------------------------------------------------------

  # Production release (App Store)
  main-prod:
    github_environment: build-production
    env:
      METAMASK_ENVIRONMENT: "production"
      METAMASK_BUILD_TYPE: "main"
      <<: *servers
      # Build config flags (not remote feature flags)
      BRIDGE_USE_DEV_APIS: "false"
      RAMP_INTERNAL_BUILD: "false"
      IS_TEST: "false"
    secrets: *secrets
    code_fencing: *code_fencing_main
    remote_feature_flags: *remote_feature_flags

  # Release candidate
  main-rc:
    github_environment: build-rc
    env:
      METAMASK_ENVIRONMENT: "rc"
      METAMASK_BUILD_TYPE: "main"
      <<: *servers
      BRIDGE_USE_DEV_APIS: "false"
      RAMP_INTERNAL_BUILD: "false"
      IS_TEST: "false"
    secrets: *secrets
    code_fencing: *code_fencing_main
    remote_feature_flags: *remote_feature_flags

  # Test builds (QA)
  main-test:
    github_environment: build-test
    env:
      METAMASK_ENVIRONMENT: "test"
      METAMASK_BUILD_TYPE: "main"
      <<: *servers
      # UAT server overrides (TODO: Add actual UAT URLs when available)
      PORTFOLIO_API_URL: "https://portfolio.dev-api.cx.metamask.io"
      REWARDS_API_URL: "https://rewards.uat-api.cx.metamask.io"
      BAANX_API_URL: "https://dev.api.baanx.com"
      RAMPS_ENVIRONMENT: "staging"
      BRIDGE_USE_DEV_APIS: "true"
      RAMP_INTERNAL_BUILD: "true"
      IS_TEST: "true"
      IGNORE_BOXLOGS_DEVELOPMENT: "true"
      IS_SIM_BUILD: "true"
    secrets: *secrets
    code_fencing: *code_fencing_main
    remote_feature_flags: *remote_feature_flags

  # E2E test builds (no Sentry)
  main-e2e:
    github_environment: build-e2e
    env:
      METAMASK_ENVIRONMENT: "e2e"
      METAMASK_BUILD_TYPE: "main"
      <<: *servers
      PORTFOLIO_API_URL: "https://portfolio.dev-api.cx.metamask.io"
      REWARDS_API_URL: "https://rewards.uat-api.cx.metamask.io"
      BAANX_API_URL: "https://dev.api.baanx.com"
      RAMPS_ENVIRONMENT: "staging"
      BRIDGE_USE_DEV_APIS: "true"
      RAMP_INTERNAL_BUILD: "true"
      IS_TEST: "true"
      IGNORE_BOXLOGS_DEVELOPMENT: "true"
      IS_SIM_BUILD: "true"
    secrets: *secrets
    code_fencing: *code_fencing_main
    remote_feature_flags: *remote_feature_flags

  # Experimental builds
  main-exp:
    github_environment: build-exp
    env:
      METAMASK_ENVIRONMENT: "exp"
      METAMASK_BUILD_TYPE: "main"
      <<: *servers
      PORTFOLIO_API_URL: "https://portfolio.dev-api.cx.metamask.io"
      REWARDS_API_URL: "https://rewards.uat-api.cx.metamask.io"
      BAANX_API_URL: "https://dev.api.baanx.com"
      RAMPS_ENVIRONMENT: "staging"
      BRIDGE_USE_DEV_APIS: "true"
      RAMP_INTERNAL_BUILD: "true"
      IS_TEST: "false"
      MM_ENABLE_SETTINGS_PAGE_DEV_OPTIONS: "true"
    secrets: *secrets
    code_fencing: *code_fencing_main
    remote_feature_flags:
      <<: *remote_feature_flags
      # Override for experimental testing
      perpsPerpTradingEnabled: true
      perpsPerpGtmOnboardingModalEnabled: true
      perpsOrderBookEnabled: true
      perpsFeedbackEnabled: true
      earnMusdConversionFlowEnabled: true
      earnMusdCtaEnabled: true
      earnMusdConversionAssetOverviewCtaEnabled: true
      earnMusdConversionTokenListItemCtaEnabled: true
      earnMusdConversionRewardsUiEnabled: true
      earnMerklCampaignClaiming: true

  # Local development / Expo development build (Runway .app for simulator)
  main-dev:
    github_environment: build-dev
    env:
      METAMASK_ENVIRONMENT: "dev"
      METAMASK_BUILD_TYPE: "main"
      <<: *servers
      PORTFOLIO_API_URL: "https://portfolio.dev-api.cx.metamask.io"
      REWARDS_API_URL: "https://rewards.uat-api.cx.metamask.io"
      BAANX_API_URL: "https://dev.api.baanx.com"
      RAMPS_ENVIRONMENT: "staging"
      BRIDGE_USE_DEV_APIS: "true"
      RAMP_INTERNAL_BUILD: "true"
      IS_TEST: "false"
      MM_ENABLE_SETTINGS_PAGE_DEV_OPTIONS: "true"
      # iOS: build for simulator (Expo dev build; no signing required)
      IS_SIM_BUILD: "true"
      # Android: build Debug APK (for Runway/testing; script verifies APK at prod/debug/)
      CONFIGURATION: "Debug"
    secrets: *secrets
    code_fencing: *code_fencing_main
    remote_feature_flags:
      <<: *remote_feature_flags
      # Override for dev testing
      perpsPerpTradingEnabled: true
      perpsPerpGtmOnboardingModalEnabled: true
      perpsOrderBookEnabled: true
      perpsFeedbackEnabled: true
      earnMusdConversionFlowEnabled: true
      earnMusdCtaEnabled: true
      earnMusdConversionAssetOverviewCtaEnabled: true
      earnMusdConversionTokenListItemCtaEnabled: true
      earnMusdConversionRewardsUiEnabled: true
      earnMerklCampaignClaiming: true

  # ---------------------------------------------------------------------------
  # FLASK BUILDS
  # ---------------------------------------------------------------------------

  # Flask production release
  flask-prod:
    github_environment: build-production
    env:
      METAMASK_ENVIRONMENT: "production"
      METAMASK_BUILD_TYPE: "flask"
      <<: *servers
      BRIDGE_USE_DEV_APIS: "false"
      RAMP_INTERNAL_BUILD: "false"
      IS_TEST: "false"
    secrets: *secrets
    code_fencing: *code_fencing_flask
    remote_feature_flags: *remote_feature_flags

  # Flask test builds (QA)
  flask-test:
    github_environment: build-test
    env:
      METAMASK_ENVIRONMENT: "test"
      METAMASK_BUILD_TYPE: "flask"
      <<: *servers
      PORTFOLIO_API_URL: "https://portfolio.dev-api.cx.metamask.io"
      REWARDS_API_URL: "https://rewards.uat-api.cx.metamask.io"
      BAANX_API_URL: "https://dev.api.baanx.com"
      RAMPS_ENVIRONMENT: "staging"
      BRIDGE_USE_DEV_APIS: "true"
      RAMP_INTERNAL_BUILD: "true"
      IS_TEST: "true"
      IGNORE_BOXLOGS_DEVELOPMENT: "true"
      IS_SIM_BUILD: "true"
    secrets: *secrets
    code_fencing: *code_fencing_flask
    remote_feature_flags: *remote_feature_flags

  # Flask E2E test builds (no Sentry)
  flask-e2e:
    github_environment: build-e2e
    env:
      METAMASK_ENVIRONMENT: "e2e"
      METAMASK_BUILD_TYPE: "flask"
      <<: *servers
      PORTFOLIO_API_URL: "https://portfolio.dev-api.cx.metamask.io"
      REWARDS_API_URL: "https://rewards.uat-api.cx.metamask.io"
      BAANX_API_URL: "https://dev.api.baanx.com"
      RAMPS_ENVIRONMENT: "staging"
      BRIDGE_USE_DEV_APIS: "true"
      RAMP_INTERNAL_BUILD: "true"
      IS_TEST: "true"
      IGNORE_BOXLOGS_DEVELOPMENT: "true"
      IS_SIM_BUILD: "true"
    secrets: *secrets
    code_fencing: *code_fencing_flask
    remote_feature_flags: *remote_feature_flags

  # Flask local development / Expo development build (Runway .app for simulator)
  flask-dev:
    github_environment: build-dev
    env:
      METAMASK_ENVIRONMENT: "dev"
      METAMASK_BUILD_TYPE: "flask"
      <<: *servers
      PORTFOLIO_API_URL: "https://portfolio.dev-api.cx.metamask.io"
      REWARDS_API_URL: "https://rewards.uat-api.cx.metamask.io"
      BAANX_API_URL: "https://dev.api.baanx.com"
      RAMPS_ENVIRONMENT: "staging"
      BRIDGE_USE_DEV_APIS: "true"
      RAMP_INTERNAL_BUILD: "true"
      IS_TEST: "false"
      MM_ENABLE_SETTINGS_PAGE_DEV_OPTIONS: "true"
      # iOS: build for simulator (Expo dev build; no signing required)
      IS_SIM_BUILD: "true"
      # Android: build Debug APK (for Runway/testing; script verifies APK at flask/debug/)
      CONFIGURATION: "Debug"
    secrets: *secrets
    code_fencing: *code_fencing_flask
    remote_feature_flags:
      <<: *remote_feature_flags
      # Override for dev testing
      perpsPerpTradingEnabled: true
      perpsPerpGtmOnboardingModalEnabled: true
      perpsOrderBookEnabled: true
      perpsFeedbackEnabled: true
      earnMusdConversionFlowEnabled: true
      earnMusdCtaEnabled: true
      earnMusdConversionAssetOverviewCtaEnabled: true
      earnMusdConversionTokenListItemCtaEnabled: true
      earnMusdConversionRewardsUiEnabled: true
      earnMerklCampaignClaiming: true

  # Flask UAT builds (User Acceptance Testing)
  flask-uat:
    github_environment: build-test
    env:
      METAMASK_ENVIRONMENT: "uat"
      METAMASK_BUILD_TYPE: "flask"
      <<: *servers
      PORTFOLIO_API_URL: "https://portfolio.dev-api.cx.metamask.io"
      REWARDS_API_URL: "https://rewards.uat-api.cx.metamask.io"
      BAANX_API_URL: "https://dev.api.baanx.com"
      RAMPS_ENVIRONMENT: "staging"
      BRIDGE_USE_DEV_APIS: "true"
      RAMP_INTERNAL_BUILD: "true"
      IS_TEST: "true"
      IGNORE_BOXLOGS_DEVELOPMENT: "true"
      IS_SIM_BUILD: "true"
    secrets: *secrets
    code_fencing: *code_fencing_flask
    remote_feature_flags: *remote_feature_flags

  # ─────────────────────────────────────────────────────────────────────────────
  # QA Builds (legacy - for internal testing)
  # ─────────────────────────────────────────────────────────────────────────────

  # QA production build
  qa-prod:
    github_environment: build-qa
    env:
      METAMASK_ENVIRONMENT: "production"
      METAMASK_BUILD_TYPE: "qa"
      <<: *servers
      BRIDGE_USE_DEV_APIS: "false"
      RAMP_INTERNAL_BUILD: "false"
      IS_TEST: "false"
    secrets:
      <<: *secrets
      # QA uses QA Segment project
      SEGMENT_WRITE_KEY: SEGMENT_WRITE_KEY_QA
      SEGMENT_PROXY_URL: SEGMENT_PROXY_URL_QA
      SEGMENT_DELETE_API_SOURCE_ID: SEGMENT_DELETE_API_SOURCE_ID_QA
      SEGMENT_REGULATIONS_ENDPOINT: SEGMENT_REGULATIONS_ENDPOINT_QA
      # QA uses UAT OAuth credentials
      IOS_GOOGLE_CLIENT_ID: MAIN_IOS_GOOGLE_CLIENT_ID_UAT
      IOS_GOOGLE_REDIRECT_URI: MAIN_IOS_GOOGLE_REDIRECT_URI_UAT
      ANDROID_GOOGLE_CLIENT_ID: MAIN_ANDROID_GOOGLE_CLIENT_ID_UAT
      ANDROID_APPLE_CLIENT_ID: MAIN_ANDROID_APPLE_CLIENT_ID_UAT
      ANDROID_GOOGLE_SERVER_CLIENT_ID: MAIN_ANDROID_GOOGLE_SERVER_CLIENT_ID_UAT
      MM_CARD_BAANX_API_CLIENT_KEY: MM_CARD_BAANX_API_CLIENT_KEY_UAT
    code_fencing: *code_fencing_main
    remote_feature_flags: *remote_feature_flags

  # QA dev build / Expo development build (Runway .app for simulator)
  qa-dev:
    github_environment: build-qa
    env:
      METAMASK_ENVIRONMENT: "dev"
      METAMASK_BUILD_TYPE: "qa"
      <<: *servers
      PORTFOLIO_API_URL: "https://portfolio.dev-api.cx.metamask.io"
      REWARDS_API_URL: "https://rewards.uat-api.cx.metamask.io"
      BAANX_API_URL: "https://dev.api.baanx.com"
      RAMPS_ENVIRONMENT: "staging"
      BRIDGE_USE_DEV_APIS: "true"
      RAMP_INTERNAL_BUILD: "true"
      IS_TEST: "false"
      MM_ENABLE_SETTINGS_PAGE_DEV_OPTIONS: "true"
      # iOS: build for simulator (Expo dev build; no signing required)
      IS_SIM_BUILD: "true"
      # Android: build Debug APK (for Runway/testing; script verifies APK at qa/debug/)
      CONFIGURATION: "Debug"
    secrets:
      <<: *secrets
      # QA uses QA Segment project
      SEGMENT_WRITE_KEY: SEGMENT_WRITE_KEY_QA
      SEGMENT_PROXY_URL: SEGMENT_PROXY_URL_QA
      SEGMENT_DELETE_API_SOURCE_ID: SEGMENT_DELETE_API_SOURCE_ID_QA
      SEGMENT_REGULATIONS_ENDPOINT: SEGMENT_REGULATIONS_ENDPOINT_QA
      # QA uses UAT OAuth credentials
      IOS_GOOGLE_CLIENT_ID: MAIN_IOS_GOOGLE_CLIENT_ID_UAT
      IOS_GOOGLE_REDIRECT_URI: MAIN_IOS_GOOGLE_REDIRECT_URI_UAT
      ANDROID_GOOGLE_CLIENT_ID: MAIN_ANDROID_GOOGLE_CLIENT_ID_UAT
      ANDROID_APPLE_CLIENT_ID: MAIN_ANDROID_APPLE_CLIENT_ID_UAT
      ANDROID_GOOGLE_SERVER_CLIENT_ID: MAIN_ANDROID_GOOGLE_SERVER_CLIENT_ID_UAT
      MM_CARD_BAANX_API_CLIENT_KEY: MM_CARD_BAANX_API_CLIENT_KEY_UAT
    code_fencing: *code_fencing_main
    remote_feature_flags:
      <<: *remote_feature_flags
      # Override for dev testing
      perpsPerpTradingEnabled: true
      perpsPerpGtmOnboardingModalEnabled: true
      perpsOrderBookEnabled: true
      perpsFeedbackEnabled: true
      earnMusdConversionFlowEnabled: true
      earnMusdCtaEnabled: true
      earnMusdConversionAssetOverviewCtaEnabled: true
      earnMusdConversionTokenListItemCtaEnabled: true
      earnMusdConversionRewardsUiEnabled: true
      earnMerklCampaignClaiming: true
