#!/usr/bin/env node
import { execSync } from 'child_process';
import { writeFileSync, readFileSync } from 'fs';

/**
 * Runs the AI root cause analysis for a bug report,
 * reads the JSON output, and generates an issue comment.
 */

const env = {
  ISSUE_NUMBER: process.env.ISSUE_NUMBER || '',
};

const COMMENT_FILE = 'issue_comment.md';
const ANALYSIS_FILE = 'root-cause-analysis.json';

function formatRegressionPRs(prs) {
  if (!prs || prs.length === 0) {
    return '_Pre-existing issue or no regression PR identified._';
  }

  const header = '| PR | Title | Author | What Changed |\n|---|---|---|---|';
  const rows = prs
    .map(
      (pr) =>
        `| #${pr.number} | ${pr.title} | ${pr.author} | ${pr.explanation} |`,
    )
    .join('\n');

  return `${header}\n${rows}`;
}

function formatScopeOfImpact(scope) {
  if (!scope || scope.length === 0) {
    return '_No additional areas of impact identified._';
  }

  const header = '| File | Line(s) | Description |\n|---|---|---|';
  const rows = scope
    .map((item) => `| ${item.file} | ${item.lines} | ${item.description} |`)
    .join('\n');

  return `${header}\n${rows}`;
}

function generateIssueComment(analysis) {
  const {
    summary,
    regressionPRs,
    errorFlow,
    scopeOfImpact,
    suggestedFix,
    confidence,
    reasoning,
  } = analysis;

  let comment = `## Root Cause Analysis\n\n`;
  comment += `**Summary:** ${summary}\n\n`;

  comment += `### Likely Regression PR(s)\n`;
  comment += `${formatRegressionPRs(regressionPRs)}\n\n`;

  if (errorFlow) {
    comment += `### Error Flow\n`;
    comment += `\`${errorFlow}\`\n\n`;
  }

  comment += `### Scope of Impact\n`;
  comment += `${formatScopeOfImpact(scopeOfImpact)}\n\n`;

  if (suggestedFix) {
    comment += `### Suggested Fix\n`;
    comment += `${suggestedFix}\n\n`;
  }

  if (reasoning) {
    comment += `<details>\n`;
    comment += `<summary>AI reasoning details</summary>\n\n`;
    comment += `${reasoning}\n`;
    comment += `</details>\n\n`;
  }

  comment += `---\n`;
  comment += `Generated by AI | Confidence: ${confidence}%\n`;

  return comment;
}

async function main() {
  try {
    if (!env.ISSUE_NUMBER) {
      console.error('ISSUE_NUMBER environment variable is required');
      process.exit(1);
    }

    const baseCmd = `node -r esbuild-register tests/tools/e2e-ai-analyzer --mode root-cause --issue ${env.ISSUE_NUMBER}`;
    console.log(`Investigating issue #${env.ISSUE_NUMBER}...`);

    try {
      execSync(baseCmd, {
        encoding: 'utf8',
        stdio: 'inherit',
      });
    } catch (error) {
      console.error('AI analyzer failed');
      process.exit(1);
    }

    // Read JSON output
    let analysis;
    try {
      const resultFile = readFileSync(ANALYSIS_FILE, 'utf8');
      analysis = JSON.parse(resultFile);
    } catch (error) {
      console.error(`Failed to read ${ANALYSIS_FILE}`);
      console.error(`Error: ${error.message}`);
      process.exit(1);
    }

    // Generate and write issue comment
    const commentBody = generateIssueComment(analysis);
    writeFileSync(COMMENT_FILE, commentBody, 'utf8');
    console.log(`Issue comment written to ${COMMENT_FILE}`);
  } catch (error) {
    console.error('Error running investigation:', error.message || error);
    process.exit(1);
  }
}

main().catch((error) => {
  console.error('\nUnexpected error:', error);
  process.exit(1);
});
