/**
 * Test identifiers for RewardsView component
 */
export const REWARDS_VIEW_SELECTORS = {
  REFERRAL_BUTTON: 'rewards-view-referral-button',
  SETTINGS_BUTTON: 'rewards-view-settings-button',
  SEASON_SUMMARY_PLACEHOLDER: 'rewards-view-season-summary-placeholder',
  TAB_CONTENT_ACTIVITY: 'rewards-view-tab-content-activity',
  TAB_CONTENT_OVERVIEW: 'rewards-view-tab-content-overview',
  TAB_CONTENT_LEVELS: 'rewards-view-tab-content-levels',
  TAB_CONTENT_PREVIOUS_SEASON: 'rewards-view-tab-content-previous-season',
  TAB_CONTROL: 'rewards-view-tab-control',
  ACTIVE_BOOST_CARD: 'rewards-view-active-boost-card',
  ACTIVE_BOOST_CARD_NAME: 'rewards-view-active-boost-card-name',
  ACTIVE_BOOST_CARD_TIME_REMAINING:
    'rewards-view-active-boost-card-time-remaining',
  ACTIVE_BOOST_CARD_ICON: 'rewards-view-active-boost-card-icon',
  TIER_IMAGE: 'rewards-view-tier-image',
  TIER_NAME: 'rewards-view-tier-name',
  TIER_POINTS_NEEDED: 'rewards-view-tier-points-needed',
  TIER_REWARDS: 'rewards-view-tier-rewards',
  TIER_REWARD_ICON: 'rewards-view-tier-reward-icon',
  TIER_REWARD_NAME: 'rewards-view-tier-reward-name',
  TIER_REWARD_DESCRIPTION: 'rewards-view-tier-reward-description',
  TIER_REWARD_CLAIM_BUTTON: 'rewards-view-tier-reward-claim-button',
  TIER_REWARD_CLAIMED_BUTTON: 'rewards-view-tier-reward-claimed-button',
  UNLOCKED_REWARDS: 'rewards-view-unlocked-rewards',
  UNLOCKED_REWARDS_EMPTY: 'rewards-view-unlocked-rewards-empty',
  UNLOCKED_REWARDS_EMPTY_CTA: 'rewards-view-unlocked-rewards-empty-cta',
  NOT_OPTED_IN_OVERLAY: 'rewards-view-not-opted-in-overlay',
  CLAIM_MODAL: 'rewards-view-claim-modal',
  CLAIM_MODAL_CONFIRM_BUTTON: 'rewards-view-claim-modal-confirm-button',
  CLAIM_MODAL_ERROR_MESSAGE: 'rewards-view-claim-modal-error-message',
  CLAIM_BUTTON: 'rewards-view-claim-button',
  SKIP_BUTTON: 'rewards-view-skip-button',
  NEXT_BUTTON: 'rewards-view-next-button',
  SEASON_STATUS_LEVEL: 'rewards-view-season-status-level',
  SEASON_STATUS_TIER_NAME: 'rewards-view-season-status-tier-name',
  SEASON_STATUS_POINTS: 'rewards-view-season-status-points',
  PREVIOUS_SEASON_SUMMARY: 'rewards-view-previous-season-summary',
  PREVIOUS_SEASON_BALANCE: 'rewards-view-previous-season-balance',
  PREVIOUS_SEASON_LEVEL: 'rewards-view-previous-season-level',
  PREVIOUS_SEASON_REFERRAL_DETAILS:
    'rewards-view-previous-season-referral-details',
  FLATLIST: 'flatlist',
  ACTIVITY_ROW: 'activity-row',
  ACTIVITY_EVENT_ROW_TITLE: 'activity-event-row-title',
  ACTIVITY_EVENT_ROW_VALUE: 'activity-event-row-value',
  ACTIVITY_EVENT_ROW_DETAILS: 'activity-event-row-details',
  ACTIVITY_EVENT_ROW_DATE: 'activity-event-row-date',
  ACTIVITY_EVENT_ROW_BONUS: 'activity-event-row-bonus',
} as const;
