# List things here that *are - 'used, that depcheck is wrong about'
ignores:
  - '@metamask/oss-attribution-generator'
  - 'webpack-cli'
  # This is used on the patch for TokenRatesController of Assets controllers, for we to be able to use the last version of it
  - cockatiel

  # Note: Everything below this line should be removed after investigation
  # TODO: Investigate each dependency to see whether it's used

  ## Unused dependencies to investigate
  - '@babel/preset-env'
  - '@babel/runtime'
  - '@cucumber/message-streams'
  - '@cucumber/messages'
  - '@metamask/mobile-provider'
  - '@rpii/wdio-html-reporter'
  - '@testing-library/react'
  - '@testing-library/react-hooks'
  - '@types/jest'
  - '@types/react-native-video'
  - '@wdio/appium-service'
  - '@wdio/browserstack-service'
  - '@wdio/junit-reporter'
  - '@wdio/local-runner'
  - '@wdio/spec-reporter'
  - 'appium'
  - 'assert'
  - 'babel-core'
  - 'babel-loader'
  - 'chromedriver'
  - 'eslint-config-prettier'
  - 'eslint-plugin-prettier'
  - 'eslint-plugin-react-native'
  - 'execa'
  - 'fbjs-scripts'
  - 'improved-yarn-audit'
  - 'jetifier'
  - 'metro-react-native-babel-preset'
  - 'octonode'
  - 'prettier-plugin-gherkin'
  - 'react-native-svg-asset-plugin'
  - 'regenerator-runtime'
  - 'rn-nodeify'

  ## Unused devDependencies to investigate
  - '@ethersproject/abi'
  - '@metamask/swappable-obj-proxy'
  - '@react-native-picker/picker'
  - '@rnhooks/keyboard'
  - '@segment/sovran-react-native'
  - '@tradle/react-native-http'
  - 'asyncstorage-down'
  - 'buffer'
  - 'd3-shape'
  - 'dnode'
  - 'eciesjs'
  - 'eth-block-tracker'
  - 'eth-json-rpc-infura'
  - 'events'
  - 'https-browserify'
  - 'obs-store'
  - 'path'
  - 'pbkdf2'
  - 'pify'
  - 'punycode'
  - 'randomfill'
  - 'react-native-aes-crypto'
  - 'react-native-aes-crypto-forked'
  - 'react-native-crypto'
  - 'react-native-flash-message'
  - 'react-native-level-fs'
  - 'react-native-os'
  - 'react-native-randombytes'
  - 'react-native-redash'
  - 'react-native-swipe-gestures'
  - 'react-native-tcp'
  - 'react-native-v8'
  - 'socket.io-client'
  - 'stream-browserify'
  - 'url'
  - 'vm-browserify'
  - 'react-native-cli'

  ## Missing dependencies to investigate
  - '@react-navigation/core'
  - 'app'
  - 'i18n-js'
  - 'images'
