enableScripts: false

nodeLinker: node-modules

npmAuditIgnoreAdvisories:
  ### Advisories:
  # Issue: Regular Expression Denial of Service (ReDoS) in cross-spawn
  # URL - https://github.com/advisories/GHSA-3xgq-45jj-v275
  # The affected versions <6.0.6, is only present in wdio which is a dev dependency
  - 1104663

yarnPath: .yarn/releases/yarn-3.8.7.cjs
