compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmAuditIgnoreAdvisories:
  - 1109627 # TODO: Remove the patch once @react-native-community/cli is upgraded to 17.0.1 / 18.0.1 / 19.1.2 / 20.0.0 , that will happen after react native upgrade to 0.80+

yarnPath: .yarn/releases/yarn-4.10.3.cjs

# Configure the NPM minimal age gate to 3 days, meaning packages must be at
# least 3 days old to be installed.
npmMinimalAgeGate: 4320 # 3 days (in minutes)

# Override the minimal age gate, allowing certain packages to be installed
# regardless of their publish age.
npmPreapprovedPackages:
  - '@metamask/*'
  - '@metamask-previews/*'
  - '@lavamoat/*'
  - '@consensys/*'
