compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmAuditIgnoreAdvisories:

yarnPath: .yarn/releases/yarn-4.10.3.cjs

# Configure the NPM minimal age gate to 3 days, meaning packages must be at
# least 3 days old to be installed.
npmMinimalAgeGate: 4320 # 3 days (in minutes)

# Override the minimal age gate, allowing certain packages to be installed
# regardless of their publish age.
npmPreapprovedPackages:
  - "@metamask/*"
  - "@metamask-previews/*"
  - "@lavamoat/*"
  - "@consensys/*"
  