compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmAuditIgnoreAdvisories:
  ### Advisories:
  # Issue: Regular Expression Denial of Service (ReDoS) in cross-spawn
  # URL - https://github.com/advisories/GHSA-3xgq-45jj-v275
  # The affected versions <6.0.6, is only present in wdio which is a dev dependency
  - 1104663
  - 1109627  # TODO: Upgrade @react-native-community/cli to 17.0.1+ when ready. Suppressing for now to unblock CI.

yarnPath: .yarn/releases/yarn-4.10.3.cjs
