compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmAuditIgnoreAdvisories:
  ### Advisories:
  # Issue: Regular Expression Denial of Service (ReDoS) in cross-spawn
  # URL - https://github.com/advisories/GHSA-3xgq-45jj-v275
  # The affected versions <6.0.6, is only present in wdio which is a dev dependency
  - 1104663

yarnPath: .yarn/releases/yarn-4.10.3.cjs

# Configure the NPM minimal age gate to 3 days, meaning packages must be at
# least 3 days old to be installed.
npmMinimalAgeGate: 4320 # 3 days (in minutes)

# Override the minimal age gate, allowing certain packages to be installed
# regardless of their publish age.
npmPreapprovedPackages:
  - "@metamask/*"
  - "@metamask-previews/*"
  - "@lavamoat/*"
