"project_id_env": CROWDIN_PROJECT_ID
"api_token_env": CROWDIN_PERSONAL_TOKEN
"base_path" : "."
"base_url" : "https://metamask.crowdin.com"

"preserve_hierarchy": true

files: [
 {
  "source" : "locales/languages/en.json",
  "translation" : "/locales/languages/%two_letters_code%.json",
 }
]
