"project_id_env": CROWDIN_PROJECT_ID
"api_token_env": CROWDIN_PERSONAL_TOKEN
"base_path" : "."

"preserve_hierarchy": true

# This array identifies the files that should be the source for translations. If a translations key is used this
# indicates that translations from the idneified files will be pushed up to Crowdin.
files: [
 {
  "source" : "locales/languages/en.json",
 },
 {
   "source" : "app/videos/subtitles/secretPhrase/subtitles-en.vtt",
 }
]
