process.env.TZ = 'America/Toronto';
process.env.MM_BLOCKAID_UI_ENABLED = 'true';

const config = {
  preset: 'react-native',
  setupFilesAfterEnv: ['<rootDir>/app/util/test/testSetup.js'],
  testEnvironment: 'jest-environment-node',
  transformIgnorePatterns: [
    'node_modules/(?!(@react-native|react-native|rn-fetch|redux-persist-filesystem|@react-navigation|@react-native-community|@react-native-masked-view|react-navigation|react-navigation-redux-helpers|@sentry|d3-color))',
  ],
  transform: {
    '^.+\\.[jt]sx?$': 'babel-jest',
    '^.+\\.(png|jpg|jpeg|gif|webp|svg|mp4)$':
      '<rootDir>/app/util/test/assetFileTransformer.js',
  },
  snapshotSerializers: ['enzyme-to-json/serializer'],
  // This is an environment variable that can be used to execute logic only in development
  testMatch: [
    '<rootDir>/app/**/?(*.)+(spec|test).[jt]s?(x)',
    '<rootDir>/locales/**/?(*.)+(spec|test).[jt]s?(x)',
  ],
  collectCoverage: process.env.NODE_ENV !== 'production',
  collectCoverageFrom: [
    '<rootDir>/app/actions/transaction/**/*.[jt]s?(x)',
    '<rootDir>/app/component-library/components-temp/CustomSpendCap/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/AnimatedTransactionHeader/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/ApproveTransactionHeader/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/ApproveTransactionReview/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/BlockaidBanner/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/CustomGasModal/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/CustomNonce/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/CustomNonceModal/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/EditGasFee1559/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/EditGasFee1559Update/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/EditGasFeeLegacy/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/EditGasFeeLegacyUpdate/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/MessageSign/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/PersonalSign/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/QRHardware/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/SignatureRequest/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/TransactionActionModal/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/TransactionEditor/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/TransactionElement/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/TransactionHeader/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/TransactionReview/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/Transactions/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/TypedSign/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/UpdateEIP1559Tx/**/*.[jt]s?(x)',
    '<rootDir>/app/components/UI/WatchAssetRequest/**/*.[jt]s?(x)',
    '<rootDir>/app/components/Views/AccountPermissions/**/*.[jt]s?(x)',
    '<rootDir>/app/components/Views/AddAsset/**/*.[jt]s?(x)',
    '<rootDir>/app/components/Views/Approval**/*.[jt]s?(x)',
    '<rootDir>/app/components/Views/ApproveView/**/*.[jt]s?(x)',
    '<rootDir>/app/components/Views/DetectTokens/**/*.[jt]s?(x)',
    '<rootDir>/app/components/Views/DetectTokensConfirmation/**/*.[jt]s?(x)',
    '<rootDir>/app/components/Views/GasEducationCarousel/**/*.[jt]s?(x)',
    '<rootDir>/app/components/Views/Send/**/*.[jt]s?(x)',
    '<rootDir>/app/components/Views/SendFlow/**/*.[jt]s?(x)',
    '<rootDir>/app/components/Views/TransactionSummary/**/*.[jt]s?(x)',
    '<rootDir>/app/components/Views/TransactionsView/**/*.[jt]s?(x)',
    '<rootDir>/app/constants/transaction.ts',
    '<rootDir>/app/core/GasPolling/**/*.[jt]s?(x)',
    '<rootDir>/app/core/Permissions/**/*.[jt]s?(x)',
    '<rootDir>/app/core/TransactionTypes.js',
    '<rootDir>/app/lib/ppom/**/*.[jt]s?(x)',
    '<rootDir>/app/reducers/transaction/**/*.[jt]s?(x)',
    '<rootDir>/app/selectors/preferencesController/**/*.[jt]s?(x)',
    '<rootDir>/app/util/blockaid/**/*.[jt]s?(x)',
    '<rootDir>/app/util/confirmation/**/*.[jt]s?(x)',
    '<rootDir>/app/util/custom-gas/**/*.[jt]s?(x)',
    '<rootDir>/app/util/dapp-transactions/**/*.[jt]s?(x)',
    '<rootDir>/app/util/transactions/**/*.[jt]s?(x)',
    '<rootDir>/app/util/confirm-tx.js',
    '<rootDir>/app/util/transaction-reducer-helpers.js',
  ],
  coveragePathIgnorePatterns: [
    '__mocks__/',
    '<rootDir>/app/util/test/',
    '<rootDir>/app/util/testUtils/',
    '<rootDir>/app/lib/ppom/ppom.html.js',
  ],
  coverageReporters: ['text-summary', 'lcov'],
  coverageDirectory: '<rootDir>/tests/coverage',
  maxWorkers: process.env.NODE_ENV === 'production' ? '50%' : '20%',
  moduleNameMapper: {
    '\\.svg': '<rootDir>/app/__mocks__/svgMock.js',
    '\\.png': '<rootDir>/app/__mocks__/pngMock.js',
  },
};

// eslint-disable-next-line import/no-commonjs
module.exports = config;
