import React from 'react';
import { fireEvent } from '@testing-library/react-native';
import renderWithProvider from '../../../../../util/test/renderWithProvider';
import MoneyHowItWorksView from './MoneyHowItWorksView';
import { MoneyHowItWorksViewTestIds } from './MoneyHowItWorksView.testIds';
import useMoneyAccountBalance from '../../hooks/useMoneyAccountBalance';
import { useMoneyAnalytics } from '../../hooks/useMoneyAnalytics';
import { SCREEN_NAMES } from '../../constants/moneyEvents';

const mockTrackScreenViewed = jest.fn();

jest.mock('../../hooks/useMoneyAnalytics', () => ({
  useMoneyAnalytics: jest.fn(),
}));

const mockGoBack = jest.fn();

jest.mock('../../hooks/useMoneyAccountBalance', () => ({
  __esModule: true,
  default: jest.fn(),
}));

jest.mock('@react-navigation/native', () => {
  const actualReactNavigation = jest.requireActual('@react-navigation/native');
  return {
    ...actualReactNavigation,
    useNavigation: () => ({
      goBack: mockGoBack,
      navigate: jest.fn(),
    }),
  };
});

jest.mock('react-native-safe-area-context', () => ({
  useSafeAreaInsets: () => ({ top: 48, bottom: 34, left: 0, right: 0 }),
}));

jest.mock('../../../../../../locales/i18n', () => ({
  __esModule: true,
  default: { locale: 'en-US' },
  strings: (key: string) => {
    const map: Record<string, string> = {
      'money.how_it_works_page.header_title': 'Money',
      'money.how_it_works_page.section_title': 'How it works',
      'money.how_it_works_page.description_1':
        'Add mUSD into your Money account and earn up to 4% APY (variable) automatically. Funds go into a DeFi vault, administered by Veda with risk monitoring by Steakhouse Financial. The rate is generated by third-party DeFi platforms that deploy funds in blockchain protocols. No staking, no claiming, no lock-ups.',
      'money.how_it_works_page.description_2':
        'Your Money balance is your spending balance. Link your MetaMask Card to spend at 150M+ merchants worldwide. Your money keeps earning until the moment you use it.',
      'money.how_it_works_page.description_3':
        'Money account is powered by Monad.',
      'money.how_it_works_page.faq_title': 'FAQs',
      'money.how_it_works_page.faq_q1': 'What is a MetaMask Money Account?',
      'money.how_it_works_page.faq_a1': 'Money Account answer 1',
      'money.how_it_works_page.faq_q2': 'Is MetaMask Money Account safe?',
      'money.how_it_works_page.faq_a2': 'Money Account answer 2',
      'money.how_it_works_page.faq_q3':
        'Who controls my MetaMask Money Account?',
      'money.how_it_works_page.faq_a3': 'Money Account answer 3',
      'money.how_it_works_page.faq_q4': 'What are MetaMask Money Account fees?',
      'money.how_it_works_page.faq_a4': 'Money Account answer 4',
      'money.how_it_works_page.faq_q5':
        'How much can I earn with a MetaMask Money Account?',
      'money.how_it_works_page.faq_a5': 'Money Account answer 5',
      'money.how_it_works_page.faq_q6': 'Where does the yield come from?',
      'money.how_it_works_page.faq_a6': 'Money Account answer 6',
      'money.how_it_works_page.faq_q7':
        'Which tokens can I deposit into the Money Account?',
      'money.how_it_works_page.faq_a7': 'Money Account answer 7',
      'money.how_it_works_page.faq_q8':
        'Can I withdraw from the MetaMask Money Account anytime?',
      'money.how_it_works_page.faq_a8': 'Money Account answer 8',
      'money.how_it_works_page.faq_q9':
        'Do I need to complete KYC to use MetaMask Money Account?',
      'money.how_it_works_page.faq_a9': 'Money Account answer 9',
      'money.how_it_works_page.faq_q10':
        'Which countries is MetaMask Money Account available in?',
      'money.how_it_works_page.faq_a10': 'Money Account answer 10',
    };
    return map[key] ?? key;
  },
}));

describe('MoneyHowItWorksView', () => {
  beforeEach(() => {
    jest.clearAllMocks();
    (useMoneyAnalytics as jest.Mock).mockReturnValue({
      trackScreenViewed: mockTrackScreenViewed,
    });
    (useMoneyAccountBalance as jest.Mock).mockReturnValue({
      apyPercent: 4,
    });
  });

  it('renders the section title', () => {
    const { getByTestId } = renderWithProvider(<MoneyHowItWorksView />);

    expect(
      getByTestId(MoneyHowItWorksViewTestIds.SECTION_TITLE),
    ).toBeOnTheScreen();
  });

  it('renders both description paragraphs', () => {
    const { getByTestId } = renderWithProvider(<MoneyHowItWorksView />);

    expect(
      getByTestId(MoneyHowItWorksViewTestIds.DESCRIPTION_1),
    ).toBeOnTheScreen();
    expect(
      getByTestId(MoneyHowItWorksViewTestIds.DESCRIPTION_2),
    ).toBeOnTheScreen();
  });

  it('renders the Monad attribution as the third description paragraph', () => {
    const { getByTestId, getByText } = renderWithProvider(
      <MoneyHowItWorksView />,
    );

    expect(
      getByTestId(MoneyHowItWorksViewTestIds.DESCRIPTION_3),
    ).toBeOnTheScreen();
    expect(getByText('Money account is powered by Monad.')).toBeOnTheScreen();
  });

  it('renders the FAQ title', () => {
    const { getByTestId } = renderWithProvider(<MoneyHowItWorksView />);

    expect(getByTestId(MoneyHowItWorksViewTestIds.FAQ_TITLE)).toBeOnTheScreen();
  });

  it('applies safe-area bottom padding to the scroll content', () => {
    const { getByTestId } = renderWithProvider(<MoneyHowItWorksView />);

    const scrollView = getByTestId(MoneyHowItWorksViewTestIds.SCROLL_VIEW);

    expect(scrollView.props.contentContainerStyle).toEqual(
      expect.objectContaining({ paddingBottom: 34 + 24 }),
    );
  });

  it('renders the "FAQs" FAQ header', () => {
    const { getByText } = renderWithProvider(<MoneyHowItWorksView />);

    expect(getByText('FAQs')).toBeOnTheScreen();
  });

  it('reveals the matching answer when a FAQ item is expanded', () => {
    const { getByTestId, getByText, queryByText } = renderWithProvider(
      <MoneyHowItWorksView />,
    );

    expect(queryByText('Money Account answer 1')).toBeNull();

    fireEvent.press(getByTestId(MoneyHowItWorksViewTestIds.FAQ_ITEM(1)));

    expect(getByText('Money Account answer 1')).toBeOnTheScreen();
  });

  it('renders all 10 FAQ questions', () => {
    const { getByText } = renderWithProvider(<MoneyHowItWorksView />);

    expect(getByText('What is a MetaMask Money Account?')).toBeOnTheScreen();
    expect(getByText('Is MetaMask Money Account safe?')).toBeOnTheScreen();
    expect(
      getByText('Who controls my MetaMask Money Account?'),
    ).toBeOnTheScreen();
    expect(
      getByText('What are MetaMask Money Account fees?'),
    ).toBeOnTheScreen();
    expect(
      getByText('How much can I earn with a MetaMask Money Account?'),
    ).toBeOnTheScreen();
    expect(getByText('Where does the yield come from?')).toBeOnTheScreen();
    expect(
      getByText('Which tokens can I deposit into the Money Account?'),
    ).toBeOnTheScreen();
    expect(
      getByText('Can I withdraw from the MetaMask Money Account anytime?'),
    ).toBeOnTheScreen();
    expect(
      getByText('Do I need to complete KYC to use MetaMask Money Account?'),
    ).toBeOnTheScreen();
    expect(
      getByText('Which countries is MetaMask Money Account available in?'),
    ).toBeOnTheScreen();
  });

  it('pressing the back button calls navigation.goBack', () => {
    const { getByTestId } = renderWithProvider(<MoneyHowItWorksView />);

    fireEvent.press(getByTestId(MoneyHowItWorksViewTestIds.BACK_BUTTON));

    expect(mockGoBack).toHaveBeenCalledTimes(1);
  });

  it('does not render a Sounds good primary CTA', () => {
    const { queryByText } = renderWithProvider(<MoneyHowItWorksView />);
    expect(queryByText('Sounds good')).toBeNull();
  });

  it('toggles a FAQ item when the question row is pressed', () => {
    const { getByTestId } = renderWithProvider(<MoneyHowItWorksView />);

    const firstFaq = getByTestId(MoneyHowItWorksViewTestIds.FAQ_ITEM(1));

    // Press once to expand, again to collapse — both branches of handlePress
    // (prev=false → 180deg, prev=true → 0deg) execute without throwing.
    fireEvent.press(firstFaq);
    fireEvent.press(firstFaq);

    expect(firstFaq).toBeOnTheScreen();
  });

  describe('analytics', () => {
    it('initialises useMoneyAnalytics with MONEY_HOW_IT_WORKS screen_name', () => {
      renderWithProvider(<MoneyHowItWorksView />);

      expect(useMoneyAnalytics).toHaveBeenCalledWith({
        screen_name: SCREEN_NAMES.MONEY_HOW_IT_WORKS,
      });
    });

    it('calls trackScreenViewed on mount', () => {
      renderWithProvider(<MoneyHowItWorksView />);

      expect(mockTrackScreenViewed).toHaveBeenCalledTimes(1);
    });
  });
});
