export const SocialProfileOnboardingSelectorsIDs = {
  CONTAINER: 'social-profile-onboarding',
  HEADER: 'social-profile-onboarding-header',
  BACK_BUTTON: 'social-profile-onboarding-back-button',
  CLOSE_BUTTON: 'social-profile-onboarding-close-button',
  PROGRESS: 'social-profile-onboarding-progress',
  INTRO: 'social-profile-onboarding-intro',
  CONNECT_X_BUTTON: 'social-profile-onboarding-connect-x-button',
  CREATE_MANUALLY_BUTTON: 'social-profile-onboarding-create-manually-button',
  USERNAME_STEP: 'social-profile-onboarding-username-step',
  USERNAME_INPUT: 'social-profile-onboarding-username-input',
  SHUFFLE_USERNAME_BUTTON: 'social-profile-onboarding-shuffle-username-button',
  USERNAME_STATUS: 'social-profile-onboarding-username-status',
  DISPLAY_NAME_INPUT: 'social-profile-onboarding-display-name-input',
  AVATAR_STEP: 'social-profile-onboarding-avatar-step',
  AVATAR_PREVIEW: 'social-profile-onboarding-avatar-preview',
  AVATAR_OPTION: 'social-profile-onboarding-avatar-option',
  CAMERA_BUTTON: 'social-profile-onboarding-camera-button',
  PHOTOS_BUTTON: 'social-profile-onboarding-photos-button',
  ACCOUNT_STEP: 'social-profile-onboarding-account-step',
  ACCOUNT_ROW: 'social-profile-onboarding-account-row',
  SHARE_ACTIVITY_SWITCH: 'social-profile-onboarding-share-activity-switch',
  READY_STEP: 'social-profile-onboarding-ready-step',
  READY_HANDLE: 'social-profile-onboarding-ready-handle',
  CONTINUE_BUTTON: 'social-profile-onboarding-continue-button',
  LETS_GO_BUTTON: 'social-profile-onboarding-lets-go-button',
} as const;
