/**
 * TX Sentinel `/networks` response body (chainId string keys).
 * Shared by default mocks and Polygon relay E2E overrides (e.g. POLYMARKET_POLYGON_RELAY_NETWORK_FLAGS_MOCKS).
 */
export const TX_SENTINEL_NETWORKS_MAP = {
  '1': {
    name: 'Mainnet',
    group: 'ethereum',
    chainID: 1,
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    network: 'ethereum-mainnet',
    explorer: 'https://etherscan.io',
    confirmations: true,
    smartTransactions: true,
    relayTransactions: true,
    hidden: false,
    sendBundle: true,
  },
  '10': {
    name: 'Optimism Mainnet',
    group: 'optimism',
    chainID: 10,
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    network: 'optimism-mainnet',
    explorer: 'https://optimistic.etherscan.io',
    confirmations: true,
    smartTransactions: false,
    relayTransactions: false,
    hidden: false,
    sendBundle: false,
  },
  '11155111': {
    name: 'Sepolia',
    group: 'ethereum',
    chainID: 11155111,
    nativeCurrency: {
      name: 'SepoliaETH',
      symbol: 'ETH',
      decimals: 18,
    },
    network: 'ethereum-sepolia',
    explorer: 'https://sepolia.etherscan.io',
    confirmations: true,
    smartTransactions: true,
    relayTransactions: false,
    hidden: false,
    sendBundle: false,
  },
  '1329': {
    name: 'Sei Mainnet',
    group: 'sei',
    chainID: 1329,
    nativeCurrency: {
      name: 'SEI',
      symbol: 'SEI',
      decimals: 18,
    },
    network: 'sei-mainnet',
    explorer: 'https://seitrace.com',
    confirmations: true,
    smartTransactions: false,
    relayTransactions: false,
    hidden: false,
    sendBundle: false,
  },
  '137': {
    name: 'Polygon Mainnet',
    group: 'polygon',
    chainID: 137,
    nativeCurrency: {
      name: 'MATIC',
      symbol: 'MATIC',
      decimals: 18,
    },
    network: 'polygon-mainnet',
    explorer: 'https://polygonscan.com/',
    confirmations: true,
    smartTransactions: false,
    relayTransactions: false,
    hidden: false,
    sendBundle: false,
  },
  '143': {
    name: 'Monad Mainnet',
    group: 'monad',
    chainID: 143,
    nativeCurrency: {
      name: 'MON',
      symbol: 'MON',
      decimals: 18,
    },
    network: 'monad-mainnet',
    explorer: 'https://monadscan.com/',
    confirmations: true,
    smartTransactions: false,
    relayTransactions: false,
    hidden: false,
    sendBundle: false,
  },
  '42161': {
    name: 'Arbitrum Mainnet',
    group: 'arbitrum',
    chainID: 42161,
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    network: 'arbitrum-mainnet',
    explorer: 'https://arbiscan.io/',
    confirmations: true,
    smartTransactions: true,
    relayTransactions: false,
    hidden: false,
    sendBundle: false,
  },
  '43114': {
    name: 'Avalanche Mainnet',
    group: 'avalanche',
    chainID: 43114,
    nativeCurrency: {
      name: 'AVAX',
      symbol: 'AVAX',
      decimals: 18,
    },
    network: 'avalanche-mainnet',
    explorer: 'https://avascan.info/',
    confirmations: true,
    smartTransactions: false,
    relayTransactions: false,
    hidden: false,
    sendBundle: false,
  },
  '56': {
    name: 'BNB Smart Chain',
    group: 'bnb',
    chainID: 56,
    nativeCurrency: {
      name: 'BNB',
      symbol: 'BNB',
      decimals: 18,
    },
    network: 'bsc-mainnet',
    explorer: 'https://bscscan.com/',
    confirmations: true,
    smartTransactions: true,
    relayTransactions: true,
    hidden: false,
    sendBundle: true,
  },
  '59144': {
    name: 'Linea Mainnet',
    group: 'linea',
    chainID: 59144,
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    network: 'linea-mainnet',
    explorer: 'https://lineascan.build',
    confirmations: true,
    smartTransactions: false,
    relayTransactions: false,
    hidden: false,
    sendBundle: false,
  },
  '8453': {
    name: 'Base Mainnet',
    group: 'base',
    chainID: 8453,
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    network: 'base-mainnet',
    explorer: 'https://basescan.org',
    confirmations: true,
    smartTransactions: true,
    relayTransactions: true,
    hidden: false,
    sendBundle: false,
  },
};
