// Legacy Aggregator SDK countries response for GET .../regions/countries.
// The old @consensys/on-ramp-sdk Country shape uses `support`, `unsupported`,
// and `enableSell`, not `supported`.
export const RAMPS_AGGREGATOR_COUNTRIES_RESPONSE = [
  {
    id: '/regions/pt',
    name: 'Portugal',
    emoji: '🇵🇹',
    currencies: ['/currencies/fiat/eur'],
    unsupported: false,
    hidden: false,
    states: [],
    support: {
      buy: true,
      sell: true,
      recurringBuy: true,
    },
    recommended: false,
    enableSell: true,
    detected: false,
  },
  {
    id: '/regions/fr',
    name: 'France',
    emoji: '🇫🇷',
    currencies: ['/currencies/fiat/eur'],
    unsupported: false,
    hidden: false,
    states: [],
    support: {
      buy: true,
      sell: true,
      recurringBuy: true,
    },
    recommended: false,
    enableSell: true,
    detected: false,
  },
  {
    id: '/regions/us',
    name: 'United States of America',
    emoji: '🇺🇸',
    currencies: ['/currencies/fiat/usd'],
    unsupported: false,
    hidden: false,
    states: [
      {
        id: '/regions/us-ca',
        name: 'California',
        stateId: 'CA',
        emoji: '🇺🇸',
        unsupported: false,
        support: {
          buy: true,
          sell: true,
          recurringBuy: true,
        },
        detected: false,
      },
    ],
    support: {
      buy: false,
      sell: false,
      recurringBuy: false,
    },
    recommended: false,
    enableSell: false,
    detected: false,
  },
  {
    id: '/regions/es',
    name: 'Spain',
    emoji: '🇪🇸',
    currencies: ['/currencies/fiat/eur'],
    unsupported: false,
    hidden: false,
    states: [],
    support: {
      buy: true,
      sell: true,
      recurringBuy: true,
    },
    recommended: false,
    enableSell: true,
    detected: false,
  },
  {
    id: '/regions/lc',
    name: 'Saint Lucia',
    emoji: '🇱🇨',
    currencies: ['/currencies/fiat/xcd'],
    unsupported: false,
    hidden: false,
    states: [],
    support: {
      buy: true,
      sell: true,
      recurringBuy: true,
    },
    recommended: false,
    enableSell: true,
    detected: false,
  },
];
