name: 'Restore Node Modules Executable Permissions'
description: 'Restores executable permissions for node_modules binaries after artifact download'

inputs:
  working-directory:
    description: 'Working directory where node_modules is located'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Restore executable permissions
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "🔧 Restoring executable permissions..."
        find node_modules/.bin -type f -exec chmod +x {} \; 2>/dev/null || true
        find node_modules -type f -name "*.node" -exec chmod +x {} \; 2>/dev/null || true
        find node_modules -path "*/bin/*" -type f -exec chmod +x {} \; 2>/dev/null || true
        find node_modules -path "*/sdks/*" -type f -exec chmod +x {} \; 2>/dev/null || true
        echo "✅ Permissions restored"
