export const KOL_DASHBOARD_SELECTORS = {
  TABS: 'rewards-kol-dashboard-tabs',
  TAB_WAYS_TO_EARN: 'rewards-kol-tab-ways-to-earn',
  TAB_EARNINGS: 'rewards-kol-tab-earnings',
  TAB_EARNINGS_DOT: 'rewards-kol-tab-earnings-dot',
  REFERRAL_HERO: 'rewards-kol-referral-hero',
  REFERRAL_CODE: 'rewards-kol-referral-code',
  SHARE_BUTTON: 'rewards-kol-share-button',
  REFERRALS_METRIC: 'rewards-kol-referrals-metric',
  TRADE_COMMISSIONS_METRIC: 'rewards-kol-trade-commissions-metric',
  SHARE_SHEET: 'rewards-kol-share-sheet',
  SHARE_VIA: 'rewards-kol-share-via',
  COPY_LINK: 'rewards-kol-copy-link',
  SHARE_MESSAGES: 'rewards-kol-share-messages',
  SHARE_TELEGRAM: 'rewards-kol-share-telegram',
  EARNINGS_TAB: 'rewards-kol-earnings-tab',
  AVAILABLE_TO_CLAIM: 'rewards-kol-available-to-claim',
  CLAIM_BUTTON: 'rewards-kol-claim-button',
  MONEY_FALL: 'rewards-kol-money-fall',
  PERFORMANCE_VIEW: 'rewards-kol-performance-view',
  PERFORMANCE_FUNNEL: 'rewards-kol-performance-funnel',
} as const;
