// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
  require('../app/component-library/components/Accordions/Accordion/Accordion.stories');
  require('../app/component-library/components/Accordions/Accordion/foundation/AccordionHeader/AccordionHeader.stories');
  require('../app/component-library/components/Avatars/Avatar/Avatar.stories');
  require('../app/component-library/components/Avatars/Avatar/variants/AvatarAccount/AvatarAccount.stories');
  require('../app/component-library/components/Avatars/Avatar/variants/AvatarFavicon/AvatarFavicon.stories');
  require('../app/component-library/components/Avatars/Avatar/variants/AvatarIcon/AvatarIcon.stories');
  require('../app/component-library/components/Avatars/Avatar/variants/AvatarNetwork/AvatarNetwork.stories');
  require('../app/component-library/components/Avatars/Avatar/variants/AvatarToken/AvatarToken.stories');
  require('../app/component-library/components/Avatars/AvatarGroup/AvatarGroup.stories');
  require('../app/component-library/components/Badges/Badge/Badge.stories');
  require('../app/component-library/components/Badges/Badge/variants/BadgeNetwork/BadgeNetwork.stories');
  require('../app/component-library/components/Badges/Badge/variants/BadgeStatus/BadgeStatus.stories');
  require('../app/component-library/components/Badges/BadgeWrapper/BadgeWrapper.stories');
  require('../app/component-library/components/Banners/Banner/Banner.stories');
  require('../app/component-library/components/Banners/Banner/variants/BannerAlert/BannerAlert.stories');
  require('../app/component-library/components/Banners/Banner/variants/BannerTip/BannerTip.stories');
  require('../app/component-library/components/BottomSheets/BottomSheetContent/BottomSheetContent.stories');
  require('../app/component-library/components/BottomSheets/BottomSheetFooter/BottomSheetFooter.stories');
  require('../app/component-library/components/BottomSheets/BottomSheetHeader/BottomSheetHeader.stories');
  require('../app/component-library/components/BottomSheets/BottomSheetOverlay/BottomSheetOverlay/BottomSheetOverlay.stories');
  require('../app/component-library/components/Buttons/Button/Button.stories');
  require('../app/component-library/components/Buttons/Button/foundation/ButtonBase/ButtonBase.stories');
  require('../app/component-library/components/Buttons/Button/variants/ButtonLink/ButtonLink.stories');
  require('../app/component-library/components/Buttons/Button/variants/ButtonPrimary/ButtonPrimary.stories');
  require('../app/component-library/components/Buttons/Button/variants/ButtonSecondary/ButtonSecondary.stories');
  require('../app/component-library/components/Buttons/ButtonIcon/ButtonIcon.stories');
  require('../app/component-library/components/Cards/Card/Card.stories');
  require('../app/component-library/components/Cells/Cell/Cell.stories');
  require('../app/component-library/components/Cells/Cell/variants/CellDisplay/CellDisplay.stories');
  require('../app/component-library/components/Cells/Cell/variants/CellMultiSelect/CellMultiSelect.stories');
  require('../app/component-library/components/Cells/Cell/variants/CellSelect/CellSelect.stories');
  require('../app/component-library/components/Checkbox/Checkbox.stories');
  require('../app/component-library/components/Form/HelpText/HelpText.stories');
  require('../app/component-library/components/Form/Label/Label.stories');
  require('../app/component-library/components/Form/TextField/TextField.stories');
  require('../app/component-library/components/Form/TextFieldSearch/TextFieldSearch.stories');
  require('../app/component-library/components/Header/Header.stories');
  require('../app/component-library/components/Icons/Icon/Icon.stories');
  require('../app/component-library/components/List/ListItem/ListItem.stories');
  require('../app/component-library/components/Modals/ModalConfirmation/ModalConfirmation.stories');
  require('../app/component-library/components/Modals/ModalMandatory/ModalMandatory.stories');
  require('../app/component-library/components/Navigation/TabBar/TabBar.stories');
  require('../app/component-library/components/Navigation/TabBarItem/TabBarItem.stories');
  require('../app/component-library/components/Overlay/Overlay.stories');
  require('../app/component-library/components/Pickers/PickerAccount/PickerAccount.stories');
  require('../app/component-library/components/Pickers/PickerBase/PickerBase.stories');
  require('../app/component-library/components/Pickers/PickerNetwork/PickerNetwork.stories');
  require('../app/component-library/components/Select/MultiSelect/MultiSelectItem/MultiSelectItem.stories');
  require('../app/component-library/components/Select/Select/SelectItem/SelectItem.stories');
  require('../app/component-library/components/Sheet/SheetBottom/SheetBottom.stories');
  require('../app/component-library/components/Sheet/SheetHeader/SheetHeader.stories');
  require('../app/component-library/components/Tags/Tag/Tag.stories');
  require('../app/component-library/components/Tags/TagUrl/TagUrl.stories');
  require('../app/component-library/components/Texts/Text/Text.stories');
  require('../app/component-library/components/Texts/TextWithPrefixIcon/TextWithPrefixIcon.stories');
  require('../app/component-library/components/Toast/Toast.stories');
  require('../app/components/Base/Alert.stories');
  require('../app/components/Base/ListItem.stories');
  require('../app/components/Base/Text/Text.stories');
  require('../app/components/Base/Title.stories');
  require('../app/components/UI/ButtonReveal/ButtonReveal.stories');
  require('../app/components/UI/Fox/Fox.stories');
  require('../app/components/UI/StyledButton/StyledButton.stories');
  require('../app/components/UI/TextEstimated/TextEstimated.stories');
  require('../app/components/UI/WarningAlert/WarningAlert.stories');
  require('../app/component-library/components-temp/Accounts/AccountBalance/AccountBalance.stories');
  require('../app/component-library/components-temp/Contracts/ContractBox/ContractBox.stories');
  require('../app/component-library/components-temp/CustomSpendCap/CustomSpendCap.stories');
}

const stories = [
  '../app/component-library/components/Accordions/Accordion/Accordion.stories',
  '../app/component-library/components/Accordions/Accordion/foundation/AccordionHeader/AccordionHeader.stories',
  '../app/component-library/components/Avatars/Avatar/Avatar.stories',
  '../app/component-library/components/Avatars/Avatar/variants/AvatarAccount/AvatarAccount.stories',
  '../app/component-library/components/Avatars/Avatar/variants/AvatarFavicon/AvatarFavicon.stories',
  '../app/component-library/components/Avatars/Avatar/variants/AvatarIcon/AvatarIcon.stories',
  '../app/component-library/components/Avatars/Avatar/variants/AvatarNetwork/AvatarNetwork.stories',
  '../app/component-library/components/Avatars/Avatar/variants/AvatarToken/AvatarToken.stories',
  '../app/component-library/components/Avatars/AvatarGroup/AvatarGroup.stories',
  '../app/component-library/components/Badges/Badge/Badge.stories',
  '../app/component-library/components/Badges/Badge/variants/BadgeNetwork/BadgeNetwork.stories',
  '../app/component-library/components/Badges/Badge/variants/BadgeStatus/BadgeStatus.stories',
  '../app/component-library/components/Badges/BadgeWrapper/BadgeWrapper.stories',
  '../app/component-library/components/Banners/Banner/Banner.stories',
  '../app/component-library/components/Banners/Banner/variants/BannerAlert/BannerAlert.stories',
  '../app/component-library/components/Banners/Banner/variants/BannerTip/BannerTip.stories',
  '../app/component-library/components/BottomSheets/BottomSheetContent/BottomSheetContent.stories',
  '../app/component-library/components/BottomSheets/BottomSheetFooter/BottomSheetFooter.stories',
  '../app/component-library/components/BottomSheets/BottomSheetHeader/BottomSheetHeader.stories',
  '../app/component-library/components/BottomSheets/BottomSheetOverlay/BottomSheetOverlay/BottomSheetOverlay.stories',
  '../app/component-library/components/Buttons/Button/Button.stories',
  '../app/component-library/components/Buttons/Button/foundation/ButtonBase/ButtonBase.stories',
  '../app/component-library/components/Buttons/Button/variants/ButtonLink/ButtonLink.stories',
  '../app/component-library/components/Buttons/Button/variants/ButtonPrimary/ButtonPrimary.stories',
  '../app/component-library/components/Buttons/Button/variants/ButtonSecondary/ButtonSecondary.stories',
  '../app/component-library/components/Buttons/ButtonIcon/ButtonIcon.stories',
  '../app/component-library/components/Cards/Card/Card.stories',
  '../app/component-library/components/Cells/Cell/Cell.stories',
  '../app/component-library/components/Cells/Cell/variants/CellDisplay/CellDisplay.stories',
  '../app/component-library/components/Cells/Cell/variants/CellMultiSelect/CellMultiSelect.stories',
  '../app/component-library/components/Cells/Cell/variants/CellSelect/CellSelect.stories',
  '../app/component-library/components/Checkbox/Checkbox.stories',
  '../app/component-library/components/Form/HelpText/HelpText.stories',
  '../app/component-library/components/Form/Label/Label.stories',
  '../app/component-library/components/Form/TextField/TextField.stories',
  '../app/component-library/components/Form/TextFieldSearch/TextFieldSearch.stories',
  '../app/component-library/components/Header/Header.stories',
  '../app/component-library/components/Icons/Icon/Icon.stories',
  '../app/component-library/components/List/ListItem/ListItem.stories',
  '../app/component-library/components/Modals/ModalConfirmation/ModalConfirmation.stories',
  '../app/component-library/components/Modals/ModalMandatory/ModalMandatory.stories',
  '../app/component-library/components/Navigation/TabBar/TabBar.stories',
  '../app/component-library/components/Navigation/TabBarItem/TabBarItem.stories',
  '../app/component-library/components/Overlay/Overlay.stories',
  '../app/component-library/components/Pickers/PickerAccount/PickerAccount.stories',
  '../app/component-library/components/Pickers/PickerBase/PickerBase.stories',
  '../app/component-library/components/Pickers/PickerNetwork/PickerNetwork.stories',
  '../app/component-library/components/Select/MultiSelect/MultiSelectItem/MultiSelectItem.stories',
  '../app/component-library/components/Select/Select/SelectItem/SelectItem.stories',
  '../app/component-library/components/Sheet/SheetBottom/SheetBottom.stories',
  '../app/component-library/components/Sheet/SheetHeader/SheetHeader.stories',
  '../app/component-library/components/Tags/Tag/Tag.stories',
  '../app/component-library/components/Tags/TagUrl/TagUrl.stories',
  '../app/component-library/components/Texts/Text/Text.stories',
  '../app/component-library/components/Texts/TextWithPrefixIcon/TextWithPrefixIcon.stories',
  '../app/component-library/components/Toast/Toast.stories',
  '../app/components/Base/Alert.stories',
  '../app/components/Base/ListItem.stories',
  '../app/components/Base/Text/Text.stories',
  '../app/components/Base/Title.stories',
  '../app/components/UI/ButtonReveal/ButtonReveal.stories',
  '../app/components/UI/Fox/Fox.stories',
  '../app/components/UI/StyledButton/StyledButton.stories',
  '../app/components/UI/TextEstimated/TextEstimated.stories',
  '../app/components/UI/WarningAlert/WarningAlert.stories',
  '../app/component-library/components-temp/Accounts/AccountBalance/AccountBalance.stories',
  '../app/component-library/components-temp/Contracts/ContractBox/ContractBox.stories',
  '../app/component-library/components-temp/CustomSpendCap/CustomSpendCap.stories',
];

module.exports = {
  loadStories,
  stories,
};
