/**
 * Component-view-style test for a perps "Position summary" view, AFTER
 * applying the fixture + contract layers.
 *
 * Mirrors the pattern of `widgetView.view.test.ts` for PerpsMini:
 *   - mocked controller slice comes from a fixture generated by the
 *     controller's own unit test (not hand-written)
 *   - the slice is fed through `mockPerpsMiniState`, which throws if the
 *     shape doesn't match what the controller actually produces
 */
import * as fs from 'fs';
import * as path from 'path';
import { mockPerpsMiniState } from './perpsMiniContract';
import {
  selectPosition,
  selectPositionSide,
  selectPositionValueUsd,
  selectOpenSymbols,
} from '../src/perpsSelectors';

const fixturePath = path.join(__dirname, '__fixtures__', 'perpsBtcLong.json');

describe('PositionSummary view (component-view style, contract-checked)', () => {
  it('reads the BTC long from the shared fixture', () => {
    const raw = JSON.parse(fs.readFileSync(fixturePath, 'utf-8'));
    const state = mockPerpsMiniState(raw);

    expect(selectOpenSymbols(state)).toEqual(['BTC']);
    expect(selectPositionSide(state, 'BTC')).toBe('long');
    expect(selectPosition(state, 'BTC')?.size).toBe(1);
    expect(selectPositionValueUsd(state, 'BTC')).toBe(50_000);
  });

  it('reports flat for symbols with no position', () => {
    const raw = JSON.parse(fs.readFileSync(fixturePath, 'utf-8'));
    const state = mockPerpsMiniState(raw);

    expect(selectPositionSide(state, 'ETH')).toBe('flat');
    expect(selectPositionValueUsd(state, 'ETH')).toBe(0);
  });

  it('rejects a hand-rolled mock that drifts from the controller shape', () => {
    expect(() =>
      mockPerpsMiniState({
        positions: {
          BTC: { side: 'long', size: 1 } as any, // forgot markPrice
        },
      } as any),
    ).toThrow(/markPrice/);
  });

  it('rejects a hand-rolled mock with an invalid side value', () => {
    expect(() =>
      mockPerpsMiniState({
        positions: {
          BTC: { side: 'bull', size: 1, markPrice: 50_000 } as any,
        },
      } as any),
    ).toThrow(/side/);
  });
});
