
/**
 * Component-view-style test, AFTER applying the fixture + contract layers.
 *
 * This is what a `WidgetSummary.test.tsx` would look like in the real mobile
 * app: it imports the same selectors the component uses, drives them with a
 * mocked controller slice, and asserts the rendered/derived value.
 *
 * The two changes versus a typical CV test:
 *   1. The mocked slice comes from a fixture generated by the controller's
 *      own unit test (not hand-written).
 *   2. The slice is fed through `mockWidgetState`, which throws if the
 *      shape doesn't match what the controller actually produces.
 */
import * as fs from 'fs';
import * as path from 'path';
import { mockWidgetState } from './widgetStateContract';
import {
  selectWidgetTotalCents,
  selectWidgetCount,
} from '../src/widgetSelectors';

const fixturePath = path.join(__dirname, '__fixtures__', 'twoWidgetsAdded.json');

describe('WidgetSummary view (component-view style, contract-checked)', () => {
  it('renders total in cents using the shared fixture', () => {
    const raw = JSON.parse(fs.readFileSync(fixturePath, 'utf-8'));
    const state = mockWidgetState(raw); // throws if controller shape drifted

    expect(selectWidgetCount(state)).toBe(2);
    expect(selectWidgetTotalCents(state)).toBe(999 + 50);
  });

  it('rejects a hand-rolled mock that drifts from the controller shape', () => {
    expect(() =>
      mockWidgetState({
        // Forgot `priceCents` — exactly the kind of mistake a CV test would
        // make if writing mocks from memory.
        widgets: {
          'w-x': { id: 'w-x', label: 'oops', price: 1.0 } as any,
        },
        loading: false,
        lastSyncedAt: null,
      } as any),
    ).toThrow(/priceCents/);
  });
});
