// Export the RTK Query API slice and hooks
export {
  rewardsApi,
  useGenerateChallengeMutation,
  useLoginMutation,
  useLogoutMutation,
  useDevOnlyLoginMutation,
  useGetSubscriptionQuery,
  useJoinSubscriptionMutation,
  useGetAccountLifetimeSpendQuery,
  useGetTokenPricesQuery,
  useGetSeasonQuery,
  useGetSeasonStatusQuery,
  useGetPointsEventsQuery,
  useGetRewardsCatalogQuery,
  useGetRewardsQuery,
  useClaimRewardMutation,
  rewardsApiReducer,
  rewardsApiMiddleware,
} from './rewardsApi';
