import { TrendingViewSelectorsIDs as AppTrendingViewSelectorsIDs } from '../../../app/components/Views/TrendingView/TrendingView.testIds';
import { ExploreSearchScreenSelectorsIDs } from '../../../app/components/Views/TrendingView/Views/ExploreSearchScreen/ExploreSearchScreen.testIds';
import { CommonSelectorsIDs } from '../../../app/util/Common.testIds';

export const TrendingViewSelectorsIDs = {
  SEARCH_BUTTON: 'explore-view-search-button',
  BROWSER_BUTTON: 'trending-view-browser-button',
  SEARCH_INPUT: 'explore-view-search-input',
  SEARCH_TEXT_INPUT: 'explore-view-search-text-input',
  SEARCH_CANCEL_BUTTON: 'explore-search-cancel-button',
  SEARCH_PILL_ALL: ExploreSearchScreenSelectorsIDs.PILL_ALL,
  SEARCH_PILL_CRYPTOS: ExploreSearchScreenSelectorsIDs.PILL_CRYPTOS,
  TOKEN_ROW_ITEM_PREFIX: 'trending-token-row-item-',
  PERPS_ROW_ITEM_PREFIX: 'perps-market-tile-card-',
  PREDICTIONS_ROW_ITEM_PREFIX: 'predict-market-row-item-',
  SITE_ROW_ITEM_PREFIX: 'site-row-item-',
  NOW_SCROLL_VIEW: AppTrendingViewSelectorsIDs.EXPLORE_NOW_SCROLL_VIEW,
  RWAS_SCROLL_VIEW: AppTrendingViewSelectorsIDs.EXPLORE_RWAS_SCROLL_VIEW,
  CRYPTO_SCROLL_VIEW: AppTrendingViewSelectorsIDs.EXPLORE_CRYPTO_SCROLL_VIEW,
  DAPPS_SCROLL_VIEW: AppTrendingViewSelectorsIDs.EXPLORE_DAPPS_SCROLL_VIEW,
  SEARCH_RESULTS_LIST: 'trending-search-results-list',
  VIEW_ALL_BUTTON_PREFIX: 'section-header-view-all-',
} as const;

export const TrendingViewSelectorsText = {
  SECTION_PREDICTIONS: 'Predictions',
  SECTION_TOKENS: 'Trending',
  SECTION_STOCKS: 'Stocks',
  SECTION_PERPS: 'Perps',
  SECTION_SITES: 'Sites',
} as const;

// Generated by TabsBar as `${TabsList testID}-bar-tab-${index}`.
export const TrendingTabTestIDs = {
  NOW: 'explore-tabs-bar-tab-0',
  RWAS: 'explore-tabs-bar-tab-2',
  CRYPTO: 'explore-tabs-bar-tab-3',
  SITES: 'explore-tabs-bar-tab-5',
} as const;

export const SECTION_TAB_CONFIG: Record<
  string,
  { tabTestID: string; scrollViewTestID: string }
> = {
  [TrendingViewSelectorsText.SECTION_PREDICTIONS]: {
    tabTestID: TrendingTabTestIDs.NOW,
    scrollViewTestID: TrendingViewSelectorsIDs.NOW_SCROLL_VIEW,
  },
  [TrendingViewSelectorsText.SECTION_TOKENS]: {
    tabTestID: TrendingTabTestIDs.CRYPTO,
    scrollViewTestID: TrendingViewSelectorsIDs.CRYPTO_SCROLL_VIEW,
  },
  [TrendingViewSelectorsText.SECTION_PERPS]: {
    tabTestID: TrendingTabTestIDs.NOW,
    scrollViewTestID: TrendingViewSelectorsIDs.NOW_SCROLL_VIEW,
  },
  [TrendingViewSelectorsText.SECTION_STOCKS]: {
    tabTestID: TrendingTabTestIDs.RWAS,
    scrollViewTestID: TrendingViewSelectorsIDs.RWAS_SCROLL_VIEW,
  },
  [TrendingViewSelectorsText.SECTION_SITES]: {
    tabTestID: TrendingTabTestIDs.SITES,
    scrollViewTestID: TrendingViewSelectorsIDs.DAPPS_SCROLL_VIEW,
  },
};

// Map section to its full view back button Test ID
export const SECTION_BACK_BUTTONS: Record<string, string> = {
  [TrendingViewSelectorsText.SECTION_TOKENS]:
    'trending-tokens-header-back-button',
  [TrendingViewSelectorsText.SECTION_STOCKS]: 'rwa-tokens-header-back-button',
  [TrendingViewSelectorsText.SECTION_PERPS]:
    'perps-market-list-close-button-back-button',
  [TrendingViewSelectorsText.SECTION_SITES]:
    'sites-full-view-header-back-button',
  [TrendingViewSelectorsText.SECTION_PREDICTIONS]: 'back-button',
};

// Map item type to its details page back button Test ID
export const DETAILS_BACK_BUTTONS: Record<string, string> = {
  token: CommonSelectorsIDs.BACK_ARROW_BUTTON,
  perp: 'perps-market-header-back-button',
  prediction: 'predict-market-details-back-button',
};

// Map section to its full view header Test ID
export const SECTION_FULL_VIEW_HEADERS: Record<string, string> = {
  [TrendingViewSelectorsText.SECTION_SITES]: 'sites-full-view-header',
  [TrendingViewSelectorsText.SECTION_TOKENS]: 'trending-tokens-header',
  [TrendingViewSelectorsText.SECTION_STOCKS]: 'rwa-tokens-header',
  [TrendingViewSelectorsText.SECTION_PERPS]: 'perps-market-list-close-button',
  [TrendingViewSelectorsText.SECTION_PREDICTIONS]: 'back-button', // PredictFeed uses back-button as main identifier
};
