name: 'Save Build Fingerprint'
description: 'Save fingerprint and cache build artifacts after successful build (Cross-platform)'
inputs:
  platform:
    description: 'Platform (android or ios)'
    required: true
  artifacts_path:
    description: 'Path to artifacts to cache'
    required: true
  pr_number:
    description: 'Pull request number for caching'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Generate and save fingerprint
      id: fingerprint
      shell: bash
      run: |
        # Set environment variables from inputs
        INPUT_PLATFORM="${{ inputs.platform }}"
        INPUT_ARTIFACTS_PATH="${{ inputs.artifacts_path }}"
        INPUT_PR_NUMBER="${{ inputs.pr_number }}"

        echo "Generating fingerprint for $INPUT_PLATFORM..."
        FINGERPRINT=$(yarn -s fingerprint:generate)
        
        if [ -z "$FINGERPRINT" ]; then
          echo "❌ Error: Failed to generate fingerprint"
          exit 1
        fi
        
        echo "$FINGERPRINT" > .app-native-fingerprint
        echo "✅ Fingerprint saved: $FINGERPRINT"
        echo "fingerprint=$FINGERPRINT" >> "$GITHUB_OUTPUT"

    - name: Cache build artifacts for future reuse
      uses: actions/cache@v4
      with:
        path: ${{ inputs.artifacts_path }}
        key: ${{ inputs.platform }}-artifacts-${{ inputs.pr_number || 'main' }}-${{ hashFiles('.app-native-fingerprint') }}

    - name: Save fingerprint cache
      uses: actions/cache@v4
      with:
        path: .app-native-fingerprint
        key: fingerprint-${{ inputs.platform }}-${{ inputs.pr_number || 'main' }}-${{ github.sha }}
