// Phase 4a cutover: the WebView now runs the modular TypeScript bundle
// generated by `yarn build:advanced-chart-webview` (source under `src/`)
// rather than the legacy `chartLogic.js` inlined via `syncChartLogic.js`.
//
// The legacy `chartLogicString.ts` remains on disk as an orphaned file so
// this cutover is a single-line revert if anything regresses in production.
// It is deleted alongside `chartLogic.js` in Phase 7.
export { default as chartLogicScript } from './chartLogicString.modular';
