/* eslint-disable import/prefer-default-export */
export const NOTIFICATIONS_ERRORS = {
  FAILED_TO_DELETE_NOTIFICATIONS: 'FAILED_TO_DELETE_NOTIFICATIONS',
  FAILED_TO_MARK_AS_READ_NOTIFICATIONS: 'FAILED_TO_MARK_AS_READ_NOTIFICATIONS',
  FAILED_TO_FETCH_NOTIFICATIONS: 'FAILED_TO_FETCH_NOTIFICATIONS',
  FAILED_TO_SET_NOTIFICATIONS_FEATURE_SEEN:
    'FAILED_TO_SET_NOTIFICATIONS_FEATURE_SEEN',
  FAILED_TO_CHECK_ACCOUNTS_PRESENCE: 'FAILED_TO_CHECK_ACCOUNTS_PRESENCE',
  FAILED_TO_ENABLE_PARTICIPATE_IN_META_METRICS:
    'FAILED_TO_ENABLE_PARTICIPATE_IN_META_METRICS',
  FAILED_TO_ENABLE_SNAP_NOTIFICATIONS: 'FAILED_TO_ENABLE_SNAP_NOTIFICATIONS',
  FAILED_TO_ENABLE_FEATURE_NOTIFICATIONS:
    'FAILED_TO_ENABLE_FEATURE_NOTIFICATIONS',
  FAILED_TO_DISABLE_METAMASK_NOTIFICATIONS:
    'FAILED_TO_DISABLE_METAMASK_NOTIFICATIONS',
  FAILED_TO_ENABLE_METAMASK_NOTIFICATIONS:
    'FAILED_TO_ENABLE_METAMASK_NOTIFICATIONS',
  FAILED_TO_DISABLE_PROFILE_SYNCING: 'FAILED_TO_DISABLE_PROFILE_SYNCING',
  FAILED_TO_ENABLE_PROFILE_SYNCING: 'FAILED_TO_ENABLE_PROFILE_SYNCING',
  FAILED_TO_SIGN_OUT: 'FAILED_TO_SIGN_OUT',
  FAILED_TO_SIGN_IN: 'FAILED_TO_SIGN_IN',
  FAILED_TO_UPDATE_ON_CHAIN_TRIGGERS: 'FAILED_TO_UPDATE_ON_CHAIN_TRIGGERS',
  FAILED_TO_DELETE_ON_CHAIN_TRIGGERS: 'FAILED_TO_DELETE_ON_CHAIN_TRIGGERS',
  FAILED_TO_ENABLE_PUSH_NOTIFICATIONS: 'FAILED_TO_ENABLE_PUSH_NOTIFICATIONS',
  FAILED_TO_DISABLE_PUSH_NOTIFICATIONS: 'FAILED_TO_DISABLE_PUSH_NOTIFICATIONS',
  FAILED_TO_UPDATE_PUSH_NOTIFICATIONS_TRIGGERS:
    'FAILED_TO_UPDATE_PUSH_NOTIFICATIONS_TRIGGERS',
};
