export const CardHomeSelectors = {
  TRY_AGAIN_BUTTON: 'try-again-button',
  BALANCE_SKELETON: 'balance-skeleton',
  CARD_ASSET_ITEM_SKELETON: 'card-asset-item-skeleton',
  ADD_FUNDS_BUTTON_SKELETON: 'add-funds-button-skeleton',
  PRIVACY_TOGGLE_BUTTON: 'privacy-toggle-button',
  ADD_FUNDS_BUTTON: 'add-funds-button',
  CHANGE_ASSET_BUTTON: 'change-asset-button',
  ADVANCED_CARD_MANAGEMENT_ITEM: 'advanced-card-management-item',
  TRAVEL_ITEM: 'travel-item',
  CARD_TOS_ITEM: 'card-tos-item',
  LOGOUT_ITEM: 'logout-item',
  ENABLE_CARD_BUTTON: 'enable-card-button',
  ENABLE_ASSETS_BUTTON: 'enable-assets-button',
  MANAGE_SPENDING_LIMIT_ITEM: 'manage-spending-limit-item',
  CARD_VIEW_TITLE: 'card-view-title',
  ADD_FUNDS_BOTTOM_SHEET: 'add-funds-bottom-sheet',
  ADD_FUNDS_BOTTOM_SHEET_DEPOSIT_OPTION:
    'add-funds-bottom-sheet-deposit-option',
  ADD_FUNDS_BOTTOM_SHEET_SWAP_OPTION: 'add-funds-bottom-sheet-swap-option',
  SPENDING_LIMIT_PROGRESS_BAR_SKELETON: 'spending-limit-progress-bar-skeleton',
  VIEW_CARD_DETAILS_BUTTON: 'view-card-details-button',
  CARD_DETAILS_IMAGE: 'card-details-image',
  CARD_DETAILS_IMAGE_SKELETON: 'card-details-image-skeleton',
  PASSWORD_BOTTOM_SHEET: 'password-bottom-sheet',
  PASSWORD_INPUT: 'password-input',
  PASSWORD_ERROR: 'password-error',
  PASSWORD_CANCEL_BUTTON: 'password-cancel-button',
  PASSWORD_CONFIRM_BUTTON: 'password-confirm-button',
};
