export const CardHomeSelectors = {
  TRY_AGAIN_BUTTON: 'try-again-button',
  BALANCE_SKELETON: 'balance-skeleton',
  CARD_ASSET_ITEM_SKELETON: 'card-asset-item-skeleton',
  ADD_FUNDS_BUTTON_SKELETON: 'add-funds-button-skeleton',
  PRIVACY_TOGGLE_BUTTON: 'privacy-toggle-button',
  ADD_FUNDS_BUTTON: 'add-funds-button',
  CHANGE_ASSET_BUTTON: 'change-asset-button',
  TRAVEL_ITEM: 'travel-item',
  CARD_TOS_ITEM: 'card-tos-item',
  LOGOUT_ITEM: 'logout-item',
  ENABLE_CARD_BUTTON: 'enable-card-button',
  CONTACT_SUPPORT_ITEM: 'contact-support-item',
  MANAGE_SPENDING_LIMIT_ITEM: 'manage-spending-limit-item',
  UNLINK_MONEY_ACCOUNT_ITEM: 'unlink-money-account-item',
  CARD_VIEW_TITLE: 'card-view-title',
  ADD_FUNDS_BOTTOM_SHEET: 'add-funds-bottom-sheet',
  ADD_FUNDS_BOTTOM_SHEET_DEPOSIT_OPTION:
    'add-funds-bottom-sheet-deposit-option',
  ADD_FUNDS_BOTTOM_SHEET_SWAP_OPTION: 'add-funds-bottom-sheet-swap-option',
  SPENDING_LIMIT_PROGRESS_BAR_SKELETON: 'spending-limit-progress-bar-skeleton',
  VIEW_CARD_DETAILS_BUTTON: 'view-card-details-button',
  CARD_DETAILS_IMAGE: 'card-details-image',
  CARD_DETAILS_IMAGE_SKELETON: 'card-details-image-skeleton',
  CARD_SENSITIVE_DETAILS: 'card-sensitive-details',
  CARD_SENSITIVE_DETAILS_PAN: 'card-sensitive-details-pan',
  CARD_SENSITIVE_DETAILS_EXPIRY: 'card-sensitive-details-expiry',
  CARD_SENSITIVE_DETAILS_CVV: 'card-sensitive-details-cvv',
  CARD_SENSITIVE_DETAILS_NAME: 'card-sensitive-details-name',
  CARD_SENSITIVE_DETAILS_COPY: 'card-sensitive-details-copy',
  PASSWORD_BOTTOM_SHEET: 'password-bottom-sheet',
  PASSWORD_INPUT: 'password-input',
  PASSWORD_ERROR: 'password-error',
  PASSWORD_CANCEL_BUTTON: 'password-cancel-button',
  PASSWORD_CONFIRM_BUTTON: 'password-confirm-button',
  ORDER_METAL_CARD_ITEM: 'order-metal-card-item',
  CASHBACK_ITEM: 'cashback-item',
  FREEZE_CARD_TOGGLE: 'freeze-card-toggle',
  VIEW_PIN_BUTTON: 'view-pin-button',
  CARD_WALLET_ADDRESS: 'card-wallet-address',
  LINK_MONEY_ACCOUNT_DIVIDER_BOTTOM: 'link-money-account-divider-bottom',
  CREDIT_BALANCE_INFO_BUTTON: 'credit-balance-info-button',
  CREDIT_BANNER: 'credit-banner',
};
