// Only keep selectors that are actually used in tests
export const TestSnapViewSelectorWebIDS = {
  clearManageStateButton: 'clearManageState',
  clearStateButton: 'clearState',
  clearStateUnencryptedButton: 'clearStateUnencrypted',
  clearUnencryptedManageStateButton: 'clearUnencryptedManageState',
  connectBip32Button: 'connectbip32',
  connectBip44Button: 'connectbip44',
  connectClientStatusSnapButton: 'connectclient-status',
  connectDialogSnapButton: 'connectdialogs',
  connectGetEntropyButton: 'connectGetEntropySnap',
  connectGetPreferencesButton: 'connectpreferences',
  connectJsonRpcButton: 'connectjson-rpc',
  connectLifeCycleButton: 'connectlifecycle-hooks',
  connectManageStateButton: 'connectmanage-state',
  connectNetworkAccessButton: 'connectnetwork-access',
  connectEthereumProviderButton: 'connectethereum-provider',
  connectStateButton: 'connectstate',
  connectWasmButton: 'connectwasm',
  getPreferencesButton: 'getPreferences',
  getPublicKeyBip44Button: 'sendBip44Test',
  signMessageBip44Button: 'signBip44Message',
  getPublicKeyBip32Button: 'bip32GetPublic',
  getCompressedPublicKeyBip32Button: 'bip32GetCompressedPublic',
  signEntropyMessageButton: 'signEntropyMessage',
  signMessageBip32Secp256k1Button: 'sendBip32-secp256k1',
  signMessageBip32ed25519Button: 'sendBip32-ed25519',
  signMessageBip32ed25519Bip32Button: 'sendBip32-ed25519Bip32',
  sendAlertButton: 'sendAlertButton',
  sendClientStatusButton: 'sendClientStatusTest',
  sendConfirmationButton: 'sendConfirmationButton',
  sendCustomButton: 'sendCustomButton',
  sendGetStateButton: 'sendGetState',
  sendGetUnencryptedStateButton: 'sendGetUnencryptedState',
  sendManageStateButton: 'sendManageState',
  sendNetworkAccessTestButton: 'sendNetworkAccessTest',
  sendRpcButton: 'sendRpc',
  sendStateButton: 'sendState',
  sendUnencryptedManageStateButton: 'sendUnencryptedManageState',
  sendUnencryptedStateButton: 'sendUnencryptedState',
  startWebSocket: 'startWebSocket',
  stopWebSocket: 'stopWebSocket',
  getWebSocketState: 'getWebSocketState',
  getChainIdButton: 'sendEthprovider',
  getAccountsButton: 'sendEthproviderAccounts',
  personalSignButton: 'signPersonalSignMessage',
  sendWasmMessageButton: 'sendWasmMessage',
  signTypedDataButton: 'signTypedDataButton',
};

export const TestSnapInputSelectorWebIDS = {
  dataManageStateInput: 'dataManageState',
  dataStateInput: 'dataState',
  dataUnencryptedManageStateInput: 'dataUnencryptedManageState',
  dataUnencryptedStateInput: 'dataUnencryptedState',
  entropyMessageInput: 'entropyMessage',
  getStateInput: 'getState',
  getUnencryptedStateInput: 'getUnencryptedState',
  messageBip44Input: 'bip44Message',
  messageEd25519Bip32Input: 'bip32Message-ed25519Bip32',
  messageEd25519Input: 'bip32Message-ed25519',
  messageSecp256k1Input: 'bip32Message-secp256k1',
  setStateKeyInput: 'setStateKey',
  setStateKeyUnencryptedInput: 'setStateKeyUnencrypted',
  webSocketUrlInput: 'webSocketUrl',
  personalSignMessageInput: 'personalSignMessage',
  signTypedDataMessageInput: 'signTypedData',
  wasmInput: 'wasmInput',
};

export const EntropyDropDownSelectorWebIDS = {
  bip32EntropyDropDown: 'bip32-entropy-selector',
  bip44EntropyDropDown: 'bip44-entropy-selector',
  getEntropyDropDown: 'get-entropy-entropy-selector',
  networkDropDown: 'select-chain',
};

export const TestSnapResultSelectorWebIDS = {
  bip44ResultSpan: 'bip44Result',
  bip44SignResultSpan: 'bip44SignResult',
  bip32MessageResultEd25519Span: 'bip32MessageResult-ed25519',
  bip32MessageResultSecp256k1Span: 'bip32MessageResult-secp256k1',
  bip32MessageResultEd25519Bip32Span: 'bip32MessageResult-ed25519Bip32',
  bip32PublicKeyResultSpan: 'bip32PublicKeyResult',
  clearManageStateResultSpan: 'clearManageStateResult',
  clearUnencryptedManageStateResultSpan: 'clearUnencryptedManageStateResult',
  clientStatusResultSpan: 'clientStatusResult',
  dialogResultSpan: 'dialogResult',
  encryptedStateResultSpan: 'encryptedStateResult',
  entropySignResultSpan: 'entropySignResult',
  preferencesResultSpan: 'preferencesResult',
  getStateResultSpan: 'getStateResult',
  getStateUnencryptedResultSpan: 'getStateUnencryptedResult',
  networkAccessResultSpan: 'networkAccessResult',
  ethereumProviderResultSpan: 'ethproviderResult',
  personalSignResultSpan: 'personalSignResult',
  retrieveManageStateResultSpan: 'retrieveManageStateResult',
  retrieveManageStateUnencryptedResultSpan:
    'retrieveManageStateUnencryptedResult',
  rpcResultSpan: 'rpcResult',
  sendManageStateResultSpan: 'sendManageStateResult',
  sendUnencryptedManageStateResultSpan: 'sendUnencryptedManageStateResult',
  signTypedDataResultSpan: 'signTypedDataResult',
  unencryptedStateResultSpan: 'unencryptedStateResult',
  wasmResultSpan: 'wasmResult',
};

export const TestSnapBottomSheetSelectorWebIDS = {
  BOTTOMSHEET_FOOTER_BUTTON_ID: 'bottomsheetfooter-button-subsequent',
};
