export const TestDappSelectorsWebIDs = {
  CHAIN_ID_TEXT: 'chainId',
  TEST_DAPP_FOX_LOGO: 'mm-logo',
  TEST_DAPP_HEADING_TITLE: 'logo-text',
  APPROVE_ERC_20_TOKENS_BUTTON_ID: 'approveTokens',
  APPROVE_ERC_721_TOKEN_BUTTON_ID: 'approveButton',
  CONNECT_BUTTON: 'connectButton',
  ERC_20_SEND_TOKENS_TRANSFER_TOKENS_BUTTON_ID: 'transferTokens',
  INCREASE_ALLOWANCE_BUTTON_ID: 'increaseTokenAllowance',
  NFT_TRANSFER_FROM_BUTTON_ID: 'transferFromButton',
  PERSONAL_SIGN: 'personalSign',
  PERMIT_SIGN: 'signPermit',
  SET_APPROVAL_FOR_ALL_NFT_BUTTON_ID: 'setApprovalForAllButton',
  SET_APPROVAL_FOR_ALL_ERC1155_BUTTON_ID: 'setApprovalForAllERC1155Button',
  SIGN_TYPE_DATA: 'signTypedData',
  SIGN_TYPE_DATA_V3: 'signTypedDataV3',
  SIGN_TYPE_DATA_V4: 'signTypedDataV4',
  ETHEREUM_SIGN: 'siwe',
  ETHEREUM_SIGN_BAD_DOMAIN: 'siweBadDomain',
  ADD_TOKENS_TO_WALLET_BUTTON: 'watchAssets',
  SEND_FAILING_TRANSACTION_BUTTON_ID: 'sendFailingButton',
  BATCH_TRANSFER_ERC1155_BUTTON_ID: 'batchTransferFromButton',
  SWITCH_ETHEREUM_CHAIN: 'switchEthereumChain',
  ERC_721_MINT_BUTTON_ID: 'mintButton',
  SEND_EIP_1559_BUTTON_ID: 'sendEIP1559Button',
  DEPLOY_CONTRACT_BUTTON_ID: 'createToken',
  SEND_CALLS_BUTTON: 'eip5792SendCallsButton',
  ERC_721_REVOKE_APPROVAL_BUTTON_ID: 'revokeButton',
  ERC_1155_REVOKE_APPROVAL_BUTTON_ID: 'revokeERC1155Button',
  REVOKE_ACCOUNTS_PERMISSIONS: 'revokeAccountsPermission',
  REQUEST_PERMISSIONS: 'requestPermissions',
  OPEN_NETWORK_PICKER: 'openNetworkPicker',
} as const;

// Export type for the selector object
export type TestDappSelectorsWebIDsType = typeof TestDappSelectorsWebIDs;
