name: Bug report (Mobile)
description: Report a reproducible issue in MetaMask Mobile
title: "[Bug]: "
labels: ["bug", "mobile"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the issue.
      placeholder: What is going wrong?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Open the app
        2. Navigate to ...
        3. Tap on ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App version
      placeholder: e.g. v7.20.0
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Android
        - iOS
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Optional but helpful.
