/* eslint-disable import-x/no-nodejs-modules */
import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'fs';
import os from 'os';
import path from 'path';
import {
  ensureE2EProxyCa,
  getE2EProxyCaFilePaths,
  type ExecFileImpl,
} from './E2EProxyCa';

const createTempCaDirectory = () =>
  mkdtempSync(path.join(os.tmpdir(), 'metamask-e2e-proxy-ca-'));

const writeExistingCaFiles = (caDirectory: string) => {
  const paths = getE2EProxyCaFilePaths(caDirectory);
  mkdirSync(caDirectory, { recursive: true });
  writeFileSync(paths.certPemPath, 'existing pem');
  writeFileSync(paths.certDerPath, 'existing cer');
  writeFileSync(paths.keyPath, 'existing key');
  return paths;
};

const createSuccessfulOpenSslMock = () => {
  const calls: { file: string; args: string[] }[] = [];
  const execFileImpl: ExecFileImpl = (file, args, callback) => {
    const argsList = [...args];
    calls.push({ file, args: argsList });

    const outIndex = argsList.lastIndexOf('-out');
    if (outIndex >= 0) {
      writeFileSync(argsList[outIndex + 1], `generated by ${argsList[0]}`);
    }

    callback(null, '', '');
  };

  return { calls, execFileImpl };
};

describe('ensureE2EProxyCa', () => {
  let caDirectory: string;

  beforeEach(() => {
    caDirectory = createTempCaDirectory();
  });

  afterEach(() => {
    rmSync(caDirectory, { recursive: true, force: true });
  });

  it('returns existing CA paths without running OpenSSL when all files exist', async () => {
    const expectedPaths = writeExistingCaFiles(caDirectory);
    const execFileImpl: ExecFileImpl = () => {
      throw new Error('OpenSSL should not run when CA files already exist');
    };

    await expect(
      ensureE2EProxyCa({ caDirectory, execFileImpl }),
    ).resolves.toEqual(expectedPaths);
  });

  it('generates the private key, PEM certificate, and DER certificate when files are missing', async () => {
    const { calls, execFileImpl } = createSuccessfulOpenSslMock();
    const paths = getE2EProxyCaFilePaths(caDirectory);

    await expect(
      ensureE2EProxyCa({ caDirectory, execFileImpl }),
    ).resolves.toEqual(paths);

    expect(calls).toEqual([
      {
        file: 'openssl',
        args: ['genrsa', '-out', paths.keyPath, '2048'],
      },
      {
        file: 'openssl',
        args: [
          'req',
          '-x509',
          '-new',
          '-nodes',
          '-key',
          paths.keyPath,
          '-sha256',
          '-days',
          '3650',
          '-subj',
          '/CN=MetaMask Mobile E2E Proxy CA',
          '-out',
          paths.certPemPath,
        ],
      },
      {
        file: 'openssl',
        args: [
          'x509',
          '-in',
          paths.certPemPath,
          '-outform',
          'der',
          '-out',
          paths.certDerPath,
        ],
      },
    ]);
    expect(existsSync(paths.keyPath)).toBe(true);
    expect(existsSync(paths.certPemPath)).toBe(true);
    expect(existsSync(paths.certDerPath)).toBe(true);
  });

  it('throws a clear error when OpenSSL completes but the CA files are missing', async () => {
    const execFileImpl: ExecFileImpl = (_file, _args, callback) => {
      callback(null, '', '');
    };

    await expect(
      ensureE2EProxyCa({ caDirectory, execFileImpl }),
    ).rejects.toThrow('Failed to generate iOS E2E proxy CA');
  });
});
