/**
 * Browser actions for Redux
 */
export enum BrowserActionTypes {
  ADD_TO_VIEWED_DAPP = 'ADD_TO_VIEWED_DAPP',
  SET_BROWSER_REQUEST_LOAD = 'SET_BROWSER_REQUEST_LOAD',
  SET_BROWSER_LOAD_START = 'SET_BROWSER_LOAD_START',
  SET_BROWSER_LOAD_END = 'SET_BROWSER_LOAD_END',
}
