export const MyProfileViewSelectorsIDs = {
  CONTAINER: 'my-profile-view-container',
  HEADER: 'my-profile-view-header',
  BACK_BUTTON: 'my-profile-view-back-button',
  INSIGHTS_BUTTON: 'my-profile-view-insights-button',
  AVATAR: 'my-profile-view-avatar',
  DISPLAY_NAME: 'my-profile-view-display-name',
  HANDLE: 'my-profile-view-handle',
  RANKING_TAG: 'my-profile-view-ranking-tag',
  X_LINK: 'my-profile-view-x-link',
  BIO: 'my-profile-view-bio',
  FOLLOWERS_COUNT: 'my-profile-view-followers-count',
  FOLLOWING_COUNT: 'my-profile-view-following-count',
  EDIT_PROFILE_BUTTON: 'my-profile-view-edit-profile-button',
  SHARE_PROFILE_BUTTON: 'my-profile-view-share-profile-button',
  POSTS_TAB: 'my-profile-view-posts-tab',
  EMPTY_STATE: 'my-profile-view-empty-state',
  SHARE_FIRST_TRADE_BUTTON: 'my-profile-view-share-first-trade-button',
  LOADING: 'my-profile-view-loading',
  ERROR: 'my-profile-view-error',
  RETRY_BUTTON: 'my-profile-view-retry-button',
} as const;
