export const CardAuthenticationSelectors = {
  VERIFY_ACCOUNT_BUTTON: 'verify-account-button',
  SIGNUP_BUTTON: 'signup-button',
  EMAIL_FIELD: 'email-field',
  PASSWORD_FIELD: 'password-field',
  PASSWORD_VISIBILITY_TOGGLE: 'password-visibility-toggle',
  FORGOT_PASSWORD_BUTTON: 'forgot-password-button',
  LOGIN_ERROR_TEXT: 'login-error-text',
  US_LOCATION_BOX: 'us-location-box',
  INTERNATIONAL_LOCATION_BOX: 'international-location-box',
  UK_LOCATION_BOX: 'uk-location-box',
  UK_ACCOUNT_SELECT: 'uk-account-select',
  UK_LOGIN_ERROR_TEXT: 'uk-login-error-text',
  OTP_CODE_FIELD: 'otp-code-field',
  OTP_CODE_FIELD_ERROR: 'otp-code-field-error',
  OTP_CONFIRM_BUTTON: 'otp-confirm-button',
  OTP_BACK_TO_LOGIN_BUTTON: 'otp-back-to-login-button',
  OTP_RESEND_VERIFICATION: 'otp-resend-verification',
  OTP_ERROR_TEXT: 'otp-error-text',
};
