/**
 * Environment Extraction Script
 *
 * Reads build environment values from build-env.json generated during the build.
 *
 * The build-env.json is generated by: node scripts/apply-build-config.js <build-name> --write-build-env
 */

import { existsSync, readFileSync } from 'fs';
import type { EnvValidationResult } from './types';

// Build environment JSON structure (generated by apply-build-config.js)
interface BuildEnvJson {
  buildName: string;
  buildTime: string;
  env: Record<string, string>;
  codeFencing?: string[];
}

/**
 * Load build environment from JSON file and extract values
 */
export function validateEnv(
  buildEnvPath: string,
  _expectedBuildName: string,
): EnvValidationResult {
  if (!existsSync(buildEnvPath)) {
    throw new Error(`Build environment file not found: ${buildEnvPath}`);
  }

  const content = readFileSync(buildEnvPath, 'utf-8');
  const buildEnv = JSON.parse(content) as BuildEnvJson;

  return {
    buildName: buildEnv.buildName,
    extractedValues: buildEnv.env,
  };
}
