/* eslint-disable react-native/no-color-literals, @metamask/design-tokens/color-no-hex */
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  fab: {
    position: 'absolute',
    bottom: 40,
    right: 16,
    backgroundColor: '#24292e',
    borderRadius: 28,
    width: 56,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
    zIndex: 9999,
  },
  fabText: {
    color: '#58a6ff',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  fabIcon: {
    fontSize: 20,
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#0d1117',
    zIndex: 9999,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#21262d',
    backgroundColor: '#161b22',
  },
  headerTitle: {
    color: '#f0f6fc',
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  closeButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#21262d',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#30363d',
  },
  closeButtonText: {
    color: '#c9d1d9',
    fontSize: 13,
    fontWeight: '600',
  },
  refreshButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#21262d',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#30363d',
  },
  refreshButtonText: {
    color: '#58a6ff',
    fontSize: 13,
    fontWeight: '600',
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    paddingBottom: 40,
  },
  section: {
    marginBottom: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#21262d',
    backgroundColor: '#161b22',
    overflow: 'hidden',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#161b22',
  },
  sectionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  sectionChevron: {
    color: '#484f58',
    fontSize: 12,
    fontWeight: '700',
    width: 16,
  },
  sectionTitle: {
    color: '#f0f6fc',
    fontSize: 13,
    fontWeight: '600',
    fontFamily: 'Courier',
  },
  sectionBadge: {
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 10,
    backgroundColor: '#21262d',
  },
  sectionBadgeText: {
    color: '#8b949e',
    fontSize: 11,
    fontWeight: '600',
    fontFamily: 'Courier',
  },
  loadingBadge: {
    backgroundColor: '#2d1b00',
  },
  loadingBadgeText: {
    color: '#d29922',
  },
  errorBadge: {
    backgroundColor: '#3d1014',
  },
  errorBadgeText: {
    color: '#f85149',
  },
  sectionContent: {
    paddingHorizontal: 12,
    paddingBottom: 10,
    borderTopWidth: 1,
    borderTopColor: '#21262d',
  },
  jsonText: {
    color: '#c9d1d9',
    fontSize: 11,
    fontFamily: 'Courier',
    lineHeight: 16,
  },
  nullText: {
    color: '#484f58',
    fontSize: 11,
    fontFamily: 'Courier',
    fontStyle: 'italic',
    paddingTop: 8,
  },
  timestamp: {
    color: '#484f58',
    fontSize: 11,
    fontFamily: 'Courier',
    textAlign: 'right',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#21262d',
  },
});

export default styles;
