export enum MarketInsightsSelectorsIDs {
  ENTRY_CARD = 'market-insights-entry-card',
  ENTRY_CARD_HEADLINE = 'market-insights-entry-card-headline',
  VIEW_CONTAINER = 'market-insights-view-container',
  VIEW_HEADER = 'market-insights-view-header',
  TREND_ITEM = 'market-insights-trend-item',
  TWEET_CARD = 'market-insights-tweet-card',
  SOURCES_FOOTER = 'market-insights-sources-footer',
  THUMBS_UP_BUTTON = 'market-insights-thumbs-up-button',
  THUMBS_DOWN_BUTTON = 'market-insights-thumbs-down-button',
  TRADE_BUTTON = 'market-insights-trade-button',
  FEEDBACK_BOTTOM_SHEET = 'market-insights-feedback-bottom-sheet',
  FEEDBACK_OPTION_NOT_RELEVANT = 'market-insights-feedback-option-not-relevant',
  FEEDBACK_OPTION_NOT_ACCURATE = 'market-insights-feedback-option-not-accurate',
  FEEDBACK_OPTION_HARD_TO_UNDERSTAND = 'market-insights-feedback-option-hard-to-understand',
  FEEDBACK_OPTION_HARMFUL_OR_OFFENSIVE = 'market-insights-feedback-option-harmful-or-offensive',
  FEEDBACK_OPTION_SOMETHING_ELSE = 'market-insights-feedback-option-something-else',
  FEEDBACK_ADDITIONAL_INPUT = 'market-insights-feedback-additional-input',
  FEEDBACK_SUBMIT_BUTTON = 'market-insights-feedback-submit-button',
}
