import {
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';
import type { ContractRule, MobileContract } from './contract';

export interface TypewriterFixturePaths {
  readonly configPath: string;
  readonly generatedDirectory: string;
  readonly planPath: string;
}

export interface TypewriterOutput {
  readonly files: readonly string[];
  readonly source: string;
}

interface TypewriterPlan {
  readonly createdAt: string;
  readonly description: string;
  readonly id: string;
  readonly name: string;
  readonly rules: readonly ContractRule[];
  readonly slug: string;
  readonly updatedAt: string | null;
}

const readFileContents = (filePath: string): string =>
  readFileSync(filePath, 'utf8');

const TYPEWRITER_CONFIG = (trackingPlanId: string): string => `client:
  language: typescript
  sdk: analytics-react-native
  languageOptions: {}
trackingPlans:
  - id: ${JSON.stringify(trackingPlanId)}
    path: ./generated
`;

const createTypewriterPlan = (
  contract: MobileContract,
  rules: readonly ContractRule[],
): TypewriterPlan => ({
  createdAt: contract.generatedAt,
  description: '',
  id: contract.trackingPlan.id,
  name: contract.trackingPlan.name,
  rules,
  slug: 'metamask-mobile',
  updatedAt: contract.trackingPlan.updatedAt,
});

/**
 * Write the local Typewriter inputs for one verified contract fixture.
 *
 * @param contract - Verified Mobile contract.
 * @param rules - The exact event/version fixture being compared.
 * @param directory - Temporary Typewriter workspace.
 * @returns Paths consumed by the Typewriter CLI.
 */
export const writeTypewriterFixture = (
  contract: MobileContract,
  rules: readonly ContractRule[],
  directory: string,
): TypewriterFixturePaths => {
  const generatedDirectory = join(directory, 'generated');
  const configPath = join(directory, 'typewriter.yml');
  const planPath = join(generatedDirectory, 'plan.json');

  mkdirSync(generatedDirectory, { recursive: true });
  writeFileSync(
    configPath,
    TYPEWRITER_CONFIG(contract.trackingPlan.id),
  );
  writeFileSync(
    planPath,
    `${JSON.stringify(createTypewriterPlan(contract, rules), null, 2)}\n`,
  );

  return {
    configPath,
    generatedDirectory,
    planPath,
  };
};

/**
 * Read TypeScript files generated by Typewriter.
 *
 * @param directory - Typewriter output directory.
 * @returns Generated file paths and concatenated source.
 */
export const readTypewriterOutput = (directory: string): TypewriterOutput => {
  const files = readdirSync(directory)
    .filter(
      (fileName) => fileName.endsWith('.ts') || fileName.endsWith('.tsx'),
    )
    .sort()
    .map((fileName) => join(directory, fileName));

  if (files.length === 0) {
    throw new Error(`Typewriter generated no TypeScript files in '${directory}'`);
  }

  return {
    files,
    source: files.map((filePath) => readFileContents(filePath)).join('\n'),
  };
};
