export const ChoosePasswordSelectorsIDs = {
  TITLE_ID: 'create-password-screen-title-id',
  DESCRIPTION_ID: 'create-password-screen-description-id',
  CONTAINER_ID: 'create-password-screen',
  NEW_PASSWORD_INPUT_ID: 'create-password-first-input-field',
  CONFIRM_PASSWORD_INPUT_ID: 'create-password-second-input-field',
  ANDROID_I_UNDERSTAND_BUTTON_ID: 'i-understand-text',
  I_UNDERSTAND_CHECKBOX_ID: 'password-understand-box',
  SUBMIT_BUTTON_ID: 'submit-button',
  RESET_PASSWORD_BUTTON_TEXT: 'Reset password',
  SAVE_PASSWORD_BUTTON_TEXT: 'Save',
  CHECKBOX_TEXT_ID: 'checkbox-text',
  LEARN_MORE_LINK_ID: 'learn-more-link',
  PASSWORD_STRENGTH_ID: 'password-strength',
  NEW_PASSWORD_SHOW_ICON_ID: 'new-password-show-hide-id',
  CONFIRM_PASSWORD_SHOW_ICON_ID: 'confirm-password-show-hide-id',
};
