export enum ETH_ACTIONS {
  TRANSFER = 'transfer',
  APPROVE = 'approve',
}

export enum PROTOCOLS {
  HTTP = 'http',
  HTTPS = 'https',
  WC = 'wc',
  ETHEREUM = 'ethereum',
  DAPP = 'dapp',
  METAMASK = 'metamask',
}

export enum ACTIONS {
  RAMP = 'ramp',
  ENABLE_CARD_BUTTON = 'enable-card-button',
  CARD_ONBOARDING = 'card-onboarding',
  CARD_HOME = 'card-home',
  DAPP = 'dapp',
  SEND = 'send',
  APPROVE = 'approve',
  PAYMENT = 'payment',
  FOCUS = 'focus',
  WC = 'wc',
  CONNECT = 'connect',
  MMSDK = 'mmsdk',
  ANDROID_SDK = 'bind',
  BUY = 'buy',
  BUY_CRYPTO = 'buy-crypto',
  SELL = 'sell',
  SELL_CRYPTO = 'sell-crypto',
  DEPOSIT = 'deposit',
  HOME = 'home',
  SWAP = 'swap',
  EMPTY = '',
  OAUTH_REDIRECT = 'oauth-redirect',
  CREATE_ACCOUNT = 'create-account',
  PERPS = 'perps',
  PERPS_MARKETS = 'perps-markets',
  PERPS_ASSET = 'perps-asset',
  REWARDS = 'rewards',
  SHIELD = 'shield',
  PREDICT = 'predict',
  ONBOARDING = 'onboarding',
  TRENDING = 'trending',
}

export const PREFIXES = {
  [ACTIONS.DAPP]: 'https://',
  [ACTIONS.SEND]: 'ethereum:',
  [ACTIONS.APPROVE]: 'ethereum:',
  [ACTIONS.FOCUS]: '',
  [ACTIONS.EMPTY]: '',
  [ACTIONS.PAYMENT]: '',
  [ACTIONS.WC]: '',
  [ACTIONS.CONNECT]: '',
  [ACTIONS.ANDROID_SDK]: '',
  [ACTIONS.BUY]: '',
  [ACTIONS.SELL]: '',
  [ACTIONS.BUY_CRYPTO]: '',
  [ACTIONS.SELL_CRYPTO]: '',
  [ACTIONS.OAUTH_REDIRECT]: '',
  [ACTIONS.HOME]: '',
  [ACTIONS.SWAP]: '',
  [ACTIONS.CREATE_ACCOUNT]: '',
  [ACTIONS.PERPS]: '',
  [ACTIONS.PERPS_MARKETS]: '',
  [ACTIONS.PERPS_ASSET]: '',
  [ACTIONS.REWARDS]: '',
  [ACTIONS.PREDICT]: '',
  [ACTIONS.ONBOARDING]: '',
  [ACTIONS.SHIELD]: '',
  [ACTIONS.ENABLE_CARD_BUTTON]: '',
  [ACTIONS.CARD_ONBOARDING]: '',
  [ACTIONS.CARD_HOME]: '',
  [ACTIONS.TRENDING]: '',
  METAMASK: 'metamask://',
};
