#!/usr/bin/env python3
"""Generate a comprehensive Money Account technical PDF."""

from pathlib import Path

from fpdf import FPDF

OUT = Path(__file__).resolve().parent / "Money-Account-Technical-Guide.pdf"


class Doc(FPDF):
    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, "MetaMask Money Account - Technical Guide", align="L")
        self.cell(0, 8, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(200, 200, 200)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(140, 140, 140)
        self.cell(
            0,
            8,
            "Internal reference - derived from metamask-mobile + Veda BoringVault docs. Not legal advice.",
            align="C",
        )

    def _mc(self, h, text, **kwargs):
        self.set_x(self.l_margin)
        self.multi_cell(0, h, text, new_x="LMARGIN", new_y="NEXT", **kwargs)

    def h1(self, text):
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(20, 20, 20)
        self._mc(10, text)
        self.ln(2)

    def h2(self, text):
        self.ln(3)
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(30, 30, 30)
        self._mc(8, text)
        self.ln(1)

    def h3(self, text):
        self.ln(2)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(40, 40, 40)
        self._mc(7, text)
        self.ln(0.5)

    def body(self, text):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(30, 30, 30)
        self._mc(5.5, text)
        self.ln(1)

    def bullet(self, text, indent=8):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(30, 30, 30)
        self.set_x(self.l_margin + indent)
        width = self.w - self.r_margin - self.l_margin - indent
        self.multi_cell(width, 5.5, f"- {text}", new_x="LMARGIN", new_y="NEXT")

    def code(self, text):
        self.set_font("Courier", "", 8)
        self.set_text_color(40, 40, 40)
        self.set_fill_color(245, 245, 245)
        self._mc(4.5, text, fill=True)
        self.ln(2)

    def note(self, text):
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(70, 70, 70)
        self._mc(5, text)
        self.ln(1)


def build():
    pdf = Doc(format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # Cover
    pdf.ln(30)
    pdf.set_font("Helvetica", "B", 24)
    pdf._mc(12, "MetaMask Money Account", align="C")
    pdf.set_font("Helvetica", "", 14)
    pdf._mc(8, "Technical & Protocol Guide", align="C")
    pdf.ln(6)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(80, 80, 80)
    pdf._mc(
        6,
        "Architecture, on-chain protocol (Veda BoringVault), EIP-7702 / CHOMP upgrade, "
        "deposit & withdraw flows, balances/APY, Card linkage, and mobile implementation.",
        align="C",
    )
    pdf.ln(10)
    pdf.set_font("Helvetica", "", 9)
    pdf._mc(
        5,
        "Sources: metamask-mobile (app/components/UI/Money, Engine controllers), "
        "@metamask/money-account-* packages, Veda docs (docs.veda.tech). "
        "Generated for engineering reference.",
        align="C",
    )

    # TOC
    pdf.add_page()
    pdf.h1("Table of contents")
    toc = [
        "1. Executive summary",
        "2. Product concept",
        "3. High-level architecture",
        "4. Protocol layer - Veda BoringVault",
        "5. Tokens - mUSD and vmUSD",
        "6. Deposit flow (protocol + app)",
        "7. Withdraw flow (protocol + app)",
        "8. Yield, exchange rate, and APY",
        "9. EIP-7702 smart-account upgrade & CHOMP",
        "10. MetaMask Card linkage",
        "11. Engine packages & state",
        "12. Mobile UX surfaces & feature flags",
        "13. Security & risk model",
        "14. Glossary & key file paths",
    ]
    for t in toc:
        pdf.bullet(t, indent=0)

    # 1
    pdf.add_page()
    pdf.h1("1. Executive summary")
    pdf.body(
        "A Money Account is a dedicated, non-exportable account address created for the "
        "user's primary HD keyring. It is MetaMask's cash + yield surface: users fund it "
        "with mUSD (or convert/fiat via MM Pay), deposits enter a Veda BoringVault on Monad "
        "and receive vmUSD vault shares that earn variable APY, and the balance can optionally "
        "delegate spend to MetaMask Card."
    )
    pdf.body(
        "At the protocol layer, Money Account is not a proprietary yield engine. Yield is "
        "generated by third-party DeFi strategies (e.g. Aave, Morpho) curated inside a Veda "
        "vault, with risk oversight described in product copy as Steakhouse Financial monitoring. "
        "MetaMask owns the wallet UX, account lifecycle, transaction batching, and Card integration."
    )
    pdf.body(
        "Money Account today is Monad-scoped for the vault path (chain id decimal 143 / hex 0x8f). "
        "mUSD also exists on other chains (Ethereum, Linea, BSC) for conversion/source liquidity, "
        "but the vault deposit target is Monad mUSD."
    )

    # 2
    pdf.h1("2. Product concept")
    pdf.h3("What users get")
    pdf.bullet("A separate Money address (not their everyday selected account).")
    pdf.bullet("USD-pegged balance displayed as Money balance (mUSD liquid + vmUSD valued in mUSD).")
    pdf.bullet("Variable APY on vaulted funds - no manual claim/stake UX.")
    pdf.bullet("Deposit via convert crypto, move existing mUSD, or fiat (MM Pay) when region-enabled.")
    pdf.bullet("Withdraw back to a selected EVM account.")
    pdf.bullet("Optional Card link so purchases pull from Money while funds keep earning until spent.")

    pdf.h3("What it is not")
    pdf.bullet("Not interest paid by MetaMask or by the mUSD issuer.")
    pdf.bullet("Not a custodial bank account - assets sit in self-custodial contracts/wallet.")
    pdf.bullet("Not guaranteed APY - rates are variable and market-dependent.")

    # 3
    pdf.h1("3. High-level architecture")
    pdf.body("Three Engine packages plus mobile UI:")
    pdf.bullet(
        "@metamask/money-account-controller - creates/tracks Money accounts in keyring state "
        "(moneyAccounts map; exportable: false)."
    )
    pdf.bullet(
        "@metamask/money-account-balance-service - on-chain Multicall balances, Accountant rate, "
        "Lens valuation, Veda REST APY."
    )
    pdf.bullet(
        "@metamask/money-account-upgrade-controller - EIP-7702 + CHOMP upgrade sequence for "
        "auto deposit/withdraw intents."
    )
    pdf.ln(1)
    pdf.body("End-to-end fund path:")
    pdf.code(
        "User EOA / fiat\n"
        "    |  MM Pay (bridge/swap/fiat into Money Account as mUSD on Monad)\n"
        "    v\n"
        "Money Account (EOA upgraded via EIP-7702)\n"
        "    |  ERC-20 approve(boringVault) + Teller.deposit(mUSD)\n"
        "    v\n"
        "Veda BoringVault  -->  user holds vmUSD shares\n"
        "    |  Curator/Manager deploys into DeFi (Aave, Morpho, ...)\n"
        "    v\n"
        "Yield increases Accountant exchange rate (vmUSD worth more mUSD)\n"
        "\n"
        "Withdraw:\n"
        "Teller.withdraw(vmUSD -> mUSD to Money Account) + ERC-20 transfer to user EOA"
    )

    # 4 Protocol
    pdf.add_page()
    pdf.h1("4. Protocol layer - Veda BoringVault")
    pdf.body(
        "Money Account uses Veda's BoringVault architecture. The vault core is intentionally "
        "minimal (~100 lines of critical custody logic). Complex behavior is delegated to "
        "external modules that can be audited and constrained independently."
    )
    pdf.note("Primary reference: https://docs.veda.tech/architecture-and-flow-of-funds")

    pdf.h3("4.1 BoringVault")
    pdf.body(
        "Central custody contract for vault assets. Holds underlying tokens, mints/burns share "
        "tokens (vmUSD for Money), and executes management calls when authorized modules request "
        "them. Rules for deposits, withdrawals, and strategy execution live in surrounding modules."
    )

    pdf.h3("4.2 Teller (user entry/exit)")
    pdf.body(
        "User-facing deposit and withdraw router. On deposit it reads the Accountant exchange "
        "rate, mints the correct number of shares, and pulls assets into the BoringVault. On "
        "withdraw it burns shares and returns underlying assets."
    )
    pdf.bullet(
        "Share lock periods after deposit mitigate MEV/arbitrage (shares may not be transferable "
        "or redeemable during the lock)."
    )
    pdf.bullet(
        "Variants exist (e.g. TellerWithBuffer for instant liquidity, TellerWithYieldStreaming)."
    )
    pdf.body("MetaMask mobile encodes these Teller methods:")
    pdf.code(
        "deposit(address depositAsset, uint256 depositAmount,\n"
        "        uint256 minimumMint, address referralAddress) payable returns (uint256 shares)\n\n"
        "withdraw(address withdrawAsset, uint256 shareAmount,\n"
        "         uint256 minimumAssets, address to) returns (uint256 assetsOut)"
    )

    pdf.h3("4.3 Accountant (exchange rate)")
    pdf.body(
        "Publishes the share <-> underlying exchange rate. Rates are typically computed offchain "
        "and pushed onchain with safety rails:"
    )
    pdf.bullet("Rate limiting - how often the rate can update.")
    pdf.bullet("Bound limiting - how far a new rate may deviate from the previous on-chain rate.")
    pdf.bullet("If bounds are violated, the Accountant can pause updates (and thus deposits/withdraws).")
    pdf.body("Mobile reads the rate via:")
    pdf.code("getRate() view returns (uint256 rate)")

    pdf.h3("4.4 Lens (preview / valuation helpers)")
    pdf.body(
        "Lens contracts provide view helpers for UIs and integrators. Money Account uses Lens for:"
    )
    pdf.bullet("previewDeposit(...) - expected shares for a deposit amount (sets minimumMint).")
    pdf.bullet(
        "balanceOfInAssets(...) - value vault shares in underlying asset terms "
        "(used by balance service as mUSD-equivalent of vmUSD)."
    )
    pdf.code(
        "previewDeposit(address depositAsset, uint256 depositAmount,\n"
        "               address boringVault, address accountant) view returns (uint256 shares)"
    )

    pdf.h3("4.5 Manager (strategy whitelist)")
    pdf.body(
        "Controls which DeFi actions the vault may execute. Permitted operations are encoded in a "
        "Merkle tree (target address, function, allowed params). A strategist/curator submits "
        "rebalances with Merkle proofs; the Manager verifies them onchain. This keeps strategy "
        "policy enforceable at execution time."
    )

    pdf.h3("4.6 DecoderAndSanitizer")
    pdf.body(
        "Decodes and validates calldata before external protocol calls, ensuring only intended "
        "interactions (per integrated protocol) execute."
    )

    pdf.h3("4.7 Hook")
    pdf.body(
        "Optional pre-transfer logic: transfer restrictions, whitelists, share locks, compliance."
    )

    pdf.h3("4.8 BoringQueue (async withdrawals)")
    pdf.body(
        "For vaults without sufficient instant buffer liquidity, withdrawals can use a "
        "time-delayed, solver-based queue: shares move to the queue, mature, then solvers fulfill "
        "by providing assets. Money Account's mobile path currently targets Teller.withdraw "
        "(instant-style path when liquidity allows); queue behavior depends on vault configuration."
    )

    pdf.h3("4.9 Flow of funds inside the vault")
    pdf.code(
        "1. User deposits mUSD via Teller -> shares (vmUSD) minted at Accountant rate\n"
        "2. Idle assets sit in vault / buffer\n"
        "3. Curator rebalances via Manager (Merkle-verified) into DeFi markets\n"
        "4. Yield accrues; Accountant rate rises over time\n"
        "5. User withdraws: shares burned, mUSD returned (subject to liquidity/locks)"
    )

    pdf.h3("4.10 Vault config in MetaMask (remote feature flag)")
    pdf.body(
        "Addresses are not hardcoded for production. Remote flag moneyAccountVaultConfig supplies:"
    )
    pdf.code(
        "MoneyAccountVaultConfig / VaultConfig =\n"
        "{\n"
        "  chainId,            // e.g. 0x8f (Monad)\n"
        "  boringVault,        // vault + share token (vmUSD)\n"
        "  tellerAddress,      // deposit / withdraw entry\n"
        "  accountantAddress,  // getRate()\n"
        "  lensAddress,        // previewDeposit / valuation\n"
        "  underlyingToken?,   // optional mUSD; else Accountant.base()\n"
        "}"
    )
    pdf.body(
        "Dev fallback exists when MM_MONEY_DEPOSIT_CONFIG_DEV_ENABLED=true "
        "(DEV_VAULT_CONFIG in moneyAccount feature-flag selectors)."
    )

    # 5 Tokens
    pdf.add_page()
    pdf.h1("5. Tokens - mUSD and vmUSD")
    pdf.h3("mUSD (MetaMask USD)")
    pdf.bullet("USD-pegged ERC-20 used as the Money Account cash unit.")
    pdf.bullet("Decimals: 6 (same pattern as USDC-style stables).")
    pdf.bullet(
        "Canonical address used across supported chains (checksum example): "
        "0xacA92E438df0B2401fF60dA7E4337B687a2435DA"
    )
    pdf.bullet(
        "Money Account vault path: Monad only (eip155:143). Other chains hold source mUSD for "
        "conversion / MM Pay funding."
    )
    pdf.bullet("Display symbol in product: mUSD.")

    pdf.h3("vmUSD (vault shares)")
    pdf.bullet("Receipt / share token of the BoringVault (boringVault address).")
    pdf.bullet("Represents claim on vault assets + accrued yield via rising exchange rate.")
    pdf.bullet("UI usually shows total Money balance in fiat/mUSD terms, not raw share count.")

    pdf.h3("Balance composition (app)")
    pdf.code(
        "MoneyAccountBalanceResponse =\n"
        "{\n"
        "  musdBalance,       // liquid mUSD on Money Account\n"
        "  vmusdValueInMusd,  // vault shares valued in mUSD (Lens)\n"
        "  totalBalance       // musdBalance + vmusdValueInMusd (raw uint256 strings)\n"
        "}"
    )

    # 6 Deposit
    pdf.h1("6. Deposit flow (protocol + app)")
    pdf.h3("6.1 Protocol steps")
    pdf.bullet("Ensure Money Account holds mUSD on the vault chain (via MM Pay).")
    pdf.bullet(
        "Approve: mUSD.approve(boringVault, amount) - spender is the vault (as encoded in app)."
    )
    pdf.bullet(
        "Preview: Lens.previewDeposit(mUSD, amount, boringVault, accountant) -> expected shares."
    )
    pdf.bullet("Apply 0.2% slippage: minimumMint = expectedShares * 998 / 1000.")
    pdf.bullet(
        "Teller.deposit(mUSD, amount, minimumMint, referral=0x0) -> mints vmUSD to depositor "
        "(Money Account)."
    )

    pdf.h3("6.2 App orchestration")
    pdf.bullet("Hook: useMoneyAccountDeposit (app/components/UI/Money/hooks/useMoneyAccount.ts).")
    pdf.bullet("Builder: buildMoneyAccountDepositBatch (moneyAccountTransactions.ts).")
    pdf.bullet(
        "Submitted as TransactionController atomic batch from = Money Account address."
    )
    pdf.bullet(
        "MM Pay selects payment token / fiat and re-encodes amounts via "
        "updateMoneyAccountDepositTokenAmount when the user sets amount."
    )
    pdf.bullet("On Monad mainnet, gas is typically sponsored (isGasFeeSponsored).")
    pdf.bullet(
        "Entry sheet MoneyAddMoneySheet offers convert crypto / fiat / move mUSD "
        "(plus coming-soon bank & receive rows)."
    )

    pdf.h3("6.3 Slippage rationale")
    pdf.body(
        "minimumMint protects against rate movement between preview and inclusion. If the "
        "sanity check would revert, funds are not lost - user retries with a fresh quote. "
        "Constant: SLIPPAGE_NUMERATOR=998, SLIPPAGE_DENOMINATOR=1000."
    )

    # 7 Withdraw
    pdf.h1("7. Withdraw flow (protocol + app)")
    pdf.h3("7.1 Protocol steps")
    pdf.bullet("Read Accountant.getRate().")
    pdf.bullet(
        "Convert desired mUSD amount to shares with ceiling division so mulDivDown on-chain "
        "does not undershoot minimumAssets (avoids MinimumAssetsNotMet)."
    )
    pdf.code(
        "SHARE_DECIMALS_SCALAR = 1_000_000\n"
        "shares = ceil(amount * SHARE_DECIMALS_SCALAR / rate)\n"
        "minimumAssets = amount - 1   # 1-unit defense-in-depth vs rounding"
    )
    pdf.bullet(
        "Teller.withdraw(mUSD, shareAmount, minimumAssets, to=MoneyAccount) - underlying "
        "lands on Money Account first."
    )
    pdf.bullet(
        "ERC-20 transfer(recipient, amount) moves exact requested mUSD to the user's selected EOA."
    )

    pdf.h3("7.2 App orchestration")
    pdf.bullet("Hook: useMoneyAccountWithdrawal.")
    pdf.bullet("Builder: buildMoneyAccountWithdrawBatch.")
    pdf.bullet("Amount updates: updateMoneyAccountWithdrawTokenAmount.")
    pdf.note(
        "Comments in code sometimes say USDC; operational asset for Money Account is mUSD."
    )

    # 8 Yield
    pdf.add_page()
    pdf.h1("8. Yield, exchange rate, and APY")
    pdf.body(
        "Yield is not streamed as a separate claim token in the Money UX. As strategies earn, "
        "the Accountant rate increases so each vmUSD share is redeemable for more mUSD. The "
        "app displays APY from Veda's REST API (MoneyAccountBalanceService.getVaultApy), with "
        "optional remote override/fallback flags (earnMoneyVaultApyControl)."
    )
    pdf.body("NormalizedVaultApyResponse includes apy (decimal), timestamp, optional fees and breakdowns.")
    pdf.body(
        "Product messaging: APY is variable and not guaranteed; earnings come from onchain "
        "returns in third-party protocols, not from MetaMask or the mUSD issuer."
    )

    # 9 Upgrade
    pdf.h1("9. EIP-7702 smart-account upgrade & CHOMP")
    pdf.body(
        "Money Account starts as a keyring account. To enable automated vault interactions "
        "(auto deposit/withdraw), MoneyAccountUpgradeController runs an idempotent upgrade "
        "sequence integrating MetaMask Delegation Framework + CHOMP."
    )

    pdf.h3("9.1 Bootstrap")
    pdf.bullet("Requires moneyEnableMoneyAccount + moneyAccountVaultConfig.")
    pdf.bullet("Ensures vault chainId exists in NetworkController (auto-adds Monad from PopularList).")
    pdf.bullet("controller.init({ chainId, boringVaultAddress }).")
    pdf.bullet("UI awaits whenMoneyAccountUpgradeReady() then upgradeAccount(address).")

    pdf.h3("9.2 Upgrade steps (ordered, skip if already-done)")
    pdf.bullet(
        "1. eip-7702-authorization - Sign EIP-7702 authorization; submit to CHOMP "
        "(409 treated as already authorized). Sets smart-account delegation slot."
    )
    pdf.bullet(
        "2. associate-address - Sign personal message 'CHOMP Authentication {timestamp}' "
        "(EIP-191); CHOMP links address to user profile."
    )
    pdf.bullet(
        "3. build-delegations - Build, sign, CHOMP-verify, and persist ERC-20 delegations "
        "for auto-deposit (mUSD) and auto-withdraw (vmUSD / boring vault). Caveats include "
        "ValueLteEnforcer, ERC20TransferAmountEnforcer (max uint256), RedeemerEnforcer "
        "(Veda vault adapter only)."
    )
    pdf.bullet(
        "4. register-intents - Register CHOMP intents for those delegations so CHOMP can "
        "monitor and execute auto deposit/withdraw flows."
    )

    pdf.h3("9.3 Delegation shape (simplified)")
    pdf.code(
        "delegation = {\n"
        "  delegate: CHOMP_delegate,\n"
        "  delegator: moneyAccountAddress,\n"
        "  authority: ROOT_AUTHORITY,\n"
        "  caveats: [valueLte, erc20TransferAmount, redeemer],\n"
        "  salt: random(32),\n"
        "  signature: DelegationController.signDelegation(...)\n"
        "}"
    )
    pdf.body(
        "Stored via AuthenticatedUserStorageService with metadata (delegationHash, chainId, "
        "token, type). CHOMP rejects invalid delegations before persistence."
    )

    # 10 Card
    pdf.h1("10. MetaMask Card linkage")
    pdf.body(
        "Card spend can be linked to Money via spending-limit style delegation on the vault/"
        "veda token configuration (Card APIs key it as 'veda'; UI shows mUSD)."
    )
    pdf.bullet("Hook: useMoneyAccountCardLinkage.")
    pdf.bullet("Gates: Money enabled, geo eligible, vault config, Money address, Card auth/verified, etc.")
    pdf.bullet("CardController.linkMoneyAccountCard({ moneyAccountAddress, delegationAmountHuman }).")
    pdf.bullet(
        "Unlink submits approve(0) style revoke and marks not-delegated on Card backend "
        "(see developer options / Card settings copy)."
    )

    # 11 Engine
    pdf.add_page()
    pdf.h1("11. Engine packages & state")
    pdf.h3("MoneyAccountController")
    pdf.code("state = { moneyAccounts: { [id]: MoneyAccount } }")
    pdf.bullet("MoneyAccount is a KeyringAccount with options.entropy and exportable: false.")
    pdf.bullet("init() creates account for primary entropy when flag on + unlocked.")
    pdf.bullet("clearState() when flag turns off.")
    pdf.bullet("selectPrimaryMoneyAccount matches options.entropy.id to primary HD keyring.")

    pdf.h3("MoneyAccountBalanceService")
    pdf.bullet("getMusdBalance / getVmusdBalance / getMoneyAccountBalance")
    pdf.bullet("getExchangeRate (Accountant)")
    pdf.bullet("getMusdEquivalentValue (Lens)")
    pdf.bullet("getVaultApy (Veda REST)")
    pdf.bullet("Reads vault config from remote flags; validates config (VaultConfigValidationError).")

    pdf.h3("MoneyAccountUpgradeController")
    pdf.bullet("Stateless (Record<string, never>).")
    pdf.bullet("Side-effect controller: init + upgradeAccount.")

    # 12 UX / flags
    pdf.h1("12. Mobile UX surfaces & feature flags")
    pdf.h3("Primary UI")
    pdf.bullet("app/components/UI/Money/ - Home, Onboarding (Rive), Activity, How it works, First-time deposit.")
    pdf.bullet("Sheets: Add Money, Transfer, Geo block, Card link, APY info.")
    pdf.bullet("Confirmations: money-account-deposit / withdraw info + MM Pay amount editing.")

    pdf.h3("Important flags")
    pdf.bullet("moneyEnableMoneyAccount - master version-gated kill switch.")
    pdf.bullet("moneyAccountVaultConfig - protocol addresses + chainId.")
    pdf.bullet("earnMoneyHubEnabled - hub discovery.")
    pdf.bullet("moneyAccount.moneyAccountDepositEnabled / WithdrawEnabled.")
    pdf.bullet("moneyAccountGeoBlockedCountries (default includes GB).")
    pdf.bullet("earnMoneyVaultApyControl - APY override/fallback.")
    pdf.bullet("Various UX polish flags (parallax, first-time deposit animation, etc.).")

    pdf.h3("Geo eligibility")
    pdf.body(
        "selectIsMoneyAccountGeoEligible fails closed when geolocation is unknown (null) for "
        "regulatory compliance - eligible users may briefly look blocked while Ramps geo loads."
    )

    # 13 Security
    pdf.h1("13. Security & risk model")
    pdf.bullet("Self-custodial: user keys control Money Account; vault shares are onchain receipts.")
    pdf.bullet("Vault strategy risk: smart contract / market / curator risk in DeFi venues.")
    pdf.bullet("Accountant pause / bound limits reduce oracle manipulation blast radius.")
    pdf.bullet("Teller share locks reduce deposit-withdraw arbitrage.")
    pdf.bullet("Manager Merkle whitelist constrains strategist actions.")
    pdf.bullet("CHOMP delegations constrained by redeemer + amount enforcers.")
    pdf.bullet("Money Account keyring accounts are non-exportable.")
    pdf.bullet("Slippage / minimumMint / minimumAssets protect users from stale quotes.")
    pdf.note(
        "This document does not replace security audits of Veda contracts, CHOMP, or MetaMask "
        "controllers."
    )

    # 14 Glossary
    pdf.add_page()
    pdf.h1("14. Glossary & key file paths")
    pdf.h3("Glossary")
    terms = [
        ("BoringVault", "Minimal Veda vault custody + share mint/burn contract."),
        ("Teller", "User deposit/withdraw router for the vault."),
        ("Accountant", "On-chain publisher of share exchange rate."),
        ("Lens", "View helpers: previewDeposit, balance valuation."),
        ("Manager", "Merkle-verified strategy execution gate."),
        ("vmUSD", "Vault share token for Money Account."),
        ("mUSD", "MetaMask USD stablecoin; deposit asset."),
        ("CHOMP", "Service that coordinates EIP-7702 upgrade + auto intents."),
        ("EIP-7702", "EOA code-delegation upgrade enabling smart-account behavior."),
        ("MM Pay", "Confirmation payment layer that funds Money Account then runs vault txs."),
        ("Delegation", "Signed caveated authorization for limited token actions."),
    ]
    for k, v in terms:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(30, 30, 30)
        pdf.set_x(pdf.l_margin)
        pdf.write(5.5, f"{k}: ")
        pdf.set_font("Helvetica", "", 10)
        pdf.write(5.5, v)
        pdf.ln(6)

    pdf.h3("Key paths (metamask-mobile)")
    paths = [
        "app/core/Engine/Engine.ts - controller registration",
        "app/core/Engine/controllers/money-account-*-init.ts",
        "app/selectors/moneyAccountController/",
        "app/selectors/featureFlagController/moneyAccount/",
        "app/lib/Money/feature-flags.ts",
        "app/actions/money/index.ts - upgradeMoneyAccount thunk",
        "app/components/UI/Money/hooks/useMoneyAccount.ts",
        "app/components/UI/Money/hooks/useMoneyAccountBalance.ts",
        "app/components/UI/Money/utils/moneyAccountTransactions.ts",
        "app/components/UI/Card/hooks/useMoneyAccountCardLinkage.tsx",
        "app/components/UI/Earn/constants/musd.ts",
        "node_modules/@metamask/money-account-{controller,balance-service,upgrade-controller}/",
    ]
    for p in paths:
        pdf.bullet(p)

    pdf.ln(6)
    pdf.h3("External docs")
    pdf.bullet("Veda architecture: https://docs.veda.tech/architecture-and-flow-of-funds")
    pdf.bullet("Veda core components: https://docs.veda.tech/architecture-and-flow-of-funds/core-components")
    pdf.bullet("BoringVault repo: https://github.com/Veda-Labs/boring-vault")

    pdf.output(OUT)
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    build()
