source 'https://rubygems.org'

# Recommended to use http://rbenv.org/ to install and use this version
ruby '>= 3.1.6'

# Allow minor version updates up to but excluding 2.0.0
gem 'cocoapods', '1.16.2'

# Allow all version updates up to but excluding 7.1.0
gem 'activesupport', '>= 6.1.7.3', '< 7.1.0'

# Fastlane for iOS automation
gem 'fastlane', '>= 2.220.0'
