export const TraderProfileViewSelectorsIDs = {
  CONTAINER: 'trader-profile-container',
  BACK_BUTTON: 'trader-profile-back-button',
  HEADER: 'trader-profile-header',
  HEADER_COMPACT_IDENTITY: 'trader-profile-header-compact-identity',
  PROFILE_HEADER: 'trader-profile-profile-header',
  TITLE_SECTION_WRAPPER: 'trader-profile-title-section-wrapper',
  COMPACT_STATS: 'trader-profile-compact-stats',
  HEADER_COMPACT_WIN_RATE: 'trader-profile-header-compact-win-rate',
  HEADER_COMPACT_PNL: 'trader-profile-header-compact-pnl',
  STATS_ROW: 'trader-profile-stats-row',
  FOLLOW_BUTTON: 'trader-profile-follow-button',
  MUTE_CHIP: 'trader-profile-mute-chip',
  TAB_OPEN: 'trader-profile-tab-open',
  TAB_CLOSED: 'trader-profile-tab-closed',
  SORT_BUTTON: 'trader-profile-sort-button',
  ERROR_BANNER: 'trader-profile-error-banner',
  TWITTER_LINK: 'trader-profile-twitter-link',
  REFRESH_CONTROL: 'trader-profile-refresh-control',
};
