export const MEMECOINS_TEST_IDS = {
  TOKEN_LIST_SCREEN: 'memecoins-token-list-screen',
  TOKEN_LIST_LOADING: 'memecoins-token-list-loading',
  TOKEN_LIST_ERROR: 'memecoins-token-list-error',
  TOKEN_LIST_ITEM: 'memecoins-token-list-item',
  TOKEN_LIST_ITEM_CHANGE: 'memecoins-token-list-item-change',
  TOKEN_LIST_SEARCH: 'memecoins-token-list-search',
  TOKEN_LIST_SEARCH_INPUT: 'memecoins-token-list-search-input',
  TOKEN_LIST_SEARCH_CLEAR: 'memecoins-token-list-search-clear',
  AMOUNT_SCREEN: 'memecoins-amount-screen',
  AMOUNT_PRESET: 'memecoins-amount-preset',
  AMOUNT_VALUE: 'memecoins-amount-value',
  AMOUNT_KEYPAD: 'memecoins-amount-keypad',
  APPLE_PAY_BUTTON: 'memecoins-apple-pay-button',
  CHECKOUT_SCREEN: 'memecoins-checkout-screen',
  CHECKOUT_WEBVIEW: 'memecoins-checkout-webview',
  CHECKOUT_LOADING: 'memecoins-checkout-loading',
  CHECKOUT_PROCESSING: 'memecoins-checkout-processing',
  CHECKOUT_SUCCESS: 'memecoins-checkout-success',
  CHECKOUT_ERROR: 'memecoins-checkout-error',
} as const;
