import { NETWORK_MULTI_SELECTOR_TEST_IDS } from '../../../app/components/UI/NetworkMultiSelector/NetworkMultiSelector.constants';
import enContent from '../../../locales/languages/en.json';

export const NetworkManagerSelectorIDs = {
  // Containers
  NETWORK_MANAGER_BOTTOM_SHEET:
    NETWORK_MULTI_SELECTOR_TEST_IDS.NETWORK_MANAGER_BOTTOM_SHEET,
  POPULAR_NETWORKS_CONTAINER:
    NETWORK_MULTI_SELECTOR_TEST_IDS.POPULAR_NETWORKS_CONTAINER,
  CUSTOM_NETWORKS_CONTAINER:
    NETWORK_MULTI_SELECTOR_TEST_IDS.CUSTOM_NETWORKS_CONTAINER,

  // Buttons
  SELECT_ALL_POPULAR_NETWORKS_SELECTED:
    NETWORK_MULTI_SELECTOR_TEST_IDS.SELECT_ALL_POPULAR_NETWORKS_SELECTED,
  SELECT_ALL_POPULAR_NETWORKS_NOT_SELECTED:
    NETWORK_MULTI_SELECTOR_TEST_IDS.SELECT_ALL_POPULAR_NETWORKS_NOT_SELECTED,
  OPEN_NETWORK_MANAGER: NETWORK_MULTI_SELECTOR_TEST_IDS.OPEN_NETWORK_MANAGER,

  // Tabs
  POPULAR_NETWORKS_TAB: NETWORK_MULTI_SELECTOR_TEST_IDS.POPULAR_NETWORKS_TAB,
  CUSTOM_NETWORKS_TAB: NETWORK_MULTI_SELECTOR_TEST_IDS.CUSTOM_NETWORKS_TAB,
};

export const NetworkManagerSelectorText = {
  POPULAR_NETWORKS_TAB: enContent.wallet.popular,
  CUSTOM_NETWORKS_TAB: enContent.wallet.custom,
};
