"use strict";
exports.__esModule = true;
exports.RampType = exports.ACTIONS = void 0;
exports.ACTIONS = {
    FIAT_ADD_ORDER: 'FIAT_ADD_ORDER',
    FIAT_UPDATE_ORDER: 'FIAT_UPDATE_ORDER',
    FIAT_REMOVE_ORDER: 'FIAT_REMOVE_ORDER',
    FIAT_RESET: 'FIAT_RESET',
    FIAT_SET_COUNTRY: 'FIAT_SET_COUNTRY',
    // aggregator actions
    FIAT_SET_REGION_AGG: 'FIAT_SET_REGION_AGG',
    FIAT_SET_PAYMENT_METHOD_AGG: 'FIAT_SET_PAYMENT_METHOD_AGG',
    FIAT_SET_GETSTARTED_AGG: 'FIAT_SET_GETSTARTED_AGG',
    FIAT_SET_GETSTARTED_SELL: 'FIAT_SET_GETSTARTED_SELL',
    FIAT_ADD_CUSTOM_ID_DATA: 'FIAT_ADD_CUSTOM_ID_DATA',
    FIAT_UPDATE_CUSTOM_ID_DATA: 'FIAT_UPDATE_CUSTOM_ID_DATA',
    FIAT_REMOVE_CUSTOM_ID_DATA: 'FIAT_REMOVE_CUSTOM_ID_DATA',
    FIAT_ADD_AUTHENTICATION_URL: 'FIAT_ADD_AUTHENTICATION_URL',
    FIAT_REMOVE_AUTHENTICATION_URL: 'FIAT_REMOVE_AUTHENTICATION_URL',
    FIAT_ADD_ACTIVATION_KEY: 'FIAT_ADD_ACTIVATION_KEY',
    FIAT_UPDATE_ACTIVATION_KEY: 'FIAT_UPDATE_ACTIVATION_KEY',
    FIAT_REMOVE_ACTIVATION_KEY: 'FIAT_REMOVE_ACTIVATION_KEY',
    FIAT_UPDATE_NETWORKS: 'FIAT_UPDATE_NETWORKS',
    FIAT_SET_SELL_TX_HASH: 'FIAT_SET_SELL_TX_HASH',
    FIAT_REMOVE_SELL_TX_HASH: 'FIAT_REMOVE_SELL_TX_HASH'
};
var RampType;
(function (RampType) {
    RampType["BUY"] = "buy";
    RampType["SELL"] = "sell";
})(RampType = exports.RampType || (exports.RampType = {}));
