"use strict";
// This file holds all events that the mobile app is going to
// track if the user has the MetaMetrics option ENABLED.
// In case that the MetaMetrics option is DISABLED, then none
// of these events should be tracked in any kind of service.
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
exports.__esModule = true;
exports.EVENT_NAME = exports.ONBOARDING_WIZARD_STEP_DESCRIPTION = exports.MetaMetricsEvents = void 0;
var generateOpt = function (name, action, description) {
    if (action || description) {
        return {
            category: name,
            properties: __assign(__assign({}, (action && { action: action })), (description && { name: description }))
        };
    }
    return { category: name };
};
var ONBOARDING_WIZARD_STEP_DESCRIPTION = {
    1: 'Welcome',
    2: 'Accounts',
    3: 'Account Name',
    4: 'Notifications',
    5: 'Main Navigation',
    6: 'Browser',
    7: 'Search'
};
exports.ONBOARDING_WIZARD_STEP_DESCRIPTION = ONBOARDING_WIZARD_STEP_DESCRIPTION;
/**
 * Analytics Tracking Events
 */
var EVENT_NAME;
(function (EVENT_NAME) {
    // Error
    EVENT_NAME["ERROR"] = "Error occurred";
    EVENT_NAME["ERROR_SCREEN_VIEWED"] = "Error Screen Viewed";
    // Approval
    EVENT_NAME["APPROVAL_STARTED"] = "Approval Started";
    EVENT_NAME["APPROVAL_COMPLETED"] = "Approval Completed";
    EVENT_NAME["APPROVAL_CANCELLED"] = "Approval Cancelled";
    EVENT_NAME["APPROVAL_PERMISSION_UPDATED"] = "Approval Permission Updated";
    // Fee changed
    EVENT_NAME["GAS_FEE_CHANGED"] = "Gas Fee Changed";
    EVENT_NAME["GAS_ADVANCED_OPTIONS_CLICKED"] = "Gas Advanced Options Clicked";
    // Dapp Transaction
    EVENT_NAME["DAPP_TRANSACTION_STARTED"] = "Dapp Transaction Started";
    EVENT_NAME["DAPP_TRANSACTION_COMPLETED"] = "Dapp Transaction Completed";
    EVENT_NAME["DAPP_TRANSACTION_CANCELLED"] = "Dapp Transaction Cancelled";
    EVENT_NAME["CONTRACT_ADDRESS_COPIED"] = "Contract Address Copied";
    EVENT_NAME["CONTRACT_ADDRESS_NICKNAME"] = "Contract Address Nickname";
    // Sign request
    EVENT_NAME["SIGNATURE_REQUESTED"] = "Signature Requested";
    EVENT_NAME["SIGNATURE_APPROVED"] = "Signature Approved";
    EVENT_NAME["SIGNATURE_REJECTED"] = "Signature Rejected";
    // Connect request
    EVENT_NAME["CONNECT_REQUEST_STARTED"] = "Connect Request Started";
    EVENT_NAME["CONNECT_REQUEST_COMPLETED"] = "Connect Request Completed";
    EVENT_NAME["CONNECT_REQUEST_OTPFAILURE"] = "Connect Request OTP Failure";
    EVENT_NAME["CONNECT_REQUEST_CANCELLED"] = "Connect Request Cancelled";
    // Wallet
    EVENT_NAME["WALLET_OPENED"] = "Wallet Opened";
    EVENT_NAME["TOKEN_ADDED"] = "Token Added";
    EVENT_NAME["COLLECTIBLE_ADDED"] = "Collectible Added";
    EVENT_NAME["COLLECTIBLE_DETAILS_OPENED"] = "Collectible Details Opened";
    EVENT_NAME["COLLECTIBLE_REMOVED"] = "Collectible Removed";
    // Network
    EVENT_NAME["NETWORK_SWITCHED"] = "Network Switched";
    EVENT_NAME["NETWORK_ADDED"] = "Network Added";
    EVENT_NAME["NETWORK_REQUESTED"] = "Network Requested";
    EVENT_NAME["NETWORK_REQUEST_REJECTED"] = "Network Request Rejected";
    EVENT_NAME["NETWORK_SELECTOR"] = "Network Menu Opened";
    // Send transaction
    EVENT_NAME["SEND_TRANSACTION_STARTED"] = "Send Transaction Started";
    EVENT_NAME["SEND_TRANSACTION_COMPLETED"] = "Send Transaction Completed";
    // Portfolio
    EVENT_NAME["PORTFOLIO_LINK_CLICKED"] = "Portfolio Link Clicked";
    // Link redirects
    EVENT_NAME["LINK_CLICKED"] = "Link Clicked";
    // On-ramp [LEGACY]
    EVENT_NAME["ONRAMP_OPENED"] = "On-ramp Opened";
    EVENT_NAME["ONRAMP_CLOSED"] = "On-ramp Closed";
    EVENT_NAME["ONRAMP_PURCHASE_EXITED"] = "On-ramp Purchase Exited";
    EVENT_NAME["ONRAMP_PURCHASE_STARTED"] = "On-ramp Purchase Started";
    EVENT_NAME["ONRAMP_PURCHASE_SUBMISSION_FAILED"] = "On-ramp Submission Failed";
    EVENT_NAME["ONRAMP_PURCHASE_SUBMITTED_LEGACY"] = "On-ramp Purchase Submitted";
    EVENT_NAME["ONRAMP_PURCHASE_FAILED_LEGACY"] = "On-ramp Purchase Failed";
    EVENT_NAME["ONRAMP_PURCHASE_CANCELLED_LEGACY"] = "On-ramp Purchase Cancelled";
    EVENT_NAME["ONRAMP_PURCHASE_COMPLETED_LEGACY"] = "On-ramp Purchase Completed";
    // Wallet Security
    EVENT_NAME["WALLET_SECURITY_STARTED"] = "Wallet Security Started";
    EVENT_NAME["WALLET_SECURITY_MANUAL_BACKUP_INITIATED"] = "Manual Backup Initiated";
    EVENT_NAME["WALLET_SECURITY_PHRASE_REVEALED"] = "Phrase Revealed";
    EVENT_NAME["WALLET_SECURITY_PHRASE_CONFIRMED"] = "Phrase Confirmed";
    EVENT_NAME["WALLET_SECURITY_SKIP_INITIATED"] = "Wallet Security Skip Initiated";
    EVENT_NAME["WALLET_SECURITY_SKIP_CONFIRMED"] = "Wallet Security Skip Confirmed";
    EVENT_NAME["WALLET_SECURITY_RECOVERY_HINT_SAVED"] = "Recovery Hint Saved";
    EVENT_NAME["WALLET_SECURITY_COMPLETED"] = "Wallet Security Completed";
    EVENT_NAME["WALLET_SECURITY_PROTECT_VIEWED"] = "Wallet Security Reminder Viewed";
    EVENT_NAME["WALLET_SECURITY_PROTECT_ENGAGED"] = "Wallet Security Reminder Engaged";
    EVENT_NAME["WALLET_SECURITY_PROTECT_DISMISSED"] = "Wallet Security Reminder Dismissed";
    // Analytics
    EVENT_NAME["ANALYTICS_PREFERENCE_SELECTED"] = "Analytics Preference Selected";
    EVENT_NAME["ANALYTICS_REQUEST_DATA_DELETION"] = "Delete MetaMetrics Data Request Submitted";
    // Onboarding
    EVENT_NAME["ONBOARDING_WELCOME_MESSAGE_VIEWED"] = "Welcome Message Viewed";
    EVENT_NAME["ONBOARDING_WELCOME_SCREEN_ENGAGEMENT"] = "Welcome Screen Engagement";
    EVENT_NAME["ONBOARDING_STARTED"] = "Onboarding Started";
    EVENT_NAME["ONBOARDING_TOUR_STARTED"] = "Onboarding Tour Started";
    EVENT_NAME["ONBOARDING_TOUR_SKIPPED"] = "Onboarding Tour Skipped";
    EVENT_NAME["ONBOARDING_TOUR_STEP_COMPLETED"] = "Onboarding Tour Step Completed";
    EVENT_NAME["ONBOARDING_TOUR_STEP_REVISITED"] = "Onboarding Tour Step Completed";
    EVENT_NAME["ONBOARDING_TOUR_COMPLETED"] = "Onboarding Tour Completed";
    EVENT_NAME["ONBOARDING_COMPLETED"] = "Onboarding Completed";
    // Wallet Setup
    EVENT_NAME["WALLET_SETUP_STARTED"] = "Wallet Setup Started";
    EVENT_NAME["WALLET_IMPORT_STARTED"] = "Wallet Import Started";
    EVENT_NAME["WALLET_IMPORT_ATTEMPTED"] = "Wallet Import Attempted";
    EVENT_NAME["WALLET_IMPORTED"] = "Wallet Imported";
    EVENT_NAME["WALLET_CREATION_ATTEMPTED"] = "Wallet Creation Attempted";
    EVENT_NAME["WALLET_CREATED"] = "Wallet Created";
    EVENT_NAME["WALLET_SETUP_FAILURE"] = "Wallet Setup Failure";
    EVENT_NAME["WALLET_SETUP_COMPLETED"] = "Wallet Setup Completed";
    // Account
    EVENT_NAME["SWITCHED_ACCOUNT"] = "Switched Account";
    // Browser
    EVENT_NAME["BROWSER_OPENED"] = "Browser Opened";
    EVENT_NAME["BROWSER_SEARCH_USED"] = "Search Used";
    EVENT_NAME["BROWSER_NEW_TAB"] = "New Tab Opened";
    EVENT_NAME["BROWSER_SWITCH_NETWORK"] = "Switch Network";
    EVENT_NAME["BROWSER_OPEN_ACCOUNT_SWITCH"] = "Opened Account Switcher";
    EVENT_NAME["BROWSER_NAVIGATION"] = "Browser Menu Navigation Used";
    EVENT_NAME["BROWSER_SHARE_SITE"] = "Shared A Site";
    EVENT_NAME["BROWSER_RELOAD"] = "Reload Browser";
    EVENT_NAME["BROWSER_ADD_FAVORITES"] = "Added Site To Favorites";
    EVENT_NAME["BROWSER_SWITCH_TAB"] = "Switched tab within Browser";
    EVENT_NAME["DAPP_VIEWED"] = "Dapp Viewed";
    // Security & Privacy Settings
    EVENT_NAME["VIEW_SECURITY_SETTINGS"] = "Views Security & Privacy";
    // Settings
    EVENT_NAME["SETTINGS_VIEWED"] = "Settings Viewed";
    EVENT_NAME["SETTINGS_UPDATED"] = "Settings Updated";
    // Reveal SRP
    EVENT_NAME["REVEAL_SRP_CTA"] = "Clicks Reveal Secret Recovery Phrase";
    EVENT_NAME["REVEAL_SRP_SCREEN"] = "Views Reveal Secret Recovery Phrase";
    EVENT_NAME["GO_BACK_SRP_SCREEN"] = "Clicked Back on Reveal SRP Password Page";
    EVENT_NAME["CANCEL_REVEAL_SRP_CTA"] = "Clicks Cancel on Reveal Secret Recovery Phrase Page";
    EVENT_NAME["NEXT_REVEAL_SRP_CTA"] = "Clicks Next on Reveal Secret Recovery Phrase";
    EVENT_NAME["VIEW_SRP"] = "Views SRP";
    EVENT_NAME["SRP_DISMISS_HOLD_TO_REVEAL_DIALOG"] = "Closes Hold To Reveal SRP";
    EVENT_NAME["VIEW_SRP_QR"] = "Views SRP QR code";
    EVENT_NAME["COPY_SRP"] = "Copies SRP to clipboard";
    EVENT_NAME["SRP_DONE_CTA"] = "Clicks Done with SRP";
    EVENT_NAME["REVEAL_SRP_INITIATED"] = "Reveal SRP Initiated";
    EVENT_NAME["REVEAL_SRP_CANCELLED"] = "Reveal SRP Cancelled";
    EVENT_NAME["REVEAL_SRP_COMPLETED"] = "Reveal SRP Completed";
    // Reveal Private Key
    EVENT_NAME["REVEAL_PRIVATE_KEY_INITIATED"] = "Reveal Private Key Initiated";
    EVENT_NAME["REVEAL_PRIVATE_KEY_CANCELLED"] = "Reveal Private Key Cancelled";
    EVENT_NAME["REVEAL_PRIVATE_KEY_COMPLETED"] = "Reveal Private Key Completed";
    // Key Management
    EVENT_NAME["ANDROID_HARDWARE_KEYSTORE"] = "Android Hardware Keystore";
    // QR Hardware Wallet
    EVENT_NAME["CONNECT_HARDWARE_WALLET"] = "Clicked Connect Hardware Wallet";
    EVENT_NAME["CONTINUE_QR_HARDWARE_WALLET"] = "Clicked Continue QR Hardware Wallet";
    EVENT_NAME["CONNECT_HARDWARE_WALLET_SUCCESS"] = "Connected Account with hardware wallet";
    EVENT_NAME["QR_HARDWARE_TRANSACTION_CANCELED"] = "User canceled QR hardware transaction";
    EVENT_NAME["HARDWARE_WALLET_ERROR"] = "Hardware wallet error";
    // Tokens
    EVENT_NAME["TOKEN_DETECTED"] = "Token Detected";
    EVENT_NAME["TOKEN_IMPORT_CLICKED"] = "Token Import Clicked";
    EVENT_NAME["TOKEN_IMPORT_CANCELED"] = "Token Import Canceled";
    EVENT_NAME["TOKENS_HIDDEN"] = "Tokens Hidden";
    EVENT_NAME["EXTERNAL_LINK_CLICKED"] = "External Link Clicked";
    // On Ramp
    EVENT_NAME["BUY_BUTTON_CLICKED"] = "Buy Button Clicked";
    EVENT_NAME["RAMP_REGION_SELECTED"] = "Ramp Region Selected";
    EVENT_NAME["ONRAMP_GET_STARTED_CLICKED"] = "On-ramp Get Started Clicked";
    EVENT_NAME["ONRAMP_PAYMENT_METHOD_SELECTED"] = "On-ramp Payment Method Selected";
    EVENT_NAME["ONRAMP_CONTINUE_TO_AMOUNT_CLICKED"] = "On-ramp Continue To Amount Clicked";
    EVENT_NAME["ONRAMP_QUOTES_REQUESTED"] = "On-ramp Quotes Requested";
    EVENT_NAME["ONRAMP_CANCELED"] = "On-ramp Canceled";
    EVENT_NAME["ONRAMP_QUOTES_RECEIVED"] = "On-ramp Quotes Received";
    EVENT_NAME["ONRAMP_QUOTES_EXPANDED"] = "On-ramp Quotes Expanded";
    EVENT_NAME["ONRAMP_PROVIDER_SELECTED"] = "On-ramp Provider Selected";
    EVENT_NAME["ONRAMP_PROVIDER_DETAILS_VIEWED"] = "On-ramp Provider Details Viewed";
    EVENT_NAME["ONRAMP_DIRECT_PROVIDER_CLICKED"] = "On-ramp Provider Custom Action Clicked";
    EVENT_NAME["ONRAMP_PURCHASE_SUBMITTED"] = "On-ramp Purchase Submitted";
    EVENT_NAME["ONRAMP_PURCHASE_COMPLETED"] = "On-ramp Purchase Completed";
    EVENT_NAME["ONRAMP_PURCHASE_FAILED"] = "On-ramp Purchase Failed";
    EVENT_NAME["ONRAMP_PURCHASE_CANCELLED"] = "On-ramp Purchase Cancelled";
    EVENT_NAME["ONRAMP_PURCHASE_DETAILS_VIEWED"] = "On-ramp Purchase Details Viewed";
    EVENT_NAME["ONRAMP_EXTERNAL_LINK_CLICKED"] = "On-ramp External Link Clicked";
    EVENT_NAME["ONRAMP_QUOTE_ERROR"] = "On-ramp Quote Error";
    EVENT_NAME["ONRAMP_ERROR"] = "On-ramp Error";
    EVENT_NAME["ONRAMP_SETTINGS_CLICKED"] = "On-ramp Settings Clicked";
    EVENT_NAME["RAMP_REGION_RESET"] = "Ramp Region Reset";
    // Off Ramp
    EVENT_NAME["SELL_BUTTON_CLICKED"] = "Sell Button Clicked";
    EVENT_NAME["OFFRAMP_GET_STARTED_CLICKED"] = "Off-ramp Get Started Clicked";
    EVENT_NAME["OFFRAMP_PAYMENT_METHOD_SELECTED"] = "Off-ramp Payment Method Selected";
    EVENT_NAME["OFFRAMP_CONTINUE_TO_AMOUNT_CLICKED"] = "Off-ramp Continue To Amount Clicked";
    EVENT_NAME["OFFRAMP_QUOTES_REQUESTED"] = "Off-ramp Quotes Requested";
    EVENT_NAME["OFFRAMP_CANCELED"] = "Off-ramp Canceled";
    EVENT_NAME["OFFRAMP_QUOTES_RECEIVED"] = "Off-ramp Quotes Received";
    EVENT_NAME["OFFRAMP_QUOTES_EXPANDED"] = "Off-ramp Quotes Expanded";
    EVENT_NAME["OFFRAMP_PROVIDER_SELECTED"] = "Off-ramp Provider Selected";
    EVENT_NAME["OFFRAMP_PROVIDER_DETAILS_VIEWED"] = "Off-ramp Provider Details Viewed";
    EVENT_NAME["OFFRAMP_DIRECT_PROVIDER_CLICKED"] = "Off-ramp Provider Custom Action Clicked";
    EVENT_NAME["OFFRAMP_PURCHASE_SUBMITTED"] = "Off-ramp Purchase Submitted";
    EVENT_NAME["OFFRAMP_PURCHASE_COMPLETED"] = "Off-ramp Purchase Completed";
    EVENT_NAME["OFFRAMP_PURCHASE_FAILED"] = "Off-ramp Purchase Failed";
    EVENT_NAME["OFFRAMP_PURCHASE_CANCELLED"] = "Off-ramp Purchase Cancelled";
    EVENT_NAME["OFFRAMP_PURCHASE_DETAILS_VIEWED"] = "Off-ramp Purchase Details Viewed";
    EVENT_NAME["OFFRAMP_QUOTE_ERROR"] = "Off-ramp Quote Error";
    EVENT_NAME["OFFRAMP_ERROR"] = "Off-ramp Error";
    EVENT_NAME["OFFRAMP_SETTINGS_CLICKED"] = "Off-ramp Settings Clicked";
    EVENT_NAME["OFFRAMP_SEND_CRYPTO_PROMPT_VIEWED"] = "Off-ramp Send Crypto Prompt Viewed";
    EVENT_NAME["OFFRAMP_SEND_TRANSACTION_INVOKED"] = "Off-ramp Send Transaction Invoked";
    EVENT_NAME["OFFRAMP_SEND_TRANSACTION_CONFIRMED"] = "Off-ramp Send Transaction Confirmed";
    EVENT_NAME["OFFRAMP_SEND_TRANSACTION_REJECTED"] = "Off-ramp Send Transaction Rejected";
    EVENT_NAME["ACCOUNTS"] = "Accounts";
    EVENT_NAME["AUTH"] = "Auth";
    EVENT_NAME["BROWSER_VIEW"] = "Browser View";
    EVENT_NAME["COMMON_NAVIGATION"] = "Common Navigation";
    EVENT_NAME["DAPP_VIEW"] = "Dapp View";
    EVENT_NAME["NAVIGATION_DRAWER"] = "Navigation Drawer";
    EVENT_NAME["ONBOARDING"] = "Onboarding";
    EVENT_NAME["SETTINGS"] = "Settings";
    EVENT_NAME["TRANSACTIONS"] = "Transactions";
    EVENT_NAME["WALLET_VIEW"] = "Wallet View";
    EVENT_NAME["RECEIVE_OPTIONS"] = "Receive Options";
    EVENT_NAME["SEND_FLOW"] = "Send Flow";
    EVENT_NAME["DAPP_INTERACTIONS"] = "Dapp Interactions";
    EVENT_NAME["PAYMENTS"] = "Payments";
    // Swaps
    EVENT_NAME["SWAPS_OPENED"] = "Swaps Opened";
    EVENT_NAME["SWAP_TRACKING_FAILED"] = "Swap Tracking Failed";
    EVENT_NAME["QUOTES_REQUESTED"] = "Quotes Requested";
    EVENT_NAME["QUOTES_RECEIVED"] = "Quotes Received";
    EVENT_NAME["QUOTES_REQUEST_CANCELLED"] = "Quotes Request Cancelled";
    EVENT_NAME["ALL_AVAILABLE_QUOTES_OPENED"] = "All Available Quotes Opened";
    EVENT_NAME["SWAP_STARTED"] = "Swap Started";
    EVENT_NAME["SWAP_COMPLETED"] = "Swap Completed";
    EVENT_NAME["SWAP_FAILED"] = "Swap Failed";
    EVENT_NAME["QUOTES_TIMED_OUT"] = "Quotes Timed Out";
    EVENT_NAME["NO_QUOTES_AVAILABLE"] = "No Quotes Available";
    EVENT_NAME["GAS_FEES_CHANGED"] = "Gas Fees Changed";
    EVENT_NAME["EDIT_SPEND_LIMIT_OPENED"] = "Edit Spend Limit Opened";
    EVENT_NAME["TOKEN_IMPORTED"] = "Custom Token Imported";
    // Bridge
    EVENT_NAME["BRIDGE_LINK_CLICKED"] = "Bridge Linked Clicked";
    // Stake
    EVENT_NAME["STAKE_BUTTON_CLICKED"] = "Stake Button Clicked";
    // Force Upgrade | Automatic Security Checks
    EVENT_NAME["FORCE_UPGRADE_UPDATE_NEEDED_PROMPT_VIEWED"] = "Force Upgrade Update Needed Prompt Viewed";
    EVENT_NAME["FORCE_UPGRADE_UPDATE_TO_THE_LATEST_VERSION_CLICKED"] = "Force Upgrade Clicked Update to Latest Version";
    EVENT_NAME["FORCE_UPGRADE_REMIND_ME_LATER_CLICKED"] = "Force Upgrade Clicked Remind Me Later";
    EVENT_NAME["AUTOMATIC_SECURITY_CHECKS_PROMPT_VIEWED"] = "Automatic Security Checks Prompt Viewed";
    EVENT_NAME["AUTOMATIC_SECURITY_CHECKS_ENABLED_FROM_PROMPT"] = "Automatic Security Checks Enabled From Prompt";
    EVENT_NAME["AUTOMATIC_SECURITY_CHECKS_DISABLED_FROM_PROMPT"] = "Automatic Security Checks Disabled From Prompt";
    EVENT_NAME["AUTOMATIC_SECURITY_CHECKS_ENABLED_FROM_SETTINGS"] = "Automatic Security Checks Enabled From Settings";
    EVENT_NAME["AUTOMATIC_SECURITY_CHECKS_DISABLED_FROM_SETTINGS"] = "Automatic Security Checks Disabled From Settings";
    // Screenshots Deterrent
    EVENT_NAME["SCREENSHOT_WARNING"] = "Screenshot Warning Displayed";
    EVENT_NAME["SCREENSHOT_LEARN_MORE"] = "Clicked Screenshot Warning Learn More";
    EVENT_NAME["SCREENSHOT_OK"] = "Clicked Screenshot Warning OK";
    //Terms of Use
    EVENT_NAME["USER_TERMS_SHOWN"] = "Terms of Use Shown";
    EVENT_NAME["USER_TERMS_ACCEPTED"] = "Terms of Use Accepted";
    // Reveal SRP Quiz
    EVENT_NAME["SRP_REVEAL_QUIZ_PROMPT_SEEN"] = "SRP reveal quiz prompt seen";
    EVENT_NAME["SRP_REVEAL_START_CTA_SELECTED"] = "SRP reveal get started CTA selected";
    EVENT_NAME["SRP_REVEAL_FIRST_QUESTION_SEEN"] = "SRP reveal first question seen";
    EVENT_NAME["SRP_REVEAL_FIRST_QUESTION_WRONG_ANSWER"] = "SRP reveal first question answered incorrectly";
    EVENT_NAME["SRP_REVEAL_FIRST_QUESTION_RIGHT_ASNWER"] = "SRP reveal first question answered correctly";
    EVENT_NAME["SRP_REVEAL_SECOND_QUESTION_SEEN"] = "SRP reveal second question seen";
    EVENT_NAME["SRP_REVEAL_SECOND_QUESTION_WRONG_ANSWER"] = "SRP reveal second question answered incorrectly";
    EVENT_NAME["SRP_REVEAL_SECOND_QUESTION_RIGHT_ASNWER"] = "SRP reveal second question answered correctly";
    EVENT_NAME["REVEAL_SRP"] = "Reveal SRP";
    EVENT_NAME["SRP_COPIED"] = "SRP copied";
    // Permission request
    EVENT_NAME["PERMISSION_REQUEST_STARTED"] = "Permission Request Started";
    EVENT_NAME["PERMISSION_REQUEST_COMPLETED"] = "Permission Request Completed";
    EVENT_NAME["PERMISSION_REQUEST_CANCELLED"] = "Permission Request Cancelled";
    EVENT_NAME["OPEN_DAPP_PERMISSIONS"] = "Viewed dapp permissions";
    EVENT_NAME["CHANGE_DAPP_PERMISSIONS"] = "Changed dapp permissions";
    // Vault Corruption
    EVENT_NAME["VAULT_CORRUPTION_RESTORE_WALLET_SCREEN_VIEWED"] = "Vault Corruption Restore Wallet Screen Viewed";
    EVENT_NAME["VAULT_CORRUPTION_RESTORE_WALLET_BUTTON_PRESSED"] = "Vault Corruption Restore Wallet Button Pressed";
    EVENT_NAME["VAULT_CORRUPTION_WALLET_SUCCESSFULLY_RESTORED_SCREEN_VIEWED"] = "Vault Corruption Wallet Successfully Restored Screen Viewed";
    EVENT_NAME["VAULT_CORRUPTION_WALLET_SUCCESSFULLY_RESTORED_CONTINUE_BUTTON_PRESSED"] = "Vault Corruption Wallet Successfully Restored Continue To Wallet Button Pressed";
    EVENT_NAME["VAULT_CORRUPTION_WALLET_RESET_NEEDED_SCREEN_VIEWED"] = "Vault Corruption Wallet Reset Needed Screen Viewed";
    EVENT_NAME["VAULT_CORRUPTION_WALLET_RESET_NEEDED_TRY_AGAIN_BUTTON_PRESSED"] = "Vault Corruption Wallet Reset Needed Try Again Button Pressed";
    EVENT_NAME["VAULT_CORRUPTION_WALLET_RESET_NEEDED_CREATE_NEW_WALLET_BUTTON_PRESSED"] = "Vault Corruption Wallet Reset Needed Create A New Wallet Button Pressed";
    // Login screen
    EVENT_NAME["LOGIN_SCREEN_VIEWED"] = "Login Screen Viewed";
    // Delete Wallet Modal
    EVENT_NAME["DELETE_WALLET_MODAL_WALLET_DELETED"] = "Delete Wallet Modal Wallet Deleted";
    // Tab Bar Actions
    EVENT_NAME["ACTIONS_BUTTON_CLICKED"] = "Global Actions Button Clicked";
    EVENT_NAME["RECEIVE_BUTTON_CLICKED"] = "Receive Button Clicked";
    EVENT_NAME["SWAP_BUTTON_CLICKED"] = "Swaps Button Clicked";
    EVENT_NAME["SEND_BUTTON_CLICKED"] = "Send Button Clicked";
    // Edit account name
    EVENT_NAME["ACCOUNT_RENAMED"] = "Account Renamed";
    //Ledger
    EVENT_NAME["CONNECT_LEDGER"] = "Clicked Connect Ledger";
    EVENT_NAME["CONTINUE_LEDGER_HARDWARE_WALLET"] = "Clicked Continue Ledger Hardware Wallet";
    EVENT_NAME["CONNECT_LEDGER_SUCCESS"] = "Connected Account with hardware wallet";
    EVENT_NAME["LEDGER_HARDWARE_TRANSACTION_CANCELLED"] = "User canceled Ledger hardware transaction";
    EVENT_NAME["LEDGER_HARDWARE_WALLET_ERROR"] = "Ledger hardware wallet error";
    // common hardware wallet
    EVENT_NAME["HARDWARE_WALLET_FORGOTTEN"] = "Hardware wallet forgotten";
    // Remove an account
    EVENT_NAME["ACCOUNT_REMOVED"] = "Account removed";
    //Notifications
    EVENT_NAME["ALL_NOTIFICATIONS"] = "All Notifications";
    EVENT_NAME["WALLET_NOTIFICATIONS"] = "Wallet Notifications";
    EVENT_NAME["ANNOUCEMENTS_NOTIFICATIONS"] = "Annoucements Notifications";
    // Smart transactions
    EVENT_NAME["SMART_TRANSACTION_OPT_IN"] = "Smart Transaction Opt In";
    // Simulations
    EVENT_NAME["INCOMPLETE_ASSET_DISPLAYED"] = "Incomplete Asset Displayed";
    // Nft auto detection modal
    EVENT_NAME["NFT_AUTO_DETECTION_ENABLED_MODAL"] = "Nft Autodetection Enabled from modal";
    EVENT_NAME["NFT_AUTO_DETECTION_DISBLED_MODAL"] = "Nft Autodetection Disabled from modal";
    // NFT auto detection events
    EVENT_NAME["NFT_AUTO_DETECTION_ENABLED"] = "nft_autodetection_enabled";
    EVENT_NAME["PRIMARY_CURRENCY_TOGGLE"] = "primary_currency_toggle";
})(EVENT_NAME || (EVENT_NAME = {}));
exports.EVENT_NAME = EVENT_NAME;
var ACTIONS;
(function (ACTIONS) {
    //Onboarding
    ACTIONS["METRICS_OPTS"] = "Metrics Option";
    ACTIONS["IMPORT_OR_CREATE"] = "Import or Create";
    ACTIONS["IMPORT_OR_SYNC"] = "Import or Sync";
    ACTIONS["ONBOARDING_NEXT"] = "Onboarding Next";
    // Navigation Drawer
    ACTIONS["NAVIGATION_DRAWER"] = "Navigation Drawer";
    // Common Navigation
    ACTIONS["COMMON_BROWSER_DAPP_WALLET"] = "Browser & Dapp & Wallet View";
    // Browser
    ACTIONS["BROWSER_VIEW"] = "Browser View";
    // Dapp
    ACTIONS["DAPP_VIEW"] = "Dapp View";
    // Wallet
    ACTIONS["WALLET_VIEW"] = "Wallet View";
    //Transactions
    ACTIONS["CONFIRM_SCREEN"] = "Confirm Screen";
    ACTIONS["SIGN_SCREEN"] = "Sign Request";
    // Accounts
    ACTIONS["ACCOUNTS_MODAL"] = "Account Modal";
    // Authentication
    ACTIONS["UNLOCK"] = "Unlock";
    ACTIONS["CONNECT"] = "Connect";
    // Settings
    ACTIONS["SETTINGS"] = "Settings";
    // Receive Options
    ACTIONS["RECEIVE_OPTIONS"] = "Receive Options";
    // Send Flow
    ACTIONS["SEND_FLOW"] = "Send Flow";
    // Dapp Interactions
    ACTIONS["APPROVE_REQUEST"] = "Approve Request";
    ACTIONS["BUY_ETH"] = "Buy ETH";
    ACTIONS["SELECTS_DEBIT_OR_ACH"] = "Selects Debit or ACH";
    ACTIONS["SELECTS_APPLE_PAY"] = "Selects Apple Pay";
    // Swaps
    ACTIONS["QUOTE"] = "Quote";
    ACTIONS["SWAP"] = "Swap";
    ACTIONS["BRIDGE"] = "Bridge";
    ACTIONS["PERMISSION_NEW_ACCOUNT"] = "Connected new account(s)";
    ACTIONS["PERMISSION_REVOKE_ACCOUNT"] = "Revoked account(s)";
    ACTIONS["ADVANCED_SETTINGS_ETH_SIGN_FRICTION_FIRST_STEP"] = "eth_sign_checkbox_seen";
    ACTIONS["ADVANCED_SETTINGS_ETH_SIGN_FRICTION_SECOND_STEP"] = "eth_sign_input_seen";
    ACTIONS["ADVANCED_SETTINGS_ETH_SIGN_ENABLED"] = "eth_sign_enabled";
    ACTIONS["ADVANCED_SETTINGS_ETH_SIGN_DISABLED"] = "eth_sign_disabled";
    ACTIONS["STAKE"] = "Stake";
    // Notifications
    ACTIONS["SELECTS_ALL_NOTIFICATIONS"] = "Selects All Notifications";
    ACTIONS["SELECTS_WALLET_NOTIFICATIONS"] = "Selects Wallet Notifications";
    ACTIONS["SELECTS_ANNOUCEMENTS_NOTIFICATIONS"] = "Selects Annoucements Notifications";
})(ACTIONS || (ACTIONS = {}));
var events = {
    ERROR: generateOpt(EVENT_NAME.ERROR),
    ERROR_SCREEN_VIEWED: generateOpt(EVENT_NAME.ERROR_SCREEN_VIEWED),
    APPROVAL_STARTED: generateOpt(EVENT_NAME.APPROVAL_STARTED),
    APPROVAL_COMPLETED: generateOpt(EVENT_NAME.APPROVAL_COMPLETED),
    APPROVAL_CANCELLED: generateOpt(EVENT_NAME.APPROVAL_CANCELLED),
    APPROVAL_PERMISSION_UPDATED: generateOpt(EVENT_NAME.APPROVAL_PERMISSION_UPDATED),
    GAS_FEE_CHANGED: generateOpt(EVENT_NAME.GAS_FEES_CHANGED),
    GAS_ADVANCED_OPTIONS_CLICKED: generateOpt(EVENT_NAME.GAS_ADVANCED_OPTIONS_CLICKED),
    DAPP_TRANSACTION_STARTED: generateOpt(EVENT_NAME.DAPP_TRANSACTION_STARTED),
    DAPP_TRANSACTION_COMPLETED: generateOpt(EVENT_NAME.DAPP_TRANSACTION_COMPLETED),
    DAPP_TRANSACTION_CANCELLED: generateOpt(EVENT_NAME.DAPP_TRANSACTION_CANCELLED),
    CONTRACT_ADDRESS_COPIED: generateOpt(EVENT_NAME.CONTRACT_ADDRESS_COPIED),
    CONTRACT_ADDRESS_NICKNAME: generateOpt(EVENT_NAME.CONTRACT_ADDRESS_NICKNAME),
    SIGNATURE_REQUESTED: generateOpt(EVENT_NAME.SIGNATURE_REQUESTED),
    SIGNATURE_APPROVED: generateOpt(EVENT_NAME.SIGNATURE_APPROVED),
    SIGNATURE_REJECTED: generateOpt(EVENT_NAME.SIGNATURE_REJECTED),
    CONNECT_REQUEST_STARTED: generateOpt(EVENT_NAME.CONNECT_REQUEST_STARTED),
    CONNECT_REQUEST_COMPLETED: generateOpt(EVENT_NAME.CONNECT_REQUEST_COMPLETED),
    CONNECT_REQUEST_OTPFAILURE: generateOpt(EVENT_NAME.CONNECT_REQUEST_OTPFAILURE),
    CONNECT_REQUEST_CANCELLED: generateOpt(EVENT_NAME.CONNECT_REQUEST_CANCELLED),
    WALLET_OPENED: generateOpt(EVENT_NAME.WALLET_OPENED),
    TOKEN_ADDED: generateOpt(EVENT_NAME.TOKEN_ADDED),
    COLLECTIBLE_ADDED: generateOpt(EVENT_NAME.COLLECTIBLE_ADDED),
    COLLECTIBLE_DETAILS_OPENED: generateOpt(EVENT_NAME.COLLECTIBLE_DETAILS_OPENED),
    COLLECTIBLE_REMOVED: generateOpt(EVENT_NAME.COLLECTIBLE_REMOVED),
    NETWORK_SWITCHED: generateOpt(EVENT_NAME.NETWORK_SWITCHED),
    NETWORK_ADDED: generateOpt(EVENT_NAME.NETWORK_ADDED),
    NETWORK_REQUESTED: generateOpt(EVENT_NAME.NETWORK_REQUESTED),
    NETWORK_REQUEST_REJECTED: generateOpt(EVENT_NAME.NETWORK_REQUEST_REJECTED),
    SEND_TRANSACTION_STARTED: generateOpt(EVENT_NAME.SEND_TRANSACTION_STARTED),
    SEND_TRANSACTION_COMPLETED: generateOpt(EVENT_NAME.SEND_TRANSACTION_COMPLETED),
    EXTERNAL_LINK_CLICKED: generateOpt(EVENT_NAME.EXTERNAL_LINK_CLICKED),
    ONRAMP_OPENED: generateOpt(EVENT_NAME.ONRAMP_OPENED),
    ONRAMP_CLOSED: generateOpt(EVENT_NAME.ONRAMP_CLOSED),
    ONRAMP_PURCHASE_EXITED: generateOpt(EVENT_NAME.ONRAMP_PURCHASE_EXITED),
    ONRAMP_PURCHASE_STARTED: generateOpt(EVENT_NAME.ONRAMP_PURCHASE_STARTED),
    ONRAMP_PURCHASE_SUBMISSION_FAILED: generateOpt(EVENT_NAME.ONRAMP_PURCHASE_SUBMISSION_FAILED),
    ONRAMP_PURCHASE_SUBMITTED_LEGACY: generateOpt(EVENT_NAME.ONRAMP_PURCHASE_SUBMITTED_LEGACY),
    ONRAMP_PURCHASE_FAILED_LEGACY: generateOpt(EVENT_NAME.ONRAMP_PURCHASE_FAILED_LEGACY),
    ONRAMP_PURCHASE_CANCELLED_LEGACY: generateOpt(EVENT_NAME.ONRAMP_PURCHASE_CANCELLED_LEGACY),
    ONRAMP_PURCHASE_COMPLETED_LEGACY: generateOpt(EVENT_NAME.ONRAMP_PURCHASE_COMPLETED_LEGACY),
    PORTFOLIO_LINK_CLICKED: generateOpt(EVENT_NAME.PORTFOLIO_LINK_CLICKED),
    LINK_CLICKED: generateOpt(EVENT_NAME.LINK_CLICKED),
    WALLET_SECURITY_STARTED: generateOpt(EVENT_NAME.WALLET_SECURITY_STARTED),
    WALLET_SECURITY_MANUAL_BACKUP_INITIATED: generateOpt(EVENT_NAME.WALLET_SECURITY_MANUAL_BACKUP_INITIATED),
    WALLET_SECURITY_PHRASE_REVEALED: generateOpt(EVENT_NAME.WALLET_SECURITY_PHRASE_REVEALED),
    WALLET_SECURITY_PHRASE_CONFIRMED: generateOpt(EVENT_NAME.WALLET_SECURITY_PHRASE_CONFIRMED),
    WALLET_SECURITY_SKIP_INITIATED: generateOpt(EVENT_NAME.WALLET_SECURITY_SKIP_INITIATED),
    WALLET_SECURITY_SKIP_CONFIRMED: generateOpt(EVENT_NAME.WALLET_SECURITY_SKIP_CONFIRMED),
    WALLET_SECURITY_RECOVERY_HINT_SAVED: generateOpt(EVENT_NAME.WALLET_SECURITY_RECOVERY_HINT_SAVED),
    WALLET_SECURITY_COMPLETED: generateOpt(EVENT_NAME.WALLET_SECURITY_COMPLETED),
    WALLET_SECURITY_PROTECT_VIEWED: generateOpt(EVENT_NAME.WALLET_SECURITY_PROTECT_VIEWED),
    WALLET_SECURITY_PROTECT_ENGAGED: generateOpt(EVENT_NAME.WALLET_SECURITY_PROTECT_ENGAGED),
    WALLET_SECURITY_PROTECT_DISMISSED: generateOpt(EVENT_NAME.WALLET_SECURITY_PROTECT_DISMISSED),
    ANALYTICS_PREFERENCE_SELECTED: generateOpt(EVENT_NAME.ANALYTICS_PREFERENCE_SELECTED),
    ANALYTICS_REQUEST_DATA_DELETION: generateOpt(EVENT_NAME.ANALYTICS_REQUEST_DATA_DELETION),
    ONBOARDING_WELCOME_MESSAGE_VIEWED: generateOpt(EVENT_NAME.ONBOARDING_WELCOME_MESSAGE_VIEWED),
    ONBOARDING_WELCOME_SCREEN_ENGAGEMENT: generateOpt(EVENT_NAME.ONBOARDING_WELCOME_SCREEN_ENGAGEMENT),
    ONBOARDING_STARTED: generateOpt(EVENT_NAME.ONBOARDING_STARTED),
    ONBOARDING_TOUR_STARTED: generateOpt(EVENT_NAME.ONBOARDING_TOUR_STARTED),
    ONBOARDING_TOUR_SKIPPED: generateOpt(EVENT_NAME.ONBOARDING_TOUR_SKIPPED),
    ONBOARDING_TOUR_STEP_COMPLETED: generateOpt(EVENT_NAME.ONBOARDING_TOUR_STEP_COMPLETED),
    ONBOARDING_TOUR_STEP_REVISITED: generateOpt(EVENT_NAME.ONBOARDING_TOUR_STEP_REVISITED),
    ONBOARDING_TOUR_COMPLETED: generateOpt(EVENT_NAME.ONBOARDING_TOUR_COMPLETED),
    ONBOARDING_COMPLETED: generateOpt(EVENT_NAME.ONBOARDING_COMPLETED),
    WALLET_SETUP_STARTED: generateOpt(EVENT_NAME.WALLET_SETUP_STARTED),
    WALLET_IMPORT_STARTED: generateOpt(EVENT_NAME.WALLET_IMPORT_STARTED),
    WALLET_IMPORT_ATTEMPTED: generateOpt(EVENT_NAME.WALLET_IMPORT_ATTEMPTED),
    WALLET_IMPORTED: generateOpt(EVENT_NAME.WALLET_IMPORTED),
    WALLET_CREATION_ATTEMPTED: generateOpt(EVENT_NAME.WALLET_CREATION_ATTEMPTED),
    WALLET_CREATED: generateOpt(EVENT_NAME.WALLET_CREATED),
    WALLET_SETUP_FAILURE: generateOpt(EVENT_NAME.WALLET_SETUP_FAILURE),
    WALLET_SETUP_COMPLETED: generateOpt(EVENT_NAME.WALLET_SETUP_COMPLETED),
    SWITCHED_ACCOUNT: generateOpt(EVENT_NAME.SWITCHED_ACCOUNT),
    BROWSER_OPENED: generateOpt(EVENT_NAME.BROWSER_OPENED),
    BROWSER_SEARCH_USED: generateOpt(EVENT_NAME.BROWSER_SEARCH_USED),
    BROWSER_NEW_TAB: generateOpt(EVENT_NAME.BROWSER_NEW_TAB),
    BROWSER_SWITCH_NETWORK: generateOpt(EVENT_NAME.BROWSER_SWITCH_NETWORK),
    BROWSER_OPEN_ACCOUNT_SWITCH: generateOpt(EVENT_NAME.BROWSER_OPEN_ACCOUNT_SWITCH),
    BROWSER_NAVIGATION: generateOpt(EVENT_NAME.BROWSER_NAVIGATION),
    BROWSER_SHARE_SITE: generateOpt(EVENT_NAME.BROWSER_SHARE_SITE),
    BROWSER_RELOAD: generateOpt(EVENT_NAME.BROWSER_RELOAD),
    BROWSER_ADD_FAVORITES: generateOpt(EVENT_NAME.BROWSER_ADD_FAVORITES),
    DAPP_VIEWED: generateOpt(EVENT_NAME.DAPP_VIEWED),
    // Security & Privacy Settings
    VIEW_SECURITY_SETTINGS: generateOpt(EVENT_NAME.VIEW_SECURITY_SETTINGS),
    // Reveal SRP
    REVEAL_SRP_CTA: generateOpt(EVENT_NAME.REVEAL_SRP_CTA),
    REVEAL_SRP_SCREEN: generateOpt(EVENT_NAME.REVEAL_SRP_SCREEN),
    GO_BACK_SRP_SCREEN: generateOpt(EVENT_NAME.GO_BACK_SRP_SCREEN),
    CANCEL_REVEAL_SRP_CTA: generateOpt(EVENT_NAME.CANCEL_REVEAL_SRP_CTA),
    NEXT_REVEAL_SRP_CTA: generateOpt(EVENT_NAME.NEXT_REVEAL_SRP_CTA),
    VIEW_SRP: generateOpt(EVENT_NAME.VIEW_SRP),
    SRP_DISMISS_HOLD_TO_REVEAL_DIALOG: generateOpt(EVENT_NAME.SRP_DISMISS_HOLD_TO_REVEAL_DIALOG),
    VIEW_SRP_QR: generateOpt(EVENT_NAME.VIEW_SRP_QR),
    COPY_SRP: generateOpt(EVENT_NAME.COPY_SRP),
    SRP_DONE_CTA: generateOpt(EVENT_NAME.SRP_DONE_CTA),
    REVEAL_SRP_INITIATED: generateOpt(EVENT_NAME.REVEAL_SRP_INITIATED),
    REVEAL_SRP_CANCELLED: generateOpt(EVENT_NAME.REVEAL_SRP_CANCELLED),
    REVEAL_SRP_COMPLETED: generateOpt(EVENT_NAME.REVEAL_SRP_COMPLETED),
    REVEAL_PRIVATE_KEY_INITIATED: generateOpt(EVENT_NAME.REVEAL_PRIVATE_KEY_INITIATED),
    REVEAL_PRIVATE_KEY_CANCELLED: generateOpt(EVENT_NAME.REVEAL_PRIVATE_KEY_CANCELLED),
    REVEAL_PRIVATE_KEY_COMPLETED: generateOpt(EVENT_NAME.REVEAL_PRIVATE_KEY_COMPLETED),
    ANDROID_HARDWARE_KEYSTORE: generateOpt(EVENT_NAME.ANDROID_HARDWARE_KEYSTORE),
    CONNECT_HARDWARE_WALLET: generateOpt(EVENT_NAME.CONNECT_HARDWARE_WALLET),
    CONTINUE_QR_HARDWARE_WALLET: generateOpt(EVENT_NAME.CONTINUE_QR_HARDWARE_WALLET),
    CONNECT_HARDWARE_WALLET_SUCCESS: generateOpt(EVENT_NAME.CONNECT_HARDWARE_WALLET_SUCCESS),
    QR_HARDWARE_TRANSACTION_CANCELED: generateOpt(EVENT_NAME.QR_HARDWARE_TRANSACTION_CANCELED),
    HARDWARE_WALLET_ERROR: generateOpt(EVENT_NAME.HARDWARE_WALLET_ERROR),
    TOKEN_DETECTED: generateOpt(EVENT_NAME.TOKEN_DETECTED),
    TOKEN_IMPORT_CLICKED: generateOpt(EVENT_NAME.TOKEN_IMPORT_CLICKED),
    TOKEN_IMPORT_CANCELED: generateOpt(EVENT_NAME.TOKEN_IMPORT_CANCELED),
    TOKENS_HIDDEN: generateOpt(EVENT_NAME.TOKENS_HIDDEN),
    // ONRAMP
    BUY_BUTTON_CLICKED: generateOpt(EVENT_NAME.BUY_BUTTON_CLICKED),
    RAMP_REGION_SELECTED: generateOpt(EVENT_NAME.RAMP_REGION_SELECTED),
    ONRAMP_GET_STARTED_CLICKED: generateOpt(EVENT_NAME.ONRAMP_GET_STARTED_CLICKED),
    ONRAMP_PAYMENT_METHOD_SELECTED: generateOpt(EVENT_NAME.ONRAMP_PAYMENT_METHOD_SELECTED),
    ONRAMP_CONTINUE_TO_AMOUNT_CLICKED: generateOpt(EVENT_NAME.ONRAMP_CONTINUE_TO_AMOUNT_CLICKED),
    ONRAMP_QUOTES_REQUESTED: generateOpt(EVENT_NAME.ONRAMP_QUOTES_REQUESTED),
    ONRAMP_CANCELED: generateOpt(EVENT_NAME.ONRAMP_CANCELED),
    ONRAMP_QUOTES_RECEIVED: generateOpt(EVENT_NAME.ONRAMP_QUOTES_RECEIVED),
    ONRAMP_QUOTES_EXPANDED: generateOpt(EVENT_NAME.ONRAMP_QUOTES_EXPANDED),
    ONRAMP_PROVIDER_SELECTED: generateOpt(EVENT_NAME.ONRAMP_PROVIDER_SELECTED),
    ONRAMP_PROVIDER_DETAILS_VIEWED: generateOpt(EVENT_NAME.ONRAMP_PROVIDER_DETAILS_VIEWED),
    ONRAMP_DIRECT_PROVIDER_CLICKED: generateOpt(EVENT_NAME.ONRAMP_DIRECT_PROVIDER_CLICKED),
    ONRAMP_PURCHASE_SUBMITTED: generateOpt(EVENT_NAME.ONRAMP_PURCHASE_SUBMITTED),
    ONRAMP_PURCHASE_COMPLETED: generateOpt(EVENT_NAME.ONRAMP_PURCHASE_COMPLETED),
    ONRAMP_PURCHASE_FAILED: generateOpt(EVENT_NAME.ONRAMP_PURCHASE_FAILED),
    ONRAMP_PURCHASE_CANCELLED: generateOpt(EVENT_NAME.ONRAMP_PURCHASE_CANCELLED),
    ONRAMP_PURCHASE_DETAILS_VIEWED: generateOpt(EVENT_NAME.ONRAMP_PURCHASE_DETAILS_VIEWED),
    ONRAMP_EXTERNAL_LINK_CLICKED: generateOpt(EVENT_NAME.ONRAMP_EXTERNAL_LINK_CLICKED),
    ONRAMP_QUOTE_ERROR: generateOpt(EVENT_NAME.ONRAMP_QUOTE_ERROR),
    ONRAMP_ERROR: generateOpt(EVENT_NAME.ONRAMP_ERROR),
    ONRAMP_SETTINGS_CLICKED: generateOpt(EVENT_NAME.ONRAMP_SETTINGS_CLICKED),
    RAMP_REGION_RESET: generateOpt(EVENT_NAME.RAMP_REGION_RESET),
    // OFFRAMP
    SELL_BUTTON_CLICKED: generateOpt(EVENT_NAME.SELL_BUTTON_CLICKED),
    OFFRAMP_GET_STARTED_CLICKED: generateOpt(EVENT_NAME.OFFRAMP_GET_STARTED_CLICKED),
    OFFRAMP_PAYMENT_METHOD_SELECTED: generateOpt(EVENT_NAME.OFFRAMP_PAYMENT_METHOD_SELECTED),
    OFFRAMP_CONTINUE_TO_AMOUNT_CLICKED: generateOpt(EVENT_NAME.OFFRAMP_CONTINUE_TO_AMOUNT_CLICKED),
    OFFRAMP_QUOTES_REQUESTED: generateOpt(EVENT_NAME.OFFRAMP_QUOTES_REQUESTED),
    OFFRAMP_CANCELED: generateOpt(EVENT_NAME.OFFRAMP_CANCELED),
    OFFRAMP_QUOTES_RECEIVED: generateOpt(EVENT_NAME.OFFRAMP_QUOTES_RECEIVED),
    OFFRAMP_QUOTES_EXPANDED: generateOpt(EVENT_NAME.OFFRAMP_QUOTES_EXPANDED),
    OFFRAMP_PROVIDER_SELECTED: generateOpt(EVENT_NAME.OFFRAMP_PROVIDER_SELECTED),
    OFFRAMP_PROVIDER_DETAILS_VIEWED: generateOpt(EVENT_NAME.OFFRAMP_PROVIDER_DETAILS_VIEWED),
    OFFRAMP_DIRECT_PROVIDER_CLICKED: generateOpt(EVENT_NAME.OFFRAMP_DIRECT_PROVIDER_CLICKED),
    OFFRAMP_PURCHASE_SUBMITTED: generateOpt(EVENT_NAME.OFFRAMP_PURCHASE_SUBMITTED),
    OFFRAMP_PURCHASE_COMPLETED: generateOpt(EVENT_NAME.OFFRAMP_PURCHASE_COMPLETED),
    OFFRAMP_PURCHASE_FAILED: generateOpt(EVENT_NAME.OFFRAMP_PURCHASE_FAILED),
    OFFRAMP_PURCHASE_CANCELLED: generateOpt(EVENT_NAME.OFFRAMP_PURCHASE_CANCELLED),
    OFFRAMP_PURCHASE_DETAILS_VIEWED: generateOpt(EVENT_NAME.OFFRAMP_PURCHASE_DETAILS_VIEWED),
    OFFRAMP_QUOTE_ERROR: generateOpt(EVENT_NAME.OFFRAMP_QUOTE_ERROR),
    OFFRAMP_ERROR: generateOpt(EVENT_NAME.OFFRAMP_ERROR),
    OFFRAMP_SETTINGS_CLICKED: generateOpt(EVENT_NAME.OFFRAMP_SETTINGS_CLICKED),
    OFFRAMP_SEND_CRYPTO_PROMPT_VIEWED: generateOpt(EVENT_NAME.OFFRAMP_SEND_CRYPTO_PROMPT_VIEWED),
    OFFRAMP_SEND_TRANSACTION_INVOKED: generateOpt(EVENT_NAME.OFFRAMP_SEND_TRANSACTION_INVOKED),
    OFFRAMP_SEND_TRANSACTION_CONFIRMED: generateOpt(EVENT_NAME.OFFRAMP_SEND_TRANSACTION_CONFIRMED),
    OFFRAMP_SEND_TRANSACTION_REJECTED: generateOpt(EVENT_NAME.OFFRAMP_SEND_TRANSACTION_REJECTED),
    FORCE_UPGRADE_UPDATE_NEEDED_PROMPT_VIEWED: generateOpt(EVENT_NAME.FORCE_UPGRADE_UPDATE_NEEDED_PROMPT_VIEWED),
    FORCE_UPGRADE_UPDATE_TO_THE_LATEST_VERSION_CLICKED: generateOpt(EVENT_NAME.FORCE_UPGRADE_UPDATE_TO_THE_LATEST_VERSION_CLICKED),
    FORCE_UPGRADE_REMIND_ME_LATER_CLICKED: generateOpt(EVENT_NAME.FORCE_UPGRADE_REMIND_ME_LATER_CLICKED),
    AUTOMATIC_SECURITY_CHECKS_PROMPT_VIEWED: generateOpt(EVENT_NAME.AUTOMATIC_SECURITY_CHECKS_PROMPT_VIEWED),
    AUTOMATIC_SECURITY_CHECKS_ENABLED_FROM_PROMPT: generateOpt(EVENT_NAME.AUTOMATIC_SECURITY_CHECKS_ENABLED_FROM_PROMPT),
    AUTOMATIC_SECURITY_CHECKS_DISABLED_FROM_PROMPT: generateOpt(EVENT_NAME.AUTOMATIC_SECURITY_CHECKS_DISABLED_FROM_PROMPT),
    AUTOMATIC_SECURITY_CHECKS_ENABLED_FROM_SETTINGS: generateOpt(EVENT_NAME.AUTOMATIC_SECURITY_CHECKS_ENABLED_FROM_SETTINGS),
    AUTOMATIC_SECURITY_CHECKS_DISABLED_FROM_SETTINGS: generateOpt(EVENT_NAME.AUTOMATIC_SECURITY_CHECKS_DISABLED_FROM_SETTINGS),
    SCREENSHOT_WARNING: generateOpt(EVENT_NAME.SCREENSHOT_WARNING),
    SCREENSHOT_LEARN_MORE: generateOpt(EVENT_NAME.SCREENSHOT_LEARN_MORE),
    SCREENSHOT_OK: generateOpt(EVENT_NAME.SCREENSHOT_OK),
    USER_TERMS_SHOWN: generateOpt(EVENT_NAME.USER_TERMS_SHOWN),
    USER_TERMS_ACCEPTED: generateOpt(EVENT_NAME.USER_TERMS_ACCEPTED),
    SRP_REVEAL_QUIZ_PROMPT_SEEN: generateOpt(EVENT_NAME.SRP_REVEAL_QUIZ_PROMPT_SEEN),
    SRP_REVEAL_START_CTA_SELECTED: generateOpt(EVENT_NAME.SRP_REVEAL_START_CTA_SELECTED),
    SRP_REVEAL_FIRST_QUESTION_SEEN: generateOpt(EVENT_NAME.SRP_REVEAL_FIRST_QUESTION_SEEN),
    SRP_REVEAL_FIRST_QUESTION_WRONG_ANSWER: generateOpt(EVENT_NAME.SRP_REVEAL_FIRST_QUESTION_WRONG_ANSWER),
    SRP_REVEAL_FIRST_QUESTION_RIGHT_ASNWER: generateOpt(EVENT_NAME.SRP_REVEAL_FIRST_QUESTION_RIGHT_ASNWER),
    SRP_REVEAL_SECOND_QUESTION_SEEN: generateOpt(EVENT_NAME.SRP_REVEAL_SECOND_QUESTION_SEEN),
    SRP_REVEAL_SECOND_QUESTION_WRONG_ANSWER: generateOpt(EVENT_NAME.SRP_REVEAL_SECOND_QUESTION_WRONG_ANSWER),
    SRP_REVEAL_SECOND_QUESTION_RIGHT_ASNWER: generateOpt(EVENT_NAME.SRP_REVEAL_SECOND_QUESTION_RIGHT_ASNWER),
    REVEAL_SRP: generateOpt(EVENT_NAME.REVEAL_SRP),
    SRP_COPIED: generateOpt(EVENT_NAME.SRP_COPIED),
    PERMISSION_REQUEST_STARTED: generateOpt(EVENT_NAME.PERMISSION_REQUEST_STARTED),
    PERMISSION_REQUEST_CANCELLED: generateOpt(EVENT_NAME.PERMISSION_REQUEST_CANCELLED),
    PERMISSION_REQUEST_COMPLETED: generateOpt(EVENT_NAME.PERMISSION_REQUEST_COMPLETED),
    OPEN_DAPP_PERMISSIONS: generateOpt(EVENT_NAME.OPEN_DAPP_PERMISSIONS),
    REVOKE_ACCOUNT_DAPP_PERMISSIONS: generateOpt(EVENT_NAME.CHANGE_DAPP_PERMISSIONS, ACTIONS.PERMISSION_REVOKE_ACCOUNT),
    ADD_ACCOUNT_DAPP_PERMISSIONS: generateOpt(EVENT_NAME.CHANGE_DAPP_PERMISSIONS, ACTIONS.PERMISSION_NEW_ACCOUNT),
    BROWSER_SWITCH_TAB: generateOpt(EVENT_NAME.BROWSER_SWITCH_TAB),
    // Vault corruption
    VAULT_CORRUPTION_RESTORE_WALLET_SCREEN_VIEWED: generateOpt(EVENT_NAME.VAULT_CORRUPTION_RESTORE_WALLET_SCREEN_VIEWED),
    VAULT_CORRUPTION_RESTORE_WALLET_BUTTON_PRESSED: generateOpt(EVENT_NAME.VAULT_CORRUPTION_RESTORE_WALLET_BUTTON_PRESSED),
    VAULT_CORRUPTION_WALLET_SUCCESSFULLY_RESTORED_SCREEN_VIEWED: generateOpt(EVENT_NAME.VAULT_CORRUPTION_WALLET_SUCCESSFULLY_RESTORED_SCREEN_VIEWED),
    VAULT_CORRUPTION_WALLET_SUCCESSFULLY_RESTORED_CONTINUE_BUTTON_PRESSED: generateOpt(EVENT_NAME.VAULT_CORRUPTION_WALLET_SUCCESSFULLY_RESTORED_CONTINUE_BUTTON_PRESSED),
    VAULT_CORRUPTION_WALLET_RESET_NEEDED_SCREEN_VIEWED: generateOpt(EVENT_NAME.VAULT_CORRUPTION_WALLET_RESET_NEEDED_SCREEN_VIEWED),
    VAULT_CORRUPTION_WALLET_RESET_NEEDED_TRY_AGAIN_BUTTON_PRESSED: generateOpt(EVENT_NAME.VAULT_CORRUPTION_WALLET_RESET_NEEDED_TRY_AGAIN_BUTTON_PRESSED),
    VAULT_CORRUPTION_WALLET_RESET_NEEDED_CREATE_NEW_WALLET_BUTTON_PRESSED: generateOpt(EVENT_NAME.VAULT_CORRUPTION_WALLET_RESET_NEEDED_CREATE_NEW_WALLET_BUTTON_PRESSED),
    // Login screen
    LOGIN_SCREEN_VIEWED: generateOpt(EVENT_NAME.LOGIN_SCREEN_VIEWED),
    // Delete Wallet Modal
    DELETE_WALLET_MODAL_WALLET_DELETED: generateOpt(EVENT_NAME.DELETE_WALLET_MODAL_WALLET_DELETED),
    ACTIONS_BUTTON_CLICKED: generateOpt(EVENT_NAME.ACTIONS_BUTTON_CLICKED),
    RECEIVE_BUTTON_CLICKED: generateOpt(EVENT_NAME.RECEIVE_BUTTON_CLICKED),
    SWAP_BUTTON_CLICKED: generateOpt(EVENT_NAME.SWAP_BUTTON_CLICKED),
    SEND_BUTTON_CLICKED: generateOpt(EVENT_NAME.SEND_BUTTON_CLICKED),
    NETWORK_SELECTOR_PRESSED: generateOpt(EVENT_NAME.NETWORK_SELECTOR),
    // Edit account name
    ACCOUNT_RENAMED: generateOpt(EVENT_NAME.ACCOUNT_RENAMED),
    // Settings
    SETTINGS_ADVANCED_ETH_SIGN_FRICTION_FIRST_STEP_VIEWED: generateOpt(EVENT_NAME.SETTINGS_VIEWED, ACTIONS.ADVANCED_SETTINGS_ETH_SIGN_FRICTION_FIRST_STEP),
    SETTINGS_ADVANCED_ETH_SIGN_FRICTION_SECOND_STEP_VIEWED: generateOpt(EVENT_NAME.SETTINGS_VIEWED, ACTIONS.ADVANCED_SETTINGS_ETH_SIGN_FRICTION_SECOND_STEP),
    SETTINGS_ADVANCED_ETH_SIGN_ENABLED: generateOpt(EVENT_NAME.SETTINGS_UPDATED, ACTIONS.ADVANCED_SETTINGS_ETH_SIGN_ENABLED),
    SETTINGS_ADVANCED_ETH_SIGN_DISABLED: generateOpt(EVENT_NAME.SETTINGS_UPDATED, ACTIONS.ADVANCED_SETTINGS_ETH_SIGN_DISABLED),
    // Experimental Settings
    SETTINGS_SECURITY_ALERTS_ENABLED: generateOpt(EVENT_NAME.SETTINGS_UPDATED),
    // Ledger
    CONNECT_LEDGER: generateOpt(EVENT_NAME.CONNECT_LEDGER),
    CONTINUE_LEDGER_HARDWARE_WALLET: generateOpt(EVENT_NAME.CONTINUE_LEDGER_HARDWARE_WALLET),
    CONNECT_LEDGER_SUCCESS: generateOpt(EVENT_NAME.CONNECT_LEDGER_SUCCESS),
    LEDGER_HARDWARE_TRANSACTION_CANCELLED: generateOpt(EVENT_NAME.LEDGER_HARDWARE_TRANSACTION_CANCELLED),
    LEDGER_HARDWARE_WALLET_ERROR: generateOpt(EVENT_NAME.LEDGER_HARDWARE_WALLET_ERROR),
    HARDWARE_WALLET_FORGOTTEN: generateOpt(EVENT_NAME.HARDWARE_WALLET_FORGOTTEN),
    // Remove an account
    ACCOUNT_REMOVED: generateOpt(EVENT_NAME.ACCOUNT_REMOVED),
    // Smart transactions
    SMART_TRANSACTION_OPT_IN: generateOpt(EVENT_NAME.SMART_TRANSACTION_OPT_IN),
    // Notifications
    ALL_NOTIFICATIONS: generateOpt(EVENT_NAME.ALL_NOTIFICATIONS, ACTIONS.SELECTS_ALL_NOTIFICATIONS),
    WALLET_NOTIFICATIONS: generateOpt(EVENT_NAME.WALLET_NOTIFICATIONS, ACTIONS.SELECTS_WALLET_NOTIFICATIONS),
    ANNOUCEMENTS_NOTIFICATIONS: generateOpt(EVENT_NAME.ANNOUCEMENTS_NOTIFICATIONS, ACTIONS.SELECTS_ANNOUCEMENTS_NOTIFICATIONS),
    // Simulations
    INCOMPLETE_ASSET_DISPLAYED: generateOpt(EVENT_NAME.INCOMPLETE_ASSET_DISPLAYED),
    // Nft auto detection modal
    NFT_AUTO_DETECTION_MODAL_ENABLE: generateOpt(EVENT_NAME.NFT_AUTO_DETECTION_ENABLED_MODAL),
    NFT_AUTO_DETECTION_MODAL_DISABLE: generateOpt(EVENT_NAME.NFT_AUTO_DETECTION_DISBLED_MODAL),
    // Nft detection event
    NFT_AUTO_DETECTION_ENABLED: generateOpt(EVENT_NAME.NFT_AUTO_DETECTION_ENABLED),
    PRIMARY_CURRENCY_TOGGLE: generateOpt(EVENT_NAME.PRIMARY_CURRENCY_TOGGLE)
};
/**
 * Legacy Analytics Tracking Events
 */
var DESCRIPTION;
(function (DESCRIPTION) {
    //Onboarding
    DESCRIPTION["ONBOARDING_METRICS_OPT_IN"] = "Metrics Opt In";
    DESCRIPTION["ONBOARDING_METRICS_OPT_OUT"] = "Metrics Opt Out";
    DESCRIPTION["ONBOARDING_SELECTED_CREATE_NEW_WALLET"] = "Selected Create New Wallet";
    DESCRIPTION["ONBOARDING_SELECTED_CREATE_NEW_PASSWORD"] = "Selected Create New Password";
    DESCRIPTION["ONBOARDING_SELECTED_IMPORT_FROM_SEED"] = "Selected Import Wallet";
    DESCRIPTION["ONBOARDING_SELECTED_SYNC_WITH_EXTENSION"] = "Selected Sync with Extension";
    DESCRIPTION["ONBOARDING_SELECTED_WITH_SEEDPHRASE"] = "Selected Import with Seedphrase";
    DESCRIPTION["ONBOARDING_SELECTED_TAKE_THE_TOUR"] = "Onboarding wizard 'Take the tour'";
    DESCRIPTION["ONBOARDING_SELECTED_NO_THANKS"] = "Onboarding wizard 'No thanks'";
    DESCRIPTION["ONBOARDING_SELECTED_SKIP_TUTORIAL"] = "Onboarding wizard Skip";
    // Navigation Drawer
    DESCRIPTION["NAVIGATION_TAPS_ACCOUNT_NAME"] = "Tapped Account Name / Profile";
    DESCRIPTION["NAVIGATION_TAPS_SEND"] = "Taps on 'Send'";
    DESCRIPTION["NAVIGATION_TAPS_RECEIVE"] = "Taps on 'Receive'";
    DESCRIPTION["NAVIGATION_TAPS_BROWSER"] = "Taps Browser";
    DESCRIPTION["NAVIGATION_TAPS_WALLET"] = "Taps Wallet";
    DESCRIPTION["NAVIGATION_TAPS_TRANSACTION_HISTORY"] = "Transaction History";
    DESCRIPTION["NAVIGATION_TAPS_SHARE_PUBLIC_ADDRESS"] = "Share my Public address";
    DESCRIPTION["NAVIGATION_TAPS_VIEW_ETHERSCAN"] = "View on Etherscan";
    DESCRIPTION["NAVIGATION_TAPS_GET_HELP"] = "Get Help";
    DESCRIPTION["NAVIGATION_TAPS_SEND_FEEDBACK"] = "Send Feedback";
    DESCRIPTION["NAVIGATION_TAPS_SETTINGS"] = "Settings";
    DESCRIPTION["NAVIGATION_TAPS_LOGOUT"] = "Logout";
    // Common Navigation
    DESCRIPTION["COMMON_TAPS_HAMBURGER_MENU"] = "Hamburger menu Tapped";
    DESCRIPTION["COMMON_SWIPED_TO_OPEN_NAVIGATION"] = "Swiped to open Navigation";
    DESCRIPTION["COMMON_TAPS_ACCOUNT_PROFILE"] = "Tapped Account Profiile";
    DESCRIPTION["COMMON_SWITCHED_NETWORKS"] = "Switched Networks";
    // Browser
    DESCRIPTION["BROWSER_SEARCH"] = "Search";
    DESCRIPTION["BROWSER_FAVORITES"] = "My Favorites";
    DESCRIPTION["BROWSER_FEATURED_APPS"] = "Featured Apps";
    DESCRIPTION["BROWSER_FEATURED_APPS_OPEN"] = "Featured Apps - Open App";
    // Dapp
    DESCRIPTION["DAPP_BROWSER_OPTIONS"] = "More Browser Options";
    DESCRIPTION["DAPP_HOME"] = "Home";
    DESCRIPTION["DAPP_ADD_TO_FAVORITE"] = "Add to Favorites";
    DESCRIPTION["DAPP_OPEN_IN_BROWSER"] = "Open in Browser";
    // Wallet
    DESCRIPTION["WALLET_TOKENS"] = "Tokens";
    DESCRIPTION["WALLET_COLLECTIBLES"] = "Collectibles";
    DESCRIPTION["WALLET_QR_SCANNER"] = "QR scanner";
    DESCRIPTION["WALLET_COPIED_ADDRESS"] = "Copied Address";
    DESCRIPTION["WALLET_ADD_COLLECTIBLES"] = "Add Collectibles";
    // Transactions
    DESCRIPTION["TRANSACTIONS_CONFIRM_STARTED"] = "Confirm Started";
    DESCRIPTION["TRANSACTIONS_EDIT_TRANSACTION"] = "Edit Transaction";
    DESCRIPTION["TRANSACTIONS_EDIT_GAS"] = "Edit Gas";
    DESCRIPTION["TRANSACTIONS_CANCEL_TRANSACTION"] = "Cancel";
    DESCRIPTION["TRANSACTIONS_COMPLETED_TRANSACTION"] = "Transaction Completed";
    DESCRIPTION["TRANSACTIONS_CONFIRM_SIGNATURE"] = "Confirm";
    DESCRIPTION["TRANSACTIONS_CANCEL_SIGNATURE"] = "Cancel";
    // Accounts
    DESCRIPTION["ACCOUNTS_SWITCHED_ACCOUNTS"] = "Switched Accounts";
    DESCRIPTION["ACCOUNTS_ADDED_NEW_ACCOUNT"] = "Added New Account";
    DESCRIPTION["ACCOUNTS_IMPORTED_NEW_ACCOUNT"] = "Imported New Account";
    // Authentication
    DESCRIPTION["AUTHENTICATION_INCORRECT_PASSWORD"] = "Incorrect Password";
    DESCRIPTION["AUTHENTICATION_CONNECT"] = "Popup Opened";
    DESCRIPTION["AUTHENTICATION_CONNECT_CONFIRMED"] = "Confirmed";
    DESCRIPTION["AUTHENTICATION_CONNECT_CANCELED"] = "Canceled";
    // Settings
    DESCRIPTION["SETTINGS_GENERAL"] = "General";
    DESCRIPTION["SETTINGS_ADVANCED"] = "Advanced";
    DESCRIPTION["SETTINGS_NOTIFICATIONS"] = "Notifications";
    DESCRIPTION["SETTINGS_SECURITY_AND_PRIVACY"] = "Security & Privacy";
    DESCRIPTION["SETTINGS_ABOUT"] = "About MetaMask";
    DESCRIPTION["SETTINGS_EXPERIMENTAL"] = "Experimental";
    // Receive Options
    DESCRIPTION["RECEIVE_OPTIONS_SHARE_ADDRESS"] = "Share address";
    DESCRIPTION["RECEIVE_OPTIONS_QR_CODE"] = "QR Code";
    DESCRIPTION["RECEIVE_OPTIONS_PAYMENT_REQUEST"] = "Payment Request";
    DESCRIPTION["RECEIVE_OPTIONS_BUY"] = "Buy";
    // Send Flow
    DESCRIPTION["SEND_FLOW_ADDS_RECIPIENT"] = "Adds recipient address 'Send to'";
    DESCRIPTION["SEND_FLOW_ADDS_AMOUNT"] = "Adds Amount";
    DESCRIPTION["SEND_FLOW_CONFIRM_SEND"] = "Confirm Send";
    DESCRIPTION["SEND_FLOW_ADJUSTS_TRANSACTION_FEE"] = "Adjusts transaction fee";
    DESCRIPTION["SEND_FLOW_SELECT_DUPLICATE_ADDRESS"] = "Select duplicate address";
    DESCRIPTION["SEND_FLOW_CANCEL"] = "Cancel";
    // Dapp Interactions
    DESCRIPTION["DAPP_APPROVE_SCREEN_APPROVE"] = "Approve";
    DESCRIPTION["DAPP_APPROVE_SCREEN_CANCEL"] = "Cancel";
    DESCRIPTION["DAPP_APPROVE_SCREEN_EDIT_FEE"] = "Edit tx fee";
    DESCRIPTION["DAPP_APPROVE_SCREEN_VIEW_DETAILS"] = "View tx details";
    DESCRIPTION["PAYMENTS_SELECTS_DEBIT_OR_ACH"] = "Selects debit card or bank account as payment method";
    DESCRIPTION["PAYMENTS_SELECTS_APPLE_PAY"] = "Selects Apple Pay as payment method";
    DESCRIPTION["SWAPS"] = "Swaps";
    DESCRIPTION["BRIDGE"] = "Bridge";
    DESCRIPTION["STAKE"] = "Stake";
    DESCRIPTION["NOTIFICATIONS"] = "Notifications";
})(DESCRIPTION || (DESCRIPTION = {}));
var legacyMetaMetricsEvents = {
    //Onboarding
    ONBOARDING_METRICS_OPT_IN: generateOpt(EVENT_NAME.ONBOARDING, ACTIONS.METRICS_OPTS, DESCRIPTION.ONBOARDING_METRICS_OPT_IN),
    ONBOARDING_METRICS_OPT_OUT: generateOpt(EVENT_NAME.ONBOARDING, ACTIONS.METRICS_OPTS, DESCRIPTION.ONBOARDING_METRICS_OPT_OUT),
    ONBOARDING_SELECTED_CREATE_NEW_WALLET: generateOpt(EVENT_NAME.ONBOARDING, ACTIONS.IMPORT_OR_CREATE, DESCRIPTION.ONBOARDING_SELECTED_CREATE_NEW_WALLET),
    ONBOARDING_SELECTED_CREATE_NEW_PASSWORD: generateOpt(EVENT_NAME.ONBOARDING, ACTIONS.IMPORT_OR_CREATE, DESCRIPTION.ONBOARDING_SELECTED_CREATE_NEW_PASSWORD),
    ONBOARDING_SELECTED_IMPORT_FROM_SEED: generateOpt(EVENT_NAME.ONBOARDING, ACTIONS.IMPORT_OR_CREATE, DESCRIPTION.ONBOARDING_SELECTED_IMPORT_FROM_SEED),
    ONBOARDING_SELECTED_IMPORT_WITH_SEEDPHRASE: generateOpt(EVENT_NAME.ONBOARDING, ACTIONS.IMPORT_OR_SYNC, DESCRIPTION.ONBOARDING_SELECTED_WITH_SEEDPHRASE),
    ONBOARDING_SELECTED_SYNC_WITH_EXTENSION: generateOpt(EVENT_NAME.ONBOARDING, ACTIONS.IMPORT_OR_SYNC, DESCRIPTION.ONBOARDING_SELECTED_SYNC_WITH_EXTENSION),
    ONBOARDING_SELECTED_TAKE_THE_TOUR: generateOpt(EVENT_NAME.ONBOARDING, ACTIONS.ONBOARDING_NEXT, DESCRIPTION.ONBOARDING_SELECTED_TAKE_THE_TOUR),
    ONBOARDING_SELECTED_NO_THANKS: generateOpt(EVENT_NAME.ONBOARDING, ACTIONS.ONBOARDING_NEXT, DESCRIPTION.ONBOARDING_SELECTED_NO_THANKS),
    ONBOARDING_SELECTED_SKIP_TUTORIAL: generateOpt(EVENT_NAME.ONBOARDING, ACTIONS.ONBOARDING_NEXT, DESCRIPTION.ONBOARDING_SELECTED_SKIP_TUTORIAL),
    // Navigation Drawer
    NAVIGATION_TAPS_ACCOUNT_NAME: generateOpt(EVENT_NAME.NAVIGATION_DRAWER, ACTIONS.NAVIGATION_DRAWER, DESCRIPTION.NAVIGATION_TAPS_ACCOUNT_NAME),
    NAVIGATION_TAPS_SEND: generateOpt(EVENT_NAME.NAVIGATION_DRAWER, ACTIONS.NAVIGATION_DRAWER, DESCRIPTION.NAVIGATION_TAPS_SEND),
    NAVIGATION_TAPS_RECEIVE: generateOpt(EVENT_NAME.NAVIGATION_DRAWER, ACTIONS.NAVIGATION_DRAWER, DESCRIPTION.NAVIGATION_TAPS_RECEIVE),
    NAVIGATION_TAPS_BROWSER: generateOpt(EVENT_NAME.NAVIGATION_DRAWER, ACTIONS.NAVIGATION_DRAWER, DESCRIPTION.NAVIGATION_TAPS_BROWSER),
    NAVIGATION_TAPS_WALLET: generateOpt(EVENT_NAME.NAVIGATION_DRAWER, ACTIONS.NAVIGATION_DRAWER, DESCRIPTION.NAVIGATION_TAPS_WALLET),
    NAVIGATION_TAPS_TRANSACTION_HISTORY: generateOpt(EVENT_NAME.NAVIGATION_DRAWER, ACTIONS.NAVIGATION_DRAWER, DESCRIPTION.NAVIGATION_TAPS_TRANSACTION_HISTORY),
    NAVIGATION_TAPS_SHARE_PUBLIC_ADDRESS: generateOpt(EVENT_NAME.NAVIGATION_DRAWER, ACTIONS.NAVIGATION_DRAWER, DESCRIPTION.NAVIGATION_TAPS_SHARE_PUBLIC_ADDRESS),
    NAVIGATION_TAPS_VIEW_ETHERSCAN: generateOpt(EVENT_NAME.NAVIGATION_DRAWER, ACTIONS.NAVIGATION_DRAWER, DESCRIPTION.NAVIGATION_TAPS_VIEW_ETHERSCAN),
    NAVIGATION_TAPS_GET_HELP: generateOpt(EVENT_NAME.NAVIGATION_DRAWER, ACTIONS.NAVIGATION_DRAWER, DESCRIPTION.NAVIGATION_TAPS_GET_HELP),
    NAVIGATION_TAPS_SEND_FEEDBACK: generateOpt(EVENT_NAME.NAVIGATION_DRAWER, ACTIONS.NAVIGATION_DRAWER, DESCRIPTION.NAVIGATION_TAPS_SEND_FEEDBACK),
    NAVIGATION_TAPS_SETTINGS: generateOpt(EVENT_NAME.NAVIGATION_DRAWER, ACTIONS.NAVIGATION_DRAWER, DESCRIPTION.NAVIGATION_TAPS_SETTINGS),
    NAVIGATION_TAPS_LOGOUT: generateOpt(EVENT_NAME.NAVIGATION_DRAWER, ACTIONS.NAVIGATION_DRAWER, DESCRIPTION.NAVIGATION_TAPS_LOGOUT),
    // Common Navigation
    COMMON_TAPS_HAMBURGER_MENU: generateOpt(EVENT_NAME.COMMON_NAVIGATION, ACTIONS.COMMON_BROWSER_DAPP_WALLET, DESCRIPTION.COMMON_TAPS_HAMBURGER_MENU),
    COMMON_SWIPED_TO_OPEN_NAVIGATION: generateOpt(EVENT_NAME.COMMON_NAVIGATION, ACTIONS.COMMON_BROWSER_DAPP_WALLET, DESCRIPTION.COMMON_SWIPED_TO_OPEN_NAVIGATION),
    COMMON_TAPS_ACCOUNT_PROFILE: generateOpt(EVENT_NAME.COMMON_NAVIGATION, ACTIONS.COMMON_BROWSER_DAPP_WALLET, DESCRIPTION.COMMON_TAPS_ACCOUNT_PROFILE),
    COMMON_SWITCHED_NETWORKS: generateOpt(EVENT_NAME.COMMON_NAVIGATION, ACTIONS.COMMON_BROWSER_DAPP_WALLET, DESCRIPTION.COMMON_SWITCHED_NETWORKS),
    // Browser
    BROWSER_SEARCH: generateOpt(EVENT_NAME.BROWSER_VIEW, ACTIONS.BROWSER_VIEW, DESCRIPTION.BROWSER_SEARCH),
    BROWSER_FAVORITES: generateOpt(EVENT_NAME.BROWSER_VIEW, ACTIONS.BROWSER_VIEW, DESCRIPTION.BROWSER_FAVORITES),
    BROWSER_FEATURED_APPS: generateOpt(EVENT_NAME.BROWSER_VIEW, ACTIONS.BROWSER_VIEW, DESCRIPTION.BROWSER_FEATURED_APPS),
    BROWSER_FEATURED_APPS_OPEN: generateOpt(EVENT_NAME.BROWSER_VIEW, ACTIONS.BROWSER_VIEW, DESCRIPTION.BROWSER_FEATURED_APPS_OPEN),
    // Dapp
    DAPP_BROWSER_OPTIONS: generateOpt(EVENT_NAME.DAPP_VIEW, ACTIONS.DAPP_VIEW, DESCRIPTION.DAPP_BROWSER_OPTIONS),
    DAPP_HOME: generateOpt(EVENT_NAME.DAPP_VIEW, ACTIONS.DAPP_VIEW, DESCRIPTION.DAPP_HOME),
    DAPP_ADD_TO_FAVORITE: generateOpt(EVENT_NAME.DAPP_VIEW, ACTIONS.DAPP_VIEW, DESCRIPTION.DAPP_ADD_TO_FAVORITE),
    DAPP_OPEN_IN_BROWSER: generateOpt(EVENT_NAME.DAPP_VIEW, ACTIONS.DAPP_VIEW, DESCRIPTION.DAPP_OPEN_IN_BROWSER),
    // Wallet
    WALLET_TOKENS: generateOpt(EVENT_NAME.WALLET_VIEW, ACTIONS.WALLET_VIEW, DESCRIPTION.WALLET_TOKENS),
    WALLET_COLLECTIBLES: generateOpt(EVENT_NAME.WALLET_VIEW, ACTIONS.WALLET_VIEW, DESCRIPTION.WALLET_COLLECTIBLES),
    WALLET_QR_SCANNER: generateOpt(EVENT_NAME.WALLET_VIEW, ACTIONS.WALLET_VIEW, DESCRIPTION.WALLET_QR_SCANNER),
    WALLET_COPIED_ADDRESS: generateOpt(EVENT_NAME.WALLET_VIEW, ACTIONS.WALLET_VIEW, DESCRIPTION.WALLET_COPIED_ADDRESS),
    WALLET_ADD_COLLECTIBLES: generateOpt(EVENT_NAME.WALLET_VIEW, ACTIONS.WALLET_VIEW, DESCRIPTION.WALLET_ADD_COLLECTIBLES),
    // Transactions
    TRANSACTIONS_CONFIRM_STARTED: generateOpt(EVENT_NAME.TRANSACTIONS, ACTIONS.CONFIRM_SCREEN, DESCRIPTION.TRANSACTIONS_CONFIRM_STARTED),
    TRANSACTIONS_EDIT_TRANSACTION: generateOpt(EVENT_NAME.TRANSACTIONS, ACTIONS.CONFIRM_SCREEN, DESCRIPTION.TRANSACTIONS_EDIT_TRANSACTION),
    TRANSACTIONS_EDIT_GAS: generateOpt(EVENT_NAME.TRANSACTIONS, ACTIONS.CONFIRM_SCREEN, DESCRIPTION.TRANSACTIONS_EDIT_GAS),
    TRANSACTIONS_CANCEL_TRANSACTION: generateOpt(EVENT_NAME.TRANSACTIONS, ACTIONS.CONFIRM_SCREEN, DESCRIPTION.TRANSACTIONS_CANCEL_TRANSACTION),
    TRANSACTIONS_COMPLETED_TRANSACTION: generateOpt(EVENT_NAME.TRANSACTIONS, ACTIONS.CONFIRM_SCREEN, DESCRIPTION.TRANSACTIONS_COMPLETED_TRANSACTION),
    TRANSACTIONS_CONFIRM_SIGNATURE: generateOpt(EVENT_NAME.TRANSACTIONS, ACTIONS.SIGN_SCREEN, DESCRIPTION.TRANSACTIONS_CONFIRM_SIGNATURE),
    TRANSACTIONS_CANCEL_SIGNATURE: generateOpt(EVENT_NAME.TRANSACTIONS, ACTIONS.SIGN_SCREEN, DESCRIPTION.TRANSACTIONS_CANCEL_SIGNATURE),
    // Accounts
    ACCOUNTS_SWITCHED_ACCOUNTS: generateOpt(EVENT_NAME.ACCOUNTS, ACTIONS.ACCOUNTS_MODAL, DESCRIPTION.ACCOUNTS_SWITCHED_ACCOUNTS),
    ACCOUNTS_ADDED_NEW_ACCOUNT: generateOpt(EVENT_NAME.ACCOUNTS, ACTIONS.ACCOUNTS_MODAL, DESCRIPTION.ACCOUNTS_ADDED_NEW_ACCOUNT),
    ACCOUNTS_IMPORTED_NEW_ACCOUNT: generateOpt(EVENT_NAME.ACCOUNTS, ACTIONS.ACCOUNTS_MODAL, DESCRIPTION.ACCOUNTS_IMPORTED_NEW_ACCOUNT),
    // Authentication
    AUTHENTICATION_INCORRECT_PASSWORD: generateOpt(EVENT_NAME.AUTH, ACTIONS.UNLOCK, DESCRIPTION.AUTHENTICATION_INCORRECT_PASSWORD),
    AUTHENTICATION_CONNECT: generateOpt(EVENT_NAME.AUTH, ACTIONS.CONNECT, DESCRIPTION.AUTHENTICATION_CONNECT),
    AUTHENTICATION_CONNECT_CONFIRMED: generateOpt(EVENT_NAME.AUTH, ACTIONS.CONNECT, DESCRIPTION.AUTHENTICATION_CONNECT_CONFIRMED),
    AUTHENTICATION_CONNECT_CANCELED: generateOpt(EVENT_NAME.AUTH, ACTIONS.CONNECT, DESCRIPTION.AUTHENTICATION_CONNECT_CANCELED),
    // Settings
    SETTINGS_GENERAL: generateOpt(EVENT_NAME.SETTINGS, ACTIONS.SETTINGS, DESCRIPTION.SETTINGS_GENERAL),
    SETTINGS_ADVANCED: generateOpt(EVENT_NAME.SETTINGS, ACTIONS.SETTINGS, DESCRIPTION.SETTINGS_ADVANCED),
    SETTINGS_SECURITY_AND_PRIVACY: generateOpt(EVENT_NAME.SETTINGS, ACTIONS.SETTINGS, DESCRIPTION.SETTINGS_SECURITY_AND_PRIVACY),
    SETTINGS_ABOUT: generateOpt(EVENT_NAME.SETTINGS, ACTIONS.SETTINGS, DESCRIPTION.SETTINGS_ABOUT),
    SETTINGS_EXPERIMENTAL: generateOpt(EVENT_NAME.SETTINGS, ACTIONS.SETTINGS, DESCRIPTION.SETTINGS_EXPERIMENTAL),
    SETTINGS_NOTIFICATIONS: generateOpt(EVENT_NAME.SETTINGS, ACTIONS.SETTINGS, DESCRIPTION.SETTINGS_NOTIFICATIONS),
    // Receive Options
    RECEIVE_OPTIONS_SHARE_ADDRESS: generateOpt(EVENT_NAME.RECEIVE_OPTIONS, ACTIONS.RECEIVE_OPTIONS, DESCRIPTION.RECEIVE_OPTIONS_SHARE_ADDRESS),
    RECEIVE_OPTIONS_QR_CODE: generateOpt(EVENT_NAME.RECEIVE_OPTIONS, ACTIONS.RECEIVE_OPTIONS, DESCRIPTION.RECEIVE_OPTIONS_QR_CODE),
    RECEIVE_OPTIONS_PAYMENT_REQUEST: generateOpt(EVENT_NAME.RECEIVE_OPTIONS, ACTIONS.RECEIVE_OPTIONS, DESCRIPTION.RECEIVE_OPTIONS_PAYMENT_REQUEST),
    RECEIVE_OPTIONS_BUY: generateOpt(EVENT_NAME.RECEIVE_OPTIONS, ACTIONS.RECEIVE_OPTIONS, DESCRIPTION.RECEIVE_OPTIONS_BUY),
    // Send flow
    SEND_FLOW_ADDS_RECIPIENT: generateOpt(EVENT_NAME.SEND_FLOW, ACTIONS.SEND_FLOW, DESCRIPTION.SEND_FLOW_ADDS_RECIPIENT),
    SEND_FLOW_ADDS_AMOUNT: generateOpt(EVENT_NAME.SEND_FLOW, ACTIONS.SEND_FLOW, DESCRIPTION.SEND_FLOW_ADDS_AMOUNT),
    SEND_FLOW_CONFIRM_SEND: generateOpt(EVENT_NAME.SEND_FLOW, ACTIONS.SEND_FLOW, DESCRIPTION.SEND_FLOW_CONFIRM_SEND),
    SEND_FLOW_ADJUSTS_TRANSACTION_FEE: generateOpt(EVENT_NAME.SEND_FLOW, ACTIONS.SEND_FLOW, DESCRIPTION.SEND_FLOW_ADJUSTS_TRANSACTION_FEE),
    SEND_FLOW_CANCEL: generateOpt(EVENT_NAME.SEND_FLOW, ACTIONS.SEND_FLOW, DESCRIPTION.SEND_FLOW_CANCEL),
    SEND_FLOW_SELECT_DUPLICATE_ADDRESS: generateOpt(EVENT_NAME.SEND_FLOW, ACTIONS.SEND_FLOW, DESCRIPTION.SEND_FLOW_SELECT_DUPLICATE_ADDRESS),
    // Dapp Interactions
    DAPP_APPROVE_SCREEN_APPROVE: generateOpt(EVENT_NAME.DAPP_INTERACTIONS, ACTIONS.APPROVE_REQUEST, DESCRIPTION.DAPP_APPROVE_SCREEN_APPROVE),
    DAPP_APPROVE_SCREEN_CANCEL: generateOpt(EVENT_NAME.DAPP_INTERACTIONS, ACTIONS.APPROVE_REQUEST, DESCRIPTION.DAPP_APPROVE_SCREEN_CANCEL),
    DAPP_APPROVE_SCREEN_EDIT_FEE: generateOpt(EVENT_NAME.DAPP_INTERACTIONS, ACTIONS.APPROVE_REQUEST, DESCRIPTION.DAPP_APPROVE_SCREEN_EDIT_FEE),
    DAPP_APPROVE_SCREEN_VIEW_DETAILS: generateOpt(EVENT_NAME.DAPP_INTERACTIONS, ACTIONS.APPROVE_REQUEST, DESCRIPTION.DAPP_APPROVE_SCREEN_VIEW_DETAILS),
    PAYMENTS_SELECTS_DEBIT_OR_ACH: generateOpt(EVENT_NAME.PAYMENTS, ACTIONS.SELECTS_DEBIT_OR_ACH, DESCRIPTION.PAYMENTS_SELECTS_DEBIT_OR_ACH),
    PAYMENTS_SELECTS_APPLE_PAY: generateOpt(EVENT_NAME.PAYMENTS, ACTIONS.SELECTS_APPLE_PAY, DESCRIPTION.PAYMENTS_SELECTS_APPLE_PAY),
    // Swaps
    SWAPS_OPENED: generateOpt(EVENT_NAME.SWAPS_OPENED, ACTIONS.SWAP, DESCRIPTION.SWAPS),
    QUOTES_REQUESTED: generateOpt(EVENT_NAME.QUOTES_REQUESTED, ACTIONS.QUOTE, DESCRIPTION.SWAPS),
    QUOTES_RECEIVED: generateOpt(EVENT_NAME.QUOTES_RECEIVED, ACTIONS.QUOTE, DESCRIPTION.SWAPS),
    QUOTES_REQUEST_CANCELLED: generateOpt(EVENT_NAME.QUOTES_REQUEST_CANCELLED, ACTIONS.QUOTE, DESCRIPTION.SWAPS),
    ALL_AVAILABLE_QUOTES_OPENED: generateOpt(EVENT_NAME.ALL_AVAILABLE_QUOTES_OPENED, ACTIONS.QUOTE, DESCRIPTION.SWAPS),
    SWAP_STARTED: generateOpt(EVENT_NAME.SWAP_STARTED, ACTIONS.SWAP, DESCRIPTION.SWAPS),
    SWAP_COMPLETED: generateOpt(EVENT_NAME.SWAP_COMPLETED, ACTIONS.SWAP, DESCRIPTION.SWAPS),
    SWAP_FAILED: generateOpt(EVENT_NAME.SWAP_FAILED, ACTIONS.SWAP, DESCRIPTION.SWAPS),
    SWAP_TRACKING_FAILED: generateOpt(EVENT_NAME.SWAP_TRACKING_FAILED, ACTIONS.SWAP, DESCRIPTION.SWAPS),
    QUOTES_TIMED_OUT: generateOpt(EVENT_NAME.QUOTES_TIMED_OUT, ACTIONS.QUOTE, DESCRIPTION.SWAPS),
    NO_QUOTES_AVAILABLE: generateOpt(EVENT_NAME.NO_QUOTES_AVAILABLE, ACTIONS.QUOTE, DESCRIPTION.SWAPS),
    GAS_FEES_CHANGED: generateOpt(EVENT_NAME.GAS_FEES_CHANGED, ACTIONS.QUOTE, DESCRIPTION.SWAPS),
    EDIT_SPEND_LIMIT_OPENED: generateOpt(EVENT_NAME.EDIT_SPEND_LIMIT_OPENED, ACTIONS.QUOTE, DESCRIPTION.SWAPS),
    CUSTOM_TOKEN_IMPORTED: generateOpt(EVENT_NAME.TOKEN_IMPORTED, ACTIONS.SWAP, DESCRIPTION.SWAPS),
    BRIDGE_LINK_CLICKED: generateOpt(EVENT_NAME.BRIDGE_LINK_CLICKED, ACTIONS.BRIDGE, DESCRIPTION.BRIDGE),
    STAKE_BUTTON_CLICKED: generateOpt(EVENT_NAME.STAKE_BUTTON_CLICKED, ACTIONS.STAKE, DESCRIPTION.STAKE)
};
var MetaMetricsEvents = __assign(__assign({}, events), legacyMetaMetricsEvents);
exports.MetaMetricsEvents = MetaMetricsEvents;
