import {
  EARN_MODULE_REDIRECT_TARGETS,
  EARN_MODULE_REDIRECT_TARGET_TYPES,
} from '../constants/earnModuleEvents';
import Logger from '../../../../util/Logger';

const SCREEN_TARGETS = new Set<string>([
  EARN_MODULE_REDIRECT_TARGETS.EARN_SECTION_LIST_VIEW,
  EARN_MODULE_REDIRECT_TARGETS.EARN_SEARCH_LIST,
  EARN_MODULE_REDIRECT_TARGETS.TOKEN_DETAILS,
  EARN_MODULE_REDIRECT_TARGETS.POOLED_STAKING_DEPOSIT,
  EARN_MODULE_REDIRECT_TARGETS.STABLECOIN_LENDING_DEPOSIT,
  EARN_MODULE_REDIRECT_TARGETS.TRX_STAKING_DEPOSIT,
  EARN_MODULE_REDIRECT_TARGETS.MONEY_HOME,
  EARN_MODULE_REDIRECT_TARGETS.MONEY_ONBOARDING,
  EARN_MODULE_REDIRECT_TARGETS.MONEY_DEPOSIT,
]);

const BOTTOM_SHEET_TARGET = new Set<string>([
  EARN_MODULE_REDIRECT_TARGETS.STRATEGY_SELECTION_BOTTOM_SHEET,
]);

export const resolveEarnModuleRedirectTargetType = (
  target: EARN_MODULE_REDIRECT_TARGETS,
): EARN_MODULE_REDIRECT_TARGET_TYPES | undefined => {
  if (SCREEN_TARGETS.has(target)) {
    return EARN_MODULE_REDIRECT_TARGET_TYPES.SCREEN;
  }

  if (BOTTOM_SHEET_TARGET.has(target)) {
    return EARN_MODULE_REDIRECT_TARGET_TYPES.BOTTOM_SHEET;
  }

  Logger.error(
    new Error(`[earnModuleAnalytics] Unknown redirect target: ${target}`),
  );
};
