export const PredictOrderFlowTestIds = {
  SHEET: 'predict-order-flow-sheet',
  OUTCOME_LABEL: 'predict-order-flow-outcome-label',
  TO_WIN: 'predict-order-flow-to-win',
  AMOUNT_INPUT: 'predict-order-flow-amount-input',
  KEYPAD: 'predict-order-flow-keypad',
  KEYPAD_KEY: (key: string) => `predict-order-flow-keypad-key-${key}`,
  QUICK_AMOUNT: (amount: string) => `predict-order-flow-quick-${amount}`,
  QUOTE: 'predict-order-flow-quote',
  ESTIMATED_CONTRACTS: 'predict-order-flow-estimated-contracts',
  AVERAGE_PRICE: 'predict-order-flow-average-price',
  POTENTIAL_PAYOUT: 'predict-order-flow-potential-payout',
  POTENTIAL_PROFIT: 'predict-order-flow-potential-profit',
  FEE: 'predict-order-flow-fee',
  FEE_COMPONENT: (source: string) => `predict-order-flow-fee-${source}`,
  TOTAL_DEBIT: 'predict-order-flow-total-debit',
  PAY_WITH: 'predict-order-flow-pay-with',
  TOTAL: 'predict-order-flow-total',
  TOTAL_INFO: 'predict-order-flow-total-info',
  BREAKDOWN: 'predict-order-flow-breakdown',
  EXPIRED: 'predict-order-flow-expired',
  REFRESH: 'predict-order-flow-refresh',
  ERROR: 'predict-order-flow-error',
  REVIEW: 'predict-order-flow-review',
  APPROVAL: 'predict-order-flow-approval',
  EXPIRY: 'predict-order-flow-expiry',
  APPROVE: 'predict-order-flow-approve',
  BACK: 'predict-order-flow-back',
  SUBMITTING: 'predict-order-flow-submitting',
  RECEIPT: 'predict-order-flow-receipt',
  RECEIPT_FILLED: 'predict-order-flow-receipt-filled',
  RECEIPT_PARTIALLY_FILLED: 'predict-order-flow-receipt-partially-filled',
  RECEIPT_NOT_FILLED: 'predict-order-flow-receipt-not-filled',
  RECEIPT_REJECTED: 'predict-order-flow-receipt-rejected',
  RECEIPT_RECONCILING: 'predict-order-flow-receipt-reconciling',
  FILLED_CONTRACTS: 'predict-order-flow-filled-contracts',
  ACTUAL_SPEND: 'predict-order-flow-actual-spend',
  AVERAGE_FILL_PRICE: 'predict-order-flow-average-fill-price',
  PAYOUT_EXPOSURE: 'predict-order-flow-payout-exposure',
  POSITION_CONTEXT: 'predict-order-flow-position-context',
  REMAINDER: 'predict-order-flow-canceled-remainder',
  KEEP_CHECKING: 'predict-order-flow-keep-checking',
  REQUOTE: 'predict-order-flow-requote',
  DONE: 'predict-order-flow-done',
} as const;
