export const PredictOrderFlowTestIds = {
  SHEET: 'predict-order-flow-sheet',
  AMOUNT_INPUT: 'predict-order-flow-amount-input',
  QUICK_AMOUNT: (amount: string) => `predict-order-flow-quick-${amount}`,
  QUOTE: 'predict-order-flow-quote',
  ESTIMATED_CONTRACTS: 'predict-order-flow-estimated-contracts',
  AVERAGE_PRICE: 'predict-order-flow-average-price',
  POTENTIAL_PAYOUT: 'predict-order-flow-potential-payout',
  POTENTIAL_PROFIT: 'predict-order-flow-potential-profit',
  FEE: 'predict-order-flow-fee',
  FEE_COMPONENT: (label: string) => `predict-order-flow-fee-${label}`,
  TOTAL_DEBIT: 'predict-order-flow-total-debit',
  EXPIRED: 'predict-order-flow-expired',
  REFRESH: 'predict-order-flow-refresh',
  ERROR: 'predict-order-flow-error',
  RETRY: 'predict-order-flow-retry',
  APPROVE: 'predict-order-flow-approve',
  SUBMITTING: 'predict-order-flow-submitting',
  SUCCESS: 'predict-order-flow-success',
  DONE: 'predict-order-flow-done',
} as const;
