export const PredictOrderFlowTestIds = {
  SHEET: 'predict-order-flow-sheet',
  OUTCOME_LABEL: 'predict-order-flow-outcome-label',
  TO_WIN: 'predict-order-flow-to-win',
  AMOUNT_INPUT: 'predict-order-flow-amount-input',
  KEYPAD: 'predict-order-flow-keypad',
  KEYPAD_KEY: (key: string) => `predict-order-flow-keypad-key-${key}`,
  QUICK_AMOUNT: (amount: string) => `predict-order-flow-quick-${amount}`,
  QUOTE: 'predict-order-flow-quote',
  ESTIMATED_CONTRACTS: 'predict-order-flow-estimated-contracts',
  AVERAGE_PRICE: 'predict-order-flow-average-price',
  POTENTIAL_PAYOUT: 'predict-order-flow-potential-payout',
  POTENTIAL_PROFIT: 'predict-order-flow-potential-profit',
  FEE: 'predict-order-flow-fee',
  FEE_COMPONENT: (source: string) => `predict-order-flow-fee-${source}`,
  TOTAL_DEBIT: 'predict-order-flow-total-debit',
  PAY_WITH: 'predict-order-flow-pay-with',
  TOTAL: 'predict-order-flow-total',
  TOTAL_INFO: 'predict-order-flow-total-info',
  BREAKDOWN: 'predict-order-flow-breakdown',
  EXPIRED: 'predict-order-flow-expired',
  REFRESH: 'predict-order-flow-refresh',
  ERROR: 'predict-order-flow-error',
  APPROVE: 'predict-order-flow-approve',
  SUBMITTING: 'predict-order-flow-submitting',
  SUCCESS: 'predict-order-flow-success',
  DONE: 'predict-order-flow-done',
} as const;
