export const ProHubTestIds = {
  CONTAINER: 'pro-hub-container',
  BACK_BUTTON: 'pro-hub-back-button',
  HEADER_ROOT: 'pro-hub-header-root',
  MANAGE_PLANS_BUTTON: 'pro-hub-manage-plans-button',
  MEMBERSHIP_BANNER: 'pro-hub-membership-banner',
  MEMBERSHIP_STATUS_LABEL: 'pro-hub-membership-status-label',
  MEMBERSHIP_STATUS_ICON: 'pro-hub-membership-status-icon',
  MEMBERSHIP_ALERT_BANNER: 'pro-hub-membership-alert-banner',
  MEMBERSHIP_ALERT_ACTION: 'pro-hub-membership-alert-action',
  PAYMENT_FAILURE_SHEET: 'pro-hub-payment-failure-sheet',
  PAYMENT_FAILURE_TITLE: 'pro-hub-payment-failure-title',
  PAYMENT_FAILURE_DESCRIPTION: 'pro-hub-payment-failure-description',
  PAYMENT_FAILURE_TRY_AGAIN: 'pro-hub-payment-failure-try-again',
  PAYMENT_FAILURE_CLOSE: 'pro-hub-payment-failure-close',
  LIFETIME_EARNINGS_SECTION: 'pro-hub-lifetime-earnings-section',
  MONEY_BALANCE_ROW: 'pro-hub-money-balance-row',
  MUSD_BACK_ROW: 'pro-hub-musd-back-row',
  PHYSICAL_CARD_BANNER: 'pro-hub-physical-card-banner',
  PHYSICAL_CARD_TITLE: 'pro-hub-physical-card-title',
  PHYSICAL_CARD_DESCRIPTION: 'pro-hub-physical-card-description',
  GET_CARD_BUTTON: 'pro-hub-get-card-button',
  ALSO_INCLUDED_SECTION: 'pro-hub-also-included-section',
  ALSO_INCLUDED_ROW: (id: string) => `pro-hub-also-included-row-${id}`,
  MEMBERSHIP_SECTION: 'pro-hub-membership-section',
  NEXT_PAYMENT_TEXT: 'pro-hub-next-payment-text',
  MANAGE_BUTTON: 'pro-hub-manage-button',
  DISCLAIMER_TEXT: 'pro-hub-disclaimer-text',
} as const;
