export const ProHubTestIds = {
  CONTAINER: 'pro-hub-container',
  BACK_BUTTON: 'pro-hub-back-button',
  TITLE: 'pro-hub-title',
  HEADER_ROOT: 'pro-hub-header-root',
  MANAGE_PLANS_BUTTON: 'pro-hub-manage-plans-button',
  EARNED_CARD: 'pro-hub-earned-card',
  SAVED_CARD: 'pro-hub-saved-card',
  CARD_PLACEHOLDER: 'pro-hub-card-placeholder',
  PHYSICAL_CARD_TITLE: 'pro-hub-physical-card-title',
  PHYSICAL_CARD_DESCRIPTION: 'pro-hub-physical-card-description',
  GET_CARD_BUTTON: 'pro-hub-get-card-button',
  BENEFITS_SECTION: 'pro-hub-benefits-section',
  ALSO_INCLUDED_SECTION: 'pro-hub-also-included-section',
  ALSO_INCLUDED_ROW: (id: string) => `pro-hub-also-included-row-${id}`,
  MANAGE_BUTTON: 'pro-hub-manage-button',
  DISCLAIMER_TEXT: 'pro-hub-disclaimer-text',
} as const;
