export const ProHubTestIds = {
  CONTAINER: 'pro-hub-container',
  BACK_BUTTON: 'pro-hub-back-button',
  HEADER_ROOT: 'pro-hub-header-root',
  MANAGE_PLANS_BUTTON: 'pro-hub-manage-plans-button',
  MEMBERSHIP_BANNER: 'pro-hub-membership-banner',
  LIFETIME_EARNINGS_SECTION: 'pro-hub-lifetime-earnings-section',
  MONEY_BALANCE_ROW: 'pro-hub-money-balance-row',
  MUSD_BACK_ROW: 'pro-hub-musd-back-row',
  PHYSICAL_CARD_BANNER: 'pro-hub-physical-card-banner',
  PHYSICAL_CARD_TITLE: 'pro-hub-physical-card-title',
  PHYSICAL_CARD_DESCRIPTION: 'pro-hub-physical-card-description',
  BENEFITS_SECTION: 'pro-hub-benefits-section',
  MEMBERSHIP_SECTION: 'pro-hub-membership-section',
  NEXT_PAYMENT_TEXT: 'pro-hub-next-payment-text',
  MANAGE_BUTTON: 'pro-hub-manage-button',
} as const;
