/**
 * Thin-seam E2E mock for `react-native-vision-camera`.
 *
 * Active ONLY when the Metro resolver swap in `metro.config.js` is enabled via
 * the env var `QR_E2E_THIN_SEAM=true` (see the `isQrThinSeam` branch there).
 * When active, Metro resolves every `react-native-vision-camera` import to
 * THIS module instead of the real native library.
 *
 * Purpose: bypass the physical camera + ML Kit barcode pipeline for QR
 * hardware-wallet E2E tests. The real Android emulator camera HAL cannot
 * decode QR codes from injected images (anti-aliasing destroys module
 * edges — see `e2e/speculos/docs/qr-e2e-status.md` §3.11). This mock keeps
 * the REAL app code paths intact (URRegistryDecoder.receivePart, scanner UI,
 * Camera mount gating) and only replaces the leaf `onCodeScanned` data
 * source: it auto-replays a deterministic, pre-baked BC-UR `crypto-account`
 * fountain fragment sequence (4 fragments) into the consumer's
 * `onCodeScanned` callback, exactly as a real animated QR scanner would.
 *
 * This is NOT a Jest mock — it ships in the RN bundle and runs on-device.
 * The Jest path uses `app/__mocks__/react-native-vision-camera.ts` (untouched).
 *
 * Fixture source: `tests/fixtures/qr/account-ur-fragments.json` (generated by
 * `scripts/qr-emulator/generate-account-ur-fixture.js`).
 */

import React, { useEffect, useRef } from 'react';
import { View } from 'react-native';
import { CAMERA_PERMISSION_STATUS } from '../../../app/constants/permissions';
import qrFixture from '../../fixtures/qr/account-ur-fragments.json';

/**
 * Minimal shape of a scanned code object that the real vision-camera emits.
 * Consumers (`AnimatedQRScanner.onBarCodeRead`) read `codes[0].value`.
 */
export type Code = {
  value?: string;
  type?: string | number;
  [key: string]: unknown;
};

type OnCodeScanned = (codes: Code[]) => void | Promise<void>;

type CodeScanner = {
  codeTypes?: string[];
  onCodeScanned?: OnCodeScanned;
};

type CodeScannerConfig = {
  codeTypes?: string[];
  onCodeScanned?: OnCodeScanned;
};

type CameraProps = {
  device?: unknown;
  isActive?: boolean;
  codeScanner?: CodeScanner;
  torch?: string;
  onError?: (error: Error) => void;
  style?: unknown;
  [key: string]: unknown;
};

/**
 * Mock camera device — mirrors `mockDevice` in `app/__mocks__/react-native-vision-camera.ts`
 * so the scanner's `cameraDevice && hasPermission` gate passes.
 */
const mockDevice = {
  id: 'back',
  position: 'back',
  hasFlash: true,
  hasTorch: true,
  isMultiCam: false,
  minFocusDistance: 10,
  supportsFocus: true,
  supportsRawCapture: false,
  supportsLowLightBoost: false,
  name: 'Mock Camera',
  neutralZoom: 1,
  minZoom: 1,
  maxZoom: 10,
  formats: [],
  hardwareLevel: 'limited' as const,
  sensorOrientation: 90,
};

const mockPermission = {
  hasPermission: true,
  requestPermission: (() =>
    Promise.resolve(
      CAMERA_PERMISSION_STATUS.granted,
    )) as () => Promise<string>,
};

/**
 * Ignores the selector arg (real API: `useCameraDevice('back' | 'front')`).
 * Always returns the mock back camera so the scanner renders.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const useCameraDevice = (_selector?: unknown): typeof mockDevice =>
  mockDevice;

export const useCameraPermission = (): typeof mockPermission => mockPermission;

/**
 * Mirrors the real hook's return shape. The `onCodeScanned` callback is what
 * `AnimatedQRScanner` passes in — the Camera component (below) captures it
 * via `props.codeScanner.onCodeScanned` and replays fragments into it.
 */
export const useCodeScanner = (
  config: CodeScannerConfig,
): { codeTypes: string[]; onCodeScanned: OnCodeScanned } => ({
  codeTypes: ['qr'],
  onCodeScanned: config?.onCodeScanned ?? (() => undefined),
});

/**
 * Camera component — renders a plain View (so the scanner branch renders and
 * Detox can see `testID`) and auto-replays the 4 BC-UR account-UR fragments
 * into `props.codeScanner.onCodeScanned` on a timer loop.
 *
 * The replay loop:
 *   - Fires only when `isActive` is true and an `onCodeScanned` callback exists.
 *   - 500ms initial delay (let scanner UI/state settle).
 *   - Then one fire every `qrFixture.refreshMs` (200ms).
 *   - Cycles through all fragments; capped at `fragments.length * 6` fires
 *     (≈6 full fountain cycles) so the loop terminates even if the scanner
 *     never unmounts (prevents timer leaks). Real animated QR loops forever;
 *     the cap is a safety bound — the app's URRegistryDecoder reaches
 *     `isSuccess()` after receiving all 4 fragments, long before the cap.
 *   - Each fire is wrapped in try/catch so a thrown consumer callback does
 *     not silently kill the replay loop.
 *   - All timers are tracked and cleared on unmount or when isActive flips.
 *
 * Ref-based callback: the latest `onCodeScanned` is read from a ref on each
 * fire rather than captured at effect-setup time. This is necessary because
 * the consumer (`AnimatedQRScanner`) calls `setProgress()` after each
 * fragment, causing a re-render; `useCodeScanner` returns a fresh object each
 * render, so keying the effect on `props.codeScanner` would reset the 500ms
 * timer after every fragment and the sequence would never complete. The
 * effect therefore keys only on the stable `isActive` boolean.
 */
const Camera = React.forwardRef((props: CameraProps, _ref: unknown) => {
  // Track the latest onCodeScanned so the timer always invokes the freshest
  // closure without restarting the replay loop on consumer re-renders.
  const fireRef = useRef<OnCodeScanned | undefined>(
    props.codeScanner?.onCodeScanned,
  );
  fireRef.current = props.codeScanner?.onCodeScanned;

  useEffect(() => {
    if (!props.isActive) {
      return;
    }
    const fragments = qrFixture.fragments;
    if (!fragments || fragments.length === 0) {
      return;
    }

    const timers: ReturnType<typeof setTimeout>[] = [];
    let i = 0;
    const maxFires = fragments.length * 6;
    let cancelled = false;

    const scheduleNext = (delay: number): void => {
      const timer = setTimeout(() => {
        if (cancelled || i >= maxFires) {
          return;
        }
        const fire = fireRef.current;
        if (fire) {
          try {
            fire([{ value: fragments[i % fragments.length], type: 'qr' }]);
          } catch (err) {
            // A thrown consumer callback must not kill the replay loop.
            // eslint-disable-next-line no-console
            console.warn(
              '[qr-thin-seam] onCodeScanned callback threw — continuing replay',
              err,
            );
          }
        }
        i += 1;
        scheduleNext(qrFixture.refreshMs);
      }, delay);
      timers.push(timer);
    };

    // Initial delay lets the scanner UI / decoder state settle before the
    // first synthetic barcode arrives.
    scheduleNext(500);

    return () => {
      cancelled = true;
      for (const t of timers) {
        clearTimeout(t);
      }
    };
  }, [props.isActive]);

  return React.createElement(View, { testID: 'qr-thin-seam-camera' });
});

Camera.displayName = 'QrThinSeamCamera';

// Static methods that some app consumers call directly on the Camera class
// (e.g. `Camera.getCameraPermissionStatus()`). Object.assign mutates the
// forwardRef component in place to attach them.
Object.assign(Camera, {
  getCameraPermissionStatus: () => CAMERA_PERMISSION_STATUS.granted,
  requestCameraPermission: async () => CAMERA_PERMISSION_STATUS.granted,
});

export { Camera };
