# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
	def bump_build_version
		increment_build_number
	end

	desc "Submit a new Beta Build to Beta"
	lane :beta do
		bump_build_version
		match(type: "development")
		gym(
			clean: true,
			scheme: "MetaMask",
			configuration: "Release",
			output_name: "MetaMask"
		)
		crashlytics(
			api_token: ‘472e253bee9272qqw5e13be160d1b2f91d6746155’,
			build_secret: ‘294d0d67fb6qwweafa7342f3d1ebfc86f040970a29934690607b10c0d7fa55076’
		)
	end
end
