export const SocialFeedPostShellSelectorsIDs = {
  CONTAINER: 'social-v1-feed-post',
  AVATAR: 'social-v1-feed-post-avatar',
  GIF: 'social-v1-feed-post-gif',
  REACTIONS: 'social-v1-feed-post-reactions',
  COPIES: 'social-v1-feed-post-copies',
  TOTAL: 'social-v1-feed-post-reaction-total',
  CHIP: 'social-v1-feed-post-reaction-chip',
  VERIFIED_BADGE: 'social-v1-feed-post-verified',
  COHORT: 'social-v1-feed-post-cohort',
  TRADER_STAT: 'social-v1-feed-post-trader-stat',
  MORE: 'social-v1-feed-post-more',
  TIMESTAMP: 'social-v1-feed-post-timestamp',
  IDENTITY_PRESS: 'social-v1-feed-post-trader',
} as const;
