export const RecurringConfirmOrderSheetSelectorsIDs = {
  SHEET: 'recurring-confirm-order-sheet',
  CLOSE_BUTTON: 'recurring-confirm-order-sheet-close',
  CONFIRM_BUTTON: 'recurring-confirm-order-sheet-confirm',
  PAYING_ALL_ORDERS: 'recurring-confirm-paying-all-orders',
  PAYING_PER_ORDER: 'recurring-confirm-paying-per-order',
  RECEIVING: 'recurring-confirm-receiving',
  EST_RECEIVING_PER_ORDER: 'recurring-confirm-est-receiving-per-order',
  EST_RECEIVING_ALL_ORDERS: 'recurring-confirm-est-receiving-all-orders',
  EXPIRES_AFTER: 'recurring-confirm-expires-after',
  SLIPPAGE: 'recurring-confirm-slippage',
  SLIPPAGE_EDIT: 'recurring-confirm-slippage-edit',
  NETWORK_FEE: 'recurring-confirm-network-fee',
  FEE_DISCLAIMER: 'recurring-confirm-fee-disclaimer',
} as const;
