export const BridgeViewSelectorsIDs = {
  SOURCE_TOKEN_AREA: 'source-token-area',
  DESTINATION_TOKEN_AREA: 'dest-token-area',
  SOURCE_TOKEN_INPUT: 'source-token-area-input',
  SOURCE_AMOUNT_TYPE_TOGGLE: 'source-token-area-amount-type-toggle',
  DESTINATION_TOKEN_INPUT: 'dest-token-area-input',
  SLIPPAGE_SETTINGS_BUTTON: 'bridge-slippage-settings-button',
  CONFIRM_BUTTON: 'bridge-confirm-button',
  CONFIRM_BUTTON_KEYPAD: 'bridge-confirm-button-keypad',
  BRIDGE_VIEW_SCROLL: 'bridge-view-scroll',
  FEE_DISCLAIMER: 'bridge-fee-disclaimer',
  QUOTE_DETAILS_SKELETON: 'bridge-quote-details-skeleton',
  MISSING_PRICE_BANNER: 'bridge-missing-price-banner',
  NO_QUOTES_BANNER: 'bridge-no-quotes',
  TABS_BAR: 'bridge-tabs-bar',
  TABS_CONTENT: 'bridge-tabs-content',
  TABS_SWIPE_GESTURE: 'bridge-tabs-swipe-gesture',
  MARKET_TAB: 'bridge-market-tab',
  LIMIT_TAB: 'bridge-limit-tab',
  RECURRING_TAB: 'bridge-recurring-tab',
  LIMIT_ORDER_CONTAINER: 'bridge-limit-order-container',
  LIMIT_ORDER_SCROLL: 'bridge-limit-order-scroll',
  LIMIT_SOURCE_TOKEN_AREA: 'limit-source-token-area',
  LIMIT_SOURCE_TOKEN_INPUT: 'limit-source-token-area-input',
  LIMIT_SOURCE_AMOUNT_TYPE_TOGGLE: 'limit-source-token-area-amount-type-toggle',
  LIMIT_DEST_TOKEN_AREA: 'limit-dest-token-area',
  LIMIT_DEST_TOKEN_INPUT: 'limit-dest-token-area-input',
  RECURRING_BUY_CONTAINER: 'bridge-recurring-buy-container',
} as const;

export type BridgeViewSelectorsIDsType = typeof BridgeViewSelectorsIDs;
