import React from 'react';
import { fireEvent } from '@testing-library/react-native';
import { Platform } from 'react-native';
import renderWithProvider from '../../../../../util/test/renderWithProvider';
import MarketInsightsDisclaimerBottomSheet from './MarketInsightsDisclaimerBottomSheet';

const mockOnCloseBottomSheet = jest.fn();

jest.mock('@metamask/design-system-react-native', () => {
  const actual = jest.requireActual('@metamask/design-system-react-native');
  const ReactActual = jest.requireActual('react');
  const { View } = jest.requireActual('react-native');

  const MockBottomSheet = ReactActual.forwardRef(
    (
      {
        children,
        onClose,
      }: {
        children: React.ReactNode;
        onClose?: () => void;
      },
      ref: React.Ref<{ onCloseBottomSheet: () => void }>,
    ) => {
      ReactActual.useImperativeHandle(ref, () => ({
        onCloseBottomSheet: () => {
          mockOnCloseBottomSheet();
          onClose?.();
        },
        onOpenBottomSheet: jest.fn(),
      }));

      return ReactActual.createElement(
        View,
        { testID: 'mock-bottom-sheet', onClose },
        children,
      );
    },
  );

  return {
    ...actual,
    BottomSheet: MockBottomSheet,
  };
});

describe('MarketInsightsDisclaimerBottomSheet', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('calls onClose when the Got it button is pressed', () => {
    const onClose = jest.fn();

    const { getByText } = renderWithProvider(
      <MarketInsightsDisclaimerBottomSheet onClose={onClose} />,
    );

    fireEvent.press(getByText('Got it'));

    expect(mockOnCloseBottomSheet).toHaveBeenCalledTimes(1);
    expect(onClose).toHaveBeenCalledTimes(1);
  });

  it('renders the disclaimer title and body text', () => {
    const { getByText } = renderWithProvider(
      <MarketInsightsDisclaimerBottomSheet onClose={jest.fn()} />,
    );

    expect(getByText('AI generated content')).toBeOnTheScreen();
    expect(
      getByText(/This summary is AI-generated by a third party/),
    ).toBeOnTheScreen();
  });

  // TAT-3758: on Android this sheet renders inside a react-native <Modal>, which
  // is its own window. Without a nested SafeAreaProvider the root provider
  // measures the activity window and reports a bottom inset of 0, collapsing
  // BottomSheetDialog's bottom padding and leaving "Got it" under the
  // navigation bar.
  describe('modal safe-area inset (TAT-3758)', () => {
    const originalPlatform = Platform.OS;

    afterEach(() => {
      Platform.OS = originalPlatform;
    });

    it('nests a SafeAreaProvider on Android so the bottom inset is measured against the modal window', () => {
      Platform.OS = 'android';

      const { getByTestId } = renderWithProvider(
        <MarketInsightsDisclaimerBottomSheet onClose={jest.fn()} />,
      );

      expect(
        getByTestId('market-insights-disclaimer-safe-area-provider'),
      ).toBeOnTheScreen();
    });

    it('does not nest a SafeAreaProvider on iOS, where the root provider already reports correct insets', () => {
      Platform.OS = 'ios';

      const { queryByTestId, getByText } = renderWithProvider(
        <MarketInsightsDisclaimerBottomSheet onClose={jest.fn()} />,
      );

      expect(
        queryByTestId('market-insights-disclaimer-safe-area-provider'),
      ).toBeNull();
      // The sheet still renders normally on iOS.
      expect(getByText('AI generated content')).toBeOnTheScreen();
    });
  });

  it('does not call onClose before the button is pressed', () => {
    const onClose = jest.fn();

    renderWithProvider(
      <MarketInsightsDisclaimerBottomSheet onClose={onClose} />,
    );

    expect(onClose).not.toHaveBeenCalled();
  });
});
