import React from 'react';
import { fireEvent } from '@testing-library/react-native';
import renderWithProvider from '../../../../../util/test/renderWithProvider';
import MarketInsightsDisclaimerBottomSheet from './MarketInsightsDisclaimerBottomSheet';

jest.mock('@metamask/design-system-react-native', () => {
  const ReactLib = jest.requireActual('react');
  const { View: MockView, Text: MockText } = jest.requireActual('react-native');
  const actual = jest.requireActual('@metamask/design-system-react-native');

  return {
    ...actual,
    BottomSheet: ReactLib.forwardRef(
      (
        {
          children,
          onClose: onCloseProp,
        }: { children: React.ReactNode; onClose?: () => void },
        ref: React.Ref<{
          onOpenBottomSheet: () => void;
          onCloseBottomSheet: () => void;
        }>,
      ) => {
        ReactLib.useImperativeHandle(ref, () => ({
          onOpenBottomSheet: jest.fn(),
          // Simulate animation completion by immediately invoking the onClose prop
          onCloseBottomSheet: jest.fn().mockImplementation(() => {
            onCloseProp?.();
          }),
        }));
        return <MockView testID="mock-bottom-sheet">{children}</MockView>;
      },
    ),
    BottomSheetHeader: ({
      children,
      onClose,
    }: {
      children: React.ReactNode;
      onClose?: () => void;
    }) => (
      <MockView testID="mock-bottom-sheet-header">
        <MockText>{children}</MockText>
        {onClose && (
          <MockView testID="mock-bottom-sheet-header-close" onPress={onClose} />
        )}
      </MockView>
    ),
  };
});

describe('MarketInsightsDisclaimerBottomSheet', () => {
  it('calls onClose when the Got it button is pressed', () => {
    const onClose = jest.fn();

    const { getByText } = renderWithProvider(
      <MarketInsightsDisclaimerBottomSheet isVisible onClose={onClose} />,
    );

    fireEvent.press(getByText('Got it'));

    expect(onClose).toHaveBeenCalledTimes(1);
  });

  it('renders the disclaimer title and body text', () => {
    const { getByText } = renderWithProvider(
      <MarketInsightsDisclaimerBottomSheet isVisible onClose={jest.fn()} />,
    );

    expect(getByText('AI generated content')).toBeOnTheScreen();
    expect(
      getByText(/This summary is AI-generated by a third party/),
    ).toBeOnTheScreen();
  });

  it('does not call onClose before the button is pressed', () => {
    const onClose = jest.fn();

    renderWithProvider(
      <MarketInsightsDisclaimerBottomSheet isVisible onClose={onClose} />,
    );

    expect(onClose).not.toHaveBeenCalled();
  });
});
