export enum AlertKeys {
  BatchedUnusedApprovals = 'batched_unused_approvals',
  Blockaid = 'blockaid',
  BurnAddress = 'burn_address',
  DomainMismatch = 'domain_mismatch',
  InsufficientBalance = 'insufficient_balance',
  InsufficientPayTokenBalance = 'insufficient_pay_token_balance',
  InsufficientPayTokenNative = 'insufficient_pay_token_native',
  InsufficientPayTokenFees = 'insufficient_pay_token_fees',
  InsufficientPredictBalance = 'insufficient_predict_balance',
  NoPayTokenQuotes = 'no_pay_token_quotes',
  PendingTransaction = 'pending_transaction',
  PerpsDepositMinimum = 'perps_deposit_minimum',
  PerpsHardwareAccount = 'perps_hardware_account',
  SignedOrSubmitted = 'signed_or_submitted',
  TokenTrustSignalMalicious = 'token_trust_signal_malicious',
  TokenTrustSignalWarning = 'token_trust_signal_warning',
}
