export const ConfirmationInfoComponentIDs = {
  APPROVE: 'approve-info',
  CONTRACT_INTERACTION: 'contract-interaction-info',
  CONTRACT_DEPLOYMENT: 'contract-deployment-info',
  LENDING_DEPOSIT: 'lending-deposit-info',
  PERSONAL_SIGN: 'personal-sign-info',
  SIGN_TYPED_DATA_V1: 'sign-typed-data-v1-info',
  SIGN_TYPED_DATA_V3V4: 'sign-typed-data-v3v4-info',
  STAKING_CLAIM: 'staking-claim-info',
  STAKING_DEPOSIT: 'staking-deposit-info',
  STAKING_WITHDRAWAL: 'staking-withdrawal-info',
  SWITCH_ACCOUNT_TYPE: 'switch-account-type-info',
  TRANSFER: 'transfer-info',
  QR_INFO: 'qr-info',
} as const;
