#!/usr/bin/env bash
#
# BN.js -> BigInt migration burn-down tracker.
#
# Replaces the type-aware `@typescript-eslint/no-deprecated` rule (which forced
# whole-project TypeScript parsing and dominated lint time) for the specific job
# of tracking which files still import the deprecated `app/util/number/index.js`
# module. The fast `import-x/no-restricted-paths` fence in `.eslintrc.js` already
# blocks *new* importers; this script maintains a committed snapshot of the
# remaining importers so the list can only shrink as the migration progresses.
#
# Usage:
#   scripts/bn-migration-burndown.sh            # check (CI/local): fail on drift
#   scripts/bn-migration-burndown.sh --check     # same as above (explicit)
#   scripts/bn-migration-burndown.sh --write      # update the snapshot in place
#   scripts/bn-migration-burndown.sh --list       # print current importers, no diff
#
# Exit codes:
#   0  snapshot matches reality (or --write/--list succeeded)
#   1  drift detected (snapshot out of sync) or a NEW importer was added
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

SNAPSHOT="scripts/bn-migration-burndown.txt"

# The deprecated module lives at exactly one path; `util/number` is unambiguous
# repo-wide (verified: no other `util/number` module exists). Sibling modules
# (`util/number/bigint`, `bignumber`, `subscriptNotation`, ...) resolve to other
# files and intentionally do NOT match.
#
# Two families of import specifiers resolve to `app/util/number/index.js`:
#   A. Anything ending in `util/number[/index[.js]]` — safe to match anywhere in
#      `app` because the literal `util/` segment disambiguates it.
#        e.g. `from '../../util/number'`, `from '../util/number/index.js'`
#   B. Relative `./number` / `../number[/index[.js]]` — only resolves to the
#      deprecated module when the importer itself lives under `app/util/`
#      (elsewhere, e.g. `app/components/.../utils/number.ts`, `./number` is a
#      different local module). So family B is searched ONLY within `app/util/`.
PATTERN_UTIL_NUMBER="(from|import|require)[[:space:]]*\(?[[:space:]]*['\"][^'\"]*util/number(/index(\.js)?)?['\"]"
PATTERN_RELATIVE_NUMBER="(from|import|require)[[:space:]]*\(?[[:space:]]*['\"]\.\.?/(\.\.?/)*number(/index(\.js)?)?['\"]"

MODE="check"
case "${1:-}" in
  ""|--check|check) MODE="check" ;;
  --write|write)    MODE="write" ;;
  --list|list)      MODE="list" ;;
  -h|--help|help)
    grep '^#' "$0" | grep -v '^#!' | sed 's/^# \{0,1\}//'
    exit 0
    ;;
  *)
    echo "Unknown argument: $1" >&2
    echo "Run with --help for usage." >&2
    exit 1
    ;;
esac

# Compute the current, sorted, de-duplicated list of importer file paths.
GREP_INCLUDES=(--include='*.ts' --include='*.tsx' --include='*.js' --include='*.jsx')
compute_current() {
  {
    grep -rEl "${GREP_INCLUDES[@]}" -e "$PATTERN_UTIL_NUMBER" app || true
    grep -rEl "${GREP_INCLUDES[@]}" -e "$PATTERN_RELATIVE_NUMBER" app/util || true
  } | LC_ALL=C sort -u
}

CURRENT="$(compute_current || true)"

if [[ "$MODE" == "list" ]]; then
  printf '%s\n' "$CURRENT"
  exit 0
fi

if [[ "$MODE" == "write" ]]; then
  {
    echo "# BN.js -> BigInt migration burn-down. AUTO-GENERATED by scripts/bn-migration-burndown.sh."
    echo "# Files still importing the deprecated app/util/number/index.js module."
    echo "# This list must only ever SHRINK. Run \`yarn lint:bn-burndown:write\` after migrating a file."
    printf '%s\n' "$CURRENT"
  } > "$SNAPSHOT"
  COUNT="$(printf '%s\n' "$CURRENT" | sed '/^$/d' | wc -l | tr -d ' ')"
  echo "Wrote $SNAPSHOT ($COUNT importers remaining)."
  exit 0
fi

# --- check mode ---
if [[ ! -f "$SNAPSHOT" ]]; then
  echo "ERROR: snapshot $SNAPSHOT does not exist. Run: yarn lint:bn-burndown:write" >&2
  exit 1
fi

# Recorded snapshot list (strip comments/blank lines).
RECORDED="$(grep -vE '^\s*(#|$)' "$SNAPSHOT" | LC_ALL=C sort -u || true)"

if [[ "$CURRENT" == "$RECORDED" ]]; then
  COUNT="$(printf '%s\n' "$CURRENT" | sed '/^$/d' | wc -l | tr -d ' ')"
  echo "BN.js burn-down in sync: $COUNT importers of deprecated app/util/number/index.js."
  exit 0
fi

# Drift: classify additions (regressions) vs removals (migration progress).
ADDED="$(comm -23 <(printf '%s\n' "$CURRENT") <(printf '%s\n' "$RECORDED") || true)"
REMOVED="$(comm -13 <(printf '%s\n' "$CURRENT") <(printf '%s\n' "$RECORDED") || true)"

echo "BN.js burn-down OUT OF SYNC." >&2
if [[ -n "$ADDED" ]]; then
  echo "" >&2
  echo "NEW importers of the deprecated app/util/number/index.js (not allowed):" >&2
  printf '  + %s\n' $ADDED >&2
  echo "" >&2
  echo "  Do not add new dependencies on app/util/number/index.js." >&2
  echo "  Import the BigInt-based replacement from app/util/number/bigint instead." >&2
fi
if [[ -n "$REMOVED" ]]; then
  echo "" >&2
  echo "Files migrated off app/util/number/index.js since last snapshot (progress!):" >&2
  printf '  - %s\n' $REMOVED >&2
  echo "" >&2
  echo "  Record this progress by running: yarn lint:bn-burndown:write" >&2
fi
echo "" >&2
exit 1
