#!/bin/bash

echo "Contents of HOME/.android/"
ls -la $HOME/.android/

echo "Contents of HOME/.android/avd"
ls -la $HOME/.android/avd

echo "Contents of HOME/.android/avd/Pixel_2_API_27.avd"
ls -la $HOME/.android/avd/Pixel_2_API_27.avd


echo "
AvdId=Pixel_2_API_27
PlayStore.enabled=false
abi.type=x86
avd.ini.displayname=Pixel 2 API 27
avd.ini.encoding=UTF-8
disk.dataPartition.size=800M
fastboot.forceColdBoot=no
hw.accelerometer=yes
hw.arc=false
hw.audioInput=yes
hw.battery=yes
hw.camera.back=none
hw.camera.front=none
hw.cpu.arch=x86
hw.dPad=no
hw.device.hash2=MD5:bc5032b2a871da511332401af3ac6bb0
hw.device.manufacturer=Google
hw.device.name=pixel_2
hw.gps=yes
hw.gpu.enabled=yes
hw.gpu.mode=guest
hw.initialOrientation=Portrait
hw.keyboard=no
hw.lcd.density=420
hw.lcd.height=1920
hw.lcd.width=1080
hw.mainKeys=no
hw.ramSize=1536
hw.sdCard=yes
hw.sensors.orientation=yes
hw.sensors.proximity=yes
hw.trackBall=no
image.sysdir.1=system-images/android-27/google_apis/x86/
runtime.network.latency=none
runtime.network.speed=full
sdcard.size=100M
showDeviceFrame=no
skin.dynamic=yes
skin.name=1080x1920
skin.path=_no_skin
skin.path.backup=_no_skin
tag.display=Google APIs
tag.id=google_apis
vm.heapSize=256" > $HOME/.android/avd/Pixel_2_API_27.avd/config.ini
