const Routes = {
  WALLET_VIEW: 'WalletView',
  BROWSER_TAB_HOME: 'BrowserTabHome',
  BROWSER_VIEW: 'BrowserView',
  SETTINGS_VIEW: 'SettingsView',
  DEPRECATED_NETWORK_DETAILS: 'DeprecatedNetworkDetails',
  RAMP: {
    ID: 'Ramp',
    BUY: 'RampBuy',
    SELL: 'RampSell',
    GET_STARTED: 'GetStarted',
    BUILD_QUOTE: 'BuildQuote',
    BUILD_QUOTE_HAS_STARTED: 'BuildQuoteHasStarted',
    QUOTES: 'Quotes',
    CHECKOUT: 'Checkout',
    REGION: 'Region',
    REGION_HAS_STARTED: 'RegionHasStarted',
    NETWORK_SWITCHER: 'BuyNetworkSwitcher',
    ORDER_DETAILS: 'OrderDetails',
    SEND_TRANSACTION: 'SendTransaction',
    SETTINGS: 'RampSettings',
    ACTIVATION_KEY_FORM: 'RampActivationKeyForm',
  },
  DEPOSIT: {
    ID: 'Deposit',
    ROOT: 'DepositRoot',
    BUILD_QUOTE: 'BuildQuote',
    ENTER_EMAIL: 'EnterEmail',
    OTP_CODE: 'OtpCode',
    VERIFY_IDENTITY: 'VerifyIdentity',
    BASIC_INFO: 'BasicInfo',
    ENTER_ADDRESS: 'EnterAddress',
    KYC_PROCESSING: 'KycProcessing',
    ORDER_PROCESSING: 'OrderProcessing',
    ORDER_DETAILS: 'DepositOrderDetails',
    BANK_DETAILS: 'BankDetails',
    ADDITIONAL_VERIFICATION: 'AdditionalVerification',
    MODALS: {
      ID: 'DepositModals',
      TOKEN_SELECTOR: 'DepositTokenSelectorModal',
      REGION_SELECTOR: 'DepositRegionSelectorModal',
      PAYMENT_METHOD_SELECTOR: 'DepositPaymentMethodSelectorModal',
      UNSUPPORTED_REGION: 'DepositUnsupportedRegionModal',
      UNSUPPORTED_STATE: 'DepositUnsupportedStateModal',
      STATE_SELECTOR: 'DepositStateSelectorModal',
      WEBVIEW: 'DepositWebviewModal',
      KYC_WEBVIEW: 'DepositKycWebviewModal',
      INCOMPATIBLE_ACCOUNT_TOKEN: 'IncompatibleAccountTokenModal',
      SSN_INFO: 'SsnInfoModal',
      CONFIGURATION: 'DepositConfigurationModal',
    },
  },
  HW: {
    CONNECT: 'ConnectHardwareWalletFlow',
    SELECT_DEVICE: 'SelectHardwareWallet',
    CONNECT_QR_DEVICE: 'ConnectQRHardwareFlow',
    CONNECT_LEDGER: 'ConnectLedgerFlow',
    LEDGER_CONNECT: 'LedgerConnect',
  },
  LEDGER_MESSAGE_SIGN_MODAL: 'LedgerMessageSignModal',
  LEDGER_TRANSACTION_MODAL: 'LedgerTransactionModal',
  QR_TAB_SWITCHER: 'QRTabSwitcher',
  OPTIONS_SHEET: 'OptionsSheet',
  QR_SCANNER: 'QRScanner',
  TRANSACTIONS_VIEW: 'TransactionsView',
  TRANSACTION_DETAILS: 'TransactionDetails',
  REWARDS_VIEW: 'RewardsView',
  REFERRAL_REWARDS_VIEW: 'ReferralRewardsView',
  REWARDS_DASHBOARD: 'RewardsDashboard',
  REWARDS_ONBOARDING_FLOW: 'RewardsOnboardingFlow',
  REWARDS_ONBOARDING_INTRO: 'RewardsOnboardingIntro',
  REWARDS_ONBOARDING_1: 'RewardsOnboarding1',
  REWARDS_ONBOARDING_2: 'RewardsOnboarding2',
  REWARDS_ONBOARDING_3: 'RewardsOnboarding3',
  REWARDS_ONBOARDING_4: 'RewardsOnboarding4',
  MODAL: {
    DELETE_WALLET: 'DeleteWalletModal',
    ROOT_MODAL_FLOW: 'RootModalFlow',
    MODAL_CONFIRMATION: 'ModalConfirmation',
    MODAL_MANDATORY: 'ModalMandatory',
    WHATS_NEW: 'WhatsNewModal',
    TURN_OFF_REMEMBER_ME: 'TurnOffRememberMeModal',
    UPDATE_NEEDED: 'UpdateNeededModal',
    DETECTED_TOKENS: 'DetectedTokens',
    SRP_REVEAL_QUIZ: 'SRPRevealQuiz',
    WALLET_ACTIONS: 'WalletActions',
    FUND_ACTION_MENU: 'FundActionMenu',
    NFT_AUTO_DETECTION_MODAL: 'NFTAutoDetectionModal',
    MULTI_RPC_MIGRATION_MODAL: 'MultiRPcMigrationModal',
    MAX_BROWSER_TABS_MODAL: 'MaxBrowserTabsModal',
    DEEP_LINK_MODAL: 'DeepLinkModal',
    MULTICHAIN_ACCOUNT_DETAIL_ACTIONS: 'MultichainAccountDetailActions',
    REWARDS_ERROR_MODAL: 'RewardsErrorModal',
  },
  ONBOARDING: {
    ROOT_NAV: 'OnboardingRootNav',
    SUCCESS_FLOW: 'OnboardingSuccessFlow',
    SUCCESS: 'OnboardingSuccess',
    DEFAULT_SETTINGS: 'DefaultSettings',
    GENERAL_SETTINGS: 'GeneralSettings',
    ASSETS_SETTINGS: 'AssetsSettings',
    SECURITY_SETTINGS: 'SecuritySettings',
    HOME_NAV: 'HomeNav',
    ONBOARDING: 'Onboarding',
    LOGIN: 'Login',
    NAV: 'OnboardingNav',
    MANUAL_BACKUP: {
      STEP_1: 'ManualBackupStep1',
      STEP_2: 'ManualBackupStep2',
      STEP_3: 'ManualBackupStep3',
    },
    IMPORT_FROM_SECRET_RECOVERY_PHRASE: 'ImportFromSecretRecoveryPhrase',
    CHOOSE_PASSWORD: 'ChoosePassword',
    OPTIN_METRICS: 'OptinMetrics',
  },
  SEND_FLOW: {
    SEND_TO: 'SendTo',
    AMOUNT: 'Amount',
    CONFIRM: 'Confirm',
  },
  ACCOUNT_BACKUP: {
    STEP_1_B: 'AccountBackupStep1B',
  },
  SETTINGS: {
    ADVANCED_SETTINGS: 'AdvancedSettings',
    CHANGE_PASSWORD: 'ResetPassword',
    CONTACT_FORM: 'ContactForm',
    DEVELOPER_OPTIONS: 'DeveloperOptions',
    EXPERIMENTAL_SETTINGS: 'ExperimentalSettings',
    NOTIFICATIONS: 'NotificationsSettings',
    REVEAL_PRIVATE_CREDENTIAL: 'RevealPrivateCredentialView',
    SDK_SESSIONS_MANAGER: 'SDKSessionsManager',
    BACKUP_AND_SYNC: 'BackupAndSyncSettings',
  },
  SHEET: {
    ACCOUNT_SELECTOR: 'AccountSelector',
    ADDRESS_SELECTOR: 'AddressSelector',
    ADD_ACCOUNT: 'AddAccount',
    AMBIGUOUS_ADDRESS: 'AmbiguousAddress',
    BASIC_FUNCTIONALITY: 'BasicFunctionality',
    CONFIRM_TURN_ON_BACKUP_AND_SYNC: 'ConfirmTurnOnBackupAndSync',
    RESET_NOTIFICATIONS: 'ResetNotifications',
    SDK_LOADING: 'SDKLoading',
    SDK_FEEDBACK: 'SDKFeedback',
    DATA_COLLECTION: 'DataCollection',
    EXPERIENCE_ENHANCER: 'ExperienceEnhancer',
    SDK_MANAGE_CONNECTIONS: 'SDKManageConnections',
    SDK_DISCONNECT: 'SDKDisconnect',
    ACCOUNT_CONNECT: 'AccountConnect',
    ACCOUNT_PERMISSIONS: 'AccountPermissions',
    REVOKE_ALL_ACCOUNT_PERMISSIONS: 'RevokeAllAccountPermissions',
    CONNECTION_DETAILS: 'ConnectionDetails',
    PERMITTED_NETWORKS_INFO_SHEET: 'PermittedNetworksInfoSheet',
    NETWORK_SELECTOR: 'NetworkSelector',
    RETURN_TO_DAPP_MODAL: 'ReturnToDappModal',
    ACCOUNT_ACTIONS: 'AccountActions',
    FIAT_ON_TESTNETS_FRICTION: 'SettingsAdvancedFiatOnTestnetsFriction',
    SHOW_IPFS: 'ShowIpfs',
    SHOW_NFT_DISPLAY_MEDIA: 'ShowNftDisplayMedia',
    SHOW_TOKEN_ID: 'ShowTokenId',
    ORIGIN_SPAM_MODAL: 'OriginSpamModal',
    TOOLTIP_MODAL: 'tooltipModal',
    TOKEN_SORT: 'TokenSort',
    TOKEN_FILTER: 'TokenFilter',
    NETWORK_MANAGER: 'NetworkManager',
    CHANGE_IN_SIMULATION_MODAL: 'ChangeInSimulationModal',
    SELECT_SRP: 'SelectSRP',
    ONBOARDING_SHEET: 'OnboardingSheet',
    SEEDPHRASE_MODAL: 'SeedphraseModal',
    SKIP_ACCOUNT_SECURITY_MODAL: 'SkipAccountSecurityModal',
    SUCCESS_ERROR_SHEET: 'SuccessErrorSheet',
    MULTICHAIN_ACCOUNT_DETAILS: {
      ACCOUNT_ACTIONS: 'MultichainAccountActions',
      EDIT_ACCOUNT_NAME: 'EditMultichainAccountName',
      LEGACY_EDIT_ACCOUNT_NAME: 'LegacyEditMultichainAccountName',
      EDIT_WALLET_NAME: 'EditWalletName',
      SHARE_ADDRESS: 'ShareAddress',
      SHARE_ADDRESS_QR: 'ShareAddressQR',
      DELETE_ACCOUNT: 'DeleteAccount',
      REVEAL_PRIVATE_CREDENTIAL: 'RevealPrivateCredential',
      REVEAL_SRP_CREDENTIAL: 'RevealSRPCredential',
      SRP_REVEAL_QUIZ: 'SRPRevealQuizInMultichainAccountDetails',
      SMART_ACCOUNT: 'SmartAccount',
    },
  },
  BROWSER: {
    HOME: 'BrowserTabHome',
    VIEW: 'BrowserView',
    ASSET_LOADER: 'AssetLoader',
    ASSET_VIEW: 'AssetView',
  },
  WEBVIEW: {
    MAIN: 'Webview',
    SIMPLE: 'SimpleWebview',
  },
  WALLET: {
    HOME: 'WalletTabHome',
    TAB_STACK_FLOW: 'WalletTabStackFlow',
    WALLET_CONNECT_SESSIONS_VIEW: 'WalletConnectSessionsView',
  },
  VAULT_RECOVERY: {
    RESTORE_WALLET: 'RestoreWallet',
    WALLET_RESTORED: 'WalletRestored',
    WALLET_RESET_NEEDED: 'WalletResetNeeded',
  },
  ADD_NETWORK: 'AddNetwork',
  EDIT_NETWORK: 'EditNetwork',
  SWAPS: 'Swaps',
  SWAPS_AMOUNT_VIEW: 'SwapsAmountView',
  BRIDGE: {
    ROOT: 'Bridge',
    BRIDGE_VIEW: 'BridgeView',
    MODALS: {
      ROOT: 'BridgeModals',
      SOURCE_TOKEN_SELECTOR: 'BridgeSourceTokenSelector',
      SOURCE_NETWORK_SELECTOR: 'BridgeSourceNetworkSelector',
      SLIPPAGE_MODAL: 'SlippageModal',
      DEST_TOKEN_SELECTOR: 'BridgeDestTokenSelector',
      DEST_NETWORK_SELECTOR: 'BridgeDestNetworkSelector',
      QUOTE_INFO_MODAL: 'QuoteInfoModal',
      TRANSACTION_DETAILS_BLOCK_EXPLORER: 'TransactionDetailsBlockExplorer',
      QUOTE_EXPIRED_MODAL: 'QuoteExpiredModal',
      BLOCKAID_MODAL: 'BlockaidModal',
      PRICE_IMPACT_WARNING_MODAL: 'PriceImpactWarningModal',
    },
    BRIDGE_TRANSACTION_DETAILS: 'BridgeTransactionDetails',
  },
  PERPS: {
    ROOT: 'Perps',
    TRADING_VIEW: 'PerpsTradingView',
    ORDER: 'PerpsOrder',
    WITHDRAW: 'PerpsWithdraw',
    POSITIONS: 'PerpsPositions',
    MARKETS: 'PerpsMarketListView',
    MARKET_DETAILS: 'PerpsMarketDetails',
    TUTORIAL: 'PerpsTutorial',
    CLOSE_POSITION: 'PerpsClosePosition',
    MODALS: {
      ROOT: 'PerpsModals',
      QUOTE_EXPIRED_MODAL: 'PerpsQuoteExpiredModal',
      BALANCE_MODAL: 'PerpsBalanceModal',
      GTM_MODAL: 'PerpsGTMModal',
    },
    POSITION_TRANSACTION: 'PerpsPositionTransaction',
    ORDER_TRANSACTION: 'PerpsOrderTransaction',
    FUNDING_TRANSACTION: 'PerpsFundingTransaction',
  },
  LOCK_SCREEN: 'LockScreen',
  CONFIRMATION_REQUEST_MODAL: 'ConfirmationRequestModal',
  CONFIRMATION_SWITCH_ACCOUNT_TYPE: 'ConfirmationSwitchAccountType',
  CONFIRMATION_PAY_WITH_MODAL: 'ConfirmationPayWithModal',
  CONFIRMATION_PAY_WITH_NETWORK_MODAL: 'ConfirmationPayWithNetworkModal',
  SMART_ACCOUNT_OPT_IN: 'SmartAccountOptIn',
  NOTIFICATIONS: {
    VIEW: 'NotificationsView',
    OPT_IN: 'OptIn',
    OPT_IN_STACK: 'OptInStack',
    DETAILS: 'NotificationsDetails',
  },
  STAKING: {
    STAKE: 'Stake',
    STAKE_CONFIRMATION: 'StakeConfirmation',
    UNSTAKE: 'Unstake',
    UNSTAKE_CONFIRMATION: 'UnstakeConfirmation',
    EARNINGS_HISTORY: 'EarningsHistory',
    CLAIM: 'Claim',
    MODALS: {
      LEARN_MORE: 'LearnMore',
      MAX_INPUT: 'MaxInput',
      GAS_IMPACT: 'GasImpact',
      EARN_TOKEN_LIST: 'EarnTokenList',
    },
  },
  EARN: {
    ROOT: 'EarnScreens',
    LENDING_DEPOSIT_CONFIRMATION: 'EarnLendingDepositConfirmation',
    LENDING_WITHDRAWAL_CONFIRMATION: 'EarnLendingWithdrawalConfirmation',
    MODALS: {
      ROOT: 'EarnModals',
      LENDING_MAX_WITHDRAWAL: 'EarnLendingMaxWithdrawalModal',
      LENDING_LEARN_MORE: 'EarnLendingLearnMoreModal',
    },
  },
  FULL_SCREEN_CONFIRMATIONS: {
    REDESIGNED_CONFIRMATIONS: 'RedesignedConfirmations',
  },
  IDENTITY: {
    TURN_ON_BACKUP_AND_SYNC: 'TurnOnBackupAndSync',
  },
  MULTI_SRP: {
    IMPORT: 'ImportSRPView',
  },
  MULTICHAIN_ACCOUNTS: {
    ACCOUNT_DETAILS: 'MultichainAccountDetails',
    ACCOUNT_GROUP_DETAILS: 'MultichainAccountGroupDetails',
    WALLET_DETAILS: 'MultichainWalletDetails',
    ADDRESS_LIST: 'MultichainAddressList',
    PRIVATE_KEY_LIST: 'MultichainPrivateKeyList',
    ACCOUNT_CELL_ACTIONS: 'MultichainAccountActions',
  },
  ///: BEGIN:ONLY_INCLUDE_IF(external-snaps)
  SNAPS: {
    SNAPS_SETTINGS_LIST: 'SnapsSettingsList',
    SNAP_SETTINGS: 'SnapSettings',
  },
  ///: END:ONLY_INCLUDE_IF
  FOX_LOADER: 'FoxLoader',
  SEEDPHRASE_MODAL: 'SeedphraseModal',
  SET_PASSWORD_FLOW: {
    ROOT: 'SetPasswordFlow',
    MANUAL_BACKUP_STEP_1: 'ManualBackupStep1',
    MANUAL_BACKUP_STEP_2: 'ManualBackupStep2',
    MANUAL_BACKUP_STEP_3: 'ManualBackupStep3',
  },

  EDIT_ACCOUNT_NAME: 'EditAccountName',
  ///: BEGIN:ONLY_INCLUDE_IF(sample-feature)
  SAMPLE_FEATURE: 'SampleFeature',
  ///: END:ONLY_INCLUDE_IF
  CARD: {
    ROOT: 'CardScreens',
    HOME: 'CardHome',
  },
  SEND: {
    RECIPIENT: 'Recipient',
    ASSET: 'Asset',
    AMOUNT: 'Amount',
    DEFAULT: 'Send',
  },
};

export default Routes;
