const Routes = {
  WALLET_VIEW: 'WalletView',
  BROWSER_TAB_HOME: 'BrowserTabHome',
  BROWSER_VIEW: 'BrowserView',
  SETTINGS_VIEW: 'SettingsView',
  DEPRECATED_NETWORK_DETAILS: 'DeprecatedNetworkDetails',
  RAMP: {
    ID: 'Ramp',
    BUY: 'RampBuy',
    SELL: 'RampSell',
    TOKEN_SELECTION: 'RampTokenSelection',
    GET_STARTED: 'GetStarted',
    BUILD_QUOTE: 'BuildQuote',
    BUILD_QUOTE_HAS_STARTED: 'BuildQuoteHasStarted',
    QUOTES: 'Quotes',
    CHECKOUT: 'Checkout',
    ORDER_DETAILS: 'OrderDetails',
    SEND_TRANSACTION: 'SendTransaction',
    SETTINGS: 'RampSettings',
    ACTIVATION_KEY_FORM: 'RampActivationKeyForm',
    MODALS: {
      ID: 'RampModals',
      TOKEN_SELECTOR: 'RampTokenSelectorModal',
      FIAT_SELECTOR: 'RampFiatSelectorModal',
      INCOMPATIBLE_ACCOUNT_TOKEN: 'RampIncompatibleAccountTokenModal',
      REGION_SELECTOR: 'RampRegionSelectorModal',
      UNSUPPORTED_REGION: 'RampUnsupportedRegionModal',
      UNSUPPORTED_TOKEN: 'RampUnsupportedTokenModal',
      PAYMENT_METHOD_SELECTOR: 'RampPaymentMethodSelectorModal',
      SETTINGS: 'RampSettingsModal',
    },
  },
  DEPOSIT: {
    ID: 'Deposit',
    ROOT: 'DepositRoot',
    BUILD_QUOTE: 'BuildQuote',
    ENTER_EMAIL: 'EnterEmail',
    OTP_CODE: 'OtpCode',
    VERIFY_IDENTITY: 'VerifyIdentity',
    BASIC_INFO: 'BasicInfo',
    ENTER_ADDRESS: 'EnterAddress',
    KYC_PROCESSING: 'KycProcessing',
    ORDER_PROCESSING: 'OrderProcessing',
    ORDER_DETAILS: 'DepositOrderDetails',
    BANK_DETAILS: 'BankDetails',
    ADDITIONAL_VERIFICATION: 'AdditionalVerification',
    MODALS: {
      ID: 'DepositModals',
      TOKEN_SELECTOR: 'DepositTokenSelectorModal',
      REGION_SELECTOR: 'DepositRegionSelectorModal',
      PAYMENT_METHOD_SELECTOR: 'DepositPaymentMethodSelectorModal',
      UNSUPPORTED_REGION: 'DepositUnsupportedRegionModal',
      UNSUPPORTED_STATE: 'DepositUnsupportedStateModal',
      STATE_SELECTOR: 'DepositStateSelectorModal',
      WEBVIEW: 'DepositWebviewModal',
      KYC_WEBVIEW: 'DepositKycWebviewModal',
      INCOMPATIBLE_ACCOUNT_TOKEN: 'IncompatibleAccountTokenModal',
      SSN_INFO: 'SsnInfoModal',
      CONFIGURATION: 'DepositConfigurationModal',
      ERROR_DETAILS: 'DepositErrorDetailsModal',
    },
  },
  HW: {
    CONNECT: 'ConnectHardwareWalletFlow',
    SELECT_DEVICE: 'SelectHardwareWallet',
    CONNECT_QR_DEVICE: 'ConnectQRHardwareFlow',
    CONNECT_LEDGER: 'ConnectLedgerFlow',
    LEDGER_CONNECT: 'LedgerConnect',
  },
  LEDGER_MESSAGE_SIGN_MODAL: 'LedgerMessageSignModal',
  LEDGER_TRANSACTION_MODAL: 'LedgerTransactionModal',
  QR_TAB_SWITCHER: 'QRTabSwitcher',
  OPTIONS_SHEET: 'OptionsSheet',
  QR_SCANNER: 'QRScanner',
  TRANSACTIONS_VIEW: 'TransactionsView',
  TRANSACTION_DETAILS: 'TransactionDetails',
  REWARDS_VIEW: 'RewardsView',
  REFERRAL_REWARDS_VIEW: 'ReferralRewardsView',
  REWARDS_SETTINGS_VIEW: 'RewardsSettingsView',
  REWARDS_DASHBOARD: 'RewardsDashboard',
  TRENDING_VIEW: 'TrendingView',
  SITES_FULL_VIEW: 'SitesFullView',
  EXPLORE_SEARCH: 'ExploreSearch',
  REWARDS_ONBOARDING_FLOW: 'RewardsOnboardingFlow',
  REWARDS_ONBOARDING_INTRO: 'RewardsOnboardingIntro',
  REWARDS_ONBOARDING_1: 'RewardsOnboarding1',
  REWARDS_ONBOARDING_2: 'RewardsOnboarding2',
  REWARDS_ONBOARDING_3: 'RewardsOnboarding3',
  REWARDS_ONBOARDING_4: 'RewardsOnboarding4',
  MODAL: {
    DELETE_WALLET: 'DeleteWalletModal',
    ROOT_MODAL_FLOW: 'RootModalFlow',
    MODAL_CONFIRMATION: 'ModalConfirmation',
    MODAL_MANDATORY: 'ModalMandatory',
    WHATS_NEW: 'WhatsNewModal',
    TURN_OFF_REMEMBER_ME: 'TurnOffRememberMeModal',
    UPDATE_NEEDED: 'UpdateNeededModal',
    DETECTED_TOKENS: 'DetectedTokens',
    SRP_REVEAL_QUIZ: 'SRPRevealQuiz',
    WALLET_ACTIONS: 'WalletActions',
    TRADE_WALLET_ACTIONS: 'TradeWalletActions',
    FUND_ACTION_MENU: 'FundActionMenu',
    NFT_AUTO_DETECTION_MODAL: 'NFTAutoDetectionModal',
    MULTI_RPC_MIGRATION_MODAL: 'MultiRPcMigrationModal',
    MAX_BROWSER_TABS_MODAL: 'MaxBrowserTabsModal',
    DEEP_LINK_MODAL: 'DeepLinkModal',
    MULTICHAIN_ACCOUNT_DETAIL_ACTIONS: 'MultichainAccountDetailActions',
    MULTICHAIN_ACCOUNTS_INTRO: 'MultichainAccountsIntroModal',
    MULTICHAIN_ACCOUNTS_LEARN_MORE: 'MultichainAccountsLearnMoreBottomSheet',
    REWARDS_BOTTOM_SHEET_MODAL: 'RewardsBottomSheetModal',
    REWARDS_CLAIM_BOTTOM_SHEET_MODAL: 'RewardsClaimBottomSheetModal',
    REWARDS_INTRO_MODAL: 'RewardsIntroModal',
    REWARDS_OPTIN_ACCOUNT_GROUP_MODAL: 'RewardOptInAccountGroupModal',
    REWARDS_REFERRAL_BOTTOM_SHEET_MODAL: 'RewardsReferralBottomSheetModal',
  },
  ONBOARDING: {
    ROOT_NAV: 'OnboardingRootNav',
    SUCCESS_FLOW: 'OnboardingSuccessFlow',
    SUCCESS: 'OnboardingSuccess',
    DEFAULT_SETTINGS: 'DefaultSettings',
    GENERAL_SETTINGS: 'GeneralSettings',
    ASSETS_SETTINGS: 'AssetsSettings',
    SECURITY_SETTINGS: 'SecuritySettings',
    HOME_NAV: 'HomeNav',
    ONBOARDING: 'Onboarding',
    LOGIN: 'Login',
    NAV: 'OnboardingNav',
    SOCIAL_LOGIN_SUCCESS_NEW_USER: 'SocialLoginSuccessNewUser',
    MANUAL_BACKUP: {
      STEP_1: 'ManualBackupStep1',
      STEP_2: 'ManualBackupStep2',
      STEP_3: 'ManualBackupStep3',
    },
    IMPORT_FROM_SECRET_RECOVERY_PHRASE: 'ImportFromSecretRecoveryPhrase',
    CHOOSE_PASSWORD: 'ChoosePassword',
    OPTIN_METRICS: 'OptinMetrics',
    SOCIAL_LOGIN_SUCCESS_EXISTING_USER: 'SocialLoginSuccessExistingUser',
  },
  SEND_FLOW: {
    SEND_TO: 'SendTo',
    AMOUNT: 'Amount',
    CONFIRM: 'Confirm',
  },
  ACCOUNT_BACKUP: {
    STEP_1_B: 'AccountBackupStep1B',
  },
  SETTINGS: {
    SECURITY_SETTINGS: 'SecuritySettings',
    ADVANCED_SETTINGS: 'AdvancedSettings',
    CHANGE_PASSWORD: 'ResetPassword',
    CONTACT_FORM: 'ContactForm',
    DEVELOPER_OPTIONS: 'DeveloperOptions',
    EXPERIMENTAL_SETTINGS: 'ExperimentalSettings',
    NOTIFICATIONS: 'NotificationsSettings',
    REVEAL_PRIVATE_CREDENTIAL: 'RevealPrivateCredentialView',
    SDK_SESSIONS_MANAGER: 'SDKSessionsManager',
    BACKUP_AND_SYNC: 'BackupAndSyncSettings',
  },
  SHEET: {
    ACCOUNT_SELECTOR: 'AccountSelector',
    ADDRESS_SELECTOR: 'AddressSelector',
    ADD_ACCOUNT: 'AddAccount',
    AMBIGUOUS_ADDRESS: 'AmbiguousAddress',
    BASIC_FUNCTIONALITY: 'BasicFunctionality',
    CONFIRM_TURN_ON_BACKUP_AND_SYNC: 'ConfirmTurnOnBackupAndSync',
    RESET_NOTIFICATIONS: 'ResetNotifications',
    SDK_LOADING: 'SDKLoading',
    SDK_FEEDBACK: 'SDKFeedback',
    DATA_COLLECTION: 'DataCollection',
    EXPERIENCE_ENHANCER: 'ExperienceEnhancer',
    SDK_MANAGE_CONNECTIONS: 'SDKManageConnections',
    SDK_DISCONNECT: 'SDKDisconnect',
    ACCOUNT_CONNECT: 'AccountConnect',
    ACCOUNT_PERMISSIONS: 'AccountPermissions',
    REVOKE_ALL_ACCOUNT_PERMISSIONS: 'RevokeAllAccountPermissions',
    CONNECTION_DETAILS: 'ConnectionDetails',
    PERMITTED_NETWORKS_INFO_SHEET: 'PermittedNetworksInfoSheet',
    NETWORK_SELECTOR: 'NetworkSelector',
    ACCOUNT_ACTIONS: 'AccountActions',
    FIAT_ON_TESTNETS_FRICTION: 'SettingsAdvancedFiatOnTestnetsFriction',
    SHOW_IPFS: 'ShowIpfs',
    SHOW_NFT_DISPLAY_MEDIA: 'ShowNftDisplayMedia',
    SHOW_TOKEN_ID: 'ShowTokenId',
    ORIGIN_SPAM_MODAL: 'OriginSpamModal',
    TOOLTIP_MODAL: 'tooltipModal',
    TOKEN_SORT: 'TokenSort',
    TOKEN_FILTER: 'TokenFilter',
    NETWORK_MANAGER: 'NetworkManager',
    CHANGE_IN_SIMULATION_MODAL: 'ChangeInSimulationModal',
    SELECT_SRP: 'SelectSRP',
    ONBOARDING_SHEET: 'OnboardingSheet',
    SEEDPHRASE_MODAL: 'SeedphraseModal',
    SKIP_ACCOUNT_SECURITY_MODAL: 'SkipAccountSecurityModal',
    SUCCESS_ERROR_SHEET: 'SuccessErrorSheet',
    ELIGIBILITY_FAILED_MODAL: 'EligibilityFailedModal',
    UNSUPPORTED_REGION_MODAL: 'UnsupportedRegionModal',
    TOKEN_INSIGHTS: 'TokenInsights',
    MULTICHAIN_ACCOUNT_DETAILS: {
      ACCOUNT_ACTIONS: 'MultichainAccountActions',
      EDIT_ACCOUNT_NAME: 'EditMultichainAccountName',
      LEGACY_EDIT_ACCOUNT_NAME: 'LegacyEditMultichainAccountName',
      EDIT_WALLET_NAME: 'EditWalletName',
      SHARE_ADDRESS: 'ShareAddress',
      SHARE_ADDRESS_QR: 'ShareAddressQR',
      DELETE_ACCOUNT: 'DeleteAccount',
      REVEAL_PRIVATE_CREDENTIAL: 'RevealPrivateCredential',
      REVEAL_SRP_CREDENTIAL: 'RevealSRPCredential',
      SRP_REVEAL_QUIZ: 'SRPRevealQuizInMultichainAccountDetails',
      SMART_ACCOUNT: 'SmartAccount',
    },
  },
  BROWSER: {
    HOME: 'BrowserTabHome',
    VIEW: 'BrowserView',
    ASSET_LOADER: 'AssetLoader',
    ASSET_VIEW: 'AssetView',
  },
  WEBVIEW: {
    MAIN: 'Webview',
    SIMPLE: 'SimpleWebview',
  },
  WALLET: {
    HOME: 'WalletTabHome',
    TAB_STACK_FLOW: 'WalletTabStackFlow',
    WALLET_CONNECT_SESSIONS_VIEW: 'WalletConnectSessionsView',
    NFTS_FULL_VIEW: 'NftFullView',
    TOKENS_FULL_VIEW: 'TokensFullView',
    TRENDING_TOKENS_FULL_VIEW: 'TrendingTokensFullView',
  },
  VAULT_RECOVERY: {
    RESTORE_WALLET: 'RestoreWallet',
    WALLET_RESTORED: 'WalletRestored',
    WALLET_RESET_NEEDED: 'WalletResetNeeded',
  },
  ADD_NETWORK: 'AddNetwork',
  EDIT_NETWORK: 'EditNetwork',
  BRIDGE: {
    ROOT: 'Bridge',
    BRIDGE_VIEW: 'BridgeView',
    MODALS: {
      ROOT: 'BridgeModals',
      SOURCE_TOKEN_SELECTOR: 'BridgeSourceTokenSelector',
      SOURCE_NETWORK_SELECTOR: 'BridgeSourceNetworkSelector',
      SLIPPAGE_MODAL: 'SlippageModal',
      DEST_TOKEN_SELECTOR: 'BridgeDestTokenSelector',
      DEST_NETWORK_SELECTOR: 'BridgeDestNetworkSelector',
      TRANSACTION_DETAILS_BLOCK_EXPLORER: 'TransactionDetailsBlockExplorer',
      QUOTE_EXPIRED_MODAL: 'QuoteExpiredModal',
      BLOCKAID_MODAL: 'BlockaidModal',
      RECIPIENT_SELECTOR_MODAL: 'RecipientSelectorModal',
    },
    BRIDGE_TRANSACTION_DETAILS: 'BridgeTransactionDetails',
  },
  PERPS: {
    ROOT: 'Perps',
    PERPS_TAB: 'PerpsTradingView', // Redirect to wallet home and select perps tab
    ORDER: 'PerpsOrder',
    WITHDRAW: 'PerpsWithdraw',
    POSITIONS: 'PerpsPositions',
    PERPS_HOME: 'PerpsMarketListView', // Home screen (positions, orders, watchlist, markets)
    MARKET_DETAILS: 'PerpsMarketDetails',
    MARKET_LIST: 'PerpsTrendingView',
    TUTORIAL: 'PerpsTutorial',
    CLOSE_POSITION: 'PerpsClosePosition',
    HIP3_DEBUG: 'PerpsHIP3Debug',
    TPSL: 'PerpsTPSL',
    ADJUST_MARGIN: 'PerpsAdjustMargin',
    SELECT_MODIFY_ACTION: 'PerpsSelectModifyAction',
    SELECT_ADJUST_MARGIN_ACTION: 'PerpsSelectAdjustMarginAction',
    SELECT_ORDER_TYPE: 'PerpsSelectOrderType',
    ORDER_DETAILS: 'PerpsOrderDetailsView',
    PNL_HERO_CARD: 'PerpsPnlHeroCard',
    ACTIVITY: 'PerpsActivity', // Stack-based activity view for proper back navigation
    ORDER_BOOK: 'PerpsOrderBook', // Full order book depth view
    MODALS: {
      ROOT: 'PerpsModals',
      CLOSE_POSITION_MODALS: 'PerpsClosePositionModals',
      QUOTE_EXPIRED_MODAL: 'PerpsQuoteExpiredModal',
      GTM_MODAL: 'PerpsGTMModal',
      CLOSE_ALL_POSITIONS: 'PerpsCloseAllPositions',
      CANCEL_ALL_ORDERS: 'PerpsCancelAllOrders',
      TOOLTIP: 'PerpsTooltip',
      CROSS_MARGIN_WARNING: 'PerpsCrossMarginWarning',
    },
    POSITION_TRANSACTION: 'PerpsPositionTransaction',
    ORDER_TRANSACTION: 'PerpsOrderTransaction',
    FUNDING_TRANSACTION: 'PerpsFundingTransaction',
  },
  PREDICT: {
    ROOT: 'Predict',
    MARKET_LIST: 'PredictMarketList',
    MARKET_DETAILS: 'PredictMarketDetails',
    ACTIVITY_DETAIL: 'PredictActivityDetail',
    MODALS: {
      ROOT: 'PredictModals',
      BUY_PREVIEW: 'PredictBuyPreview',
      SELL_PREVIEW: 'PredictSellPreview',
      UNAVAILABLE: 'PredictUnavailable',
      ADD_FUNDS_SHEET: 'PredictAddFundsSheet',
      GTM_MODAL: 'PredictGTMModal',
    },
  },
  LOCK_SCREEN: 'LockScreen',
  CONFIRMATION_REQUEST_MODAL: 'ConfirmationRequestModal',
  CONFIRMATION_SWITCH_ACCOUNT_TYPE: 'ConfirmationSwitchAccountType',
  CONFIRMATION_PAY_WITH_MODAL: 'ConfirmationPayWithModal',
  CONFIRMATION_PAY_WITH_NETWORK_MODAL: 'ConfirmationPayWithNetworkModal',
  SMART_ACCOUNT_OPT_IN: 'SmartAccountOptIn',
  NOTIFICATIONS: {
    VIEW: 'NotificationsView',
    OPT_IN: 'OptIn',
    OPT_IN_STACK: 'OptInStack',
    DETAILS: 'NotificationsDetails',
  },
  STAKING: {
    STAKE: 'Stake',
    STAKE_CONFIRMATION: 'StakeConfirmation',
    UNSTAKE: 'Unstake',
    UNSTAKE_CONFIRMATION: 'UnstakeConfirmation',
    EARNINGS_HISTORY: 'EarningsHistory',
    CLAIM: 'Claim',
    MODALS: {
      LEARN_MORE: 'LearnMore',
      MAX_INPUT: 'MaxInput',
      GAS_IMPACT: 'GasImpact',
      EARN_TOKEN_LIST: 'EarnTokenList',
    },
  },
  EARN: {
    ROOT: 'EarnScreens',
    LENDING_DEPOSIT_CONFIRMATION: 'EarnLendingDepositConfirmation',
    LENDING_WITHDRAWAL_CONFIRMATION: 'EarnLendingWithdrawalConfirmation',
    MUSD: {
      CONVERSION_EDUCATION: 'EarnMusdConversionEducation',
    },
    MODALS: {
      ROOT: 'EarnModals',
      LENDING_MAX_WITHDRAWAL: 'EarnLendingMaxWithdrawalModal',
      LENDING_LEARN_MORE: 'EarnLendingLearnMoreModal',
    },
  },
  FULL_SCREEN_CONFIRMATIONS: {
    REDESIGNED_CONFIRMATIONS: 'RedesignedConfirmations',
    NO_HEADER: 'NoHeaderConfirmations',
  },
  IDENTITY: {
    TURN_ON_BACKUP_AND_SYNC: 'TurnOnBackupAndSync',
  },
  MULTI_SRP: {
    IMPORT: 'ImportSRPView',
  },
  MULTICHAIN_ACCOUNTS: {
    ACCOUNT_DETAILS: 'MultichainAccountDetails',
    ACCOUNT_GROUP_DETAILS: 'MultichainAccountGroupDetails',
    WALLET_DETAILS: 'MultichainWalletDetails',
    ADDRESS_LIST: 'MultichainAddressList',
    PRIVATE_KEY_LIST: 'MultichainPrivateKeyList',
    ACCOUNT_CELL_ACTIONS: 'MultichainAccountActions',
  },
  ///: BEGIN:ONLY_INCLUDE_IF(external-snaps)
  SNAPS: {
    SNAPS_SETTINGS_LIST: 'SnapsSettingsList',
    SNAP_SETTINGS: 'SnapSettings',
  },
  ///: END:ONLY_INCLUDE_IF
  FOX_LOADER: 'FoxLoader',
  SEEDPHRASE_MODAL: 'SeedphraseModal',
  SET_PASSWORD_FLOW: {
    ROOT: 'SetPasswordFlow',
    MANUAL_BACKUP_STEP_1: 'ManualBackupStep1',
    MANUAL_BACKUP_STEP_2: 'ManualBackupStep2',
    MANUAL_BACKUP_STEP_3: 'ManualBackupStep3',
  },

  EDIT_ACCOUNT_NAME: 'EditAccountName',
  ///: BEGIN:ONLY_INCLUDE_IF(sample-feature)
  SAMPLE_FEATURE: 'SampleFeature',
  ///: END:ONLY_INCLUDE_IF
  CARD: {
    ROOT: 'CardScreens',
    HOME: 'CardHome',
    WELCOME: 'CardWelcome',
    AUTHENTICATION: 'CardAuthentication',
    NOTIFICATION: 'CardNotification',
    SPENDING_LIMIT: 'CardSpendingLimit',
    CHANGE_ASSET: 'CardChangeAsset',
    VERIFYING_REGISTRATION: 'VerifyingRegistration',
    ONBOARDING: {
      ROOT: 'CardOnboarding',
      SIGN_UP: 'CardOnboardingSignUp',
      CONFIRM_EMAIL: 'CardOnboardingConfirmEmail',
      SET_PHONE_NUMBER: 'CardOnboardingSetPhoneNumber',
      CONFIRM_PHONE_NUMBER: 'CardOnboardingConfirmPhoneNumber',
      VERIFY_IDENTITY: 'CardOnboardingVerifyIdentity',
      VALIDATING_KYC: 'CardOnboardingValidatingKYC',
      PERSONAL_DETAILS: 'CardOnboardingPersonalDetails',
      PHYSICAL_ADDRESS: 'CardOnboardingPhysicalAddress',
      MAILING_ADDRESS: 'CardOnboardingMailingAddress',
      COMPLETE: 'CardOnboardingComplete',
      KYC_FAILED: 'CardOnboardingKYCFailed',
      WEBVIEW: 'CardOnboardingWebview',
    },
    MODALS: {
      ID: 'CardModals',
      ADD_FUNDS: 'CardAddFundsModal',
      ASSET_SELECTION: 'CardAssetSelectionModal',
    },
  },
  SEND: {
    RECIPIENT: 'Recipient',
    ASSET: 'Asset',
    AMOUNT: 'Amount',
    DEFAULT: 'Send',
  },
  SDK: {
    RETURN_TO_DAPP_NOTIFICATION: 'ReturnToDappToast',
  },
  FEATURE_FLAG_OVERRIDE: 'FeatureFlagOverride',
};

export default Routes;
