export const EditProfileSelectorsIDs = {
  SAFE_AREA: 'edit-profile-safe-area',
  HEADER: 'edit-profile-header',
  CONTENT: 'edit-profile-content',
  AVATAR: 'edit-profile-avatar',
  ABOUT_SECTION: 'edit-profile-about-section',
  PRIVACY_SECTION: 'edit-profile-privacy-section',
  DISPLAY_NAME_ROW: 'edit-profile-display-name-row',
  HANDLE_ROW: 'edit-profile-handle-row',
  BIO_ROW: 'edit-profile-bio-row',
  SOCIALS_ROW: 'edit-profile-socials-row',
  TRADING_ACTIVITY_ROW: 'edit-profile-trading-activity-row',
  LINKED_SOCIAL_ACCOUNT_ROW: 'edit-profile-linked-social-account-row',
  FIELD_SHEET: 'edit-profile-field-sheet',
  FIELD_SHEET_CLOSE: 'edit-profile-field-sheet-close',
  FIELD_SHEET_INPUT: 'edit-profile-field-sheet-input',
  FIELD_SHEET_SWITCH: 'edit-profile-field-sheet-switch',
  FIELD_SHEET_SAVE: 'edit-profile-field-sheet-save',
  TOGGLE_DESCRIPTION: 'edit-profile-toggle-description',
  TOGGLE_HELPER_TEXT: 'edit-profile-toggle-helper-text',
  TOGGLE_INFO_BUTTON: 'edit-profile-toggle-info-button',
};
