export const SocialBundleV1ViewSelectorsIDs = {
  CONTAINER: 'social-bundle-v1-view-container',
  HEADER: 'social-bundle-v1-view-header',
  HEADER_TITLE: 'social-bundle-v1-view-header-title',
  TITLE: 'social-bundle-v1-view-title',
  TABS: 'social-bundle-v1-view-tabs',
  PAGER: 'social-bundle-v1-view-pager',
  LEADERBOARD_PAGE: 'social-bundle-v1-view-leaderboard-page',
  FEED_PAGE: 'social-bundle-v1-view-feed-page',
  LIVE_TRADES_PAGE: 'social-bundle-v1-view-live-trades-page',
  NOTIFICATIONS_BANNER: 'social-bundle-v1-view-notifications-banner',
  AVATAR_BUTTON: 'social-bundle-v1-view-avatar-button',
  HEART_BUTTON: 'social-bundle-v1-view-heart-button',
  PLUS_BUTTON: 'social-bundle-v1-view-plus-button',
} as const;
