export const ManageProfileSelectorsIDs = {
  SAFE_AREA: 'manage-profile-safe-area',
  HEADER: 'manage-profile-header',
  CONTENT: 'manage-profile-content',
  AVATAR: 'manage-profile-avatar',
  ABOUT_SECTION: 'manage-profile-about-section',
  PRIVACY_SECTION: 'manage-profile-privacy-section',
  DISPLAY_NAME_ROW: 'manage-profile-display-name-row',
  HANDLE_ROW: 'manage-profile-handle-row',
  BIO_ROW: 'manage-profile-bio-row',
  X_ACCOUNT_ROW: 'manage-profile-x-account-row',
  TRADING_ACTIVITY_ROW: 'manage-profile-trading-activity-row',
  LINKED_SOCIAL_ACCOUNT_ROW: 'manage-profile-linked-social-account-row',
  FIELD_SCREEN: 'manage-profile-field-screen',
  FIELD_HEADER: 'manage-profile-field-header',
  FIELD_INPUT: 'manage-profile-field-input',
  BIO_HELPER: 'manage-profile-bio-helper',
  BIO_CHARACTER_COUNT: 'manage-profile-bio-character-count',
  FIELD_SAVE: 'manage-profile-field-save',
};
