/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei/native';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Headlights_1: THREE.Mesh;
    Headlights_2: THREE.Mesh;
    Bottom: THREE.Mesh;
    Rear_bumper_1: THREE.Mesh;
    Rear_bumper_2: THREE.Mesh;
    Rear_bumper_3: THREE.Mesh;
    Rear_bumper_4: THREE.Mesh;
    FL_WHEEL_1: THREE.Mesh;
    FL_WHEEL_2: THREE.Mesh;
    FR_WHEEL_1: THREE.Mesh;
    FR_WHEEL_2: THREE.Mesh;
    RL_WHEEL_1: THREE.Mesh;
    RL_WHEEL_2: THREE.Mesh;
    RR_WHEEL_1: THREE.Mesh;
    RR_WHEEL_2: THREE.Mesh;
    Logos: THREE.Mesh;
    Exhaust: THREE.Mesh;
    Plane013: THREE.Mesh;
  };
  materials: {
    Body_paint: THREE.MeshStandardMaterial;
    ['Emission.001']: THREE.MeshStandardMaterial;
    Miscs: THREE.MeshStandardMaterial;
    Black_matte: THREE.MeshStandardMaterial;
    Glass: THREE.MeshStandardMaterial;
    Rims: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(require('./mazda.glb')) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.002, 0.757, 0]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={100}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Headlights_1.geometry}
          material={materials.Body_paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Headlights_2.geometry}
          material={materials['Emission.001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bottom.geometry}
        material={materials.Miscs}
        position={[-0.002, 0.757, 0]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={100}
      />
      <group
        position={[-0.002, 0.757, 0]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={100}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rear_bumper_1.geometry}
          material={materials.Miscs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rear_bumper_2.geometry}
          material={materials.Body_paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rear_bumper_3.geometry}
          material={materials.Black_matte}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rear_bumper_4.geometry}
          material={materials.Glass}
        />
      </group>
      <group
        position={[0.862, 0.306, 1.221]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={21.229}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FL_WHEEL_1.geometry}
          material={materials.Miscs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FL_WHEEL_2.geometry}
          material={materials.Rims}
        />
      </group>
      <group
        position={[-0.863, 0.306, 1.221]}
        rotation={[Math.PI / 2, -1.571, 0]}
        scale={21.229}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FR_WHEEL_1.geometry}
          material={materials.Miscs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FR_WHEEL_2.geometry}
          material={materials.Rims}
        />
      </group>
      <group
        position={[0.862, 0.306, -1.228]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={21.229}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RL_WHEEL_1.geometry}
          material={materials.Miscs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RL_WHEEL_2.geometry}
          material={materials.Rims}
        />
      </group>
      <group
        position={[-0.863, 0.306, -1.228]}
        rotation={[Math.PI / 2, -1.571, 0]}
        scale={21.229}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RR_WHEEL_1.geometry}
          material={materials.Miscs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RR_WHEEL_2.geometry}
          material={materials.Rims}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Logos.geometry}
        material={materials.Miscs}
        position={[0.577, 0.81, -2.048]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={2.243}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Exhaust.geometry}
        material={materials.Miscs}
        position={[-0.002, 0.757, 0]}
        scale={6.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={materials.Body_paint}
        position={[-0.002, 0.757, 0]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload(require('./mazda.glb'));
