//@ts-expect-error TS issue: Cannot find module '../../node_modules/@metamask/...
// eslint-disable-next-line import/prefer-default-export
export { default as html } from '../../node_modules/@metamask/snaps-execution-environments/dist/browserify/webview/index.html';
