//@ts-expect-error TS issue: Cannot find module '../../node_modules/@metamask/...

export { default as html } from '../../node_modules/@metamask/snaps-execution-environments/dist/browserify/webview/index.html';
