export const WalletRecoveryPrototypeTestIds = {
  CONTAINER: 'wallet-recovery-prototype',
  BACK: 'wallet-recovery-prototype-back',
  REFRESH: 'wallet-recovery-prototype-refresh',
  EXISTING_WALLET: 'wallet-recovery-prototype-existing-wallet',
  EXISTING_SHEET: 'wallet-recovery-prototype-existing-sheet',
  GOOGLE: 'wallet-recovery-prototype-google',
  APPLE: 'wallet-recovery-prototype-apple',
  TELEGRAM: 'wallet-recovery-prototype-telegram',
  IMPORT_SRP: 'wallet-recovery-prototype-import-srp',
  GOOGLE_ACCOUNT: 'wallet-recovery-prototype-google-account',
  PASSKEY_SHEET: 'wallet-recovery-prototype-passkey-sheet',
  USE_PASSKEY: 'wallet-recovery-prototype-use-passkey',
  USE_PASSWORD: 'wallet-recovery-prototype-use-password',
  USE_SMS: 'wallet-recovery-prototype-use-sms',
  USE_AUTHENTICATOR: 'wallet-recovery-prototype-use-authenticator',
  PASSWORD_INPUT: 'wallet-recovery-prototype-password-input',
  CONTINUE: 'wallet-recovery-prototype-continue',
  CODE_INPUT: 'wallet-recovery-prototype-code-input',
  CODE_DIGIT_PREFIX: 'wallet-recovery-prototype-code-digit',
  SRP_INPUT: 'wallet-recovery-prototype-srp-input',
  PASTE_PHRASE: 'wallet-recovery-prototype-paste-phrase',
  CLEAR_PHRASE: 'wallet-recovery-prototype-clear-phrase',
  WALLET_HOME: 'wallet-recovery-prototype-wallet-home',
  MONEY_TAB: 'wallet-recovery-prototype-money-tab',
  MONEY_VERIFIED: 'wallet-recovery-prototype-money-verified',
} as const;
