export enum notificationsAction {
  PERFORM_SIGN_IN = 'notifications/perform_sign_in',
  PERFORM_SIGN_OUT = 'notifications/perform_sign_out',
  ENABLE_PROFILE_SYNCING = 'notifications/enable_profile_syncing',
  DISABLE_PROFILE_SYNCING = 'notifications/disable_profile_syncing',
  ENABLE_PUSH_NOTIFICATIONS = 'notifications/enable_push_notifications',
  DISABLE_PUSH_NOTIFICATIONS = 'notifications/disable_push_notifications',
  CHECK_ACCOUNTS_PRESENCE = 'notifications/check_accounts_presence',
  DELETE_ON_CHAIN_TRIGGERS_BY_ACCOUNT = 'notifications/delete_on_chain_triggers_by_account',
  UPDATE_ON_CHAIN_TRIGGERS_BY_ACCOUNT = 'notifications/update_on_chain_triggers_by_account',
  SET_FEATURE_ANNOUNCEMENTS_ENABLED = 'notifications/set_feature_announcements_enabled',
  SET_SNAP_NOTIFICATIONS_ENABLED = 'notifications/set_snap_notifications_enabled',
  SET_METAMASK_NOTIFICATIONS_FEATURE_SEEN = 'notifications/set_metamask_notifications_feature_seen',
  FETCH_AND_UPDATE_METAMASK_NOTIFICATIONS = 'notifications/fetch_and_update_metamask_notifications',
  MARK_METAMASK_NOTIFICATIONS_AS_READ = 'notifications/mark_metamask_notifications_as_read',
  DELETE_NOTIFICATION_STATUS = 'notifications/delete_notification_status',
  SET_PARTICIPATE_IN_META_METRICS = 'notifications/set_participate_in_meta_metrics',
  UPDATE_TRIGGER_PUSH_NOTIFICATIONS = 'notifications/update_trigger_push_notifications',
  ENABLE_NOTIFICATIONS_SERVICES = 'notifications/enable_notifications_services',
  DISABLE_NOTIFICATIONS_SERVICES = 'notifications/disable_notifications_services',
}

export enum notificationsErrors {
  PERFORM_SIGN_IN = 'Error while trying to sign in',
  PERFORM_SIGN_OUT = 'Error while trying to sign out',
  ENABLE_PROFILE_SYNCING = 'Error while trying to enable profile syncing',
  DISABLE_PROFILE_SYNCING = 'Error while trying to disable profile syncing',
  ENABLE_PUSH_NOTIFICATIONS = 'Error while trying to enable push notifications',
  DISABLE_PUSH_NOTIFICATIONS = 'Error while trying to disable push notifications',
  CHECK_ACCOUNTS_PRESENCE = 'Error while trying to check accounts presence',
  DELETE_ON_CHAIN_TRIGGERS_BY_ACCOUNT = 'Error while trying to delete on chain triggers by account',
  UPDATE_ON_CHAIN_TRIGGERS_BY_ACCOUNT = 'Error while trying to update on chain triggers by account',
  SET_FEATURE_ANNOUNCEMENTS_ENABLED = 'Error while trying to set feature announcements enabled',
  SET_SNAP_NOTIFICATIONS_ENABLED = 'Error while trying to set snap notifications enabled',
  SET_METAMASK_NOTIFICATIONS_FEATURE_SEEN = 'Error while trying to set metamask notifications feature seen',
  FETCH_AND_UPDATE_METAMASK_NOTIFICATIONS = 'Error while trying to fetch and update metamask notifications',
  MARK_METAMASK_NOTIFICATIONS_AS_READ = 'Error while trying to mark metamask notifications as read',
  DELETE_NOTIFICATION_STATUS = 'Error while trying to delete notification',
  SET_PARTICIPATE_IN_META_METRICS = 'Error while trying to set participate in meta metrics',
  UPDATE_TRIGGER_PUSH_NOTIFICATIONS = 'Error while trying to update trigger push notifications',
  ENABLE_NOTIFICATIONS_SERVICES = 'Error while trying to enable notifications services',
  DISABLE_NOTIFICATIONS_SERVICES = 'Error while trying to disable notifications services',
}
