import { stringToBytes } from '@metamask/utils';
import { pbkdf2 } from './pbkdf2';
import { bytesToHex } from '../../util/test/nodeQuickCryptoMock';

// pbkdf2.ts calls `Crypto.subtle.importKey` / `deriveBits` directly, not the
// legacy `NativeModules.Aes.pbkdf2` bridge. Delegate the mock to Node's
// WebCrypto `subtle` implementation so derived keys are byte-for-byte
// comparable against published PBKDF2-HMAC-SHA512 known-answer vectors —
// react-native-quick-crypto is a native module and cannot run inside Jest.
jest.mock('react-native-quick-crypto', () =>
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  require('../../util/test/nodeQuickCryptoMock'),
);

/**
 * PBKDF2-HMAC-SHA512 known-vector test cases.
 *
 * Vectors 1–2 reproduce the widely published PBKDF2-HMAC-SHA512 test
 * vectors (P="password", S="salt", dkLen=64) verified against Node's
 * `crypto.pbkdf2`, matching the "PBKDF2 HMAC-SHA512 Test Vectors" set
 * generated by Andrey Zholos (referenced by RFC 6070-derived test suites) —
 * https://gist.github.com/jakcron/ab05a200e5a6b53c77f28ebfc6342885. Node's
 * WebCrypto `subtle.deriveBits` is backed by the same OpenSSL PBKDF2
 * implementation that react-native-quick-crypto 1.x wraps natively, so this
 * proves byte-exact parity for the algorithm contract our wrapper relies on.
 */
const PBKDF2_VECTORS = [
  {
    label: 'vector 1 — password/salt, c=1, dkLen=64',
    password: 'password',
    salt: 'salt',
    iterations: 1,
    keyLength: 64,
    expected:
      '867f70cf1ade02cff3752599a3a53dc' +
      '4af34c7a669815ae5d513554e1c8cf2' +
      '52c02d470a285a0501bad999bfe943c' +
      '08f050235d7d68b1da55e63f73b60a5' +
      '7fce',
  },
  {
    label: 'vector 2 — password/salt, c=2, dkLen=64',
    password: 'password',
    salt: 'salt',
    iterations: 2,
    keyLength: 64,
    expected:
      'e1d9c16aa681708a45f5c7c4e215ceb' +
      '66e011a2e9f0040713f18aefdb866d5' +
      '3cf76cab2868a39b9f7840edce4fef5' +
      'a82be67335c77a6068e04112754f27c' +
      'cf4e',
  },
] as const;

/**
 * Production-shaped fixtures matching real call sites: iterations=2048 is
 * used by snap/keyring `pbkdf2Sha512` derivation
 * (see app/core/Engine/wallet-init/keyrings.ts), and iterations=5000 is the
 * legacy vault default (see KeyDerivationIteration.Legacy5000 in
 * ./constants.ts). Expected values precomputed with Node's WebCrypto
 * `subtle.deriveBits`, the same OpenSSL PBKDF2 backend used by
 * react-native-quick-crypto 1.x.
 */
const PRODUCTION_VECTORS = [
  {
    label: 'iterations=2048 (snap/keyring pbkdf2Sha512), dkLen=64',
    password: 'mockPassword',
    salt: 'mockSalt-metamask-parity',
    iterations: 2048,
    keyLength: 64,
    expected:
      'bdff44b84f6094c593d18d44be31c51' +
      '473d556b42e0c0d60aa65283f7c7457' +
      'bb0984b71064010c1552583891b86dd' +
      '725ade28e9d09ac8422b551526efc80' +
      '07ed',
  },
  {
    label: 'iterations=5000 (legacy vault default), dkLen=64',
    password: 'mockPassword',
    salt: 'mockSalt-metamask-parity',
    iterations: 5000,
    keyLength: 64,
    expected:
      'd47621b494c25e7c454c32928a10359' +
      '7aeb4593089b5f748edfe065ae80743' +
      '16bccdd793955c1c8b45a1ffbc74a4e' +
      'f78bc1b67d39705de72415d59c586be' +
      '6e03',
  },
] as const;

describe('pbkdf2', () => {
  describe('PBKDF2-HMAC-SHA512 known-vector correctness', () => {
    it.each(PBKDF2_VECTORS)(
      'produces the correct derived key for $label',
      async ({ password, salt, iterations, keyLength, expected }) => {
        const passwordBytes = stringToBytes(password);
        const saltBytes = stringToBytes(salt);

        const result = await pbkdf2(
          passwordBytes,
          saltBytes,
          iterations,
          keyLength,
        );

        expect(bytesToHex(result)).toBe(expected);
      },
    );

    it.each(PRODUCTION_VECTORS)(
      'produces the correct derived key for $label',
      async ({ password, salt, iterations, keyLength, expected }) => {
        const passwordBytes = stringToBytes(password);
        const saltBytes = stringToBytes(salt);

        const result = await pbkdf2(
          passwordBytes,
          saltBytes,
          iterations,
          keyLength,
        );

        expect(bytesToHex(result)).toBe(expected);
      },
    );
  });

  describe('edge cases', () => {
    it('derives a key of the requested byte length for an empty password', async () => {
      const passwordBytes = stringToBytes('');
      const saltBytes = stringToBytes('mockSalt-metamask-parity');

      const result = await pbkdf2(passwordBytes, saltBytes, 2048, 64);

      expect(bytesToHex(result)).toBe(
        '53cd348c010dc354ce76bcdb23e40283' +
          '5ecc0fd13fcebc14ae7b3698c8b55de8' +
          '18700b1f8c2eabcd7a62d1825c60a151' +
          'bed234b2c8d467cf8e28e0546b258942',
      );
    });

    it('derives a key of the requested byte length for an empty salt', async () => {
      const passwordBytes = stringToBytes('mockPassword');
      const saltBytes = stringToBytes('');

      const result = await pbkdf2(passwordBytes, saltBytes, 2048, 64);

      expect(bytesToHex(result)).toBe(
        'd69bf9dc174c5b751c001b642974bda8' +
          '0d2fe93b5bad025b253f03a454f63610' +
          '01b2e2c6659ca6f3d020442f244160f5' +
          'ffc935113cf319a45578d94047fed6d9',
      );
    });

    it('returns different derived keys for different iteration counts', async () => {
      const passwordBytes = stringToBytes('mockPassword');
      const saltBytes = stringToBytes('mockSalt-metamask-parity');

      const low = await pbkdf2(passwordBytes, saltBytes, 2048, 64);
      const high = await pbkdf2(passwordBytes, saltBytes, 5000, 64);

      expect(bytesToHex(low)).not.toBe(bytesToHex(high));
    });
  });
});
