export const ManualBackUpStepsSelectorsIDs = {
  PROTECT_CONTAINER: 'protect-your-account-screen',
  STEP_1_CONTAINER: 'manual_backup_step_1-screen',
  REMIND_ME_LATER_BUTTON: 'remind-me-later-button',
  SUBMIT_BUTTON: 'submit-button',
  VIEW_BUTTON: 'view-button',
  CONTINUE_BUTTON: 'manual-backup-step-continue-button',
  DONE_BUTTON: 'manual-backup-step-done-button',
  CONFIRM_PASSWORD_INPUT: 'private-credential-password-input-field',
  GRID_ITEM: 'grid-item',
  BACK_BUTTON: 'back-button',
  WORD_ITEM: 'manual-backup-step-1-word',
  BLUR_BUTTON: 'blur-button',
  MISSING_WORDS: 'missing-words',
  WORD_ITEM_MISSING: 'word-item-missing',
  WORD_ITEM_USED: 'word-item-used',
  SEEDPHRASE_LINK: 'seedphrase-link',
  GRID_ITEM_EMPTY: 'grid-item-empty',
};
