/* eslint-disable import/prefer-default-export */
import { StyleSheet } from 'react-native';
import { fontStyles, colors as importedColors } from '../../../styles/common';
import Device from '../../../util/device';

// TODO: Replace "any" with type
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const createStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      padding: 16,
      paddingTop: 0,
    },
    step: {
      fontSize: 14,
      color: importedColors.textAlternative,
      ...fontStyles.normal,
      marginBottom: 6,
    },
    mainWrapper: {
      backgroundColor: colors.background.default,
      flex: 1,
      marginTop: 16,
    },
    wrapper: {
      flex: 1,
      height: '100%',
      flexDirection: 'column',
    },
    onBoardingWrapper: {
      paddingHorizontal: 20,
    },
    loader: {
      backgroundColor: colors.background.default,
      flex: 1,
      minHeight: 300,
      justifyContent: 'center',
      alignItems: 'center',
    },
    action: {
      fontSize: 32,
      color: colors.text.default,
      justifyContent: 'flex-start',
      textAlign: 'left',
      ...fontStyles.bold,
      alignSelf: 'flex-start',
    },
    infoWrapper: {
      justifyContent: 'flex-start',
    },
    info: {
      fontSize: 14,
      color: colors.text.default,
      textAlign: 'left',
      ...fontStyles.normal,
      marginVertical: 16,
      // paddingHorizontal: 6,
    },
    seedPhraseConcealerContainer: {
      flex: 1,
      borderRadius: 8,
    },
    seedPhraseConcealer: {
      backgroundColor: colors.overlay.alternative,
      alignItems: 'center',
      borderRadius: 8,
      paddingHorizontal: 24,
      paddingVertical: 45,
    },
    blurView: {
      position: 'absolute',
      top: 0,
      left: 0,
      bottom: 0,
      right: 0,
      borderRadius: 8,
    },
    icon: {
      width: 24,
      height: 24,
      color: colors.overlay.inverse,
      textAlign: 'center',
      marginBottom: 32,
    },
    reveal: {
      fontSize: Device.isMediumDevice() ? 13 : 16,
      ...fontStyles.bold,
      color: colors.overlay.inverse,
      lineHeight: 22,
      marginBottom: 8,
      textAlign: 'center',
    },
    watching: {
      fontSize: Device.isMediumDevice() ? 10 : 12,
      color: colors.overlay.inverse,
      lineHeight: 17,
      marginBottom: 32,
      textAlign: 'center',
    },
    viewButtonContainer: {
      width: 155,
      padding: 12,
    },
    seedPhraseWrapper: {
      backgroundColor: colors.background.default,
      borderRadius: 8,
      flexDirection: 'row',
      borderColor: colors.border.default,
      borderWidth: 1,
      marginBottom: 64,
      minHeight: 275,
    },
    seedPhraseContainerText: {
      fontSize: 14,
      color: importedColors.textAlternative,
      ...fontStyles.normal,
    },
    seedPhraseContainer: {
      paddingTop: 16,
      backgroundColor: colors.background.muted,
      borderRadius: 10,
      height: 'auto',
      flex: 1,
      flexDirection: 'column',
      minHeight: 275,
      marginBottom: 64,
    },
    seedPhraseInnerContainer: {
      paddingBottom: 16,
    },
    seedPhraseContainerCta: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '100%',
      marginTop: 'auto',
      borderTopWidth: 1,
      borderTopColor: colors.background.default,
      paddingHorizontal: 16,
    },
    seedPhraseDefaultInput: {
      fontSize: 14,
      color: importedColors.textAlternative,
      borderWidth: 0,
      outlineWidth: 0,
      ...fontStyles.normal,
      backgroundColor: colors.background.muted,
      paddingHorizontal: 0,
      height: 44,
    },
    seedPhraseInputContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap', // Allows wrapping to new lines
      justifyContent: 'center',
      paddingHorizontal: 16,
    },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      height: 40,
      borderWidth: 1,
      borderColor: colors.border.muted,
      borderRadius: 8,
      paddingHorizontal: 8,
      paddingVertical: 4,
      backgroundColor: colors.background.default,
      flex: 1,
      margin: 5,
      columnGap: 8,
    },
    inputNumber: {
      color: colors.text.muted,
      fontSize: 14,
      ...fontStyles.medium,
    },
    seedPhraseInput: {
      color: colors.text.default,
      fontSize: 14,
      fontWeight: '500',
      justifyContent: 'center',
      alignItems: 'center',
      flex: 1,
    },
    wordColumn: {
      flex: 1,
      alignItems: 'center',
      paddingHorizontal: Device.isMediumDevice() ? 18 : 24,
      paddingVertical: 18,
      justifyContent: 'space-between',
    },
    wordWrapper: {
      flexDirection: 'row',
    },
    word: {
      paddingHorizontal: 8,
      paddingVertical: 6,
      fontSize: 14,
      color: colors.text.default,
      backgroundColor: colors.background.default,
      borderColor: colors.primary.default,
      borderWidth: 1,
      borderRadius: 13,
      textAlign: 'center',
      textAlignVertical: 'center',
      lineHeight: 14,
      flex: 1,
    },
    confirmPasswordWrapper: {
      flex: 1,
      // padding: 30,
      // paddingTop: 0,
    },
    passwordRequiredContent: {
      marginBottom: 20,
    },
    content: {
      alignItems: 'flex-start',
    },
    title: {
      fontSize: 32,
      // marginTop: 20,
      marginBottom: 8,
      color: colors.text.default,
      justifyContent: 'center',
      textAlign: 'left',
      ...fontStyles.normal,
    },
    text: {
      marginBottom: 10,
      marginTop: 20,
      justifyContent: 'center',
    },
    label: {
      fontSize: 16,
      lineHeight: 23,
      color: colors.text.default,
      textAlign: 'left',
      ...fontStyles.normal,
    },
    buttonWrapper: {
      flex: 1,
      marginTop: 0,
      justifyContent: 'flex-end',
    },
    input: {
      borderWidth: 2,
      borderRadius: 5,
      width: '100%',
      borderColor: colors.border.default,
      padding: 10,
      height: 40,
      color: colors.text.default,
    },
    warningMessageText: {
      paddingVertical: 10,
      color: colors.error.default,
      ...fontStyles.normal,
    },
    keyboardAvoidingView: {
      flex: 1,
      flexDirection: 'row',
      alignSelf: 'center',
    },
    passwordContainer: {
      flexDirection: 'column',
      gap: 16,
      marginVertical: 16,
    },
    passwordInputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderWidth: 1,
      borderColor: colors.border.default,
      borderRadius: 8,
      height: 48,
    },
    passwordInputContainerFocused: {
      borderColor: colors.primary.default,
      borderWidth: 2,
    },
    passwordInput: {
      flex: 1,
      fontSize: 16,
      color: colors.text.default,
      fontWeight: '500',
    },
    field: {
      position: 'relative',
      flexDirection: 'column',
      gap: 8,
      width: '100%',
    },
    button: {
      backgroundColor: importedColors.primaryDefault,
    },
  });
