export const ActivityDetailsSelectorsIDs = {
  SCREEN: 'activity-details-screen',
  HEADER: 'activity-details-header',
  BACK_BUTTON: 'activity-details-back-button',
  AMOUNT_HEADER: 'activity-details-amount-header',
  STATUS_ROW: 'activity-details-status-row',
  STATUS_PILL: 'activity-details-status-pill',
  DATE_ROW: 'activity-details-date-row',
  ACCOUNT_ROW: 'activity-details-account-row',
  ADDRESS_ROW: 'activity-details-address-row',
  FROM_ROW: 'activity-details-from-row',
  TO_ROW: 'activity-details-to-row',
  NETWORK_ROW: 'activity-details-network-row',
  TRANSACTION_ID_ROW: 'activity-details-transaction-id-row',
  TRANSACTION_ID_COPY: 'activity-details-transaction-id-copy',
  FEE_ROW: 'activity-details-fee-row',
  TOTAL_ROW: 'activity-details-total-row',
  FOOTER: 'activity-details-footer',
  BLOCK_EXPLORER_BUTTON: 'activity-details-block-explorer-button',
  DO_IT_AGAIN_BUTTON: 'activity-details-do-it-again-button',
  NOT_FOUND: 'activity-details-not-found',
  PENDING_BANNER: 'activity-details-pending-banner',
  PENDING_SPEED_UP_BUTTON: 'activity-details-pending-speed-up-button',
  PENDING_CANCEL_BUTTON: 'activity-details-pending-cancel-button',
  PENDING_QR_SIGN_BUTTON: 'activity-details-pending-qr-sign-button',
  PENDING_QR_CANCEL_BUTTON: 'activity-details-pending-qr-cancel-button',
  PENDING_LEDGER_SIGN_BUTTON: 'activity-details-pending-ledger-sign-button',
} as const;
