export const ActivityDetailsSelectorsIDs = {
  SCREEN: 'activity-details-screen',
  HEADER: 'activity-details-header',
  BACK_BUTTON: 'activity-details-back-button',
  AMOUNT_HEADER: 'activity-details-amount-header',
  STATUS_ROW: 'activity-details-status-row',
  STATUS_PILL: 'activity-details-status-pill',
  DATE_ROW: 'activity-details-date-row',
  ACCOUNT_ROW: 'activity-details-account-row',
  FROM_ROW: 'activity-details-from-row',
  TO_ROW: 'activity-details-to-row',
  NETWORK_ROW: 'activity-details-network-row',
  TRANSACTION_ID_ROW: 'activity-details-transaction-id-row',
  FEE_ROW: 'activity-details-fee-row',
  TOTAL_ROW: 'activity-details-total-row',
  FOOTER: 'activity-details-footer',
  BLOCK_EXPLORER_BUTTON: 'activity-details-block-explorer-button',
  DO_IT_AGAIN_BUTTON: 'activity-details-do-it-again-button',
  NOT_FOUND: 'activity-details-not-found',
} as const;
