import { ACTIONS, PROTOCOLS } from '../../../constants/deeplinks';
import AppConstants from '../../AppConstants';
import { AuthConnection } from '../OAuthInterface';

export const AppRedirectUri = `${PROTOCOLS.HTTPS}://${AppConstants.MM_UNIVERSAL_LINK_HOST}/${ACTIONS.OAUTH_REDIRECT}`;

if (
  !AppConstants.SEEDLESS_ONBOARDING.WEB3AUTH_NETWORK ||
  !AppConstants.SEEDLESS_ONBOARDING.ANDROID_APPLE_CLIENT_ID ||
  !AppConstants.SEEDLESS_ONBOARDING.ANDROID_GOOGLE_CLIENT_ID ||
  !AppConstants.SEEDLESS_ONBOARDING.ANDROID_GOOGLE_SERVER_CLIENT_ID ||
  // !AppConstants.SEEDLESS_ONBOARDING.ANDROID_APPLE_REDIRECT_URI ||
  !AppConstants.SEEDLESS_ONBOARDING.IOS_GOOGLE_CLIENT_ID ||
  !AppConstants.SEEDLESS_ONBOARDING.IOS_GOOGLE_REDIRECT_URI ||
  !AppConstants.SEEDLESS_ONBOARDING.IOS_APPLE_CLIENT_ID ||
  !AppConstants.SEEDLESS_ONBOARDING.ANDROID_APPLE_AUTH_CONNECTION_ID ||
  !AppConstants.SEEDLESS_ONBOARDING.ANDROID_GOOGLE_AUTH_CONNECTION_ID ||
  !AppConstants.SEEDLESS_ONBOARDING.IOS_APPLE_AUTH_CONNECTION_ID ||
  !AppConstants.SEEDLESS_ONBOARDING.IOS_GOOGLE_AUTH_CONNECTION_ID ||
  !AppConstants.SEEDLESS_ONBOARDING.APPLE_GROUPED_AUTH_CONNECTION_ID ||
  !AppConstants.SEEDLESS_ONBOARDING.GOOGLE_GROUPED_AUTH_CONNECTION_ID ||
  !AppConstants.SEEDLESS_ONBOARDING.AUTH_SERVER_URL
) {
  throw new Error(
    `Missing environment variables for OAuthLoginHandlers\n
    WEB3AUTH_NETWORK: ${AppConstants.SEEDLESS_ONBOARDING.WEB3AUTH_NETWORK}\n
    ANDROID_APPLE_CLIENT_ID: ${AppConstants.SEEDLESS_ONBOARDING.ANDROID_APPLE_CLIENT_ID}\n
    ANDROID_GOOGLE_CLIENT_ID: ${AppConstants.SEEDLESS_ONBOARDING.ANDROID_GOOGLE_CLIENT_ID}\n
    ANDROID_GOOGLE_SERVER_CLIENT_ID: ${AppConstants.SEEDLESS_ONBOARDING.ANDROID_GOOGLE_SERVER_CLIENT_ID}\n
    // ANDROID_APPLE_REDIRECT_URI: ${AppConstants.SEEDLESS_ONBOARDING.ANDROID_APPLE_REDIRECT_URI}\n
    IOS_GOOGLE_CLIENT_ID: ${AppConstants.SEEDLESS_ONBOARDING.IOS_GOOGLE_CLIENT_ID}\n
    IOS_GOOGLE_REDIRECT_URI: ${AppConstants.SEEDLESS_ONBOARDING.IOS_GOOGLE_REDIRECT_URI}\n
    IOS_APPLE_CLIENT_ID: ${AppConstants.SEEDLESS_ONBOARDING.IOS_APPLE_CLIENT_ID}\n
    ANDROID_APPLE_AUTH_CONNECTION_ID: ${AppConstants.SEEDLESS_ONBOARDING.ANDROID_APPLE_AUTH_CONNECTION_ID}\n
    ANDROID_GOOGLE_AUTH_CONNECTION_ID: ${AppConstants.SEEDLESS_ONBOARDING.ANDROID_GOOGLE_AUTH_CONNECTION_ID}\n
    IOS_APPLE_AUTH_CONNECTION_ID: ${AppConstants.SEEDLESS_ONBOARDING.IOS_APPLE_AUTH_CONNECTION_ID}\n
    IOS_GOOGLE_AUTH_CONNECTION_ID: ${AppConstants.SEEDLESS_ONBOARDING.IOS_GOOGLE_AUTH_CONNECTION_ID}\n
    APPLE_GROUPED_AUTH_CONNECTION_ID: ${AppConstants.SEEDLESS_ONBOARDING.APPLE_GROUPED_AUTH_CONNECTION_ID}\n
    GOOGLE_GROUPED_AUTH_CONNECTION_ID: ${AppConstants.SEEDLESS_ONBOARDING.GOOGLE_GROUPED_AUTH_CONNECTION_ID}\n
    AUTH_SERVER_URL: ${AppConstants.SEEDLESS_ONBOARDING.AUTH_SERVER_URL}\n
    `,
  );
}

export const web3AuthNetwork =
  AppConstants.SEEDLESS_ONBOARDING.WEB3AUTH_NETWORK;
export const AuthServerUrl = AppConstants.SEEDLESS_ONBOARDING.AUTH_SERVER_URL;

export const IosGID = AppConstants.SEEDLESS_ONBOARDING.IOS_GOOGLE_CLIENT_ID;
export const IosGoogleRedirectUri =
  AppConstants.SEEDLESS_ONBOARDING.IOS_GOOGLE_REDIRECT_URI;
export const IosAppleClientId =
  AppConstants.SEEDLESS_ONBOARDING.IOS_APPLE_CLIENT_ID;

export const AndroidGoogleWebGID =
  AppConstants.SEEDLESS_ONBOARDING.ANDROID_GOOGLE_SERVER_CLIENT_ID;
export const AppleWebClientId =
  AppConstants.SEEDLESS_ONBOARDING.ANDROID_APPLE_CLIENT_ID;

export const AppleServerRedirectUri = `${AuthServerUrl}/api/v1/oauth/callback`;

export enum SupportedPlatforms {
  Android = 'android',
  IOS = 'ios',
}

export const AuthConnectionConfig: Record<SupportedPlatforms, Record<AuthConnection, {
  authConnectionId: string;
  groupedAuthConnectionId?: string;
}>> = {
  [SupportedPlatforms.Android]: {
    [AuthConnection.Google]: {
      authConnectionId: AppConstants.SEEDLESS_ONBOARDING.ANDROID_GOOGLE_AUTH_CONNECTION_ID,
      groupedAuthConnectionId: AppConstants.SEEDLESS_ONBOARDING.GOOGLE_GROUPED_AUTH_CONNECTION_ID,
    },
    [AuthConnection.Apple]: {
      authConnectionId: AppConstants.SEEDLESS_ONBOARDING.ANDROID_APPLE_AUTH_CONNECTION_ID,
      groupedAuthConnectionId: AppConstants.SEEDLESS_ONBOARDING.APPLE_GROUPED_AUTH_CONNECTION_ID,
    },
  },
  [SupportedPlatforms.IOS]: {
    [AuthConnection.Google]: {
      authConnectionId: AppConstants.SEEDLESS_ONBOARDING.IOS_GOOGLE_AUTH_CONNECTION_ID,
      groupedAuthConnectionId: AppConstants.SEEDLESS_ONBOARDING.GOOGLE_GROUPED_AUTH_CONNECTION_ID,
    },
    [AuthConnection.Apple]: {
      authConnectionId: AppConstants.SEEDLESS_ONBOARDING.IOS_APPLE_AUTH_CONNECTION_ID,
      groupedAuthConnectionId: AppConstants.SEEDLESS_ONBOARDING.APPLE_GROUPED_AUTH_CONNECTION_ID,
    },
  },
};
