export const TraderStatsSheetSelectorsIDs = {
  SHEET: 'trader-stats-sheet',
  CLOSE_BUTTON: 'trader-stats-sheet-close',
  HEADER_HANDLE: 'trader-stats-sheet-header-handle',
  HEADER_AVATAR: 'trader-stats-sheet-header-avatar',
  HERO_PNL: 'trader-stats-sheet-hero-pnl',
  ROW_PNL: 'trader-stats-sheet-row-pnl',
  ROW_WIN_RATE: 'trader-stats-sheet-row-win-rate',
  ROW_VOLUME: 'trader-stats-sheet-row-volume',
  ROW_TRADE_COUNT: 'trader-stats-sheet-row-trade-count',
  ROW_HOLD_TIME: 'trader-stats-sheet-row-hold-time',
  SECTION_BREAKDOWN: 'trader-stats-sheet-section-breakdown',
  ROW_PROFILE_AGE: 'trader-stats-sheet-row-profile-age',
  ROW_POSITIONS: 'trader-stats-sheet-row-positions',
  ROW_AVG_POSITION_VALUE: 'trader-stats-sheet-row-avg-position-value',
  ROW_AVG_30D_SAMPLE: 'trader-stats-sheet-row-avg-30d-sample',
  SECTION_PERFORMANCE: 'trader-stats-sheet-section-performance',
  ROW_FOLLOWERS: 'trader-stats-sheet-row-followers',
  ROW_TRADES_COPIED: 'trader-stats-sheet-row-trades-copied',
  ROW_COPY_SUCCESS_RATE: 'trader-stats-sheet-row-copy-success-rate',
} as const;
