/**
 * Test IDs for ExploreSearchScreen and its child ExploreSearchResultsV2.
 *
 * Pill IDs are generated by PillRow using the pattern:
 * `${testIdPrefix}-pill-${pill.key}` where testIdPrefix="explore-search".
 * Feed keys map directly to SearchFeedId values.
 */
export const ExploreSearchScreenSelectorsIDs = {
  /** FlashList in ExploreSearchResultsV2 (testID set directly on the component) */
  SEARCH_RESULTS_LIST: 'trending-search-results-list',
  /** Horizontal ScrollView wrapping all pills */
  PILL_ROW: 'explore-search-pills',
  /** "All" pill */
  PILL_ALL: 'explore-search-pill-all',
  /** Crypto / tokens feed pill */
  PILL_CRYPTOS: 'explore-search-pill-tokens',
  /** Perps feed pill */
  PILL_PERPS: 'explore-search-pill-perps',
  /** Stocks feed pill */
  PILL_STOCKS: 'explore-search-pill-stocks',
  /** Predictions feed pill */
  PILL_PREDICTIONS: 'explore-search-pill-predictions',
  /** Sites feed pill */
  PILL_SITES: 'explore-search-pill-sites',
} as const;

export type ExploreSearchScreenSelectorsIDsType =
  typeof ExploreSearchScreenSelectorsIDs;
