name: 'Bump build version'
description: 'Bump build version number in project files and commit the changes'
inputs:
  build-version:
    description: 'Build version number to set'
    required: true
  ref:
    description: 'Git ref/branch to push to (e.g., release/1.2.3)'
    required: true
outputs:
  commit-hash:
    description: "Commit hash with build version bumped"
    value: ${{ steps.bump-build-version.outputs.commit-hash }}

runs:
  using: 'composite'
  steps:
    - name: Bump build version
      id: bump-build-version
      shell: bash
      env:
        BUILD_NUMBER: ${{ inputs.build-version }}
        GH_REF_NAME: ${{ inputs.ref }}
      run: |
        ./scripts/set-build-version.sh $BUILD_NUMBER
        git diff
        git config user.name metamaskbot
        git config user.email metamaskbot@users.noreply.github.com
        git add bitrise.yml
        git add package.json
        git add ios/MetaMask.xcodeproj/project.pbxproj
        git add android/app/build.gradle
        git commit -m "[skip ci] Bump version number to ${BUILD_NUMBER}"
        git push origin HEAD:$GH_REF_NAME --force-with-lease
        echo "commit-hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
