name: 'Fingerprint Build Check'
description: 'Check fingerprint and decide between full build, repack, or skip (Cross-platform)'
inputs:
  platform:
    description: 'Platform to check (android or ios)'
    required: true
  build_action:
    description: 'Build action from needs workflow (full, check_fingerprint, skip)'
    required: true
    default: 'full'
  artifact_path:
    description: 'Path to the APK or APP file to check for reuse'
    required: false
    default: ''
  pr_number:
    description: 'Pull request number for caching'
    required: false
    default: ''

outputs:
  build_method:
    description: 'Determined build method: full, repack, or skip'
    value: ${{ steps.decide.outputs.build_method }}
  can_repack:
    description: 'Whether repackaging is possible'
    value: ${{ steps.decide.outputs.can_repack }}
  cache_hit:
    description: 'Whether a cache hit occurred'
    value: ${{ steps.decide.outputs.cache_hit }}

runs:
  using: 'composite'
  steps:
    - name: Restore fingerprint cache
      uses: actions/cache@v4
      with:
        path: .app-native-fingerprint
        key: fingerprint-${{ inputs.platform }}-${{ inputs.pr_number || 'main' }}-${{ github.sha }}
        restore-keys: |
          fingerprint-${{ inputs.platform }}-${{ inputs.pr_number || 'main' }}-

    - name: Restore previous build artifacts
      if: ${{ inputs.build_action == 'check_fingerprint' && inputs.artifact_path != '' }}
      uses: actions/cache@v4
      with:
        path: ${{ inputs.artifact_path }}
        key: ${{ inputs.platform }}-artifacts-${{ inputs.pr_number || 'main' }}-${{ hashFiles('.app-native-fingerprint') }}
        restore-keys: |
          ${{ inputs.platform }}-artifacts-${{ inputs.pr_number || 'main' }}-

    - name: Check fingerprint and decide build method
      id: decide
      shell: bash
      run: |
        echo "🔍 Fingerprint Build Check for ${{ inputs.platform }}"
        echo "============================================"
        echo "📊 Input Parameters:"
        echo "  - Build action: ${{ inputs.build_action }}"
        echo "  - Platform: ${{ inputs.platform }}"
        echo "  - PR Number: ${{ inputs.pr_number || 'main' }}"
        echo "  - Artifact Path: ${{ inputs.artifact_path }}"
        echo ""
        
        # Initialize variables to track decisions
        BUILD_METHOD=""
        CAN_REPACK=""
        CACHE_HIT=""
        
        if [[ "${{ inputs.build_action }}" == "skip" ]]; then
          echo "⏭️ Build action is skip - no build required"
          BUILD_METHOD="skip"
          CAN_REPACK="false"
          CACHE_HIT="false"
          echo "build_method=$BUILD_METHOD" >> "$GITHUB_OUTPUT"
          echo "can_repack=$CAN_REPACK" >> "$GITHUB_OUTPUT"
          echo "cache_hit=$CACHE_HIT" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        
        if [[ "${{ inputs.build_action }}" == "full" ]]; then
          echo "🏗️ Build action is full - native code likely changed"
          BUILD_METHOD="full"
          CAN_REPACK="false"
          CACHE_HIT="false"
          echo "build_method=$BUILD_METHOD" >> "$GITHUB_OUTPUT"
          echo "can_repack=$CAN_REPACK" >> "$GITHUB_OUTPUT"
          echo "cache_hit=$CACHE_HIT" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        
        if [[ "${{ inputs.build_action }}" == "check_fingerprint" ]]; then
          echo "🔍 Checking fingerprint for potential reuse..."
          echo ""
          
          # Display current and saved fingerprints
          if [ -f ".app-native-fingerprint" ]; then
            SAVED_FP=$(cat .app-native-fingerprint)
            echo "📌 Saved fingerprint: $SAVED_FP"
          else
            echo "❌ No saved fingerprint found"
            BUILD_METHOD="full"
            CAN_REPACK="false"
            CACHE_HIT="false"
            echo "build_method=$BUILD_METHOD" >> "$GITHUB_OUTPUT"
            echo "can_repack=$CAN_REPACK" >> "$GITHUB_OUTPUT"
            echo "cache_hit=$CACHE_HIT" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          
          # Generate current fingerprint for comparison
          CURRENT_FP=$(yarn -s fingerprint:generate 2>/dev/null || echo "")
          if [ -z "$CURRENT_FP" ]; then
            echo "❌ Failed to generate current fingerprint"
            BUILD_METHOD="full"
            CAN_REPACK="false"
            CACHE_HIT="false"
            echo "build_method=$BUILD_METHOD" >> "$GITHUB_OUTPUT"
            echo "can_repack=$CAN_REPACK" >> "$GITHUB_OUTPUT"
            echo "cache_hit=$CACHE_HIT" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          echo "🔍 Current fingerprint: $CURRENT_FP"
          echo ""
          
          # Check if fingerprint matches
          if yarn fingerprint:check; then
            echo "✅ Fingerprints match! Native code unchanged."
            echo "📦 Checking for existing artifacts..."
            
            # Check if we have cached artifacts
            if [[ "${{ inputs.artifact_path }}" != "" ]]; then
              # Check if artifact exists (file for Android, directory for iOS)
              if [[ "${{ inputs.platform }}" == "android" && -f "${{ inputs.artifact_path }}" ]] || [[ "${{ inputs.platform }}" == "ios" && -d "${{ inputs.artifact_path }}" ]]; then
                # Validate the artifact
                if [[ "${{ inputs.platform }}" == "android" ]]; then
                  ARTIFACT_SIZE=$(stat -f%z "${{ inputs.artifact_path }}" 2>/dev/null || stat -c%s "${{ inputs.artifact_path }}" 2>/dev/null || echo "0")
                  MIN_SIZE=1000000  # APK should be at least 1MB
                  ARTIFACT_TYPE="APK"
                else
                  ARTIFACT_SIZE=$(du -sb "${{ inputs.artifact_path }}" 2>/dev/null | cut -f1 || echo "0")
                  MIN_SIZE=10000000  # .app should be at least 10MB
                  ARTIFACT_TYPE=".app bundle"
                fi

                if [[ $ARTIFACT_SIZE -gt $MIN_SIZE ]]; then
                  echo "✅ Found valid cached $ARTIFACT_TYPE (size: $ARTIFACT_SIZE bytes)"
                  echo "🎯 Decision: REPACK - Using cached build with updated JS bundle"
                  BUILD_METHOD="repack"
                  CAN_REPACK="true"
                  CACHE_HIT="true"
                  echo "build_method=$BUILD_METHOD" >> "$GITHUB_OUTPUT"
                  echo "can_repack=$CAN_REPACK" >> "$GITHUB_OUTPUT"
                  echo "cache_hit=$CACHE_HIT" >> "$GITHUB_OUTPUT"
                else
                  echo "⚠️ Cached $ARTIFACT_TYPE appears invalid (size: $ARTIFACT_SIZE bytes)"
                  echo "🎯 Decision: FULL BUILD - Invalid cached artifacts"
                  BUILD_METHOD="full"
                  CAN_REPACK="false"
                  CACHE_HIT="false"
                  echo "build_method=$BUILD_METHOD" >> "$GITHUB_OUTPUT"
                  echo "can_repack=$CAN_REPACK" >> "$GITHUB_OUTPUT"
                  echo "cache_hit=$CACHE_HIT" >> "$GITHUB_OUTPUT"
                fi
              else
                echo "🔍 Cached artifact not found or invalid at: ${{ inputs.artifact_path }}"
                echo "🎯 Decision: FULL BUILD - No cached artifacts available"
                BUILD_METHOD="full"
                CAN_REPACK="false"
                CACHE_HIT="false"
                echo "build_method=$BUILD_METHOD" >> "$GITHUB_OUTPUT"
                echo "can_repack=$CAN_REPACK" >> "$GITHUB_OUTPUT"
                echo "cache_hit=$CACHE_HIT" >> "$GITHUB_OUTPUT"
              fi
          else
            echo "🔄 Fingerprints differ - native code has changed"
            echo "  Saved:   $SAVED_FP"
            echo "  Current: $CURRENT_FP"
            echo "🎯 Decision: FULL BUILD - Native code changed"
            BUILD_METHOD="full"
            CAN_REPACK="false"
            CACHE_HIT="false"
            echo "build_method=$BUILD_METHOD" >> "$GITHUB_OUTPUT"
            echo "can_repack=$CAN_REPACK" >> "$GITHUB_OUTPUT"
            echo "cache_hit=$CACHE_HIT" >> "$GITHUB_OUTPUT"
          fi
        else
          echo "❓ Unknown build action: ${{ inputs.build_action }}"
          echo "🎯 Decision: FULL BUILD - Unknown action, defaulting to safe option"
          BUILD_METHOD="full"
          CAN_REPACK="false"
          CACHE_HIT="false"
          echo "build_method=$BUILD_METHOD" >> "$GITHUB_OUTPUT"
          echo "can_repack=$CAN_REPACK" >> "$GITHUB_OUTPUT"
          echo "cache_hit=$CACHE_HIT" >> "$GITHUB_OUTPUT"
        fi
        
        echo ""
        echo "============================================"
        echo "📊 Final Decision Summary:"
        echo "  - Build Method: $BUILD_METHOD"
        echo "  - Can Repack: $CAN_REPACK"
        echo "  - Cache Hit: $CACHE_HIT"
        echo "============================================"
