name: 'Fingerprint Build Check'
description: 'Check fingerprint and decide between full build, repack, or skip (Cross-platform)'
inputs:
  platform:
    description: 'Platform to check (android or ios)'
    required: true
  build_action:
    description: 'Build action from needs workflow (full, check_fingerprint, skip)'
    required: true
    default: 'full'
  artifact_path:
    description: 'Path to the APK or APP file to check for reuse'
    required: false
    default: ''
  pr_number:
    description: 'Pull request number for caching'
    required: false
    default: ''

outputs:
  build_method:
    description: 'Determined build method: full, repack, or skip'
    value: ${{ steps.decide.outputs.build_method }}
  can_repack:
    description: 'Whether repackaging is possible'
    value: ${{ steps.decide.outputs.can_repack }}
  cache_hit:
    description: 'Whether a cache hit occurred'
    value: ${{ steps.decide.outputs.cache_hit }}

runs:
  using: 'composite'
  steps:
    - name: Restore fingerprint cache
      uses: actions/cache@v4
      with:
        path: .app-native-fingerprint
        key: fingerprint-${{ inputs.platform }}-${{ inputs.pr_number || 'main' }}-${{ github.sha }}
        restore-keys: |
          fingerprint-${{ inputs.platform }}-${{ inputs.pr_number || 'main' }}-

    - name: Restore previous build artifacts
      if: ${{ inputs.build_action == 'check_fingerprint' && inputs.artifact_path != '' }}
      uses: actions/cache@v4
      with:
        path: ${{ inputs.artifact_path }}
        key: ${{ inputs.platform }}-artifacts-${{ inputs.pr_number || 'main' }}-${{ hashFiles('.app-native-fingerprint') }}
        restore-keys: |
          ${{ inputs.platform }}-artifacts-${{ inputs.pr_number || 'main' }}-

    - name: Check fingerprint and decide build method
      id: decide
      shell: bash
      run: |
        ./scripts/fingerprint-build-check.sh \
          "${{ inputs.platform }}" \
          "${{ inputs.build_action }}" \
          "${{ inputs.artifact_path }}" \
          "${{ inputs.pr_number }}"
