import Routes from '../../../../constants/navigation/Routes';

export const RAMP_SCREEN_CONTENT_STATE = {
  POPULATED: 'populated',
  EMPTY: 'empty',
  ERROR: 'error',
} as const;

export type RampScreenContentState =
  (typeof RAMP_SCREEN_CONTENT_STATE)[keyof typeof RAMP_SCREEN_CONTENT_STATE];

export const RAMP_V2_SCREEN_ID = {
  TOKEN_SELECTION: 'token_selection',
  AMOUNT_INPUT: 'amount_input',
  ENTER_EMAIL: 'enter_email',
  OTP_CODE: 'otp_code',
  BASIC_INFO: 'basic_info',
  ENTER_ADDRESS: 'enter_address',
  VERIFY_IDENTITY: 'verify_identity',
  BANK_DETAILS: 'bank_details',
  ORDER_PROCESSING: 'order_processing',
  KYC_PROCESSING: 'kyc_processing',
  ADDITIONAL_VERIFICATION: 'additional_verification',
  CHECKOUT: 'checkout',
  KYC_WEBVIEW: 'kyc_webview',
  ORDER_DETAILS: 'order_details',
  HEADLESS_HOST: 'headless_host',
  UNSUPPORTED_TOKEN_MODAL: 'unsupported_token_modal',
  SETTINGS_MODAL: 'settings_modal',
  PAYMENT_SELECTION_MODAL: 'payment_selection_modal',
  TOKEN_NOT_AVAILABLE_MODAL: 'token_not_available_modal',
  PROVIDER_SELECTION_MODAL: 'provider_selection_modal',
  ERROR_DETAILS_MODAL: 'error_details_modal',
  PROCESSING_INFO_MODAL: 'processing_info_modal',
  SSN_INFO_MODAL: 'ssn_info_modal',
  PHONE_COUNTRY_SELECTOR_MODAL: 'phone_country_selector_modal',
  STATE_SELECTOR_MODAL: 'state_selector_modal',
  UNSUPPORTED_STATE_MODAL: 'unsupported_state_modal',
} as const;

export type RampV2ScreenId =
  (typeof RAMP_V2_SCREEN_ID)[keyof typeof RAMP_V2_SCREEN_ID];

export const RAMP_V2_MAIN_ROUTE_SCREEN_IDS = {
  [Routes.RAMP.TOKEN_SELECTION]: RAMP_V2_SCREEN_ID.TOKEN_SELECTION,
  [Routes.RAMP.AMOUNT_INPUT]: RAMP_V2_SCREEN_ID.AMOUNT_INPUT,
  [Routes.RAMP.ENTER_EMAIL]: RAMP_V2_SCREEN_ID.ENTER_EMAIL,
  [Routes.RAMP.OTP_CODE]: RAMP_V2_SCREEN_ID.OTP_CODE,
  [Routes.RAMP.BASIC_INFO]: RAMP_V2_SCREEN_ID.BASIC_INFO,
  [Routes.RAMP.ENTER_ADDRESS]: RAMP_V2_SCREEN_ID.ENTER_ADDRESS,
  [Routes.RAMP.VERIFY_IDENTITY]: RAMP_V2_SCREEN_ID.VERIFY_IDENTITY,
  [Routes.RAMP.BANK_DETAILS]: RAMP_V2_SCREEN_ID.BANK_DETAILS,
  [Routes.RAMP.ORDER_PROCESSING]: RAMP_V2_SCREEN_ID.ORDER_PROCESSING,
  [Routes.RAMP.KYC_PROCESSING]: RAMP_V2_SCREEN_ID.KYC_PROCESSING,
  [Routes.RAMP.ADDITIONAL_VERIFICATION]:
    RAMP_V2_SCREEN_ID.ADDITIONAL_VERIFICATION,
  [Routes.RAMP.CHECKOUT]: RAMP_V2_SCREEN_ID.CHECKOUT,
  [Routes.RAMP.KYC_WEBVIEW]: RAMP_V2_SCREEN_ID.KYC_WEBVIEW,
  [Routes.RAMP.RAMPS_ORDER_DETAILS]: RAMP_V2_SCREEN_ID.ORDER_DETAILS,
  [Routes.RAMP.HEADLESS_HOST]: RAMP_V2_SCREEN_ID.HEADLESS_HOST,
} as const;

export const RAMP_V2_MODAL_ROUTE_SCREEN_IDS = {
  [Routes.RAMP.MODALS.UNSUPPORTED_TOKEN]:
    RAMP_V2_SCREEN_ID.UNSUPPORTED_TOKEN_MODAL,
  [Routes.RAMP.MODALS.BUILD_QUOTE_SETTINGS]: RAMP_V2_SCREEN_ID.SETTINGS_MODAL,
  [Routes.RAMP.MODALS.PAYMENT_SELECTION]:
    RAMP_V2_SCREEN_ID.PAYMENT_SELECTION_MODAL,
  [Routes.RAMP.MODALS.TOKEN_NOT_AVAILABLE]:
    RAMP_V2_SCREEN_ID.TOKEN_NOT_AVAILABLE_MODAL,
  [Routes.RAMP.MODALS.PROVIDER_SELECTION]:
    RAMP_V2_SCREEN_ID.PROVIDER_SELECTION_MODAL,
  [Routes.RAMP.MODALS.ERROR_DETAILS]: RAMP_V2_SCREEN_ID.ERROR_DETAILS_MODAL,
  [Routes.RAMP.MODALS.PROCESSING_INFO]: RAMP_V2_SCREEN_ID.PROCESSING_INFO_MODAL,
  [Routes.RAMP.MODALS.SSN_INFO]: RAMP_V2_SCREEN_ID.SSN_INFO_MODAL,
  [Routes.RAMP.MODALS.PHONE_COUNTRY_SELECTOR]:
    RAMP_V2_SCREEN_ID.PHONE_COUNTRY_SELECTOR_MODAL,
  [Routes.RAMP.MODALS.STATE_SELECTOR]: RAMP_V2_SCREEN_ID.STATE_SELECTOR_MODAL,
  [Routes.RAMP.MODALS.UNSUPPORTED_STATE]:
    RAMP_V2_SCREEN_ID.UNSUPPORTED_STATE_MODAL,
} as const;

/** Shared modal routes intentionally owned by the legacy Aggregator stack. */
export const RAMP_AGGREGATOR_ONLY_MODAL_ROUTES = new Set<string>([
  Routes.RAMP.MODALS.TOKEN_SELECTOR,
  Routes.RAMP.MODALS.FIAT_SELECTOR,
  Routes.RAMP.MODALS.INCOMPATIBLE_ACCOUNT_TOKEN,
  Routes.RAMP.MODALS.REGION_SELECTOR,
  Routes.RAMP.MODALS.UNSUPPORTED_REGION,
  Routes.RAMP.MODALS.PAYMENT_METHOD_SELECTOR,
  Routes.RAMP.MODALS.SETTINGS,
]);
