import {
  generateOpt,
  EVENT_NAME as METRICS_EVENT_NAME,
} from '../../MetaMetrics.events';

enum EVENT_NAME {
  ADVANCED_DETAILS_CLICKED = 'Confirmation Advanced Details Clicked',
  BLOCKAID_ALERT_LINK_CLICKED = 'Blockaid Alert Link Clicked',
  TOOLTIP_CLICKED = 'Confirmation Tooltip Clicked',
  SCREEN_VIEWED = 'Confirmation Screen Viewed',
  SECURITY_CHECK_STARTED = 'Security Check Started',
  SECURITY_CHECK_QUESTION_ANSWERED = 'Security Check Question Answered',
  SECURITY_CHECK_COMPLETED_CLEAN = 'Security Check Completed Clean',
  SECURITY_CHECK_DISMISSED = 'Security Check Dismissed',
  SCAM_WARNING_SHOWN = 'Scam Warning Shown',
  SCAM_WARNING_STOPPED = 'Scam Warning Stopped',
  SCAM_WARNING_CONTACT_SUPPORT = 'Scam Warning Contact Support',
  SCAM_WARNING_PROCEEDED = 'Scam Warning Proceeded',
}

enum TRANSACTION_EVENT_NAMES {
  TRANSACTION_ADDED = 'Transaction Added',
  TRANSACTION_APPROVED = 'Transaction Approved',
  // Finalized is the unified event that is triggered
  // when the transaction is confirmed, dropped or failed
  TRANSACTION_FINALIZED = 'Transaction Finalized',
  TRANSACTION_REJECTED = 'Transaction Rejected',
  TRANSACTION_SUBMITTED = 'Transaction Submitted',
}

// This function helps prevent repeat of type conversions
const createEvent = (name: EVENT_NAME | TRANSACTION_EVENT_NAMES) =>
  generateOpt(name as unknown as METRICS_EVENT_NAME);

export const CONFIRMATION_EVENTS = {
  ADVANCED_DETAILS_CLICKED: createEvent(EVENT_NAME.ADVANCED_DETAILS_CLICKED),
  BLOCKAID_ALERT_LINK_CLICKED: createEvent(
    EVENT_NAME.BLOCKAID_ALERT_LINK_CLICKED,
  ),
  SCREEN_VIEWED: createEvent(EVENT_NAME.SCREEN_VIEWED),
  TOOLTIP_CLICKED: createEvent(EVENT_NAME.TOOLTIP_CLICKED),
  SECURITY_CHECK_STARTED: createEvent(EVENT_NAME.SECURITY_CHECK_STARTED),
  SECURITY_CHECK_QUESTION_ANSWERED: createEvent(
    EVENT_NAME.SECURITY_CHECK_QUESTION_ANSWERED,
  ),
  SECURITY_CHECK_COMPLETED_CLEAN: createEvent(
    EVENT_NAME.SECURITY_CHECK_COMPLETED_CLEAN,
  ),
  SECURITY_CHECK_DISMISSED: createEvent(EVENT_NAME.SECURITY_CHECK_DISMISSED),
  SCAM_WARNING_SHOWN: createEvent(EVENT_NAME.SCAM_WARNING_SHOWN),
  SCAM_WARNING_STOPPED: createEvent(EVENT_NAME.SCAM_WARNING_STOPPED),
  SCAM_WARNING_CONTACT_SUPPORT: createEvent(
    EVENT_NAME.SCAM_WARNING_CONTACT_SUPPORT,
  ),
  SCAM_WARNING_PROCEEDED: createEvent(EVENT_NAME.SCAM_WARNING_PROCEEDED),
};

export const TRANSACTION_EVENTS = {
  TRANSACTION_ADDED: createEvent(TRANSACTION_EVENT_NAMES.TRANSACTION_ADDED),
  TRANSACTION_APPROVED: createEvent(
    TRANSACTION_EVENT_NAMES.TRANSACTION_APPROVED,
  ),
  TRANSACTION_FINALIZED: createEvent(
    TRANSACTION_EVENT_NAMES.TRANSACTION_FINALIZED,
  ),
  TRANSACTION_REJECTED: createEvent(
    TRANSACTION_EVENT_NAMES.TRANSACTION_REJECTED,
  ),
  TRANSACTION_SUBMITTED: createEvent(
    TRANSACTION_EVENT_NAMES.TRANSACTION_SUBMITTED,
  ),
};
