name: Add release label to PR and linked issues when PR gets merged

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  add-release-label:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
            fetch-depth: 0 # This is needed to checkout all branches

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4.4.0
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn --immutable
        working-directory: '.github/scripts'

      - name: Get the next semver version
        id: get-next-semver-version
        env:
          FORCE_NEXT_SEMVER_VERSION: ${{ vars.FORCE_NEXT_SEMVER_VERSION }}
        run: ./get-next-semver-version.sh "$FORCE_NEXT_SEMVER_VERSION"
        working-directory: '.github/scripts'

      - name: Add release label to PR and linked issues
        id: add-release-label-to-pr-and-linked-issues
        env:
          RELEASE_LABEL_TOKEN: ${{ secrets.RELEASE_LABEL_TOKEN }}
          NEXT_SEMVER_VERSION: ${{ env.NEXT_SEMVER_VERSION }}
        run: yarn run add-release-label-to-pr-and-linked-issues
        working-directory: '.github/scripts'
