name: Automated RCA

on:
  issues:
    types: [closed]

permissions:
  issues: write
  contents: read

jobs:
  automated-rca:
    uses: MetaMask/github-tools/.github/workflows/post-gh-rca.yml@727c028d5fdb2b86f6b1cf205b97fa8e79f7de61
    with:
      google-form-base-url: 'https://docs.google.com/forms/d/e/1FAIpQLSdnPbJISzFlR_aQD2uRpnMKSoGAopuTd_yeZK7J4Q5GzgbsOA/viewform'
      repo-owner: ${{ github.repository_owner }}
      repo-name: ${{ github.event.repository.name }}
      issue-number: ${{ github.event.issue.number }}
      issue-labels: '["Sev0-urgent", "Sev1-high"]'
      entry-team: 'entry.1698032149'
      entry-regression: 'entry.1228565618'
      entry-issue: 'entry.340898780'
