name: Check issue template and add labels

on:
  issues:
    types:
      - opened
      - edited

jobs:
  add-regression-prod-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            fetch-depth: 1 # This retrieves only the latest commit.

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Check issue template and add labels
        id: check-issue-template-and-add-labels
        env:
          LABEL_TOKEN: ${{ secrets.LABEL_TOKEN }}
        run: npm run check-issue-template-and-add-labels
