name: 'Check PR Max Lines'

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read
  pull-requests: write # Required for the called workflow to manage labels

jobs:
  check-pr-max-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR lines changed
        uses: MetaMask/github-tools/.github/actions/pr-line-check@7e0d74bc7b79ce9601e52f58d5e4d36c19591df9 # v1.19.0
        with:
          max-lines: '1000'
          ignore-patterns: '(\.lock|\.snap|\.md|\.svg|\.yaml)'
