name: Check Attributions

on:
  push:
    branches: release/*

jobs:
  check-attributions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install dependencies from cache
        run: yarn --immutable
      - name: Check attributions changes
        run: yarn test:attribution-check
