name: "Check PR has required labels"
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

jobs:
  check-pr-labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            fetch-depth: 1 # This retrieves only the latest commit.

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn --immutable
        working-directory: '.github/scripts'

      - name: Check PR has required labels
        id: check-pr-has-required-labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run check-pr-has-required-labels
        working-directory: '.github/scripts'
