name: Check Bitrise E2E Status

on:
  issue_comment:
    types: [edited, deleted]
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

env:
  E2E_LABEL: 'Run Smoke E2E'
  E2E_PIPELINE: 'pr_smoke_e2e_pipeline'
  WORKFLOW_NAME: 'check-bitrise-e2e-status'

jobs:
  check-bitrise-e2e-status:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request || github.event_name == 'pull_request' }}
    permissions:
      pull-requests: write
      contents: write
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Check Bitrise E2E Status
        env:
          BITRISE_BUILD_TRIGGER_TOKEN: ${{ secrets.BITRISE_BUILD_TRIGGER_TOKEN }}
          BITRISE_APP_ID: ${{ secrets.BITRISE_APP_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run check-bitrise-e2e-status
