# Fails the pull request if it has the "DO-NOT-MERGE" label

name: ci / check all branches

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

jobs:
  do-not-merge:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'DONOTMERGE') }}
    steps:
      - name: 'Check for label "DONOTMERGE"' 
        run: |
          echo 'This check fails PRs with the "DONOTMERGE" label to block merging'
          exit 1
