name: CI (Namespace shadow)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '.github/CODEOWNERS'
  push:
    branches: [main]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

concurrency:
  group: ns-shadow-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shadow-ci:
    name: '[shadow] CI'
    uses: ./.github/workflows/ci.yml
    with:
      runner_provider: namespace
    secrets: inherit
