# This workflow is used to detect changes in the Android and iOS projects.
# It can be used to determine if the build should be triggered for the Android and iOS projects.
# Outputs:
# - android_changed: Whether Android-impacting files changed
# - ios_changed: Whether iOS-impacting files changed
# - any_changed: Whether either platform requires a build

name: Detect Mobile Build Changes

on:
  workflow_call:
    outputs:
      android_changed:
        description: 'Whether Android-impacting files changed'
        value: ${{ jobs.detect.outputs.android }}
      ios_changed:
        description: 'Whether iOS-impacting files changed'
        value: ${{ jobs.detect.outputs.ios }}

jobs:
  detect:
    name: Detect platform changes (Android/iOS)
    runs-on: ubuntu-latest
    outputs:
      android: ${{ steps.set-outputs.outputs.android_final }}
      ios: ${{ steps.set-outputs.outputs.ios_final }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Paths filter (Android/iOS impact)
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        with:
          filters: |
            android:
              - 'android/**'                       # All Android project files

            ios:
              - 'ios/**'                           # All iOS project files

            shared:
              - 'package.json'                     # If native deps change
              - 'metro.config.js'                  # Metro bundler affects both
              - 'tsconfig.json'                    # TypeScript config affects both
              - 'babel.config.js'                  # Transpilation affects both
              - 'yarn.lock'                        # Dependency changes affect both
              - 'app/**'                           # Shared app files

            ignore:
              - '**/*.md'                          # Documentation files
              - 'docs/**'                          # Documentation directory
              - '**/*.yml'                         # Workflow files  
              - '.github/**'                       # GitHub workflow changes
              - 'LICENSE'                          # License file
              - 'README.md'                        # Main README
              - 'RELEASE.MD'                       # Release notes
              - 'CHANGELOG.md'                     # Changelog
              - 'attribution.txt'                  # Attribution file
              - '*.svg'                            # SVG files (like architecture.svg)
              - '*.png'                            # PNG files (like logo.png, image.png)
              - 'codecov.yml'                      # Code coverage config
              - 'crowdin.yml'                      # Translation config
              - 'bitrise.yml'                      # CI config (non-GitHub)
              - 'sonar-project.properties'        # SonarQube config
              - 'sentry*.properties*'              # Sentry configs
              - 'e2e/**'                          # E2E test files (separate from mobile builds)
              - 'wdio/**'                         # WebDriver test files
              - 'wdio.conf.js'                    # WebDriver config
              - 'appwright/**'                    # Appwright test files
              - 'scripts/**'                      # Build/utility scripts
              - 'patches/**'                      # Dependency patches
              - 'ppom/**'                         # PPOM sub-project

      - name: Set final outputs
        id: set-outputs
        run: |
          # Get individual filter results
          android="${{ steps.filter.outputs.android }}"
          ios="${{ steps.filter.outputs.ios }}"
          shared="${{ steps.filter.outputs.shared }}"
          ignore="${{ steps.filter.outputs.ignore }}"
          
          # Calculate final results
          if [[ "$shared" == 'true' ]]; then
            # Shared files changed - trigger both platforms
            android_final="true"
            ios_final="true"
          else
            # Only platform-specific changes
            android_final="$android"
            ios_final="$ios"
          fi
          
          # Skip builds if no mobile code changed
          if [[ "$ignore" == 'true' && "$android_final" == 'false' && "$ios_final" == 'false' ]]; then
            echo "Skipping all mobile builds - changes only affect docs/workflows, no mobile code changed"
            echo "android_final=false" >> "${GITHUB_OUTPUT}"
            echo "ios_final=false" >> "${GITHUB_OUTPUT}"
          else
            echo "Mobile build decisions:"
            echo "  Android: $android_final (direct: $android, shared: $shared)"
            echo "  iOS: $ios_final (direct: $ios, shared: $shared)"
            
            echo "android_final=$android_final" >> "${GITHUB_OUTPUT}"
            echo "ios_final=$ios_final" >> "${GITHUB_OUTPUT}"
          fi
          
      - name: Summary
        run: |
          {
            echo "Android changed: ${{ steps.set-outputs.outputs.android_final }}"
            echo "iOS changed: ${{ steps.set-outputs.outputs.ios_final }}"
          } >> "${GITHUB_STEP_SUMMARY}"
