# This workflow is used to detect changes in the Android and iOS projects.
# It can be used to determine if the build should be triggered for the Android and iOS projects.
# Outputs:
# - android_changed: Whether Android-impacting files changed
# - ios_changed: Whether iOS-impacting files changed
# - any_changed: Whether either platform requires a build

name: Detect Mobile Build Changes

on:
  workflow_call:
    outputs:
      android_changed:
        description: 'Whether Android-impacting files changed'
        value: ${{ jobs.detect.outputs.android }}
      ios_changed:
        description: 'Whether iOS-impacting files changed'
        value: ${{ jobs.detect.outputs.ios }}

jobs:
  detect:
    name: Detect platform changes (Android/iOS)
    runs-on: ubuntu-latest
    outputs:
      android: ${{ steps.set-outputs.outputs.android_final }}
      ios: ${{ steps.set-outputs.outputs.ios_final }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Paths filter (Android/iOS impact)
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        with:
          filters: |
            android:
              - 'android/**'                       # All Android project files

            ios:
              - 'ios/**'                           # All iOS project files

            shared:
              - 'package.json'                     # If native deps change
              - 'metro.config.js'                  # Metro bundler affects both
              - 'tsconfig.json'                    # TypeScript config affects both
              - 'babel.config.js'                  # Transpilation affects both
              - 'yarn.lock'                        # Dependency changes affect both
              - 'app/**'                           # Shared app files
              - 'e2e/**'                           # E2E test files (separate from mobile builds)
              - 'sentry*.properties*'              # Sentry configs
              - 'wdio/**'                          # WebDriver test files
              - 'wdio.conf.js'                     # WebDriver config
              - 'appwright/**'                     # Appwright test files


            ignore:
              - '**/*.md'                          # Documentation files
              - 'docs/**'                          # Documentation directory
              - '**/*.yml'                         # Workflow files  
              #- '.github/**'                       # GitHub workflow changes
              - 'LICENSE'                          # License file
              - 'README.md'                        # Main README
              - 'RELEASE.MD'                       # Release notes
              - 'CHANGELOG.md'                     # Changelog
              - 'attribution.txt'                  # Attribution file
              - '*.svg'                            # SVG files (like architecture.svg)
              - '*.png'                            # PNG files (like logo.png, image.png)
              - 'codecov.yml'                      # Code coverage config
              - 'crowdin.yml'                      # Translation config
              - 'bitrise.yml'                      # CI config (non-GitHub)
              - 'sonar-project.properties'         # SonarQube config
              - 'scripts/**'                       # Build/utility scripts
              - 'patches/**'                       # Dependency patches
              - 'ppom/**'                          # PPOM sub-project

      - name: Set final outputs
        id: set-outputs
        run: |
          # Get individual filter results
          android="${{ steps.filter.outputs.android }}"
          ios="${{ steps.filter.outputs.ios }}"
          shared="${{ steps.filter.outputs.shared }}"
          ignore="${{ steps.filter.outputs.ignore }}"
          
          # State Machine for Build Decisions:
          # 1. Purely ignored changes -> Skip both
          # 2. Shared changes -> Build both
          # 3. Android-only changes -> Android only
          # 4. iOS-only changes -> iOS only
          # 5. Unmatched/new files -> Conservative (Build both)

          # Determine build decisions
          if [[ "$ignore" == 'true' && "$shared" == 'false' && "$android" != 'true' && "$ios" != 'true' ]]; then
            echo "Ignoring - no mobile code changes"
            android_final="false"
            ios_final="false"
          elif [[ "$shared" == 'true' ]]; then
            echo "Building both platforms"
            android_final="true"
            ios_final="true"
          elif [[ "$android" == 'true' && "$ios" != 'true' ]]; then
            echo "Building Android only"
            android_final="true"
            ios_final="false"
          elif [[ "$ios" == 'true' && "$android" != 'true' ]]; then
            echo "Building iOS only"
            android_final="false"
            ios_final="true"
          else
            echo "Building both platforms (conservative)"
            android_final="true"
            ios_final="true"
          fi

          echo "android_final=$android_final" >> "${GITHUB_OUTPUT}"
          echo "ios_final=$ios_final" >> "${GITHUB_OUTPUT}"

      - name: Summary
        run: |
          {
            echo "Android changed: ${{ steps.set-outputs.outputs.android_final }}"
            echo "iOS changed: ${{ steps.set-outputs.outputs.ios_final }}"
          } >> "${GITHUB_STEP_SUMMARY}"
