name: Example - Detect Mobile Build Changes

on:
  push:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  detect-changes:
    name: Detect platform changes
    uses: ./.github/workflows/detect-mobile-build-changes.yml
    secrets: inherit

  print-results:
    name: Print detection results
    runs-on: ubuntu-latest
    needs: detect-changes
    steps:
      - name: Print outputs
        run: |
          echo "🤖 Android changed: ${{ needs.detect-changes.outputs.android_changed }}"
          echo "🍎 iOS changed: ${{ needs.detect-changes.outputs.ios_changed }}"
          echo "📱 Any platform changed: ${{ needs.detect-changes.outputs.any_changed }}"
          
          echo "## Change Detection Results" >> $GITHUB_STEP_SUMMARY
          echo "- **Android changed**: ${{ needs.detect-changes.outputs.android_changed }}" >> $GITHUB_STEP_SUMMARY
          echo "- **iOS changed**: ${{ needs.detect-changes.outputs.ios_changed }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Any platform changed**: ${{ needs.detect-changes.outputs.any_changed }}" >> $GITHUB_STEP_SUMMARY

  conditional-android-job:
    name: Android job (conditional)
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.android_changed == 'true'
    steps:
      - name: Android build would run here
        run: |
          echo "🤖 This job only runs when Android files changed"
          echo "Android-impacting changes detected, proceeding with Android build..."

  conditional-ios-job:
    name: iOS job (conditional)
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.ios_changed == 'true'
    steps:
      - name: iOS build would run here
        run: |
          echo "🍎 This job only runs when iOS files changed"
          echo "iOS-impacting changes detected, proceeding with iOS build..."

  conditional-any-job:
    name: Any platform job (conditional)
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'
    steps:
      - name: Cross-platform job would run here
        run: |
          echo "📱 This job runs when either platform has changes"
          echo "Mobile changes detected, proceeding with cross-platform tasks..."

  always-run-job:
    name: Always run job (for comparison)
    runs-on: ubuntu-latest
    needs: detect-changes
    steps:
      - name: This always runs
        run: |
          echo "🔄 This job always runs regardless of changes"
          echo "Use this pattern for jobs that should run unconditionally"