name: Configure iOS Keystore for E2E Tests

on:
  push:

permissions:
  contents: write
  id-token: write

jobs:
  ios-e2e:
    runs-on: macos-14
    env:
      GITHUB_CI: "true"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Keystores for iOS E2E Tests
        uses: MetaMask/github-tools/.github/actions/configure-keystore@e2e-env-actions
        with:
          aws-role-to-assume: ${{ secrets.QA_CERTIFICATE_MANAGER_AWS_ROLE}}
          aws-region: 'us-east-2'
          platform: ios
          environment: 'qa'






