name: Merge Stable Sync PR

on:
  # Trigger the workflow when a comment is created on an issue or pull request
  issue_comment:
    types: [created]

jobs:
  merge-pr:
    # Only run if the comment is on a PR and the comment body matches exactly "Merge my PR"
    if: >-
      github.event.issue.pull_request &&
      github.event.comment.body == 'Merge my PR' &&
      (
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'OWNER'
      )
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Get token
        id: get-token
        uses: MetaMask/github-tools/.github/actions/get-token@v1
        with:
          token-exchange-url: ${{ vars.TOKEN_EXCHANGE_URL }}
          permissions: |
            pull_requests: write
            contents: write
            members: read

      - name: Merge approved PR
        uses: MetaMask/github-tools/.github/actions/merge-approved-pr@v1
        with:
          pr-number: ${{ github.event.issue.number }}
          # Merge PRs from stable-main-X.Y.Z into main
          required-base-branch: 'main'
          head-branch-pattern: '^stable-main-[0-9]+\.[0-9]+\.[0-9]+$'
          github-token: ${{ steps.get-token.outputs.token }}
