name: Needs E2E

on:
  workflow_call:
    outputs:
      needs-e2e:
        description: Whether E2E tests are needed
        value: ${{ jobs.needs-e2e.outputs.needs-e2e }}

jobs:
  needs-e2e:
    runs-on: ubuntu-latest
    outputs:
      needs-e2e: ${{ steps.determine.outputs.NEEDS_E2E }}
    env:
      # For a `pull_request` event, the head commit hash is `github.event.pull_request.head.sha`.
      # For a `push` event, the head commit hash is `github.sha`.
      HEAD_COMMIT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Specifying `ref` ensures that the head commit is checked out directly.
          ref: ${{ env.HEAD_COMMIT_HASH }}

      - name: Check skip tag
        id: skip-tag
        run: |
          echo "SKIP=false" >> "$GITHUB_OUTPUT"
          if [[ "${{ github.event_name }}" == "pull_request" ]] || [[ "${{ github.event_name }}" == "merge_group" ]]; then
            if git show --format='%B' --no-patch "${HEAD_COMMIT_HASH}" | grep --fixed-strings --quiet '[skip-e2e]'; then
              echo "SKIP=true" >> "$GITHUB_OUTPUT"
              echo "-> SKIP=true due to [skip-e2e] tag in last commit message"
            fi
          fi

      - name: Check skip label
        id: skip-label
        if: github.event_name == 'pull_request'
        run: |
          echo "SKIP=false" >> "$GITHUB_OUTPUT"
          if gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name' | grep -qx "skip-e2e"; then
            echo "SKIP=true" >> "$GITHUB_OUTPUT"
            echo "-> SKIP=true due to 'skip-e2e' label on PR"
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Determine if E2E needed
        id: determine
        run: |
          # Default to running E2E tests
          echo "NEEDS_E2E=true" >> "$GITHUB_OUTPUT"

          # Only consider skipping for PRs and merge-queue events
          if [[ "${{ github.event_name }}" == "pull_request" ]] || [[ "${{ github.event_name }}" == "merge_group" ]]; then

            # Skip if [skip e2e] tag found or label exists on PR
            if [[ "${{ steps.skip-tag.outputs.SKIP }}" == "true" ]] || [[ "${{ steps.skip-label.outputs.SKIP }}" == "true" ]]; then
              echo "NEEDS_E2E=false" >> "$GITHUB_OUTPUT"
              echo "-> Skipping E2E tests due to 'skip-e2e' tag"
            else
              echo "-> E2E tests needed"
            fi
          fi
