name: "Conventional Commit Validation PR Title"
on:
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # v5.2.0
      - name: Conventional Commit Validation PR Title
        uses: amannn/action-semantic-pull-request@c3cd5d1ea3580753008872425915e343e351ab54
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
