name: Trigger Publish Slack Release Testing Status

on:
  schedule:
    - cron: '0 15 * * 1-5'  #M-F at 15:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  call-publish-slack-release-testing-status:
    name: Publish Slack release testing status
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Get token
        id: get-token
        uses: MetaMask/github-tools/.github/actions/get-token@v1
        with:
          token-exchange-url: ${{ vars.TOKEN_EXCHANGE_URL }}
          permissions: |
            contents: read
            pull_requests: read

      - name: Publish Slack release testing status
        uses: MetaMask/github-tools/.github/actions/publish-slack-release-testing-status@v1
        with:
          platform: 'mobile'
          test-only: 'true'
          google-document-id: '1tsoodlAlyvEUpkkcNcbZ4PM9HuC9cEM80RZeoVv5OCQ'
          slack-api-key: ${{ secrets.SLACKBOT_RLS_TOKEN }}
          github-token: ${{ steps.get-token.outputs.token }}
          google-application-creds-base64: ${{ secrets.GCP_RLS_SHEET_ACCOUNT_BASE64 }}
