name: Check SonarCloud Quality Gate Status

on:
  push:
    branches: 10689-enable-merge-queues-gh-action-to-check-for-passfail-sonarquality-gate
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  check-sonarcloud-status:
    name: Check SonarCloud Quality Gate Status
    runs-on: ubuntu-latest
    # if: github.event_name == 'pull_request_target' || contains(github.event.comment.html_url, '/pull/')

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Get SonarCloud Quality Gate Status
        id: sonar-status
        run: |
          PROJECT_KEY="metamask-mobile"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}"

          if [ -z "$PR_NUMBER" ]; then
            echo "No pull request number found. Skipping SonarCloud Quality Gate check."
            exit 0
          fi

          RESPONSE=$(curl -s -u "$SONAR_TOKEN:" \
            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECT_KEY&pullRequest=$PR_NUMBER")
          echo "SonarCloud API Response: $RESPONSE"

          STATUS=$(echo "$RESPONSE" | jq -r '.projectStatus.status')

          if [[ "$STATUS" == "ERROR" ]]; then
            echo "Quality Gate failed."
            echo "quality_gate_passed=false" >> "$GITHUB_OUTPUT"
          elif [[ "$STATUS" == "OK" ]]; then
            echo "Quality Gate passed."
            echo "quality_gate_passed=true" >> "$GITHUB_OUTPUT"
          else
            echo "Could not determine Quality Gate status."
            exit 1
          fi

      - name: Fail if Quality Gate did not pass
        if: steps.sonar-status.outputs.quality_gate_passed == 'false'
        run: |
          echo "SonarCloud Quality Gate did not pass. Failing the check."
          exit 1

      - name: Success if Quality Gate passed
        if: steps.sonar-status.outputs.quality_gate_passed == 'true'
        run: echo "SonarCloud Quality Gate passed. Marking the check as successful."
