name: Check SonarCloud Quality Gate Comment

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  check-sonarcloud-comment:
    name: Check SonarCloud Quality Gate Comment
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' || contains(github.event.comment.html_url, '/pull/')

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Get PR comments
        id: get-comments
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          COMMENTS=$(gh pr view "$PR_NUMBER" --json comments --jq '.comments[].body')
          echo "$COMMENTS" > comments.txt
          echo "comments=$COMMENTS" >> $GITHUB_OUTPUT

      - name: Check for SonarCloud Quality Gate Pass
        id: check-quality-gate
        run: |
          if grep -q "Quality Gate passed" comments.txt; then
            echo "Quality Gate passed found in comments."
            echo "quality_gate_passed=true" >> $GITHUB_OUTPUT
          elif grep -q "Quality Gate failed" comments.txt; then
            echo "Quality Gate failed found in comments."
            echo "quality_gate_passed=false" >> $GITHUB_OUTPUT
          else
            echo "SonarCloud Quality Gate result not found in comments."
            exit 1

      - name: Fail if Quality Gate did not pass
        if: steps.check-quality-gate.outputs.quality_gate_passed == 'false'
        run: |
          echo "SonarCloud Quality Gate did not pass. Failing the check."
          exit 1

      - name: Success if Quality Gate passed
        if: steps.check-quality-gate.outputs.quality_gate_passed == 'true'
        run: echo "SonarCloud Quality Gate passed. Marking the check as successful."
