name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@72afbce2b0dbd1d903bb142cebe2d15dc307ae57
        with:
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity in the last 90 days. It will be closed in 7 days. Thank you for your contributions.'
          stale-issue-label: 'stale'
          only-issue-labels: 'type-bug'
          exempt-issue-labels: 'type-security, type-pinned, feature-request, awaiting-metamask'
          stale-pr-message: 'This PR has been automatically marked as stale because it has not had recent activity in the last 90 days. It will be closed in 7 days. Thank you for your contributions.'
          stale-pr-label: 'stale'
          exempt-pr-labels: 'work-in-progress'
          close-issue-message: 'This issue was closed because there has been no follow activity in 7 days. If you feel this was closed in error please provide evidence on the current production app in a new issue or comment in the existing issue to a maintainer. Thank you for your contributions.'
          close-pr-message: 'This PR was closed because there has been no follow up activity in 7 days. Thank you for your contributions.'
          days-before-issue-stale: 90
          days-before-pr-stale: 90
          days-before-issue-close: 7
          days-before-pr-close: 7
          operations-per-run: 200
          