name: Test Merge Validation

on:
  push:
    branches:
      - chore-post-validation

permissions:
  pull-requests: write
  contents: read

jobs:
  test-validation:
    uses: MetaMask/github-tools/.github/workflows/post-merge-validation.yml@chore-post-validation
    with:
      repo-owner: MetaMask
      repo-name: metamask-mobile
      pr-number: '17941'
      pr-author: 'jvbriones'
      pr-title: 'feat: test issue'