name: Test Merge Validation

on:
  push:
    branches:
      - chore-post-validation

permissions:
  pull-requests: write
  contents: read

jobs:
  test-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Post Feature Validation Checklist
        uses: actions/github-script@v7
        env:
          OWNER_NAME: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: '17937'
          PR_AUTHOR: 'jvbriones'
          PR_TITLE: 'chore: add post merge validation bot'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const {
              OWNER_NAME: owner,
              REPO_NAME: repo,
              PR_NUMBER: prNumStr,
              PR_AUTHOR: author,
              PR_TITLE: title,
            } = process.env;

            const pull_number = parseInt(prNumStr, 10);

            // Check if PR title starts with "feat" or "perf" (conventional commits)
            const titleLower = title.toLowerCase();
            if (!titleLower.startsWith('chore:') && !titleLower.startsWith('chore(') && 
                !titleLower.startsWith('perf:') && !titleLower.startsWith('perf(')) {
              console.log(`❌ PR #${pull_number} title doesn't start with feat or perf - skipping.`);
              return;
            }

            const body = `Hi @${author},

            On the day following feat or perf PR merge, PM and author to test feature on main (feature+exploratory around the edges) using the latest [nightly build](https://consensys.slack.com/archives/C093JQSEPJL) with [casual user persona](https://consensyssoftware.atlassian.net/wiki/spaces/TL1/pages/400085221547/Mobile+User+Persona+Definition) and also a [power user persona](https://consensyssoftware.atlassian.net/wiki/spaces/TL1/pages/400085221547/Mobile+User+Persona+Definition) where performance might be a challenge. Record a video, check the relevant post-merge checklist box below, and post the video in the relevant comment at the bottom of the PR.

            ### Author validation checklist
            - [ ] Validated the changes in main branch using the nightly build
            - [ ] Video shared

            ### PM validation checklist
            - [ ] Validated the changes in main branch using the nightly build
            - [ ] Video shared

            <!-- AUTO-VALIDATION-CHECKLIST PR:${pull_number} -->`;

            // Post the comment
            try {
             await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pull_number,
              body
             });
             console.log(`✅ Validation checklist posted on PR #${pull_number}`);
            } catch (error) {
              console.log(`⚠️  Could not post comment: ${error.message}`);
            }            

            // Add the needs-validation label
            try {
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: pull_number,
                labels: ['needs-validation']
              });
              console.log(`✅ Added 'needs-validation' label to PR #${pull_number}`);
            } catch (error) {
              console.log(`⚠️  Could not add label: ${error.message}`);
            }