name: Test Android Build Only (temp)

on:
  workflow_dispatch:
    inputs:
      runner_provider:
        description: Runner provider
        required: true
        type: choice
        options:
          - current
          - namespace
        default: namespace

jobs:
  build-android-apks:
    name: 'Build Android APKs'
    permissions:
      contents: read
      id-token: write
      actions: read
      statuses: read
      pull-requests: read
    uses: ./.github/workflows/build-android-e2e.yml
    with:
      build_type: 'main'
      metamask_environment: 'e2e'
      runner_provider: ${{ inputs.runner_provider }}
    secrets: inherit
