name: Test Merge Validation

on:
  push:
    branches:
      - chore-post-validation

permissions:
  pull-requests: write
  contents: read

jobs:
  test-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Post Feature Validation Checklist
        uses: actions/github-script@v7
        env:
          OWNER_NAME: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const {
              OWNER_NAME: owner,
              REPO_NAME: repo,
              PR_NUMBER: prNumStr,
              PR_AUTHOR: author,
              PR_TITLE: title,
            } = process.env;

            const pull_number = parseInt(prNumStr, 10);

            // Check if PR title starts with "feat" or "perf" (conventional commits)
            const titleLower = title.toLowerCase();
            if (!titleLower.startsWith('chore:') && !titleLower.startsWith('feat(') && 
                !titleLower.startsWith('perf:') && !titleLower.startsWith('perf(')) {
              console.log(`❌ PR #${pull_number} title doesn't start with feat or perf - skipping.`);
              return;
            }

            const body = `Hi @${author},

            This PR has been merged to the main branch. Please ensure the following validation steps are completed.
            Please use power user persona where performance might be a challenge.

            ## Validation Checklist
            - [ ] Author validated the changes in main branch using the nightly build
            - [ ] PM of the team validated the changes in main branch using the nightly build            
            - [ ] Video URL shared: 

            <!-- AUTO-VALIDATION-CHECKLIST PR:${pull_number} -->`;

            // Post the comment
            try {
             await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pull_number,
              body
             });
             console.log(`✅ Validation checklist posted on PR #${pull_number}`);
            } catch (error) {
              console.log(`⚠️  Could not post comment: ${error.message}`);
            }            

            // Add the needs-validation label
            try {
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: pull_number,
                labels: ['needs-validation']
              });
              console.log(`✅ Added 'needs-validation' label to PR #${pull_number}`);
            } catch (error) {
              console.log(`⚠️  Could not add label: ${error.message}`);
            }