/* eslint-disable import/prefer-default-export */
/* eslint-disable import/no-commonjs */
/* eslint-disable @typescript-eslint/no-require-imports */
///////////////////////////////////////////////////////
// This is a generated file
// DO NOT EDIT - Use generate-assets.js
///////////////////////////////////////////////////////
import { AssetByIconName, IconName } from './Icon.types';

/**
 * Asset stored by icon name
 */
export const assetByIconName: AssetByIconName = {
  [IconName.AddOutline]: require('./assets/add-outline.png'),
  [IconName.AddSquareFilled]: require('./assets/add-square-filled.png'),
  [IconName.Arrow2DownOutline]: require('./assets/arrow-2-down-outline.png'),
  [IconName.Arrow2LeftOutline]: require('./assets/arrow-2-left-outline.png'),
  [IconName.Arrow2RightOutline]: require('./assets/arrow-2-right-outline.png'),
  [IconName.Arrow2UpOutline]: require('./assets/arrow-2-up-outline.png'),
  [IconName.ArrowDownOutline]: require('./assets/arrow-down-outline.png'),
  [IconName.ArrowLeftOutline]: require('./assets/arrow-left-outline.png'),
  [IconName.ArrowRightOutline]: require('./assets/arrow-right-outline.png'),
  [IconName.ArrowUpOutline]: require('./assets/arrow-up-outline.png'),
  [IconName.BankFilled]: require('./assets/bank-filled.png'),
  [IconName.BankTokenFilled]: require('./assets/bank-token-filled.png'),
  [IconName.BookFilled]: require('./assets/book-filled.png'),
  [IconName.BookmarkFilled]: require('./assets/bookmark-filled.png'),
  [IconName.CalculatorFilled]: require('./assets/calculator-filled.png'),
  [IconName.CardFilled]: require('./assets/card-filled.png'),
  [IconName.CardPosFilled]: require('./assets/card-pos-filled.png'),
  [IconName.CardTokenFilled]: require('./assets/card-token-filled.png'),
  [IconName.CategoryFilled]: require('./assets/category-filled.png'),
  [IconName.ChartFilled1]: require('./assets/chart-filled-1.png'),
  [IconName.ChartFilled]: require('./assets/chart-filled.png'),
  [IconName.CheckOutline]: require('./assets/check-outline.png'),
  [IconName.ClockFilled]: require('./assets/clock-filled.png'),
  [IconName.CloseOutline]: require('./assets/close-outline.png'),
  [IconName.CodeCircleFilled]: require('./assets/code-circle-filled.png'),
  [IconName.CoinFilled]: require('./assets/coin-filled.png'),
  [IconName.ConnectFilled]: require('./assets/connect-filled.png'),
  [IconName.CopyFilled]: require('./assets/copy-filled.png'),
  [IconName.CopySuccessFilled]: require('./assets/copy-success-filled.png'),
  [IconName.DangerFilled]: require('./assets/danger-filled.png'),
  [IconName.DarkFilled]: require('./assets/dark-filled.png'),
  [IconName.DataFilled]: require('./assets/data-filled.png'),
  [IconName.DiagramOutline]: require('./assets/diagram-outline.png'),
  [IconName.DocumentCodeFilled]: require('./assets/document-code-filled.png'),
  [IconName.EditFilled]: require('./assets/edit-filled.png'),
  [IconName.EraserFilled]: require('./assets/eraser-filled.png'),
  [IconName.ExpandOutline]: require('./assets/expand-outline.png'),
  [IconName.ExploreFilled]: require('./assets/explore-filled.png'),
  [IconName.ExportOutline]: require('./assets/export-outline.png'),
  [IconName.EyeFilled]: require('./assets/eye-filled.png'),
  [IconName.EyeSlashFilled]: require('./assets/eye-slash-filled.png'),
  [IconName.FilterOutline]: require('./assets/filter-outline.png'),
  [IconName.FlagFilled]: require('./assets/flag-filled.png'),
  [IconName.FlashFilled]: require('./assets/flash-filled.png'),
  [IconName.FlashSlashFilled]: require('./assets/flash-slash-filled.png'),
  [IconName.FullCircleFilled]: require('./assets/full-circle-filled.png'),
  [IconName.GasFilled]: require('./assets/gas-filled.png'),
  [IconName.GlobalFilled]: require('./assets/global-filled.png'),
  [IconName.GlobalSearchFilled]: require('./assets/global-search-filled.png'),
  [IconName.GraphFilled]: require('./assets/graph-filled.png'),
  [IconName.HeartFilled]: require('./assets/heart-filled.png'),
  [IconName.HierarchyFilled]: require('./assets/hierarchy-filled.png'),
  [IconName.HomeFilled]: require('./assets/home-filled.png'),
  [IconName.ImportOutline]: require('./assets/import-outline.png'),
  [IconName.InfoFilled]: require('./assets/info-filled.png'),
  [IconName.KeyFilled]: require('./assets/key-filled.png'),
  [IconName.LightFilled]: require('./assets/light-filled.png'),
  [IconName.Link2Outline]: require('./assets/link-2-outline.png'),
  [IconName.LinkOutline]: require('./assets/link-outline.png'),
  [IconName.LoadingFilled]: require('./assets/loading-filled.png'),
  [IconName.LockCircleFilled]: require('./assets/lock-circle-filled.png'),
  [IconName.LockFilled]: require('./assets/lock-filled.png'),
  [IconName.LockSlashFilled]: require('./assets/lock-slash-filled.png'),
  [IconName.LoginOutline]: require('./assets/login-outline.png'),
  [IconName.LogoutOutline]: require('./assets/logout-outline.png'),
  [IconName.MenuOutline]: require('./assets/menu-outline.png'),
  [IconName.MessageQuestionFilled]: require('./assets/message-question-filled.png'),
  [IconName.MessagesFilled]: require('./assets/messages-filled.png'),
  [IconName.MinusOutine]: require('./assets/minus-outine.png'),
  [IconName.MinusSquareFilled]: require('./assets/minus-square-filled.png'),
  [IconName.MobileFilled]: require('./assets/mobile-filled.png'),
  [IconName.MoneyFilled]: require('./assets/money-filled.png'),
  [IconName.MonitorFilled]: require('./assets/monitor-filled.png'),
  [IconName.MoreHorizontalOutline]: require('./assets/more-horizontal-outline.png'),
  [IconName.MoreVerticalOutline]: require('./assets/more-vertical-outline.png'),
  [IconName.NotificationCircleFilled]: require('./assets/notification-circle-filled.png'),
  [IconName.NotificationFilled]: require('./assets/notification-filled.png'),
  [IconName.PasswordCheckFilled]: require('./assets/password-check-filled.png'),
  [IconName.PeopleFilled]: require('./assets/people-filled.png'),
  [IconName.ProgrammingArrowsFilled]: require('./assets/programming-arrows-filled.png'),
  [IconName.QuestionFilled]: require('./assets/question-filled.png'),
  [IconName.ReceivedOutline]: require('./assets/received-outline.png'),
  [IconName.RefreshOutline]: require('./assets/refresh-outline.png'),
  [IconName.SaveFilled]: require('./assets/save-filled.png'),
  [IconName.ScanBarcodeFilled]: require('./assets/scan-barcode-filled.png'),
  [IconName.ScanFilled]: require('./assets/scan-filled.png'),
  [IconName.ScanFocusOutline]: require('./assets/scan-focus-outline.png'),
  [IconName.ScrollFilled]: require('./assets/scroll-filled.png'),
  [IconName.SearchFilled]: require('./assets/search-filled.png'),
  [IconName.SecurityCardFilled]: require('./assets/security-card-filled.png'),
  [IconName.SecurityCrossFilled]: require('./assets/security-cross-filled.png'),
  [IconName.SecurityFilled]: require('./assets/security-filled.png'),
  [IconName.SecurityKeyFilled]: require('./assets/security-key-filled.png'),
  [IconName.SecuritySearchFilled]: require('./assets/security-search-filled.png'),
  [IconName.SecuritySlashFilled]: require('./assets/security-slash-filled.png'),
  [IconName.SecurityTickFilled]: require('./assets/security-tick-filled.png'),
  [IconName.SecurityTimeFilled]: require('./assets/security-time-filled.png'),
  [IconName.SecurityUserFilled]: require('./assets/security-user-filled.png'),
  [IconName.Send1Filled]: require('./assets/send-1-filled.png'),
  [IconName.Send2Outline]: require('./assets/send-2-outline.png'),
  [IconName.SettingFilled]: require('./assets/setting-filled.png'),
  [IconName.SlashFilled]: require('./assets/slash-filled.png'),
  [IconName.SnapsFilled]: require('./assets/snaps-filled.png'),
  [IconName.SnapsMobileFilled]: require('./assets/snaps-mobile-filled.png'),
  [IconName.SnapsPlusFilled]: require('./assets/snaps-plus-filled.png'),
  [IconName.SpeedometerFilled]: require('./assets/speedometer-filled.png'),
  [IconName.StarFilled]: require('./assets/star-filled.png'),
  [IconName.StudentFilled]: require('./assets/student-filled.png'),
  [IconName.SwapHorizontalOutline]: require('./assets/swap-horizontal-outline.png'),
  [IconName.SwapVertivalFilled]: require('./assets/swap-vertival-filled.png'),
  [IconName.TagFilled]: require('./assets/tag-filled.png'),
  [IconName.TimerTimer]: require('./assets/timer-timer.png'),
  [IconName.TrashFilled]: require('./assets/trash-filled.png'),
  [IconName.TrendDownFilled]: require('./assets/trend-down-filled.png'),
  [IconName.TrendUpFilled]: require('./assets/trend-up-filled.png'),
  [IconName.UserAddFilled1]: require('./assets/user-add-filled-1.png'),
  [IconName.UserAddFilled]: require('./assets/user-add-filled.png'),
  [IconName.UserCircleFilled]: require('./assets/user-circle-filled.png'),
  [IconName.UserCirlceAddFilled]: require('./assets/user-cirlce-add-filled.png'),
  [IconName.UserFilled]: require('./assets/user-filled.png'),
  [IconName.UserMinusFilled]: require('./assets/user-minus-filled.png'),
  [IconName.UserRemoveFilled]: require('./assets/user-remove-filled.png'),
  [IconName.UserSearchFilled]: require('./assets/user-search-filled.png'),
  [IconName.UserTickFilled]: require('./assets/user-tick-filled.png'),
  [IconName.WalletCardFilled]: require('./assets/wallet-card-filled.png'),
  [IconName.WalletFilled]: require('./assets/wallet-filled.png'),
  [IconName.WalletMoneyFilled]: require('./assets/wallet-money-filled.png'),
  [IconName.WarningFilled]: require('./assets/warning-filled.png'),
};
