export const ReviewOrderSelectors = {
  CONTAINER: 'review-order-container',
  TITLE: 'review-order-title',
  SUBTITLE: 'review-order-subtitle',
  SHIPPING_ADDRESS_CARD: 'review-order-shipping-address-card',
  ADDRESS_LINE_1: 'review-order-address-line-1',
  ADDRESS_LINE_2: 'review-order-address-line-2',
  ADDRESS_CITY_STATE_ZIP: 'review-order-address-city-state-zip',
  ORDER_SUMMARY: 'review-order-summary',
  ORDER_ITEM: 'review-order-item',
  ORDER_ITEM_PRESSABLE: 'review-order-item-pressable',
  PAY_BUTTON: 'review-order-pay-button',
  PAYMENT_ERROR: 'review-order-payment-error',
  PAY_LOADING: 'review-order-pay-loading',
};
